{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Meetings",
    "description" : "Meetings Service For HubSpot Sales",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "PROFESSIONAL",
      "sales" : "PROFESSIONAL",
      "service" : "PROFESSIONAL",
      "cms" : "PROFESSIONAL"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "You need to get a list of meeting links or book meetings, or you need to create an interface so customers can book meetings with your team.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Meetings Guide",
      "url" : "https://developers.hubspot.com/docs/reference/api/crm/engagements/meetings"
    } ],
    "x-hubspot-introduction" : "Use the Meetings API to retrieve information about meetings created through a scheduling page. You can also book a meeting with a scheduling page through the API."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "External_Meetings_Link"
  } ],
  "paths" : {
    "/scheduler/v3/meetings/meeting-links/book/{slug}" : {
      "get" : {
        "tags" : [ "External_Meetings_Link" ],
        "operationId" : "get-/scheduler/v3/meetings/meeting-links/book/{slug}",
        "security" : [ {
          "oauth2" : [ "scheduler.meetings.meeting-link.read" ]
        }, {
          "private_apps" : [ "scheduler.meetings.meeting-link.read" ]
        } ]
      }
    },
    "/scheduler/v3/meetings/meeting-links" : {
      "get" : {
        "tags" : [ "External_Meetings_Link" ],
        "operationId" : "get-/scheduler/v3/meetings/meeting-links",
        "security" : [ {
          "oauth2" : [ "scheduler.meetings.meeting-link.read" ]
        }, {
          "private_apps" : [ "scheduler.meetings.meeting-link.read" ]
        } ]
      }
    },
    "/scheduler/v3/meetings/meeting-links/book" : {
      "post" : {
        "tags" : [ "External_Meetings_Link" ],
        "operationId" : "post-/scheduler/v3/meetings/meeting-links/book",
        "security" : [ {
          "private_apps" : [ "crm.schemas.contacts.write", "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write", "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write", "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write", "crm.objects.services.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write", "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write", "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write", "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write", "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write", "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write", "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write", "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write", "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write", "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write", "crm.objects.line_items.write" ]
        } ]
      }
    },
    "/scheduler/v3/meetings/meeting-links/book/availability-page/{slug}" : {
      "get" : {
        "tags" : [ "External_Meetings_Link" ],
        "operationId" : "get-/scheduler/v3/meetings/meeting-links/book/availability-page/{slug}",
        "security" : [ {
          "oauth2" : [ "scheduler.meetings.meeting-link.read" ]
        }, {
          "private_apps" : [ "scheduler.meetings.meeting-link.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "scheduler.meetings.meeting-link.read" : "Read from meeting links",
              "crm.schemas.contacts.write" : " ",
              "crm.objects.deals.write" : " ",
              "crm.objects.companies.write" : " ",
              "crm.objects.services.write" : "Write services",
              "crm.objects.listings.write" : "Write listings",
              "crm.objects.contacts.write" : " ",
              "crm.objects.courses.write" : "Write courses",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.appointments.write" : "Write appointments"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  }
}