{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Marketing Campaigns Public Api",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "PROFESSIONAL",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "Campaigns",
      "url" : "https://developers.hubspot.com/docs/guides/api/marketing/campaigns"
    } ],
    "x-hubspot-introduction" : "You can use campaign endpoints to create, read, update, and delete marketing campaign data. For example, you can use these endpoints to create and manage HubSpot campaigns from your external applications. You can also transfer campaign data to external data warehouses for analytics."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Public_Campaign_Budget"
  }, {
    "name" : "Public_Campaign_Spend"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Public_Campaign_Report"
  }, {
    "name" : "Public_Campaign_Asset"
  } ],
  "paths" : {
    "/marketing/v3/campaigns/{campaignGuid}/spend/{spendId}" : {
      "get" : {
        "tags" : [ "Public_Campaign_Spend" ],
        "summary" : "Read campaign spend item",
        "description" : "Read a campaign spend item by its spendId",
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/spend/{spendId}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Public_Campaign_Spend" ],
        "summary" : "Update campaign spend item",
        "description" : "Update a specific campaign spend item by ID",
        "operationId" : "put-/marketing/v3/campaigns/{campaignGuid}/spend/{spendId}",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Public_Campaign_Spend" ],
        "summary" : "Delete campaign spend item",
        "description" : "Delete a specific campaign spend item by ID",
        "operationId" : "delete-/marketing/v3/campaigns/{campaignGuid}/spend/{spendId}",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update a batch of campaigns",
        "description" : "This endpoint updates a batch of campaigns based on the provided input data.\nThe maximum number of items in a batch request is 50.\nIf an empty string (\"\") is passed for any property in the Batch Update, it will reset that property's value.",
        "operationId" : "post-/marketing/v3/campaigns/batch/update",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/budget/{budgetId}" : {
      "get" : {
        "tags" : [ "Public_Campaign_Budget" ],
        "summary" : "Get budget item",
        "description" : "Get a specific budget item by ID",
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/budget/{budgetId}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Public_Campaign_Budget" ],
        "summary" : "Update budget item",
        "description" : "Update a specific budget item by ID",
        "operationId" : "put-/marketing/v3/campaigns/{campaignGuid}/budget/{budgetId}",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Public_Campaign_Budget" ],
        "summary" : "Delete budget item",
        "description" : "Delete a specific budget item by ID",
        "operationId" : "delete-/marketing/v3/campaigns/{campaignGuid}/budget/{budgetId}",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}/{assetId}" : {
      "put" : {
        "tags" : [ "Public_Campaign_Asset" ],
        "summary" : "Add asset association",
        "description" : "Associate a specified asset with a campaign. Using the API, you can create and remove associations for the following asset types: forms, static lists, external website pages, sequences, meetings, playbooks, feedback surveys, podcast episodes, sales documents, marketing emails, case studies, knowledge base articles, calls, and CTAs. \n\nFor other asset types, it is recommended to manage your associations directly in the campaign tool in HubSpot.",
        "operationId" : "put-/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}/{assetId}",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Public_Campaign_Asset" ],
        "summary" : "Remove asset association",
        "description" : "Disassociate a specified asset from a campaign.\nImportant: Currently, only the following asset types can be associated and disassociated via the API: Forms, Static lists, External website pages",
        "operationId" : "delete-/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}/{assetId}",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/budget/totals" : {
      "get" : {
        "tags" : [ "Public_Campaign_Budget" ],
        "summary" : "Read budget",
        "description" : "Retrieve detailed information about the budget and spend items for a specified campaign, including the total budget, total spend, and remaining budget.\nBudget and Spend items may be returned in any order, but the order field specifies their sequence based on the creation date. The item with order 0 is the oldest, and items with higher order values are newer",
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/budget/totals",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Campaign search",
        "description" : "This endpoint allows users to search for and return a page of campaigns based on various query parameters. Users can filter by name, sort, and paginate through the campaigns, as well as control which properties are returned in the response.",
        "operationId" : "get-/marketing/v3/campaigns/",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a campaign",
        "description" : "Create a campaign with the given properties and return the campaign object, including the campaignGuid and created properties. ",
        "operationId" : "post-/marketing/v3/campaigns/",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of campaigns",
        "description" : "This endpoint reads a batch of campaigns based on the provided input data and returns the campaigns along with their associated assets. \nThe maximum number of items in a batch request is 50.\nThe campaigns in the response are not guaranteed to be in the same order as they were provided in the request.\nIf duplicate campaign IDs are provided in the request, duplicates will be ignored. The response will include only unique IDs and will be returned without duplicates.\n",
        "operationId" : "post-/marketing/v3/campaigns/batch/read",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/reports/metrics" : {
      "get" : {
        "tags" : [ "Public_Campaign_Report" ],
        "summary" : "Get Campaign Metrics\n",
        "description" : "This endpoint retrieves key attribution metrics for a specified campaign, such as sessions, new contacts, and influenced contacts.",
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/reports/metrics",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}" : {
      "get" : {
        "tags" : [ "Public_Campaign_Asset" ],
        "summary" : "List assets",
        "description" : "This endpoint lists all assets of the campaign by asset type. The assetType parameter is required, and each request can only fetch assets of a single type.\nAsset metrics can also be fetched along with the assets; they are available only if start and end dates are provided.",
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Delete a batch of campaigns",
        "description" : "This endpoint deletes a batch of campaigns. \nThe maximum number of items in a batch request is 50.\nThe response will always be 204 No Content, regardless of whether the campaigns exist or not, whether they were successfully deleted or not, or if only some of the campaigns in the batch were deleted.",
        "operationId" : "post-/marketing/v3/campaigns/batch/archive",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/reports/revenue" : {
      "get" : {
        "tags" : [ "Public_Campaign_Report" ],
        "summary" : "Fetch revenue",
        "description" : "Fetch revenue attribution report data for a specified campaign\n",
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/reports/revenue",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.revenue.read" ]
        }, {
          "oauth2" : [ "marketing.campaigns.revenue.read" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of campaigns",
        "description" : "This endpoint creates a batch of campaigns. The maximum number of items in a batch request is 50.\nThe campaigns in the response are not guaranteed to be in the same order as they were provided in the request.",
        "operationId" : "post-/marketing/v3/campaigns/batch/create",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read a campaign",
        "description" : "Get a campaign identified by a specific campaignGuid with the given properties. Along with the campaign information, it also returns information about assets. Depending on the query parameters used, this can also be used to return information about the corresponding assets' metrics. Metrics are available only if startDate and endDate are provided.",
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete campaign ",
        "description" : "Delete a specified campaign from the system.\nThis call will return a 204 No Content response regardless of whether the campaignGuid provided corresponds to an existing campaign or not.",
        "operationId" : "delete-/marketing/v3/campaigns/{campaignGuid}",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update campaign",
        "description" : "Perform a partial update of a campaign identified by the specified campaignGuid. Provided property values will be overwritten. Read-only and non-existent properties will cause 400 error.\nIf an empty string is passed for any property in the Batch Update, it will reset that property's value.\n",
        "operationId" : "patch-/marketing/v3/campaigns/{campaignGuid}",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/budget" : {
      "post" : {
        "tags" : [ "Public_Campaign_Budget" ],
        "summary" : "Add budget item",
        "description" : "Add a new budget item to the campaign",
        "operationId" : "post-/marketing/v3/campaigns/{campaignGuid}/budget",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/reports/contacts/{contactType}" : {
      "get" : {
        "tags" : [ "Public_Campaign_Report" ],
        "summary" : "Fetch contact IDs",
        "description" : "Fetch the list of contact IDs for the specified campaign and contact type",
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/reports/contacts/{contactType}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/spend" : {
      "post" : {
        "tags" : [ "Public_Campaign_Spend" ],
        "summary" : "Create campaign spend item",
        "description" : "Create a new campaign spend item",
        "operationId" : "post-/marketing/v3/campaigns/{campaignGuid}/spend",
        "security" : [ {
          "private_apps" : [ "marketing.campaigns.write" ]
        }, {
          "oauth2" : [ "marketing.campaigns.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "marketing.campaigns.read" : "Read marketing campaigns",
              "marketing.campaigns.write" : "Write marketing campaigns",
              "marketing.campaigns.revenue.read" : "Read campaigns attribution revenue"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "PROFESSIONAL",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}