{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Marketing Campaigns Public Api",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "PROFESSIONAL",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "Campaigns",
      "url" : "https://developers.hubspot.com/docs/guides/api/marketing/campaigns"
    } ]
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Public_Campaign_Asset"
  }, {
    "name" : "Public_Campaign_Budget"
  }, {
    "name" : "Public_Campaign_Report"
  }, {
    "name" : "Public_Campaign_Spend"
  } ],
  "paths" : {
    "/marketing/v3/campaigns/" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/marketing/v3/campaigns/",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "operationId" : "post-/marketing/v3/campaigns/",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "operationId" : "post-/marketing/v3/campaigns/batch/archive",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "operationId" : "post-/marketing/v3/campaigns/batch/create",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "operationId" : "post-/marketing/v3/campaigns/batch/read",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "operationId" : "post-/marketing/v3/campaigns/batch/update",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/marketing/v3/campaigns/{campaignGuid}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "operationId" : "patch-/marketing/v3/campaigns/{campaignGuid}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}" : {
      "get" : {
        "tags" : [ "Public_Campaign_Asset" ],
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}/{assetId}" : {
      "put" : {
        "tags" : [ "Public_Campaign_Asset" ],
        "operationId" : "put-/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}/{assetId}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Public_Campaign_Asset" ],
        "operationId" : "delete-/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}/{assetId}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/budget" : {
      "post" : {
        "tags" : [ "Public_Campaign_Budget" ],
        "operationId" : "post-/marketing/v3/campaigns/{campaignGuid}/budget",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/budget/totals" : {
      "get" : {
        "tags" : [ "Public_Campaign_Budget" ],
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/budget/totals",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/budget/{budgetId}" : {
      "get" : {
        "tags" : [ "Public_Campaign_Budget" ],
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/budget/{budgetId}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Public_Campaign_Budget" ],
        "operationId" : "put-/marketing/v3/campaigns/{campaignGuid}/budget/{budgetId}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Public_Campaign_Budget" ],
        "operationId" : "delete-/marketing/v3/campaigns/{campaignGuid}/budget/{budgetId}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/reports/contacts/{contactType}" : {
      "get" : {
        "tags" : [ "Public_Campaign_Report" ],
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/reports/contacts/{contactType}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/reports/metrics" : {
      "get" : {
        "tags" : [ "Public_Campaign_Report" ],
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/reports/metrics",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/reports/revenue" : {
      "get" : {
        "tags" : [ "Public_Campaign_Report" ],
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/reports/revenue",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.revenue.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.revenue.read" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/spend" : {
      "post" : {
        "tags" : [ "Public_Campaign_Spend" ],
        "operationId" : "post-/marketing/v3/campaigns/{campaignGuid}/spend",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/spend/{spendId}" : {
      "get" : {
        "tags" : [ "Public_Campaign_Spend" ],
        "operationId" : "get-/marketing/v3/campaigns/{campaignGuid}/spend/{spendId}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.read" ]
        }, {
          "private_apps" : [ "marketing.campaigns.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Public_Campaign_Spend" ],
        "operationId" : "put-/marketing/v3/campaigns/{campaignGuid}/spend/{spendId}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Public_Campaign_Spend" ],
        "operationId" : "delete-/marketing/v3/campaigns/{campaignGuid}/spend/{spendId}",
        "security" : [ {
          "oauth2" : [ "marketing.campaigns.write" ]
        }, {
          "private_apps" : [ "marketing.campaigns.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "marketing.campaigns.read" : "Read marketing campaigns",
              "marketing.campaigns.revenue.read" : "Read campaigns attribution revenue",
              "marketing.campaigns.write" : "Write marketing campaigns"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "PROFESSIONAL",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}