{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Pages",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "After noticing that a website page was updated incorrectly, use the API to view revisions of that page, then restore the page to a previous version.",
    "x-hubspot-introduction" : "Use the pages API to create and manage website pages."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "A/B tests"
  }, {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Folders"
  }, {
    "name" : "Landing pages"
  }, {
    "name" : "Multi-language"
  }, {
    "name" : "Website pages"
  } ],
  "paths" : {
    "/cms/pages/2026-03/landing-pages" : {
      "get" : {
        "tags" : [ "Landing pages" ],
        "summary" : "Get all landing pages",
        "description" : "Get the list of landing pages. Supports paging and filtering. This method would be useful for an integration that examined these models and used an external service to suggest edits.\n",
        "operationId" : "get-/cms/pages/2026-03/landing-pages_getPage",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Landing pages" ],
        "summary" : "Create a landing page",
        "description" : "Create a new landing page.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages_create",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/ab-test/create-variation" : {
      "post" : {
        "tags" : [ "A/B tests" ],
        "summary" : "Create a new A/B test variation",
        "description" : "Create a new A/B test variation based on the information provided in the request body.\n",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/ab-test/create-variation_createABTestVariation",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/ab-test/end" : {
      "post" : {
        "tags" : [ "A/B tests" ],
        "summary" : "End an active A/B test",
        "description" : "End an active A/B test and designate a winner.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/ab-test/end_endActiveABTest",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/ab-test/rerun" : {
      "post" : {
        "tags" : [ "A/B tests" ],
        "summary" : "Rerun a previous A/B test",
        "description" : "Rerun a previous A/B test.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/ab-test/rerun_rerunPreviousABTest",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Delete landing pages",
        "description" : "Delete landing pages specified by ID in the request body. Note: this is not the same as the dashboard `archive` function. To perform a dashboard `archive` send an normal update with the `archivedInDashboard` field set to `true`.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/batch/archive_archiveBatch",
        "security" : [ {
          "app_cookie" : [ "landingpages-publish", "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-publish", "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-publish", "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create landing pages",
        "description" : "Create a batch of landing pages as detailed in the request body.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/batch/create_createBatch",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve landing pages",
        "description" : "Retrieve a batch of landing pages as specified in the request body.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/batch/read_readBatch",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update landing pages",
        "description" : "Update a batch of landing pages as specified in the request body.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/batch/update_updateBatch",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/clone" : {
      "post" : {
        "tags" : [ "Landing pages" ],
        "summary" : "Clone a landing page",
        "description" : "Create a copy of an existing landing page.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/clone_clone",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/cursor" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/cms/pages/2026-03/landing-pages/cursor_/cms/pages/v3/landing-pages/cursor",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/cursor/query" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/cms/pages/2026-03/landing-pages/cursor/query_/cms/pages/v3/landing-pages/cursor/query",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/folders" : {
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Get all landing page folders",
        "description" : "Get the list of Landing Page Folders. Supports paging and filtering. This method would be useful for an integration that examined these models and used an external service to suggest edits.\n",
        "operationId" : "get-/cms/pages/2026-03/landing-pages/folders_getFoldersPage",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Folders" ],
        "summary" : "Create a landing page folder",
        "description" : "Create a new folder for landing pages.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/folders_createFolder",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/folders/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Delete folders",
        "description" : "Delete a batch of folders as specified in the request body.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/folders/batch/archive_archiveFolders",
        "security" : [ {
          "app_cookie" : [ "landingpages-publish", "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-publish", "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-publish", "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/folders/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create folders",
        "description" : "Create a batch of folders as detailed in the request body.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/folders/batch/create_createFolders",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/folders/batch/read" : {
      "post" : {
        "tags" : [ "Folders" ],
        "summary" : "Retrieve folders",
        "description" : "Retrieve a batch of landing page folders as identified in the request body.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/folders/batch/read_readFolders",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/folders/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update folders",
        "description" : "Update a batch of landing page folders as specified in the request body.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/folders/batch/update_updateFolders",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/folders/cursor" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/cms/pages/2026-03/landing-pages/folders/cursor_/cms/pages/v3/landing-pages/folders/cursor",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/folders/cursor/query" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/cms/pages/2026-03/landing-pages/folders/cursor/query_/cms/pages/v3/landing-pages/folders/cursor/query",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/folders/{objectId}" : {
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Retrieve a landing page folder",
        "description" : "Retrieve a landing page folder, specified by its ID.",
        "operationId" : "get-/cms/pages/2026-03/landing-pages/folders/{objectId}_getFolderById",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Folders" ],
        "summary" : "Delete a landing page folder",
        "description" : "Delete a landing page folder, specified by its ID.",
        "operationId" : "delete-/cms/pages/2026-03/landing-pages/folders/{objectId}_archiveFolder",
        "security" : [ {
          "app_cookie" : [ "landingpages-publish", "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-publish", "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-publish", "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Folders" ],
        "summary" : "Update a landing page folder",
        "description" : "Partially update a landing page folder, specified by the folder ID. You only need to specify the details values that you are modifying.\n",
        "operationId" : "patch-/cms/pages/2026-03/landing-pages/folders/{objectId}_updateFolder",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/folders/{objectId}/revisions" : {
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Retrieves previous versions of a folder",
        "description" : "Retrieves all the previous versions of a landing page folder.",
        "operationId" : "get-/cms/pages/2026-03/landing-pages/folders/{objectId}/revisions_getFolderPreviousVersions",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/folders/{objectId}/revisions/{revisionId}" : {
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Retrieve a previous version of a folder",
        "description" : "Retrieve a previous version of a folder, specified by the folder ID and revision ID.",
        "operationId" : "get-/cms/pages/2026-03/landing-pages/folders/{objectId}/revisions/{revisionId}_getFolderPreviousVersion",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/folders/{objectId}/revisions/{revisionId}/restore" : {
      "post" : {
        "tags" : [ "Folders" ],
        "summary" : "Restore a previous version of a folder",
        "description" : "Takes a specified version of a landing page folder and restores it.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/folders/{objectId}/revisions/{revisionId}/restore_restoreFolderPreviousVersion",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/multi-language/attach-to-lang-group" : {
      "post" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Add a landing page to a multi-language group",
        "description" : "Attach a landing page to a multi-language group.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/multi-language/attach-to-lang-group_attachToLangGroup",
        "security" : [ {
          "app_cookie" : [ "landingpages-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-multilanguage" ]
        }, {
          "oauth2" : [ "landingpages-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/multi-language/create-language-variation" : {
      "post" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Create a new language variation",
        "description" : "Create a new language variation from an existing landing page",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/multi-language/create-language-variation_createLangVariation",
        "security" : [ {
          "app_cookie" : [ "landingpages-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-multilanguage" ]
        }, {
          "oauth2" : [ "landingpages-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/multi-language/detach-from-lang-group" : {
      "post" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Remove a landing page from a multi-language group",
        "description" : "Detach a landing page from a multi-language group.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/multi-language/detach-from-lang-group_detachFromLangGroup",
        "security" : [ {
          "app_cookie" : [ "landingpages-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-multilanguage" ]
        }, {
          "oauth2" : [ "landingpages-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/multi-language/set-new-lang-primary" : {
      "put" : {
        "tags" : [ "Website pages" ],
        "summary" : "Set a new primary language",
        "description" : "Set a landing page as the primary language of a multi-language group.",
        "operationId" : "put-/cms/pages/2026-03/landing-pages/multi-language/set-new-lang-primary_setLangPrimary",
        "security" : [ {
          "app_cookie" : [ "landingpages-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-multilanguage" ]
        }, {
          "oauth2" : [ "landingpages-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/multi-language/update-languages" : {
      "post" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Update languages of multi-language group",
        "description" : "Explicitly set new languages for each landing page in a multi-language group.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/multi-language/update-languages_updateLangs",
        "security" : [ {
          "app_cookie" : [ "landingpages-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-multilanguage" ]
        }, {
          "oauth2" : [ "landingpages-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/schedule" : {
      "post" : {
        "tags" : [ "Landing pages" ],
        "summary" : "Schedule landing page publishing",
        "description" : "Schedule a landing page to be published.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/schedule_schedule",
        "security" : [ {
          "app_cookie" : [ "landingpages-publish" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-publish" ]
        }, {
          "oauth2" : [ "landingpages-publish" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/{objectId}" : {
      "get" : {
        "tags" : [ "Landing pages" ],
        "summary" : "Retrieve a landing page",
        "description" : "Retrieve a landing page, specified by its ID.",
        "operationId" : "get-/cms/pages/2026-03/landing-pages/{objectId}_getById",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Landing pages" ],
        "summary" : "Delete a landing page",
        "description" : "Delete a landing page, specified by its ID.",
        "operationId" : "delete-/cms/pages/2026-03/landing-pages/{objectId}_archive",
        "security" : [ {
          "app_cookie" : [ "landingpages-publish", "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-publish", "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-publish", "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Landing pages" ],
        "summary" : "Update a landing page",
        "description" : "Sparse updates a single Landing Page object identified by the id in the path.\nYou only need to specify the column values that you are modifying.",
        "operationId" : "patch-/cms/pages/2026-03/landing-pages/{objectId}_update",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/{objectId}/draft" : {
      "get" : {
        "tags" : [ "Landing pages" ],
        "summary" : "Retrieve a landing page draft",
        "description" : "Retrieve the full draft version of a landing page, specified by page ID.",
        "operationId" : "get-/cms/pages/2026-03/landing-pages/{objectId}/draft_getDraftById",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Landing pages" ],
        "summary" : "Update the draft of a landing page",
        "description" : "Partially updates the draft version of a single landing page, specified by its ID. You only need to specify the column values that you are modifying.\n",
        "operationId" : "patch-/cms/pages/2026-03/landing-pages/{objectId}/draft_updateDraft",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/{objectId}/draft/push-live" : {
      "post" : {
        "tags" : [ "Landing pages" ],
        "summary" : "Push Landing Page draft edits live",
        "description" : "Take any changes from the draft version of the Landing Page and apply them to the live version.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/{objectId}/draft/push-live_pushLive",
        "security" : [ {
          "app_cookie" : [ "landingpages-publish" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-publish" ]
        }, {
          "oauth2" : [ "landingpages-publish" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/{objectId}/draft/reset" : {
      "post" : {
        "tags" : [ "Landing pages" ],
        "summary" : "Reset a landing page draft",
        "description" : "Discards any edits and resets the draft to match the live version.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/{objectId}/draft/reset_resetDraft",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/{objectId}/revisions" : {
      "get" : {
        "tags" : [ "Advanced" ],
        "summary" : "Retrieve all previous versions of a landing page",
        "description" : "Retrieve all the previous versions of a landing page, specified by page ID.",
        "operationId" : "get-/cms/pages/2026-03/landing-pages/{objectId}/revisions_getPreviousVersions",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/{objectId}/revisions/{revisionId}" : {
      "get" : {
        "tags" : [ "Advanced" ],
        "summary" : "Retrieve a previous version of a landing page",
        "description" : "Retrieve a previous version of a landing page, specified by page ID and revision ID.",
        "operationId" : "get-/cms/pages/2026-03/landing-pages/{objectId}/revisions/{revisionId}_getPreviousVersion",
        "security" : [ {
          "app_cookie" : [ "landingpages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-access" ]
        }, {
          "oauth2" : [ "landingpages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/{objectId}/revisions/{revisionId}/restore" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Restore a previous version of a landing page",
        "description" : "Restores a previous version of a landing page, specified by page ID and revision ID.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/{objectId}/revisions/{revisionId}/restore_restorePreviousVersion",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/landing-pages/{objectId}/revisions/{revisionId}/restore-to-draft" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Restore a previous version of a landing page",
        "description" : "Specify a previous version of a landing page to set as the page draft.",
        "operationId" : "post-/cms/pages/2026-03/landing-pages/{objectId}/revisions/{revisionId}/restore-to-draft_restorePreviousVersionToDraft",
        "security" : [ {
          "app_cookie" : [ "landingpages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "landingpages-write" ]
        }, {
          "oauth2" : [ "landingpages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages" : {
      "get" : {
        "tags" : [ "Website pages" ],
        "summary" : "Retrieve all website pages",
        "description" : "Retrieve all website pages. Supports paging and filtering. This method would be useful for an integration that examined these models and used an external service to suggest edits.",
        "operationId" : "get-/cms/pages/2026-03/site-pages_getPage",
        "security" : [ {
          "app_cookie" : [ "pages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-access" ]
        }, {
          "oauth2" : [ "pages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Website pages" ],
        "summary" : "Create a website page",
        "description" : "Create a new website page.",
        "operationId" : "post-/cms/pages/2026-03/site-pages_create",
        "security" : [ {
          "app_cookie" : [ "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-write" ]
        }, {
          "oauth2" : [ "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/ab-test/create-variation" : {
      "post" : {
        "tags" : [ "A/B tests" ],
        "summary" : "Create a new A/B test variation",
        "description" : "Create a new A/B test variation based on the information provided in the request body.\n",
        "operationId" : "post-/cms/pages/2026-03/site-pages/ab-test/create-variation_createABTestVariation",
        "security" : [ {
          "app_cookie" : [ "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-write" ]
        }, {
          "oauth2" : [ "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/ab-test/end" : {
      "post" : {
        "tags" : [ "A/B tests" ],
        "summary" : "End an active A/B test",
        "description" : "End an active A/B test and designate a winner.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/ab-test/end_endActiveABTest",
        "security" : [ {
          "app_cookie" : [ "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-write" ]
        }, {
          "oauth2" : [ "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/ab-test/rerun" : {
      "post" : {
        "tags" : [ "A/B tests" ],
        "summary" : "Rerun a previous A/B test",
        "description" : "Rerun a previous A/B test.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/ab-test/rerun_rerunPreviousABTest",
        "security" : [ {
          "app_cookie" : [ "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-write" ]
        }, {
          "oauth2" : [ "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Delete website pages",
        "description" : "Delete a batch of website pages as specified in the request body. Note: this is not the same as the dashboard `archive` function. To perform a dashboard `archive` send an normal update with the `archivedInDashboard` field set to `true`.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/batch/archive_archiveBatch",
        "security" : [ {
          "app_cookie" : [ "pages-publish", "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-publish", "pages-write" ]
        }, {
          "oauth2" : [ "pages-publish", "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create website pages",
        "description" : "Create a batch of website pages as specified in the request body.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/batch/create_createBatch",
        "security" : [ {
          "app_cookie" : [ "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-write" ]
        }, {
          "oauth2" : [ "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve website pages",
        "description" : "Retrieve a batch of website pages as specified in the request body.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/batch/read_readBatch",
        "security" : [ {
          "app_cookie" : [ "pages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-access" ]
        }, {
          "oauth2" : [ "pages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update website pages",
        "description" : "Update a batch of website pages as specified in the request body.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/batch/update_updateBatch",
        "security" : [ {
          "app_cookie" : [ "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-write" ]
        }, {
          "oauth2" : [ "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/clone" : {
      "post" : {
        "tags" : [ "Website pages" ],
        "summary" : "Clone a website page",
        "description" : "Create a copy of an existing website page.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/clone_clone",
        "security" : [ {
          "app_cookie" : [ "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-write" ]
        }, {
          "oauth2" : [ "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/cursor" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/cms/pages/2026-03/site-pages/cursor_/cms/pages/v3/site-pages/cursor",
        "security" : [ {
          "app_cookie" : [ "pages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-access" ]
        }, {
          "oauth2" : [ "pages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/cursor/query" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/cms/pages/2026-03/site-pages/cursor/query_/cms/pages/v3/site-pages/cursor/query",
        "security" : [ {
          "app_cookie" : [ "pages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-access" ]
        }, {
          "oauth2" : [ "pages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/multi-language/attach-to-lang-group" : {
      "post" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Add a website page to a multi-language group",
        "description" : "Attach a site page to a multi-language group.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/multi-language/attach-to-lang-group_attachToLangGroup",
        "security" : [ {
          "app_cookie" : [ "sitepages-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "sitepages-multilanguage" ]
        }, {
          "oauth2" : [ "sitepages-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/multi-language/create-language-variation" : {
      "post" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Create a new language variation",
        "description" : "Create a new language variation from an existing site page",
        "operationId" : "post-/cms/pages/2026-03/site-pages/multi-language/create-language-variation_createLangVariation",
        "security" : [ {
          "app_cookie" : [ "sitepages-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "sitepages-multilanguage" ]
        }, {
          "oauth2" : [ "sitepages-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/multi-language/detach-from-lang-group" : {
      "post" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Remove a website page from a multi-language group",
        "description" : "Detach a website page from a multi-language group.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/multi-language/detach-from-lang-group_detachFromLangGroup",
        "security" : [ {
          "app_cookie" : [ "sitepages-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "sitepages-multilanguage" ]
        }, {
          "oauth2" : [ "sitepages-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/multi-language/set-new-lang-primary" : {
      "put" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Set a new primary language",
        "description" : "Set a site page as the primary language of a multi-language group.",
        "operationId" : "put-/cms/pages/2026-03/site-pages/multi-language/set-new-lang-primary_setLangPrimary",
        "security" : [ {
          "app_cookie" : [ "sitepages-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "sitepages-multilanguage" ]
        }, {
          "oauth2" : [ "sitepages-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/multi-language/update-languages" : {
      "post" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Update languages of multi-language group",
        "description" : "Explicitly set new languages for each site page in a multi-language group.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/multi-language/update-languages_updateLangs",
        "security" : [ {
          "app_cookie" : [ "sitepages-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "sitepages-multilanguage" ]
        }, {
          "oauth2" : [ "sitepages-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/schedule" : {
      "post" : {
        "tags" : [ "Website pages" ],
        "summary" : "Schedule a website page to be published",
        "description" : "Schedule a website page to published at a future time.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/schedule_schedule",
        "security" : [ {
          "app_cookie" : [ "pages-publish" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-publish" ]
        }, {
          "oauth2" : [ "pages-publish" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/{objectId}" : {
      "get" : {
        "tags" : [ "Website pages" ],
        "summary" : "Retrieve a website page",
        "description" : "Retrieve a website page by its ID.",
        "operationId" : "get-/cms/pages/2026-03/site-pages/{objectId}_getById",
        "security" : [ {
          "app_cookie" : [ "pages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-access" ]
        }, {
          "oauth2" : [ "pages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Website pages" ],
        "summary" : "Delete a website page",
        "description" : "Delete a website page, specified by its ID.",
        "operationId" : "delete-/cms/pages/2026-03/site-pages/{objectId}_archive",
        "security" : [ {
          "app_cookie" : [ "pages-publish", "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-publish", "pages-write" ]
        }, {
          "oauth2" : [ "pages-publish", "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Website pages" ],
        "summary" : "Update a website page",
        "description" : "Partially updates a single website page, specified by its ID. You only need to specify the column values that you are modifying.\n",
        "operationId" : "patch-/cms/pages/2026-03/site-pages/{objectId}_update",
        "security" : [ {
          "app_cookie" : [ "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-write" ]
        }, {
          "oauth2" : [ "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/{objectId}/draft" : {
      "get" : {
        "tags" : [ "Website pages" ],
        "summary" : "Retrieve a website page draft",
        "description" : "Retrieve the full draft version of a website page, specified by its ID.",
        "operationId" : "get-/cms/pages/2026-03/site-pages/{objectId}/draft_getDraftById",
        "security" : [ {
          "app_cookie" : [ "pages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-access" ]
        }, {
          "oauth2" : [ "pages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Website pages" ],
        "summary" : "Update a website page draft",
        "description" : "Partially update the draft version of a website page, specified by page ID. You only need to specify the values for the details that you're modifying.",
        "operationId" : "patch-/cms/pages/2026-03/site-pages/{objectId}/draft_updateDraft",
        "security" : [ {
          "app_cookie" : [ "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-write" ]
        }, {
          "oauth2" : [ "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/{objectId}/draft/push-live" : {
      "post" : {
        "tags" : [ "Website pages" ],
        "summary" : "Publish website page draft",
        "description" : "Take any changes from the draft version of the website page and apply them to the live version.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/{objectId}/draft/push-live_pushLive",
        "security" : [ {
          "app_cookie" : [ "pages-publish" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-publish" ]
        }, {
          "oauth2" : [ "pages-publish" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/{objectId}/draft/reset" : {
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Reset the draft of a website page",
        "description" : "Discards any edits and resets the draft to match the live version.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/{objectId}/draft/reset_resetDraft",
        "security" : [ {
          "app_cookie" : [ "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-write" ]
        }, {
          "oauth2" : [ "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/{objectId}/revisions" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve all previous versions of a website page",
        "description" : "Retrieves all the previous versions of a website page, specified by page ID.",
        "operationId" : "get-/cms/pages/2026-03/site-pages/{objectId}/revisions_getPreviousVersions",
        "security" : [ {
          "app_cookie" : [ "pages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-access" ]
        }, {
          "oauth2" : [ "pages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/{objectId}/revisions/{revisionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve a previous version of a website page",
        "description" : "Retrieve a previous version of a website page by the revision ID.",
        "operationId" : "get-/cms/pages/2026-03/site-pages/{objectId}/revisions/{revisionId}_getPreviousVersion",
        "security" : [ {
          "app_cookie" : [ "pages-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-access" ]
        }, {
          "oauth2" : [ "pages-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/{objectId}/revisions/{revisionId}/restore" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Restore a previous version of a website page",
        "description" : "Restores a website page to a previous version, specified by page ID and version ID.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/{objectId}/revisions/{revisionId}/restore_restorePreviousVersion",
        "security" : [ {
          "app_cookie" : [ "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-write" ]
        }, {
          "oauth2" : [ "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/pages/2026-03/site-pages/{objectId}/revisions/{revisionId}/restore-to-draft" : {
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Restore a previous draft of a website page",
        "description" : "Takes a specified version of a website page and sets it as the new draft version of the page.",
        "operationId" : "post-/cms/pages/2026-03/site-pages/{objectId}/revisions/{revisionId}/restore-to-draft_restorePreviousVersionToDraft",
        "security" : [ {
          "app_cookie" : [ "pages-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "pages-write" ]
        }, {
          "oauth2" : [ "pages-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm-import" : "",
              "crm-import-read" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}