{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Automation Sequences",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Enrollment"
  } ],
  "paths" : {
    "/automation/sequences/2026-09" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List sequences",
        "description" : "Retrieve a list of sequences for a specified user in your HubSpot account. This endpoint allows you to filter sequences by user ID and optionally paginate through results using a cursor. It is useful for managing and reviewing sequences associated with a particular user. ",
        "operationId" : "get-/automation/sequences/2026-09",
        "security" : [ {
          "oauth2" : [ "automation.sequences.read" ]
        } ]
      }
    },
    "/automation/sequences/2026-09/enrollments" : {
      "post" : {
        "tags" : [ "Enrollment" ],
        "summary" : "Enroll a contact",
        "description" : "Enroll a contact into a sequence using the specified sequence ID. This operation requires the user ID to be provided as a query parameter. The request body must include the contact ID, sender email, and sequence ID. This endpoint is useful for automating the enrollment of contacts into predefined sequences for streamlined communication and follow-up processes.",
        "operationId" : "post-/automation/sequences/2026-09/enrollments",
        "security" : [ {
          "oauth2" : [ "automation.sequences.enrollments.write" ]
        } ]
      }
    },
    "/automation/sequences/2026-09/enrollments/contact/{contactId}" : {
      "get" : {
        "tags" : [ "Enrollment" ],
        "summary" : "Retrieve enrollment details",
        "description" : "Retrieve the sequence enrollment details for a specific contact in your HubSpot account. This endpoint provides information about the sequence a contact is enrolled in, including enrollment dates and the sequence's name and ID.",
        "operationId" : "get-/automation/sequences/2026-09/enrollments/contact/{contactId}",
        "security" : [ {
          "oauth2" : [ "automation.sequences.read" ]
        } ]
      }
    },
    "/automation/sequences/2026-09/serviceaccounts/enrollments" : {
      "post" : {
        "tags" : [ "Enrollment" ],
        "summary" : "Enroll Service Account",
        "description" : "Enroll a service account into a sequence using the specified enrollment details. This endpoint is useful for automating the process of adding service accounts to sequences, which can help streamline workflows and ensure consistent engagement strategies. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.",
        "operationId" : "post-/automation/sequences/2026-09/serviceaccounts/enrollments",
        "security" : [ {
          "oauth2" : [ "automation.sequences.enrollments.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/automation/sequences/2026-09/serviceaccounts/sequences" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List sequences",
        "description" : "Retrieve a list of sequences available in the service account. This endpoint supports pagination and allows filtering by sequence name. It is useful for obtaining an overview of sequences for management or reporting purposes. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.",
        "operationId" : "get-/automation/sequences/2026-09/serviceaccounts/sequences",
        "security" : [ {
          "oauth2" : [ "automation.sequences.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create sequence",
        "description" : "Create a new sequence in your HubSpot account using the specified settings and steps. This endpoint allows you to define the sequence's properties, such as its name, settings, steps, and dependencies, to automate processes effectively. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.",
        "operationId" : "post-/automation/sequences/2026-09/serviceaccounts/sequences",
        "security" : [ {
          "oauth2" : [ "automation.sequences.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/automation/sequences/2026-09/serviceaccounts/sequences/{sequenceId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve sequence",
        "description" : "Retrieve details of a specific sequence in your HubSpot account using the sequence ID. This endpoint provides comprehensive information about the sequence, including its settings, steps, and dependencies. It is useful for obtaining sequence configurations and understanding the sequence's structure and components. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.",
        "operationId" : "get-/automation/sequences/2026-09/serviceaccounts/sequences/{sequenceId}",
        "security" : [ {
          "oauth2" : [ "automation.sequences.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update sequence",
        "description" : "Update an existing sequence in your HubSpot account using its unique identifier. This endpoint allows you to modify the sequence settings, steps, and dependencies. Ensure that the sequenceId provided in the path is valid and corresponds to the sequence you wish to update. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.",
        "operationId" : "put-/automation/sequences/2026-09/serviceaccounts/sequences/{sequenceId}",
        "security" : [ {
          "oauth2" : [ "automation.sequences.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete sequence",
        "description" : "Delete a specific sequence in your HubSpot account using its unique identifier. This operation will remove the sequence and can optionally override active enrollments if specified. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.",
        "operationId" : "delete-/automation/sequences/2026-09/serviceaccounts/sequences/{sequenceId}",
        "security" : [ {
          "oauth2" : [ "automation.sequences.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/automation/sequences/2026-09/serviceaccounts/sequences/{sequenceId}/performance" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve performance",
        "description" : "Retrieve the performance metrics of a specific sequence in your HubSpot account. This endpoint provides detailed insights into the sequence's effectiveness, including metrics such as opened, clicked, and replied rates. It is useful for analyzing the success of your sequences over time. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.",
        "operationId" : "get-/automation/sequences/2026-09/serviceaccounts/sequences/{sequenceId}/performance",
        "security" : [ {
          "oauth2" : [ "automation.sequences.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/automation/sequences/2026-09/{sequenceId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve sequence",
        "description" : "Retrieve details of a specific sequence in your HubSpot account using its unique identifier. This endpoint requires specifying the sequence ID and the user ID associated with the sequence. It is useful for accessing detailed information about a sequence's configuration and status. Please note: the scopes for this endpoint requires user-level access and will not work for existing apps with portal-level access.",
        "operationId" : "get-/automation/sequences/2026-09/{sequenceId}",
        "security" : [ {
          "oauth2" : [ "automation.sequences.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "automation.sequences.enrollments.write" : "",
              "automation.sequences.read" : "",
              "automation.sequences.write" : "",
              "sequences-public-delete" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}