{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Schemas",
    "description" : "The CRM uses schemas to define how custom objects should store and represent information in the HubSpot CRM. Schemas define details about an object's type, properties, and associations. The schema can be uniquely identified by its **object type ID**.",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "ENTERPRISE",
      "sales" : "ENTERPRISE",
      "service" : "ENTERPRISE",
      "cms" : "ENTERPRISE",
      "commerce" : "ENTERPRISE",
      "crmHub" : "ENTERPRISE",
      "dataHub" : "ENTERPRISE"
    },
    "x-hubspot-api-use-case" : "Create a new object for storing information about cars at a car dealership. Your object definition could include properties to store information as well as the filters available on the custom object index page.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Custom Object Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/objects/custom-objects"
    } ],
    "x-hubspot-introduction" : "Use the custom objects schema API to define new types of CRM records in your account. After setting up an object schema, you'll then be able to create records for that custom object both in HubSpot and using the objects API."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Core"
  }, {
    "name" : "Public_Object_Schemas"
  } ],
  "paths" : {
    "/crm-object-schemas/v3/schemas" : {
      "get" : {
        "tags" : [ "Core" ],
        "operationId" : "get-/crm-object-schemas/v3/schemas_getAll",
        "security" : [ {
          "oauth2" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        } ]
      },
      "post" : {
        "tags" : [ "Core" ],
        "operationId" : "post-/crm-object-schemas/v3/schemas_create",
        "security" : [ {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        } ]
      }
    },
    "/crm-object-schemas/v3/schemas/batch/read" : {
      "post" : {
        "tags" : [ "Public_Object_Schemas" ],
        "operationId" : "post-/crm-object-schemas/v3/schemas/batch/read_/crm-object-schemas/v3/schemas/batch/read",
        "security" : [ {
          "oauth2" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "oauth" ]
        } ]
      }
    },
    "/crm-object-schemas/v3/schemas/{objectType}" : {
      "get" : {
        "tags" : [ "Core" ],
        "operationId" : "get-/crm-object-schemas/v3/schemas/{objectType}_getById",
        "security" : [ {
          "oauth2" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "oauth" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Core" ],
        "operationId" : "delete-/crm-object-schemas/v3/schemas/{objectType}_archive",
        "security" : [ {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Core" ],
        "operationId" : "patch-/crm-object-schemas/v3/schemas/{objectType}_update",
        "security" : [ {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        } ]
      }
    },
    "/crm-object-schemas/v3/schemas/{objectType}/associations" : {
      "post" : {
        "tags" : [ "Core" ],
        "operationId" : "post-/crm-object-schemas/v3/schemas/{objectType}/associations_createAssociation",
        "security" : [ {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        } ]
      }
    },
    "/crm-object-schemas/v3/schemas/{objectType}/associations/{associationIdentifier}" : {
      "delete" : {
        "tags" : [ "Core" ],
        "operationId" : "delete-/crm-object-schemas/v3/schemas/{objectType}/associations/{associationIdentifier}_archiveAssociation",
        "security" : [ {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.custom.highly_sensitive.read.v2" : "View custom object records (highly-sensitive)",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.custom.sensitive.read.v2" : "View custom object records (sensitive)",
              "crm.schemas.custom.read" : "View custom object definitions",
              "crm.schemas.custom.write" : "Change custom object definitions",
              "oauth" : "Basic HubSpot account information"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "ENTERPRISE",
    "sales" : "ENTERPRISE",
    "service" : "ENTERPRISE",
    "cms" : "ENTERPRISE",
    "commerce" : "ENTERPRISE",
    "crmHub" : "ENTERPRISE",
    "dataHub" : "ENTERPRISE"
  }
}