{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Calling Extensions",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "sales" : "STARTER",
      "service" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "Create an integration for a third-party calling service that your company uses, rather than using HubSpot's native calling tool.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Call SDK Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/crm/extensions/calling-sdk"
    } ],
    "x-hubspot-introduction" : "Use the calling extensions SDK to provide HubSpot users with custom calling options on CRM records."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Call_Record"
  }, {
    "name" : "Settings"
  }, {
    "name" : "Recording settings"
  }, {
    "name" : "Calling_Event_Webhook_Subscriptions"
  }, {
    "name" : "Third_Party_Call_Crm_Object_Mapping"
  }, {
    "name" : "Calling_Event_Webhook_Target_Url"
  }, {
    "name" : "Channel_Connection_Settings"
  } ],
  "paths" : {
    "/crm/v3/extensions/calling/inbound-call-record" : {
      "post" : {
        "tags" : [ "Call_Record" ],
        "operationId" : "post-/crm/v3/extensions/calling/inbound-call-record",
        "security" : [ {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/{appId}/settings" : {
      "get" : {
        "tags" : [ "Settings" ],
        "summary" : "Get calling settings",
        "description" : "Returns the calling extension settings configured for your app.",
        "operationId" : "get-/crm/v3/extensions/calling/{appId}/settings_getById",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Settings" ],
        "summary" : "Configure a calling extension",
        "description" : "Used to set the menu label, target iframe URL, and dimensions for your calling extension.",
        "operationId" : "post-/crm/v3/extensions/calling/{appId}/settings_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Settings" ],
        "summary" : "Delete calling settings",
        "description" : "Deletes this calling extension. This will remove your service as an option for all connected accounts.",
        "operationId" : "delete-/crm/v3/extensions/calling/{appId}/settings_archive",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "patch" : {
        "tags" : [ "Settings" ],
        "summary" : "Update settings",
        "description" : "Updates existing calling extension settings.",
        "operationId" : "patch-/crm/v3/extensions/calling/{appId}/settings_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/{appId}/settings/recording" : {
      "get" : {
        "tags" : [ "Recording settings" ],
        "summary" : "Read calling app recording settings",
        "description" : "Retrieve the recording endpoint configured for a calling extension app.",
        "operationId" : "get-/crm/v3/extensions/calling/{appId}/settings/recording_getUrlFormat",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Recording settings" ],
        "summary" : "Register calling app for recording",
        "description" : "Configure a calling extension app with an external URL that HubSpot will use to retrieve call recordings.",
        "operationId" : "post-/crm/v3/extensions/calling/{appId}/settings/recording_registerUrlFormat",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "patch" : {
        "tags" : [ "Recording settings" ],
        "summary" : "Update calling app's recording settings",
        "description" : "Update the URL that HubSpot will use to retrieve call recordings for a calling extension app.",
        "operationId" : "patch-/crm/v3/extensions/calling/{appId}/settings/recording_updateUrlFormat",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/{appId}/settings/event-webhooks/subscriptions" : {
      "get" : {
        "tags" : [ "Calling_Event_Webhook_Subscriptions" ],
        "operationId" : "get-/crm/v3/extensions/calling/{appId}/settings/event-webhooks/subscriptions",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/call-object-mapping" : {
      "post" : {
        "tags" : [ "Third_Party_Call_Crm_Object_Mapping" ],
        "operationId" : "post-/crm/v3/extensions/calling/call-object-mapping",
        "security" : [ {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/{appId}/settings/event-webhooks" : {
      "get" : {
        "tags" : [ "Calling_Event_Webhook_Target_Url" ],
        "operationId" : "get-/crm/v3/extensions/calling/{appId}/settings/event-webhooks",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "put" : {
        "tags" : [ "Calling_Event_Webhook_Target_Url" ],
        "operationId" : "put-/crm/v3/extensions/calling/{appId}/settings/event-webhooks",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Calling_Event_Webhook_Target_Url" ],
        "operationId" : "post-/crm/v3/extensions/calling/{appId}/settings/event-webhooks",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Calling_Event_Webhook_Target_Url" ],
        "operationId" : "delete-/crm/v3/extensions/calling/{appId}/settings/event-webhooks",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/recordings/ready" : {
      "post" : {
        "tags" : [ "Recording settings" ],
        "summary" : "Mark recording as ready for transcription",
        "description" : "Mark a call recording as ready for transcription, specifying the call by its ID (`engagementid`).",
        "operationId" : "post-/crm/v3/extensions/calling/recordings/ready_markAsReady",
        "security" : [ {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/{appId}/settings/event-webhooks/subscriptions/{eventType}" : {
      "post" : {
        "tags" : [ "Calling_Event_Webhook_Subscriptions" ],
        "operationId" : "post-/crm/v3/extensions/calling/{appId}/settings/event-webhooks/subscriptions/{eventType}",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Calling_Event_Webhook_Subscriptions" ],
        "operationId" : "delete-/crm/v3/extensions/calling/{appId}/settings/event-webhooks/subscriptions/{eventType}",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/{appId}/settings/channel-connection" : {
      "get" : {
        "tags" : [ "Channel_Connection_Settings" ],
        "operationId" : "get-/crm/v3/extensions/calling/{appId}/settings/channel-connection",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Channel_Connection_Settings" ],
        "operationId" : "post-/crm/v3/extensions/calling/{appId}/settings/channel-connection",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Channel_Connection_Settings" ],
        "operationId" : "delete-/crm/v3/extensions/calling/{appId}/settings/channel-connection",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "patch" : {
        "tags" : [ "Channel_Connection_Settings" ],
        "operationId" : "patch-/crm/v3/extensions/calling/{appId}/settings/channel-connection",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.schemas.contacts.write" : " ",
              "crm.objects.contacts.write" : " ",
              "crm.objects.contacts.read" : " ",
              "crm.schemas.contacts.read" : " "
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "sales" : "STARTER",
    "service" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}