{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Calling Extensions",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "STARTER",
      "service" : "STARTER",
      "cms" : "FREE"
    },
    "x-hubspot-api-use-case" : "Create an integration for a third-party calling service that your company uses, rather than using HubSpot's native calling tool.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Call SDK Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/extensions/calling-sdk"
    } ],
    "x-hubspot-introduction" : "Use the calling extensions SDK to provide HubSpot users with custom calling options on CRM records."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Channel Connection Settings"
  }, {
    "name" : "Settings"
  }, {
    "name" : "Recording settings"
  } ],
  "paths" : {
    "/crm/v3/extensions/calling/{appId}/settings/recording" : {
      "get" : {
        "tags" : [ "Recording settings" ],
        "summary" : "Retrieve recording settings",
        "description" : "Retrieve the URL that is registered for [call recording](https://developers.hubspot.com/docs/guides/apps/extensions/calling-extensions/recordings-and-transcriptions#register-your-app-s-endpoint-with-hubspot-using-the-calling-settings-api).",
        "operationId" : "get-/crm/v3/extensions/calling/{appId}/settings/recording_getUrlFormat",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Recording settings" ],
        "summary" : "Enable the app for call recording",
        "description" : "Register an external URL that HubSpot will use to retrieve [call recordings](https://developers.hubspot.com/docs/guides/apps/extensions/calling-extensions/recordings-and-transcriptions#register-your-app-s-endpoint-with-hubspot-using-the-calling-settings-api).",
        "operationId" : "post-/crm/v3/extensions/calling/{appId}/settings/recording_registerUrlFormat",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "patch" : {
        "tags" : [ "Recording settings" ],
        "summary" : "Update recording settings",
        "description" : "Update the URL that HubSpot will use to retrieve [call recordings](https://developers.hubspot.com/docs/guides/apps/extensions/calling-extensions/recordings-and-transcriptions#register-your-app-s-endpoint-with-hubspot-using-the-calling-settings-api).",
        "operationId" : "patch-/crm/v3/extensions/calling/{appId}/settings/recording_updateUrlFormat",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/{appId}/settings" : {
      "get" : {
        "tags" : [ "Settings" ],
        "summary" : "Retrieve settings",
        "description" : "Retrieve the settings configured for the app.",
        "operationId" : "get-/crm/v3/extensions/calling/{appId}/settings_getById",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Settings" ],
        "summary" : "Configure a calling extension",
        "description" : "Set the menu label, target iframe URL, and dimensions for your calling extension.",
        "operationId" : "post-/crm/v3/extensions/calling/{appId}/settings_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Settings" ],
        "summary" : "Delete calling settings",
        "description" : "Delete a calling extension. This will remove your service as an option for all connected accounts.",
        "operationId" : "delete-/crm/v3/extensions/calling/{appId}/settings_archive",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "patch" : {
        "tags" : [ "Settings" ],
        "summary" : "Update settings",
        "description" : "Update existing calling extension settings.",
        "operationId" : "patch-/crm/v3/extensions/calling/{appId}/settings_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/recordings/ready" : {
      "post" : {
        "tags" : [ "Recording settings" ],
        "summary" : "Mark recording as ready for transcription",
        "description" : "Mark a call recording as ready for transcription, specifying the call by its ID (`engagementid`).",
        "operationId" : "post-/crm/v3/extensions/calling/recordings/ready_markAsReady",
        "security" : [ {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/{appId}/settings/channel-connection" : {
      "get" : {
        "tags" : [ "Channel Connection Settings" ],
        "summary" : "Retrieve channel connection settings",
        "description" : "Retrieve the settings related to the app's [channel connection](https://developers.hubspot.com/docs/guides/api/crm/extensions/third-party-calling#fetch-existing-channel-connection-settings).",
        "operationId" : "get-/crm/v3/extensions/calling/{appId}/settings/channel-connection_getById",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Channel Connection Settings" ],
        "summary" : "Configure channel connection settings",
        "description" : "Configure [channel connection settings](https://developers.hubspot.com/docs/guides/api/crm/extensions/third-party-calling#create-channel-connection-settings) for the app. ",
        "operationId" : "post-/crm/v3/extensions/calling/{appId}/settings/channel-connection_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Channel Connection Settings" ],
        "summary" : "Delete channel connection settings",
        "description" : "Delete the [channel connection settings](https://developers.hubspot.com/docs/guides/api/crm/extensions/third-party-calling#delete-existing-channel-connection-settings) for the app.",
        "operationId" : "delete-/crm/v3/extensions/calling/{appId}/settings/channel-connection_archive",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "patch" : {
        "tags" : [ "Channel Connection Settings" ],
        "summary" : "Update channel connection settings",
        "description" : "Update existing [channel connection settings](https://developers.hubspot.com/docs/guides/api/crm/extensions/third-party-calling#manage-the-webhook-settings-for-channel-connection) for your app.",
        "operationId" : "patch-/crm/v3/extensions/calling/{appId}/settings/channel-connection_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.contacts.write" : "Create or update contact records",
              "crm.objects.contacts.sensitive.write.v2" : "Create or update sensitive properties on contact records",
              "crm.schemas.contacts.write" : "Create new contact properties or change contact property settings",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.schemas.contacts.read" : "View contacts property settings",
              "crm.objects.contacts.sensitive.read.v2" : "View sensitive properties on contact records",
              "crm.objects.contacts.read" : "View contact records",
              "crm.extensions_calling_transcripts.write" : "Provides possibility to save and delete transcriptions",
              "crm.extensions_calling_transcripts.read" : "Provides possibility to read transcriptions"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "STARTER",
    "service" : "STARTER",
    "cms" : "FREE"
  }
}