{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Calling Extensions",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "Call SDK Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/extensions/calling-sdk"
    } ]
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Channel_Connection_Settings"
  }, {
    "name" : "Inbound_Call"
  }, {
    "name" : "Recording_Settings"
  }, {
    "name" : "Recordings"
  }, {
    "name" : "Settings"
  } ],
  "paths" : {
    "/crm/v3/extensions/calling/inbound-call" : {
      "post" : {
        "tags" : [ "Inbound_Call" ],
        "operationId" : "post-/crm/v3/extensions/calling/inbound-call_/crm/v3/extensions/calling/inbound-call",
        "security" : [ {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/recordings/ready" : {
      "post" : {
        "tags" : [ "Recordings" ],
        "summary" : "Mark a call recording as ready for retrieval.",
        "description" : "This endpoint is used to mark a call recording as ready. It requires the engagementId to identify the specific recording.",
        "operationId" : "post-/crm/v3/extensions/calling/recordings/ready_markAsReady",
        "security" : [ {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/{appId}/settings" : {
      "get" : {
        "tags" : [ "Settings" ],
        "summary" : "Retrieve the calling extension settings for a specific app.",
        "description" : "Retrieve the current settings of the calling extension for the specified appId. ",
        "operationId" : "get-/crm/v3/extensions/calling/{appId}/settings_get",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Settings" ],
        "summary" : "Create new calling extension settings for a specific app.",
        "description" : "Create new settings for the calling extension associated with the specified appId.",
        "operationId" : "post-/crm/v3/extensions/calling/{appId}/settings_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Settings" ],
        "summary" : "Delete the calling extension settings for a specific app.",
        "description" : "Remove the calling extension settings associated with the specified appId. This action cannot be undone.",
        "operationId" : "delete-/crm/v3/extensions/calling/{appId}/settings_remove",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "patch" : {
        "tags" : [ "Settings" ],
        "summary" : "Update the calling extension settings for a specific app.",
        "description" : "Modify existing calling extension settings for the specified appId. Only the fields provided in the request will be updated.",
        "operationId" : "patch-/crm/v3/extensions/calling/{appId}/settings_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/{appId}/settings/channel-connection" : {
      "get" : {
        "tags" : [ "Channel_Connection_Settings" ],
        "summary" : "Retrieve the channel connection settings for a specific app.",
        "description" : "Access the current channel connection settings for the specified app.",
        "operationId" : "get-/crm/v3/extensions/calling/{appId}/settings/channel-connection_get",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Channel_Connection_Settings" ],
        "summary" : "Create new channel connection settings for a specific app.",
        "description" : "Establish new channel connection settings for the specified app.",
        "operationId" : "post-/crm/v3/extensions/calling/{appId}/settings/channel-connection_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Channel_Connection_Settings" ],
        "summary" : "Remove the channel connection settings for a specific app.",
        "description" : "Delete the channel connection settings associated with the specified app.",
        "operationId" : "delete-/crm/v3/extensions/calling/{appId}/settings/channel-connection_remove",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "patch" : {
        "tags" : [ "Channel_Connection_Settings" ],
        "summary" : "Update the channel connection settings for a specific app.",
        "description" : "Modify the existing channel connection settings for the specified app.",
        "operationId" : "patch-/crm/v3/extensions/calling/{appId}/settings/channel-connection_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/crm/v3/extensions/calling/{appId}/settings/recording" : {
      "get" : {
        "tags" : [ "Recording_Settings" ],
        "summary" : "Retrieve recording settings for an app.",
        "description" : "Retrieve the current recording settings for a specific app using the provided app ID.",
        "operationId" : "get-/crm/v3/extensions/calling/{appId}/settings/recording_get",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Recording_Settings" ],
        "summary" : "Create recording settings for an app.",
        "description" : "Create new recording settings for a specific app using the provided app ID.",
        "operationId" : "post-/crm/v3/extensions/calling/{appId}/settings/recording_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "patch" : {
        "tags" : [ "Recording_Settings" ],
        "summary" : "Update recording settings for an app.",
        "description" : "Update the recording settings for a specific app using the provided app ID.",
        "operationId" : "patch-/crm/v3/extensions/calling/{appId}/settings/recording_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.extensions_calling_transcripts.read" : "Provides possibility to read transcriptions",
              "crm.extensions_calling_transcripts.write" : "Provides possibility to save and delete transcriptions",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.contacts.read" : "View contact records",
              "crm.objects.contacts.sensitive.read.v2" : "View sensitive properties on contact records",
              "crm.objects.contacts.sensitive.write.v2" : "Create or update sensitive properties on contact records",
              "crm.objects.contacts.write" : "Create or update contact records",
              "crm.schemas.contacts.read" : "View contacts property settings",
              "crm.schemas.contacts.write" : "Create new contact properties or change contact property settings"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}