{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Conversations Conversations",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "Inbox & Messages Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/conversations/inbox-and-messages"
    } ]
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Public_Actor"
  }, {
    "name" : "Public_Channel"
  }, {
    "name" : "Public_Channel_Account"
  }, {
    "name" : "Public_Inbox"
  }, {
    "name" : "Public_Message"
  }, {
    "name" : "Public_Thread"
  } ],
  "paths" : {
    "/conversations/v3/conversations/actors/batch/read" : {
      "post" : {
        "tags" : [ "Public_Actor" ],
        "operationId" : "post-/conversations/v3/conversations/actors/batch/read",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/actors/{actorId}" : {
      "get" : {
        "tags" : [ "Public_Actor" ],
        "operationId" : "get-/conversations/v3/conversations/actors/{actorId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/channel-accounts" : {
      "get" : {
        "tags" : [ "Public_Channel_Account" ],
        "operationId" : "get-/conversations/v3/conversations/channel-accounts",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/channel-accounts/{channelAccountId}" : {
      "get" : {
        "tags" : [ "Public_Channel_Account" ],
        "operationId" : "get-/conversations/v3/conversations/channel-accounts/{channelAccountId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/channels" : {
      "get" : {
        "tags" : [ "Public_Channel" ],
        "operationId" : "get-/conversations/v3/conversations/channels",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/channels/{channelId}" : {
      "get" : {
        "tags" : [ "Public_Channel" ],
        "operationId" : "get-/conversations/v3/conversations/channels/{channelId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/inboxes" : {
      "get" : {
        "tags" : [ "Public_Inbox" ],
        "operationId" : "get-/conversations/v3/conversations/inboxes",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/inboxes/{inboxId}" : {
      "get" : {
        "tags" : [ "Public_Inbox" ],
        "operationId" : "get-/conversations/v3/conversations/inboxes/{inboxId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads" : {
      "get" : {
        "tags" : [ "Public_Thread" ],
        "operationId" : "get-/conversations/v3/conversations/threads",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads/{threadId}" : {
      "get" : {
        "tags" : [ "Public_Thread" ],
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Public_Thread" ],
        "operationId" : "delete-/conversations/v3/conversations/threads/{threadId}",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        }, {
          "private_apps" : [ "conversations.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Public_Thread" ],
        "operationId" : "patch-/conversations/v3/conversations/threads/{threadId}",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        }, {
          "private_apps" : [ "conversations.write" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads/{threadId}/messages" : {
      "get" : {
        "tags" : [ "Public_Message" ],
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}/messages",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Public_Message" ],
        "operationId" : "post-/conversations/v3/conversations/threads/{threadId}/messages",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        }, {
          "private_apps" : [ "conversations.write" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads/{threadId}/messages/{messageId}" : {
      "get" : {
        "tags" : [ "Public_Message" ],
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}/messages/{messageId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads/{threadId}/messages/{messageId}/original-content" : {
      "get" : {
        "tags" : [ "Public_Message" ],
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}/messages/{messageId}/original-content",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        }, {
          "private_apps" : [ "conversations.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "conversations.read" : "Read from conversations",
              "conversations.write" : "Write to conversations"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}