{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Appointments",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/objects/2026-09/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Batch" ],
        "summary" : "Create Association",
        "description" : "Create the default association type between two specified object types in HubSpot. This endpoint is used to establish a generic association between two objects, identified by their types and IDs. It is useful for linking related objects within the CRM, enabling better data organization and relationship tracking.",
        "operationId" : "put-/crm/objects/2026-09/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}_/crm/objects/2026-09-beta/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{objectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List",
        "description" : "Read a page of appointments. Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/objects/2026-09/{objectType}_/crm/objects/2026-09-beta/{objectType}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create",
        "description" : "Create a appointment with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard appointments is provided.",
        "operationId" : "post-/crm/objects/2026-09/{objectType}_/crm/objects/2026-09-beta/{objectType}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{objectType}/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Archive a batch of appointments by ID",
        "description" : "Archive multiple appointments using their IDs.",
        "operationId" : "post-/crm/objects/2026-09/{objectType}/batch/archive_/crm/objects/2026-09-beta/{objectType}/batch/archive",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{objectType}/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of appointments",
        "description" : "Create multiple appointments in a single request.",
        "operationId" : "post-/crm/objects/2026-09/{objectType}/batch/create_/crm/objects/2026-09-beta/{objectType}/batch/create",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{objectType}/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of appointments by internal ID, or unique property values",
        "description" : "Retrieve records by record ID or include the `idProperty` parameter to retrieve records by a custom unique value property. ",
        "operationId" : "post-/crm/objects/2026-09/{objectType}/batch/read_/crm/objects/2026-09-beta/{objectType}/batch/read",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{objectType}/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update a batch of appointments by internal ID, or unique property values",
        "description" : "Update a batch of CRM objects of a specified type in HubSpot. This endpoint allows you to modify multiple objects in a single request, making it efficient for bulk updates. The request body must include the objects and their properties to be updated.",
        "operationId" : "post-/crm/objects/2026-09/{objectType}/batch/update_/crm/objects/2026-09-beta/{objectType}/batch/update",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{objectType}/batch/upsert" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create or update a batch of appointments by unique property values",
        "description" : "Create or update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
        "operationId" : "post-/crm/objects/2026-09/{objectType}/batch/upsert_/crm/objects/2026-09-beta/{objectType}/batch/upsert",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{objectType}/gdpr-delete" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "GDPR-delete an object",
        "description" : "Fully purge an object type and any GDPR related data",
        "operationId" : "post-/crm/objects/2026-09/{objectType}/gdpr-delete_/crm/objects/2026-09-beta/{objectType}/gdpr-delete",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ]
      }
    },
    "/crm/objects/2026-09/{objectType}/merge" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Merge objects",
        "description" : "Merge two object types together",
        "operationId" : "post-/crm/objects/2026-09/{objectType}/merge_/crm/objects/2026-09-beta/{objectType}/merge",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{objectType}/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "summary" : "Search",
        "description" : "Search for appointments based on specified criteria. Learn more about [CRM search](https://developers.hubspot.com/docs/guides/api/crm/search#make-a-search-request).",
        "operationId" : "post-/crm/objects/2026-09/{objectType}/search_/crm/objects/2026-09-beta/{objectType}/search",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{objectType}/{objectId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read",
        "description" : "Read an Object identified by `{appointmentId}`. `{appointmentId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/objects/2026-09/{objectType}/{objectId}_/crm/objects/2026-09-beta/{objectType}/{objectId}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archive",
        "description" : "Move an Object identified by `{appointmentId}` to the recycling bin.",
        "operationId" : "delete-/crm/objects/2026-09/{objectType}/{objectId}_/crm/objects/2026-09-beta/{objectType}/{objectId}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update",
        "description" : "Perform a partial update of an Object identified by `{appointmentId}`or optionally a unique property value as specified by the `idProperty` query param. `{appointmentId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty str[...]",
        "operationId" : "patch-/crm/objects/2026-09/{objectType}/{objectId}_/crm/objects/2026-09-beta/{objectType}/{objectId}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{objectType}/{objectId}/associations/{toObjectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List associations",
        "description" : "Retrieve associated object IDs for a given object type.",
        "operationId" : "get-/crm/objects/2026-09/{objectType}/{objectId}/associations/{toObjectType}_/crm/objects/2026-09-beta/{objectType}/{objectId}/associations/{toObjectType}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Create Association",
        "description" : "Set association labels between two records in the CRM. This endpoint allows you to define relationships between different object types by specifying association labels. It is useful for organizing and managing interconnected data within your HubSpot account.",
        "operationId" : "put-/crm/objects/2026-09/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_/crm/objects/2026-09-beta/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete",
        "description" : "Delete all associations between two specified records in the CRM. This operation is useful when you need to remove the relationship between two objects, such as contacts or deals, without deleting the objects themselves.",
        "operationId" : "delete-/crm/objects/2026-09/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_/crm/objects/2026-09-beta/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.appointments.read" : "",
              "crm.objects.appointments.sensitive.read.v2" : "",
              "crm.objects.appointments.sensitive.write.v2" : "",
              "crm.objects.appointments.write" : "",
              "crm.objects.calls.read" : "",
              "crm.objects.carts.read" : "",
              "crm.objects.carts.write" : "",
              "crm.objects.commercepayments.read" : "",
              "crm.objects.commercepayments.write" : "",
              "crm.objects.companies.highly_sensitive.read.v2" : "",
              "crm.objects.companies.highly_sensitive.write.v2" : "",
              "crm.objects.companies.read" : "",
              "crm.objects.companies.sensitive.read.v2" : "",
              "crm.objects.companies.sensitive.write.v2" : "",
              "crm.objects.companies.write" : "",
              "crm.objects.contacts.highly_sensitive.read.v2" : "",
              "crm.objects.contacts.highly_sensitive.write.v2" : "",
              "crm.objects.contacts.read" : "",
              "crm.objects.contacts.sensitive.read.v2" : "",
              "crm.objects.contacts.sensitive.write.v2" : "",
              "crm.objects.contacts.write" : "",
              "crm.objects.courses.read" : "",
              "crm.objects.courses.write" : "",
              "crm.objects.custom.highly_sensitive.read.v2" : "",
              "crm.objects.custom.highly_sensitive.write.v2" : "",
              "crm.objects.custom.read" : "",
              "crm.objects.custom.sensitive.read.v2" : "",
              "crm.objects.custom.sensitive.write.v2" : "",
              "crm.objects.custom.write" : "",
              "crm.objects.deals.highly_sensitive.read.v2" : "",
              "crm.objects.deals.highly_sensitive.write.v2" : "",
              "crm.objects.deals.read" : "",
              "crm.objects.deals.sensitive.read.v2" : "",
              "crm.objects.deals.sensitive.write.v2" : "",
              "crm.objects.deals.write" : "",
              "crm.objects.emails.read" : "",
              "crm.objects.goals.read" : "",
              "crm.objects.goals.write" : "",
              "crm.objects.invoices.read" : "",
              "crm.objects.invoices.write" : "",
              "crm.objects.leads.read" : "",
              "crm.objects.leads.write" : "",
              "crm.objects.line_items.read" : "",
              "crm.objects.line_items.write" : "",
              "crm.objects.listings.read" : "",
              "crm.objects.listings.write" : "",
              "crm.objects.meetings.read" : "",
              "crm.objects.notes.read" : "",
              "crm.objects.orders.read" : "",
              "crm.objects.orders.write" : "",
              "crm.objects.partner-clients.read" : "",
              "crm.objects.partner-clients.write" : "",
              "crm.objects.partner-services.read" : "",
              "crm.objects.partner-services.write" : "",
              "crm.objects.products.read" : "",
              "crm.objects.products.write" : "",
              "crm.objects.projects.highly_sensitive.read" : "",
              "crm.objects.projects.highly_sensitive.write" : "",
              "crm.objects.projects.read" : "",
              "crm.objects.projects.sensitive.read" : "",
              "crm.objects.projects.sensitive.write" : "",
              "crm.objects.projects.write" : "",
              "crm.objects.quotes.read" : "",
              "crm.objects.quotes.write" : "",
              "crm.objects.services.read" : "",
              "crm.objects.services.write" : "",
              "crm.objects.subscriptions.read" : "",
              "crm.objects.subscriptions.write" : "",
              "crm.objects.tasks.read" : "",
              "crm.objects.tickets.highly_sensitive.read" : "",
              "crm.objects.tickets.highly_sensitive.write" : "",
              "crm.objects.tickets.sensitive.read" : "",
              "crm.objects.tickets.sensitive.write" : "",
              "crm.objects.users.read" : "",
              "crm.objects.users.write" : "",
              "e-commerce" : "",
              "media_bridge.read" : "",
              "oauth" : "",
              "oauth-access" : "",
              "tickets.highly_sensitive.v2" : "",
              "tickets.sensitive.v2" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}