{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Services",
    "description" : "CRM objects such as companies, contacts, deals, line items, products, tickets, and quotes are standard objects in HubSpot’s CRM. These core building blocks support custom properties, store critical information, and play a central role in the HubSpot application.\n\n## Supported Object Types\n\nThis API provides access to collections of CRM objects, which return a map of property names to values. Each object type has its own set of default properties, which can be found by ex[...]",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Batch"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/v3/objects/{objectType}/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of objects by internal ID, or unique property values",
        "description" : "Retrieve records by record ID or include the `idProperty` parameter to retrieve records by a custom unique value property. ",
        "operationId" : "post-/crm/v3/objects/{objectType}/batch/read",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        } ]
      }
    },
    "/crm/v3/objects/{objectType}/{objectId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read",
        "description" : "Read an Object identified by `{objectId}`. `{objectId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/v3/objects/{objectType}/{objectId}",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archive",
        "description" : "Move an Object identified by `{objectId}` to the recycling bin.",
        "operationId" : "delete-/crm/v3/objects/{objectType}/{objectId}",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update",
        "description" : "Perform a partial update of an Object identified by `{objectId}`or optionally a unique property value as specified by the `idProperty` query param. `{objectId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
        "operationId" : "patch-/crm/v3/objects/{objectType}/{objectId}",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        } ]
      }
    },
    "/crm/v3/objects/{objectType}/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Archive a batch of objects by ID",
        "operationId" : "post-/crm/v3/objects/{objectType}/batch/archive",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        } ]
      }
    },
    "/crm/v3/objects/{objectType}/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of objects",
        "operationId" : "post-/crm/v3/objects/{objectType}/batch/create",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        } ]
      }
    },
    "/crm/v3/objects/{objectType}/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update a batch of objects by internal ID, or unique property values",
        "operationId" : "post-/crm/v3/objects/{objectType}/batch/update",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        } ]
      }
    },
    "/crm/v3/objects/{objectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List",
        "description" : "Read a page of objects. Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/v3/objects/{objectType}",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create",
        "description" : "Create a CRM object with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard objects is provided.",
        "operationId" : "post-/crm/v3/objects/{objectType}",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        } ]
      }
    },
    "/crm/v3/objects/{objectType}/batch/upsert" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create or update a batch of objects by unique property values",
        "description" : "Create or update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
        "operationId" : "post-/crm/v3/objects/{objectType}/batch/upsert",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        } ]
      }
    },
    "/crm/v3/objects/{objectType}/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "operationId" : "post-/crm/v3/objects/{objectType}/search",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.deals.read" : " ",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.services.read" : "Read services",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.listings.write" : "Write listings",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.companies.write" : " ",
              "crm.objects.custom.sensitive.write.v2" : "Change custom object records (sensitive)",
              "crm.objects.custom.highly_sensitive.write.v2" : "Change custom object records (highly-sensitive)",
              "crm.objects.companies.read" : " ",
              "crm.objects.appointments.sensitive.read.v2" : "Read appointments (sensitive)",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.objects.companies.sensitive.read.v2" : " ",
              "media_bridge.read" : "Read media and media events",
              "crm.objects.deals.highly_sensitive.read.v2" : "View deal records (highly-sensitive)",
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.read.v2" : "View company records (highly-sensitive)",
              "crm.objects.commercepayments.write" : "Write commerce payments",
              "crm.objects.invoices.write" : "Write invoices",
              "crm.objects.contacts.sensitive.write.v2" : " ",
              "crm.objects.users.write" : "Write User CRM objects",
              "crm.objects.custom.sensitive.read.v2" : "View custom object records (sensitive)",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.partner-services.read" : "View Partner Service CRM objects",
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.partner-services.write" : "Modify Partner Service CRM objects",
              "crm.objects.appointments.write" : "Write appointments",
              "crm.objects.carts.write" : "Write cart",
              "tickets" : "Read and write tickets",
              "crm.objects.commercepayments.read" : "Read the COMMERCE_PAYMENT object.",
              "crm.objects.products.write" : "Write to my Product Library",
              "crm.objects.services.write" : "Write services",
              "crm.objects.subscriptions.write" : "Write to Commerce Subscriptions",
              "crm.objects.deals.sensitive.write.v2" : " ",
              "crm.objects.contacts.read" : " ",
              "crm.objects.appointments.sensitive.write.v2" : "Write appointments (sensitive)",
              "crm.objects.invoices.read" : "Read invoices objects",
              "tickets.sensitive.v2" : "Tickets (sensitive)",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.deals.write" : " ",
              "e-commerce" : "e-commerce",
              "crm.objects.appointments.read" : "Read appointments",
              "crm.objects.companies.sensitive.write.v2" : " ",
              "crm.objects.deals.highly_sensitive.write.v2" : "Change deal records (highly-sensitive)",
              "crm.objects.custom.highly_sensitive.read.v2" : "View custom object records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.write.v2" : "Change company records (highly-sensitive)",
              "crm.objects.goals.write" : "Write goals",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.contacts.write" : " ",
              "crm.objects.goals.read" : "Read goals",
              "crm.objects.partner-clients.write" : "Modify Partner Client CRM objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.deals.sensitive.read.v2" : " ",
              "tickets.highly_sensitive.v2" : "Tickets (highly-sensitive)",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.courses.write" : "Write courses",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.courses.read" : "Read courses",
              "crm.objects.listings.read" : "Read listings",
              "crm.objects.contacts.sensitive.read.v2" : " ",
              "crm.objects.products.read" : "Read from my Product Library"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  }
}