{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Marketing Emails",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "You want to programmatically create marketing emails, then retrieve their send statistics at a later time.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Marketing Emails Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/marketing/emails/marketing-emails"
    } ],
    "x-hubspot-introduction" : "Use the marketing email API to create, manage, and retrieve details about marketing emails. You can also this use API to retrieve statistics related to email sends, similar to what you can see in HubSpot."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Emails"
  }, {
    "name" : "Marketing Emails"
  }, {
    "name" : "Statistics"
  } ],
  "paths" : {
    "/marketing/v3/emails/" : {
      "get" : {
        "tags" : [ "Marketing Emails" ],
        "summary" : "Get all marketing emails",
        "description" : "The results can be filtered, allowing you to find a specific set of emails. See the table below for a full list of filtering options.",
        "operationId" : "get-/marketing/v3/emails/_getPage",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      },
      "post" : {
        "tags" : [ "Emails" ],
        "summary" : "Create a new marketing email",
        "description" : "Use this endpoint to create a new marketing email.",
        "operationId" : "post-/marketing/v3/emails/_create",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/ab-test/create-variation" : {
      "post" : {
        "tags" : [ "Emails" ],
        "summary" : "Create an A/B test variation of a marketing email",
        "description" : "Create a variation of a marketing email for an A/B test. The new variation will be created as a draft. If an active variation already exists, a new one won't be created.",
        "operationId" : "post-/marketing/v3/emails/ab-test/create-variation_createAbTestVariation",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/clone" : {
      "post" : {
        "tags" : [ "Emails" ],
        "summary" : "Clone a marketing email",
        "description" : "This will create a duplicate email with the same properties as the original, with the exception of a unique ID.",
        "operationId" : "post-/marketing/v3/emails/clone_clone",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/statistics/histogram" : {
      "get" : {
        "tags" : [ "Statistics" ],
        "summary" : "Get aggregated statistic intervals",
        "description" : "Get aggregated statistics in intervals for a specified time span. Each interval contains aggregated statistics of the emails that were sent in that time.",
        "operationId" : "get-/marketing/v3/emails/statistics/histogram_getHistogram",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/statistics/list" : {
      "get" : {
        "tags" : [ "Statistics" ],
        "summary" : "Get aggregated statistics",
        "description" : "Use this endpoint to get aggregated statistics of emails sent in a specified time span. It also returns the list of emails that were sent during the time span.",
        "operationId" : "get-/marketing/v3/emails/statistics/list_getEmailsList",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/{emailId}" : {
      "get" : {
        "tags" : [ "Emails" ],
        "summary" : "Get the details of a specified marketing email",
        "description" : "Get the details for a marketing email.",
        "operationId" : "get-/marketing/v3/emails/{emailId}_getById",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Emails" ],
        "summary" : "Delete a marketing email",
        "description" : "Delete a marketing email by its ID",
        "operationId" : "delete-/marketing/v3/emails/{emailId}_archive",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Emails" ],
        "summary" : "Update a marketing email",
        "description" : "Change properties of a marketing email.",
        "operationId" : "patch-/marketing/v3/emails/{emailId}_update",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/{emailId}/ab-test/get-variation" : {
      "get" : {
        "tags" : [ "Emails" ],
        "summary" : "Get the variation of a an A/B marketing email",
        "description" : "This endpoint lets you obtain the variation of an A/B marketing email. If the email is variation A (master) it will return variation B (variant) and vice versa.",
        "operationId" : "get-/marketing/v3/emails/{emailId}/ab-test/get-variation_getAbTestVariation",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/{emailId}/draft" : {
      "get" : {
        "tags" : [ "Marketing Emails" ],
        "summary" : "Get draft version of a marketing email",
        "description" : "Get the draft version of an email (if it exists). If no draft version exists, the published email is returned.",
        "operationId" : "get-/marketing/v3/emails/{emailId}/draft_getDraft",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Marketing Emails" ],
        "summary" : "Create or update draft version",
        "description" : "Create or update the draft version of a marketing email. If no draft exists, the system creates a draft from the current “live” email then applies the request body to that draft. The draft version only lives on the buffer—the email is not cloned.",
        "operationId" : "patch-/marketing/v3/emails/{emailId}/draft_upsertDraft",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/{emailId}/draft/reset" : {
      "post" : {
        "tags" : [ "Marketing Emails" ],
        "summary" : "Reset the draft version",
        "description" : "Resets the draft back to a copy of the live object.",
        "operationId" : "post-/marketing/v3/emails/{emailId}/draft/reset_resetDraft",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/{emailId}/publish" : {
      "post" : {
        "tags" : [ "Emails" ],
        "summary" : "Publish or send a marketing email",
        "description" : "If you have a Marketing Hub Enterprise account or the transactional email add-on, you can use this endpoint to publish an automated email or send/schedule a regular email.",
        "operationId" : "post-/marketing/v3/emails/{emailId}/publish_publishOrSend",
        "security" : [ {
          "oauth2" : [ "marketing-email" ]
        }, {
          "oauth2" : [ "transactional-email" ]
        }, {
          "private_apps" : [ "marketing-email" ]
        }, {
          "private_apps" : [ "transactional-email" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/marketing/v3/emails/{emailId}/revisions" : {
      "get" : {
        "tags" : [ "Marketing Emails" ],
        "summary" : "Get revisions of a marketing email",
        "description" : "Get a list of all versions of a marketing email, with each entry including the full state of that particular version. To view the most recent version, sort by the updatedAt parameter. ",
        "operationId" : "get-/marketing/v3/emails/{emailId}/revisions_getRevisions",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/{emailId}/revisions/{revisionId}" : {
      "get" : {
        "tags" : [ "Marketing Emails" ],
        "summary" : "Get a revision of a marketing email",
        "description" : "Get a specific revision of a marketing email.",
        "operationId" : "get-/marketing/v3/emails/{emailId}/revisions/{revisionId}_getRevisionById",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/{emailId}/revisions/{revisionId}/restore" : {
      "post" : {
        "tags" : [ "Marketing Emails" ],
        "summary" : "Restore a revision of a marketing email",
        "description" : "Restores a previous revision of a marketing email. The current revision becomes old, and the restored revision is given a new version number.",
        "operationId" : "post-/marketing/v3/emails/{emailId}/revisions/{revisionId}/restore_restoreRevision",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/{emailId}/revisions/{revisionId}/restore-to-draft" : {
      "post" : {
        "tags" : [ "Marketing Emails" ],
        "summary" : "Restore a revision of a marketing email to DRAFT state",
        "description" : "Restores a previous revision of a marketing email to DRAFT state. If there is currently something in the draft for that object, it is overwritten. ",
        "operationId" : "post-/marketing/v3/emails/{emailId}/revisions/{revisionId}/restore-to-draft_restoreDraftRevision",
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/marketing/v3/emails/{emailId}/unpublish" : {
      "post" : {
        "tags" : [ "Emails" ],
        "summary" : "Unpublish or cancel a marketing email",
        "description" : "If you have a Marketing Hub Enterprise account or the transactional email add-on, you can use this endpoint to unpublish an automated email or cancel a regular email. If the email is already in the process of being sent, canceling might not be possible.",
        "operationId" : "post-/marketing/v3/emails/{emailId}/unpublish_unpublishOrCancel",
        "security" : [ {
          "oauth2" : [ "marketing-email" ]
        }, {
          "oauth2" : [ "transactional-email" ]
        }, {
          "private_apps" : [ "marketing-email" ]
        }, {
          "private_apps" : [ "transactional-email" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "content" : "Content",
              "marketing-email" : "Marketing Single Send API access",
              "transactional-email" : "Access to transactional emails"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}