{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Webhooks Webhooks",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2027-03-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  } ],
  "paths" : {
    "/app-webhooks/2027-03-beta/{appId}/settings" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/app-webhooks/2027-03-beta/{appId}/settings",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        }, {
          "oauth2" : [ "private-apps-read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/app-webhooks/2027-03-beta/{appId}/settings",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        }, {
          "oauth2" : [ "private-apps-write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/app-webhooks/2027-03-beta/{appId}/settings",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        }, {
          "oauth2" : [ "private-apps-write" ]
        } ]
      }
    },
    "/app-webhooks/2027-03-beta/{appId}/subscriptions" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/app-webhooks/2027-03-beta/{appId}/subscriptions",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        }, {
          "oauth2" : [ "private-apps-read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "operationId" : "post-/app-webhooks/2027-03-beta/{appId}/subscriptions",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        }, {
          "oauth2" : [ "private-apps-write" ]
        } ]
      }
    },
    "/app-webhooks/2027-03-beta/{appId}/subscriptions/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "operationId" : "post-/app-webhooks/2027-03-beta/{appId}/subscriptions/batch/update",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        }, {
          "oauth2" : [ "private-apps-write" ]
        } ]
      }
    },
    "/app-webhooks/2027-03-beta/{appId}/subscriptions/{subscriptionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/app-webhooks/2027-03-beta/{appId}/subscriptions/{subscriptionId}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        }, {
          "oauth2" : [ "private-apps-read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/app-webhooks/2027-03-beta/{appId}/subscriptions/{subscriptionId}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        }, {
          "oauth2" : [ "private-apps-write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "operationId" : "patch-/app-webhooks/2027-03-beta/{appId}/subscriptions/{subscriptionId}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        }, {
          "oauth2" : [ "private-apps-write" ]
        } ]
      }
    },
    "/webhooks-journal/journal-local/2027-03-beta/batch/earliest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "operationId" : "get-/webhooks-journal/journal-local/2027-03-beta/batch/earliest/{count}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2027-03-beta/batch/latest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "operationId" : "get-/webhooks-journal/journal-local/2027-03-beta/batch/latest/{count}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2027-03-beta/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "operationId" : "post-/webhooks-journal/journal-local/2027-03-beta/batch/read",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2027-03-beta/batch/{offset}/next/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "operationId" : "get-/webhooks-journal/journal-local/2027-03-beta/batch/{offset}/next/{count}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2027-03-beta/earliest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal-local/2027-03-beta/earliest",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2027-03-beta/latest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal-local/2027-03-beta/latest",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2027-03-beta/offset/{offset}/next" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal-local/2027-03-beta/offset/{offset}/next",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2027-03-beta/status/{statusId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal-local/2027-03-beta/status/{statusId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-snapshot-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2027-03-beta/batch/earliest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "operationId" : "get-/webhooks-journal/journal/2027-03-beta/batch/earliest/{count}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2027-03-beta/batch/latest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "operationId" : "get-/webhooks-journal/journal/2027-03-beta/batch/latest/{count}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2027-03-beta/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "operationId" : "post-/webhooks-journal/journal/2027-03-beta/batch/read",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2027-03-beta/batch/{offset}/next/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "operationId" : "get-/webhooks-journal/journal/2027-03-beta/batch/{offset}/next/{count}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2027-03-beta/earliest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal/2027-03-beta/earliest",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2027-03-beta/latest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal/2027-03-beta/latest",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2027-03-beta/offset/{offset}/next" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal/2027-03-beta/offset/{offset}/next",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2027-03-beta/status/{statusId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal/2027-03-beta/status/{statusId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-snapshot-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/snapshots/2027-03-beta/crm" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "operationId" : "post-/webhooks-journal/snapshots/2027-03-beta/crm",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-snapshot-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2027-03-beta" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/subscriptions/2027-03-beta",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "operationId" : "post-/webhooks-journal/subscriptions/2027-03-beta",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2027-03-beta/filters" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "operationId" : "post-/webhooks-journal/subscriptions/2027-03-beta/filters",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2027-03-beta/filters/subscription/{subscriptionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/subscriptions/2027-03-beta/filters/subscription/{subscriptionId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2027-03-beta/filters/{filterId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/subscriptions/2027-03-beta/filters/{filterId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/webhooks-journal/subscriptions/2027-03-beta/filters/{filterId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2027-03-beta/portals/{portalId}" : {
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/webhooks-journal/subscriptions/2027-03-beta/portals/{portalId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2027-03-beta/{subscriptionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/subscriptions/2027-03-beta/{subscriptionId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/webhooks-journal/subscriptions/2027-03-beta/{subscriptionId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "developers-read" : "",
              "developers-write" : "",
              "private-apps-read" : "",
              "private-apps-write" : "",
              "webhooks-journal-data-access" : "",
              "webhooks-journal-snapshot-management" : "",
              "webhooks-journal-subscription-management" : "",
              "webhooks-journal-subscription-read" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}