{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Webhooks Webhooks",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  } ],
  "paths" : {
    "/webhooks-journal/journal-local/2026-03/batch/earliest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve earliest batch",
        "description" : "Retrieve the earliest batch of webhook journal entries up to a specified count. This endpoint is useful for accessing the oldest records available in the webhook journal, allowing you to process or analyze historical webhook data.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/batch/earliest/{count}_/webhooks-journal/journal-local/2026-03/batch/earliest/{count}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/batch/latest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve latest batch",
        "description" : "Retrieve the latest batch of webhook journal entries up to a specified count. This endpoint is useful for fetching the most recent webhook events processed by the system. It requires authentication and supports various security schemes.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/batch/latest/{count}_/webhooks-journal/journal-local/2026-03/batch/latest/{count}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch read",
        "description" : "Perform a batch read operation on the webhooks journal. This endpoint allows you to retrieve a batch of journal entries by providing the necessary input data. It is useful for processing large volumes of webhook data efficiently.",
        "operationId" : "post-/webhooks-journal/journal-local/2026-03/batch/read_/webhooks-journal/journal-local/2026-03/batch/read",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/batch/{offset}/next/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "summary" : "Fetch Batch",
        "description" : "Retrieve a batch of webhook journal entries starting from a specified offset. This endpoint is useful for fetching sequential batches of data, allowing you to paginate through large sets of webhook journal entries efficiently.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/batch/{offset}/next/{count}_/webhooks-journal/journal-local/2026-03/batch/{offset}/next/{count}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/earliest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve earliest",
        "description" : "Retrieve the earliest entry from the webhooks journal for the specified portal. This endpoint is useful for accessing the oldest available data in the journal, which can be used for historical analysis or troubleshooting.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/earliest_/webhooks-journal/journal-local/2026-03/earliest",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/latest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve latest",
        "description" : "Retrieve the latest entries from the webhooks journal. This endpoint is useful for accessing the most recent webhook data for analysis or troubleshooting. It supports filtering by the installPortalId to narrow down results to a specific portal.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/latest_/webhooks-journal/journal-local/2026-03/latest",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/offset/{offset}/next" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve next journal",
        "description" : "Retrieve the next set of journal entries starting from a specified offset. This endpoint is useful for paginating through webhook journal entries in a sequential manner. It requires specifying the offset from which the next entries should be fetched.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/offset/{offset}/next_/webhooks-journal/journal-local/2026-03/offset/{offset}/next",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/status/{statusId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve status",
        "description" : "Retrieve the status of a specific webhook journal entry using its unique status ID. This endpoint is useful for checking the progress or result of a webhook operation, such as whether it is pending, in progress, completed, failed, or expired.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/status/{statusId}_/webhooks-journal/journal-local/2026-03/status/{statusId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/batch/earliest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "summary" : "Fetch Earliest Batch",
        "description" : "Retrieve the earliest batch of webhook journal entries up to the specified count. This endpoint is useful for fetching historical webhook data in batches, allowing you to process or analyze them as needed.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/batch/earliest/{count}_/webhooks-journal/journal/2026-03/batch/earliest/{count}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/batch/latest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve latest batch",
        "description" : "Retrieve the latest batch of webhook journal entries up to a specified count. This endpoint is useful for fetching the most recent webhook events processed by your HubSpot account. The response includes details about each event, and you can specify the number of entries to retrieve.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/batch/latest/{count}_/webhooks-journal/journal/2026-03/batch/latest/{count}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read Batch",
        "description" : "Read a batch of webhook journal entries for the specified portal. This endpoint allows you to retrieve detailed information about webhook events processed by your HubSpot account. It is useful for auditing and tracking webhook activity.",
        "operationId" : "post-/webhooks-journal/journal/2026-03/batch/read_/webhooks-journal/journal/2026-03/batch/read",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/batch/{offset}/next/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve batch",
        "description" : "Retrieve a batch of webhook journal entries starting from a specified offset. This endpoint allows you to specify the number of entries to retrieve, helping you manage and paginate through large sets of webhook data efficiently.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/batch/{offset}/next/{count}_/webhooks-journal/journal/2026-03/batch/{offset}/next/{count}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/earliest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve earliest entry",
        "description" : "Retrieve the earliest entry from the webhooks journal for the specified portal. This endpoint is useful for accessing the initial entries in the journal, which can be helpful for debugging or auditing purposes.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/earliest_/webhooks-journal/journal/2026-03/earliest",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/latest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve latest entry",
        "description" : "Retrieve the latest entry from the webhooks journal for the specified portal. This endpoint is useful for accessing the most recent webhook data available in the journal.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/latest_/webhooks-journal/journal/2026-03/latest",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/offset/{offset}/next" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve Next Journal",
        "description" : "Retrieve the next set of webhook journal entries starting from a specified offset. This endpoint is useful for paginating through webhook journal entries in a HubSpot account. It allows you to continue fetching entries from where the last request left off, using the offset parameter.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/offset/{offset}/next_/webhooks-journal/journal/2026-03/offset/{offset}/next",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/status/{statusId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve status",
        "description" : "Retrieve the status of a specific webhook journal entry using its unique status ID. This endpoint is useful for monitoring the progress or outcome of a webhook operation, providing insights into whether it is pending, in progress, completed, failed, or expired.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/status/{statusId}_/webhooks-journal/journal/2026-03/status/{statusId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/snapshots/2026-03/crm" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create Snapshot",
        "description" : "Create a batch of CRM object snapshots for a specified portal. This endpoint allows you to capture the current state of CRM objects by submitting a batch request with the necessary object details. It is useful for tracking changes or maintaining historical records of CRM data.",
        "operationId" : "post-/webhooks-journal/snapshots/2026-03/crm_/webhooks-journal/snapshots/2026-03/crm",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List Subscriptions",
        "description" : "Retrieve a list of webhook journal subscriptions for the specified version. This endpoint allows you to view all active subscriptions without pagination. It is useful for managing and auditing webhook subscriptions in your HubSpot account.",
        "operationId" : "get-/webhooks-journal/subscriptions/2026-03_/webhooks-journal/subscriptions/2026-03",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create Subscription",
        "description" : "Create a new subscription in the webhooks journal for the specified version. This endpoint allows you to define the subscription details, including actions and object types, to manage webhook events effectively. It requires a valid request body with the subscription details.",
        "operationId" : "post-/webhooks-journal/subscriptions/2026-03_/webhooks-journal/subscriptions/2026-03",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/filters" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create Filter",
        "description" : "Create a new filter for a webhook subscription in the HubSpot account. This endpoint allows you to define conditions that determine when a webhook event should be triggered for a specific subscription. The request body must include the subscription ID and the filter details.",
        "operationId" : "post-/webhooks-journal/subscriptions/2026-03/filters_/webhooks-journal/subscriptions/2026-03/filters",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/filters/subscription/{subscriptionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve filters",
        "description" : "Retrieve the filters associated with a specific webhook subscription. This endpoint is useful for obtaining detailed information about the filters applied to a subscription, which can help in managing and understanding the data flow through your webhook integrations.",
        "operationId" : "get-/webhooks-journal/subscriptions/2026-03/filters/subscription/{subscriptionId}_/webhooks-journal/subscriptions/2026-03/filters/subscription/{subscriptionId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/filters/{filterId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve filter",
        "description" : "Retrieve a specific filter associated with a webhook journal subscription. This endpoint allows you to access detailed information about the filter identified by the filterId path parameter. It is useful for managing and reviewing filter configurations within your webhook subscriptions.",
        "operationId" : "get-/webhooks-journal/subscriptions/2026-03/filters/{filterId}_/webhooks-journal/subscriptions/2026-03/filters/{filterId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete filter",
        "description" : "Remove a specific filter from your webhook journal subscriptions. This operation is useful when you need to clean up or modify the filters applied to your webhook subscriptions. The filter identified by the filterId will be permanently deleted.",
        "operationId" : "delete-/webhooks-journal/subscriptions/2026-03/filters/{filterId}_/webhooks-journal/subscriptions/2026-03/filters/{filterId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/portals/{portalId}" : {
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete subscription",
        "description" : "Delete a webhook journal subscription for a specific portal. This operation removes the subscription associated with the given portalId, effectively stopping any webhook events from being sent to the portal.",
        "operationId" : "delete-/webhooks-journal/subscriptions/2026-03/portals/{portalId}_/webhooks-journal/subscriptions/2026-03/portals/{portalId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/{subscriptionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve subscription",
        "description" : "Retrieve details of a specific webhook journal subscription using its unique identifier. This endpoint is useful for obtaining information about a particular subscription, such as its actions, object types, and associated properties.",
        "operationId" : "get-/webhooks-journal/subscriptions/2026-03/{subscriptionId}_/webhooks-journal/subscriptions/2026-03/{subscriptionId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete subscription",
        "description" : "Delete a specific webhook journal subscription using its unique identifier. This operation is useful for managing and cleaning up subscriptions that are no longer needed.",
        "operationId" : "delete-/webhooks-journal/subscriptions/2026-03/{subscriptionId}_/webhooks-journal/subscriptions/2026-03/{subscriptionId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks/2026-03/{appId}/settings" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read webhook settings",
        "description" : "Retrieve the webhook settings for the specified app, including the webhook’s target URL, throttle configuration, and create/update date.",
        "operationId" : "get-/webhooks/2026-03/{appId}/settings_getAll",
        "security" : [ {
          "app_cookie" : [ "developers-read", "private-apps-read" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-read", "private-apps-read" ]
        }, {
          "oauth2" : [ "developers-read", "private-apps-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update webhook settings",
        "description" : "Update webhook settings for the specified app.",
        "operationId" : "put-/webhooks/2026-03/{appId}/settings_configure",
        "security" : [ {
          "app_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete webhook settings",
        "description" : "Delete the webhook settings for the specified app. Event subscriptions will not be deleted, but will be paused until another webhook is created.",
        "operationId" : "delete-/webhooks/2026-03/{appId}/settings_clear",
        "security" : [ {
          "app_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/webhooks/2026-03/{appId}/subscriptions" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read event subscriptions",
        "description" : "Retrieve event subscriptions for the specified app.",
        "operationId" : "get-/webhooks/2026-03/{appId}/subscriptions_getAll",
        "security" : [ {
          "app_cookie" : [ "developers-read", "private-apps-read" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-read", "private-apps-read" ]
        }, {
          "oauth2" : [ "developers-read", "private-apps-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create an event subscription",
        "description" : "Create new event subscription for the specified app.",
        "operationId" : "post-/webhooks/2026-03/{appId}/subscriptions_create",
        "security" : [ {
          "app_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/webhooks/2026-03/{appId}/subscriptions/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch create event subscriptions",
        "description" : "Batch create event subscriptions for the specified app.",
        "operationId" : "post-/webhooks/2026-03/{appId}/subscriptions/batch/update_updateBatch",
        "security" : [ {
          "app_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/webhooks/2026-03/{appId}/subscriptions/{subscriptionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read an event subscription",
        "description" : "Retrieve a specific event subscription by ID.",
        "operationId" : "get-/webhooks/2026-03/{appId}/subscriptions/{subscriptionId}_getById",
        "security" : [ {
          "app_cookie" : [ "developers-read", "private-apps-read" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-read", "private-apps-read" ]
        }, {
          "oauth2" : [ "developers-read", "private-apps-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete event subscription",
        "description" : "Delete an existing event subscription by ID.",
        "operationId" : "delete-/webhooks/2026-03/{appId}/subscriptions/{subscriptionId}_archive",
        "security" : [ {
          "app_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update an event subscription",
        "description" : "Update an existing event subscription by ID.",
        "operationId" : "patch-/webhooks/2026-03/{appId}/subscriptions/{subscriptionId}_update",
        "security" : [ {
          "app_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token"
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}