{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Webhooks Webhooks",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  } ],
  "paths" : {
    "/webhooks-journal/journal-local/2026-03/batch/earliest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve Batch",
        "description" : "Retrieve the earliest batch of webhook journal entries based on the specified count. This endpoint is useful for fetching a specific number of the earliest entries in the webhook journal for analysis or processing.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/batch/earliest/{count}_/webhooks-journal/journal-local/2026-03/batch/earliest/{count}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/batch/latest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve latest batch",
        "description" : "Retrieve the latest batch of webhook journal entries. This endpoint is useful for accessing the most recent data entries processed by the webhook journal. It requires specifying the number of entries to retrieve.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/batch/latest/{count}_/webhooks-journal/journal-local/2026-03/batch/latest/{count}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch read",
        "description" : "Perform a batch read operation on the webhooks journal. This endpoint allows you to read multiple entries from the journal in a single request. It requires a JSON request body specifying the inputs to be read. The response includes the results of the batch read operation, and may return multiple statuses if there are errors.",
        "operationId" : "post-/webhooks-journal/journal-local/2026-03/batch/read_/webhooks-journal/journal-local/2026-03/batch/read",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/batch/{offset}/next/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve batch",
        "description" : "Retrieve a batch of webhook journal entries starting from a specified offset. This endpoint allows you to fetch a defined number of entries, facilitating the processing of webhook data in manageable chunks.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/batch/{offset}/next/{count}_/webhooks-journal/journal-local/2026-03/batch/{offset}/next/{count}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/earliest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve earliest",
        "description" : "Retrieve the earliest entry from the webhooks journal for the specified portal. This endpoint is useful for accessing the oldest records in the journal, which can be helpful for auditing or tracking purposes.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/earliest_/webhooks-journal/journal-local/2026-03/earliest",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/latest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve latest journal",
        "description" : "Retrieve the latest entries from the webhooks journal for the specified portal. This endpoint is useful for accessing the most recent webhook events that have been logged, allowing you to process or analyze them as needed.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/latest_/webhooks-journal/journal-local/2026-03/latest",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/offset/{offset}/next" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve Next Batch",
        "description" : "Retrieve the next set of webhook journal entries starting from a specified offset. This endpoint is useful for paginating through webhook journal data in a sequential manner, allowing you to fetch entries beyond a given point.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/offset/{offset}/next_/webhooks-journal/journal-local/2026-03/offset/{offset}/next",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/status/{statusId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve status",
        "description" : "Retrieve the status of a specific webhook journal entry using its unique status ID. This endpoint is useful for monitoring the progress or completion of webhook processing tasks.",
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/status/{statusId}_/webhooks-journal/journal-local/2026-03/status/{statusId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-snapshot-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/batch/earliest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve Batch",
        "description" : "Retrieve the earliest batch of webhook journal entries up to the specified count. This endpoint is useful for fetching historical webhook data in batches, allowing you to process or analyze the earliest entries first.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/batch/earliest/{count}_/webhooks-journal/journal/2026-03/batch/earliest/{count}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/batch/latest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve latest batch",
        "description" : "Retrieve the latest batch of webhook journal entries. This endpoint allows you to specify the number of entries to fetch, providing a way to access recent webhook activity within your HubSpot account.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/batch/latest/{count}_/webhooks-journal/journal/2026-03/batch/latest/{count}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch read",
        "description" : "Perform a batch read operation on the webhooks journal for the specified date. This endpoint allows you to retrieve multiple entries from the webhooks journal in a single request, which can be useful for processing large amounts of data efficiently.",
        "operationId" : "post-/webhooks-journal/journal/2026-03/batch/read_/webhooks-journal/journal/2026-03/batch/read",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/batch/{offset}/next/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "summary" : "Fetch Batch Entries",
        "description" : "Retrieve a batch of webhook journal entries starting from a specified offset. This endpoint allows you to fetch a specified number of entries, making it useful for paginating through large sets of webhook journal data.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/batch/{offset}/next/{count}_/webhooks-journal/journal/2026-03/batch/{offset}/next/{count}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/earliest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve earliest",
        "description" : "Retrieve the earliest entry from the webhooks journal for the specified version. This endpoint is useful for accessing the oldest records available in the journal, which can be helpful for auditing or historical data analysis.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/earliest_/webhooks-journal/journal/2026-03/earliest",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/latest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve latest journal",
        "description" : "Retrieve the latest entries from the webhooks journal for the specified portal. This endpoint is useful for accessing the most recent webhook events processed by your HubSpot account. It allows you to filter the results by the portal ID to ensure you are retrieving data relevant to a specific installation.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/latest_/webhooks-journal/journal/2026-03/latest",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/offset/{offset}/next" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve Next Batch",
        "description" : "Retrieve the next batch of webhook journal entries starting from a specified offset. This endpoint is useful for paginating through large sets of webhook data, allowing you to continue fetching entries from where you last left off.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/offset/{offset}/next_/webhooks-journal/journal/2026-03/offset/{offset}/next",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-data-access" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/status/{statusId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve status",
        "description" : "Retrieve the status of a specific webhook journal entry using its status ID. This endpoint is useful for checking the current state of a webhook process, such as whether it is pending, in progress, completed, failed, or expired.",
        "operationId" : "get-/webhooks-journal/journal/2026-03/status/{statusId}_/webhooks-journal/journal/2026-03/status/{statusId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-snapshot-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/snapshots/2026-03/crm" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create Snapshot",
        "description" : "Create a batch of CRM object snapshots for the specified portal. This endpoint allows you to capture the state of CRM objects at a specific point in time, which can be useful for auditing or historical analysis. The request requires a list of CRM object snapshot requests, each specifying the portal ID, object ID, object type ID, and properties to include in the snapshot.",
        "operationId" : "post-/webhooks-journal/snapshots/2026-03/crm_/webhooks-journal/snapshots/2026-03/crm",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-snapshot-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List subscriptions",
        "description" : "Retrieve a list of webhook journal subscriptions for the specified API version. This endpoint provides details about each subscription, including actions, object types, and associated properties. It is useful for managing and reviewing current webhook subscriptions.",
        "operationId" : "get-/webhooks-journal/subscriptions/2026-03_/webhooks-journal/subscriptions/2026-03",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create Subscription",
        "description" : "Create a new webhook subscription for the specified portal in the HubSpot account. This endpoint allows you to define the subscription details, including the types of events you want to subscribe to. The request body must include the necessary subscription information as defined by the SubscriptionUpsertRequest schema.",
        "operationId" : "post-/webhooks-journal/subscriptions/2026-03_/webhooks-journal/subscriptions/2026-03",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/filters" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create Filter",
        "description" : "Create a new filter for a webhook subscription in your HubSpot account. This endpoint allows you to define specific conditions that a webhook event must meet to trigger the subscription. It is useful for managing and customizing the behavior of webhook subscriptions based on specific criteria.",
        "operationId" : "post-/webhooks-journal/subscriptions/2026-03/filters_/webhooks-journal/subscriptions/2026-03/filters",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/filters/subscription/{subscriptionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve Filters",
        "description" : "Retrieve the filters associated with a specific webhook subscription in the HubSpot account. This endpoint is useful for obtaining detailed information about the filters applied to a given subscription, identified by its subscription ID.",
        "operationId" : "get-/webhooks-journal/subscriptions/2026-03/filters/subscription/{subscriptionId}_/webhooks-journal/subscriptions/2026-03/filters/subscription/{subscriptionId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/filters/{filterId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve filter",
        "description" : "Retrieve details of a specific filter associated with a webhook subscription in the HubSpot account. This endpoint is useful for accessing the configuration and conditions of a filter by its unique identifier.",
        "operationId" : "get-/webhooks-journal/subscriptions/2026-03/filters/{filterId}_/webhooks-journal/subscriptions/2026-03/filters/{filterId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete filter",
        "description" : "Delete a specific filter associated with a webhook journal subscription. This operation is useful for managing and cleaning up filters that are no longer needed in your subscription setup. The endpoint requires the unique identifier of the filter to be deleted.",
        "operationId" : "delete-/webhooks-journal/subscriptions/2026-03/filters/{filterId}_/webhooks-journal/subscriptions/2026-03/filters/{filterId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/portals/{portalId}" : {
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete subscription",
        "description" : "Delete a webhook journal subscription for a specific portal. This operation removes the subscription associated with the given portalId, and no content is returned upon successful deletion.",
        "operationId" : "delete-/webhooks-journal/subscriptions/2026-03/portals/{portalId}_/webhooks-journal/subscriptions/2026-03/portals/{portalId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/{subscriptionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve subscription",
        "description" : "Retrieve details of a specific webhook subscription using its unique identifier. This endpoint is useful for obtaining information about a particular subscription's configuration and status within the HubSpot account.",
        "operationId" : "get-/webhooks-journal/subscriptions/2026-03/{subscriptionId}_/webhooks-journal/subscriptions/2026-03/{subscriptionId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete subscription",
        "description" : "Delete a specific webhook journal subscription using its unique identifier. This operation is useful for managing and cleaning up subscriptions that are no longer needed or relevant.",
        "operationId" : "delete-/webhooks-journal/subscriptions/2026-03/{subscriptionId}_/webhooks-journal/subscriptions/2026-03/{subscriptionId}",
        "security" : [ {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks/2026-03/{appId}/settings" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read webhook settings",
        "description" : "Retrieve the webhook settings for the specified app, including the webhook’s target URL, throttle configuration, and create/update date.",
        "operationId" : "get-/webhooks/2026-03/{appId}/settings_getAll",
        "security" : [ {
          "oauth2" : [ "developers-read", "private-apps-read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update webhook settings",
        "description" : "Update webhook settings for the specified app.",
        "operationId" : "put-/webhooks/2026-03/{appId}/settings_configure",
        "security" : [ {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete webhook settings",
        "description" : "Delete the webhook settings for the specified app. Event subscriptions will not be deleted, but will be paused until another webhook is created.",
        "operationId" : "delete-/webhooks/2026-03/{appId}/settings_clear",
        "security" : [ {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        } ]
      }
    },
    "/webhooks/2026-03/{appId}/subscriptions" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read event subscriptions",
        "description" : "Retrieve event subscriptions for the specified app.",
        "operationId" : "get-/webhooks/2026-03/{appId}/subscriptions_getAll",
        "security" : [ {
          "oauth2" : [ "developers-read", "private-apps-read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create an event subscription",
        "description" : "Create new event subscription for the specified app.",
        "operationId" : "post-/webhooks/2026-03/{appId}/subscriptions_create",
        "security" : [ {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        } ]
      }
    },
    "/webhooks/2026-03/{appId}/subscriptions/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch create event subscriptions",
        "description" : "Batch create event subscriptions for the specified app.",
        "operationId" : "post-/webhooks/2026-03/{appId}/subscriptions/batch/update_updateBatch",
        "security" : [ {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        } ]
      }
    },
    "/webhooks/2026-03/{appId}/subscriptions/{subscriptionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read an event subscription",
        "description" : "Retrieve a specific event subscription by ID.",
        "operationId" : "get-/webhooks/2026-03/{appId}/subscriptions/{subscriptionId}_getById",
        "security" : [ {
          "oauth2" : [ "developers-read", "private-apps-read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete event subscription",
        "description" : "Delete an existing event subscription by ID.",
        "operationId" : "delete-/webhooks/2026-03/{appId}/subscriptions/{subscriptionId}_archive",
        "security" : [ {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update an event subscription",
        "description" : "Update an existing event subscription by ID.",
        "operationId" : "patch-/webhooks/2026-03/{appId}/subscriptions/{subscriptionId}_update",
        "security" : [ {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "developers-read" : "",
              "developers-write" : "",
              "private-apps-read" : "",
              "private-apps-write" : "",
              "webhooks-journal-data-access" : "",
              "webhooks-journal-snapshot-management" : "",
              "webhooks-journal-subscription-management" : "",
              "webhooks-journal-subscription-read" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}