{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Webhooks Webhooks",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  } ],
  "paths" : {
    "/webhooks-journal/journal-local/2026-03/batch/earliest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/batch/earliest/{count}_/webhooks-journal/journal-local/2026-03/batch/earliest/{count}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/batch/latest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/batch/latest/{count}_/webhooks-journal/journal-local/2026-03/batch/latest/{count}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "operationId" : "post-/webhooks-journal/journal-local/2026-03/batch/read_/webhooks-journal/journal-local/2026-03/batch/read",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/batch/{offset}/next/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/batch/{offset}/next/{count}_/webhooks-journal/journal-local/2026-03/batch/{offset}/next/{count}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/earliest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/earliest_/webhooks-journal/journal-local/2026-03/earliest",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/latest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/latest_/webhooks-journal/journal-local/2026-03/latest",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/offset/{offset}/next" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/offset/{offset}/next_/webhooks-journal/journal-local/2026-03/offset/{offset}/next",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal-local/2026-03/status/{statusId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal-local/2026-03/status/{statusId}_/webhooks-journal/journal-local/2026-03/status/{statusId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/batch/earliest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "operationId" : "get-/webhooks-journal/journal/2026-03/batch/earliest/{count}_/webhooks-journal/journal/2026-03/batch/earliest/{count}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/batch/latest/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "operationId" : "get-/webhooks-journal/journal/2026-03/batch/latest/{count}_/webhooks-journal/journal/2026-03/batch/latest/{count}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "operationId" : "post-/webhooks-journal/journal/2026-03/batch/read_/webhooks-journal/journal/2026-03/batch/read",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/batch/{offset}/next/{count}" : {
      "get" : {
        "tags" : [ "Batch" ],
        "operationId" : "get-/webhooks-journal/journal/2026-03/batch/{offset}/next/{count}_/webhooks-journal/journal/2026-03/batch/{offset}/next/{count}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/earliest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal/2026-03/earliest_/webhooks-journal/journal/2026-03/earliest",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/latest" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal/2026-03/latest_/webhooks-journal/journal/2026-03/latest",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/offset/{offset}/next" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal/2026-03/offset/{offset}/next_/webhooks-journal/journal/2026-03/offset/{offset}/next",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-data-access" ]
        }, {
          "oauth2" : [ "webhooks-journal-data-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/journal/2026-03/status/{statusId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/journal/2026-03/status/{statusId}_/webhooks-journal/journal/2026-03/status/{statusId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/snapshots/2026-03/crm" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "operationId" : "post-/webhooks-journal/snapshots/2026-03/crm_/webhooks-journal/snapshots/2026-03/crm",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-snapshot-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/subscriptions/2026-03_/webhooks-journal/subscriptions/2026-03",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "operationId" : "post-/webhooks-journal/subscriptions/2026-03_/webhooks-journal/subscriptions/2026-03",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/filters" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "operationId" : "post-/webhooks-journal/subscriptions/2026-03/filters_/webhooks-journal/subscriptions/2026-03/filters",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/filters/subscription/{subscriptionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/subscriptions/2026-03/filters/subscription/{subscriptionId}_/webhooks-journal/subscriptions/2026-03/filters/subscription/{subscriptionId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/filters/{filterId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/subscriptions/2026-03/filters/{filterId}_/webhooks-journal/subscriptions/2026-03/filters/{filterId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/webhooks-journal/subscriptions/2026-03/filters/{filterId}_/webhooks-journal/subscriptions/2026-03/filters/{filterId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/portals/{portalId}" : {
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/webhooks-journal/subscriptions/2026-03/portals/{portalId}_/webhooks-journal/subscriptions/2026-03/portals/{portalId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks-journal/subscriptions/2026-03/{subscriptionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/webhooks-journal/subscriptions/2026-03/{subscriptionId}_/webhooks-journal/subscriptions/2026-03/{subscriptionId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-read" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/webhooks-journal/subscriptions/2026-03/{subscriptionId}_/webhooks-journal/subscriptions/2026-03/{subscriptionId}",
        "security" : [ {
          "app_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "webhooks-journal-subscription-management" ]
        }, {
          "oauth2" : [ "webhooks-journal-subscription-management" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL",
        "x-hubspot-rate-limit-exemptions" : [ "daily", "ten-secondly" ]
      }
    },
    "/webhooks/2026-03/{appId}/settings" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read webhook settings",
        "description" : "Retrieve the webhook settings for the specified app, including the webhook’s target URL, throttle configuration, and create/update date.",
        "operationId" : "get-/webhooks/2026-03/{appId}/settings_getAll",
        "security" : [ {
          "app_cookie" : [ "developers-read", "private-apps-read" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-read", "private-apps-read" ]
        }, {
          "oauth2" : [ "developers-read", "private-apps-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update webhook settings",
        "description" : "Update webhook settings for the specified app.",
        "operationId" : "put-/webhooks/2026-03/{appId}/settings_configure",
        "security" : [ {
          "app_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete webhook settings",
        "description" : "Delete the webhook settings for the specified app. Event subscriptions will not be deleted, but will be paused until another webhook is created.",
        "operationId" : "delete-/webhooks/2026-03/{appId}/settings_clear",
        "security" : [ {
          "app_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/webhooks/2026-03/{appId}/subscriptions" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read event subscriptions",
        "description" : "Retrieve event subscriptions for the specified app.",
        "operationId" : "get-/webhooks/2026-03/{appId}/subscriptions_getAll",
        "security" : [ {
          "app_cookie" : [ "developers-read", "private-apps-read" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-read", "private-apps-read" ]
        }, {
          "oauth2" : [ "developers-read", "private-apps-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create an event subscription",
        "description" : "Create new event subscription for the specified app.",
        "operationId" : "post-/webhooks/2026-03/{appId}/subscriptions_create",
        "security" : [ {
          "app_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/webhooks/2026-03/{appId}/subscriptions/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch create event subscriptions",
        "description" : "Batch create event subscriptions for the specified app.",
        "operationId" : "post-/webhooks/2026-03/{appId}/subscriptions/batch/update_updateBatch",
        "security" : [ {
          "app_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/webhooks/2026-03/{appId}/subscriptions/{subscriptionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read an event subscription",
        "description" : "Retrieve a specific event subscription by ID.",
        "operationId" : "get-/webhooks/2026-03/{appId}/subscriptions/{subscriptionId}_getById",
        "security" : [ {
          "app_cookie" : [ "developers-read", "private-apps-read" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-read", "private-apps-read" ]
        }, {
          "oauth2" : [ "developers-read", "private-apps-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete event subscription",
        "description" : "Delete an existing event subscription by ID.",
        "operationId" : "delete-/webhooks/2026-03/{appId}/subscriptions/{subscriptionId}_archive",
        "security" : [ {
          "app_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update an event subscription",
        "description" : "Update an existing event subscription by ID.",
        "operationId" : "patch-/webhooks/2026-03/{appId}/subscriptions/{subscriptionId}_update",
        "security" : [ {
          "app_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write", "private-apps-write" ]
        }, {
          "oauth2" : [ "developers-write", "private-apps-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2_1" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "campaigns-access" : "",
              "campaigns-revenue-pro" : "",
              "campaigns-write" : "",
              "revenue-attribution-read" : ""
            }
          }
        }
      },
      "oauth2_2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "campaigns-access" : "",
              "campaigns-revenue-pro" : "",
              "campaigns-write" : "",
              "revenue-attribution-read" : ""
            }
          }
        }
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token"
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}