{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Users",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "Sync HubSpot user working hours with an external workforce management tool.",
    "x-hubspot-introduction" : "Use this API to fetch information about users in the account, along with updating their working hours, timezone, additional phone number, and job title properties."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "GDPR"
  }, {
    "name" : "Public_Object__MA_RC_H_2026"
  }, {
    "name" : "Public_Object_Search_Post__MA_RC_H_2026"
  } ],
  "paths" : {
    "/crm/objects/2026-03/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/objects/2026-03/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}_/crm/objects/2026-03/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "oauth" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/objects/2026-03/{objectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List",
        "description" : "Read a page of users. Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/objects/2026-03/{objectType}_/crm/objects/2026-03/{objectType}",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create",
        "description" : "Create a user with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard users is provided.",
        "operationId" : "post-/crm/objects/2026-03/{objectType}_/crm/objects/2026-03/{objectType}",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/crm/objects/2026-03/{objectType}/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Archive a batch of users by ID",
        "description" : "Archive multiple users by their IDs in a single request. This operation moves the specified users to the recycling bin, effectively deactivating them from active use.",
        "operationId" : "post-/crm/objects/2026-03/{objectType}/batch/archive_/crm/objects/2026-03/{objectType}/batch/archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/crm/objects/2026-03/{objectType}/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of users",
        "description" : "Create multiple users in a single request by providing a batch of user properties and associations. This endpoint returns the created users along with their IDs.",
        "operationId" : "post-/crm/objects/2026-03/{objectType}/batch/create_/crm/objects/2026-03/{objectType}/batch/create",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/crm/objects/2026-03/{objectType}/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of users by internal ID, or unique property values",
        "description" : "Retrieve records by record ID or include the `idProperty` parameter to retrieve records by a custom unique value property. ",
        "operationId" : "post-/crm/objects/2026-03/{objectType}/batch/read_/crm/objects/2026-03/{objectType}/batch/read",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        } ]
      }
    },
    "/crm/objects/2026-03/{objectType}/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update a batch of users by internal ID, or unique property values",
        "description" : "Update multiple user records in a single request by specifying their internal IDs or unique property values. This operation allows for batch processing of user data, ensuring efficient updates across multiple user profiles.",
        "operationId" : "post-/crm/objects/2026-03/{objectType}/batch/update_/crm/objects/2026-03/{objectType}/batch/update",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/crm/objects/2026-03/{objectType}/batch/upsert" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create or update a batch of users by unique property values",
        "description" : "Create or update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
        "operationId" : "post-/crm/objects/2026-03/{objectType}/batch/upsert_/crm/objects/2026-03/{objectType}/batch/upsert",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/crm/objects/2026-03/{objectType}/gdpr-delete" : {
      "post" : {
        "tags" : [ "GDPR" ],
        "operationId" : "post-/crm/objects/2026-03/{objectType}/gdpr-delete_/crm/objects/2026-03/{objectType}/gdpr-delete",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/crm/objects/2026-03/{objectType}/merge" : {
      "post" : {
        "tags" : [ "Public_Object__MA_RC_H_2026" ],
        "operationId" : "post-/crm/objects/2026-03/{objectType}/merge_/crm/objects/2026-03/{objectType}/merge",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/crm/objects/2026-03/{objectType}/search" : {
      "post" : {
        "tags" : [ "Public_Object_Search_Post__MA_RC_H_2026" ],
        "summary" : "Search for users based on specified criteria.",
        "description" : "Execute a search for users using defined filters, properties, and sorting options. The request must include a search query and can return up to 200 results per request.",
        "operationId" : "post-/crm/objects/2026-03/{objectType}/search_/crm/objects/2026-03/{objectType}/search",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/objects/2026-03/{objectType}/{objectId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read",
        "description" : "Read an Object identified by `{userId}`. `{userId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/objects/2026-03/{objectType}/{objectId}_/crm/objects/2026-03/{objectType}/{objectId}",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archive",
        "description" : "Move an Object identified by `{userId}` to the recycling bin.",
        "operationId" : "delete-/crm/objects/2026-03/{objectType}/{objectId}_/crm/objects/2026-03/{objectType}/{objectId}",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update",
        "description" : "Perform a partial update of an Object identified by `{userId}`or optionally a unique property value as specified by the `idProperty` query param. `{userId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
        "operationId" : "patch-/crm/objects/2026-03/{objectType}/{objectId}_/crm/objects/2026-03/{objectType}/{objectId}",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}_/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        } ]
      }
    },
    "/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "oauth" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "oauth" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.appointments.read" : "Read appointments",
              "crm.objects.appointments.sensitive.read.v2" : "Read appointments (sensitive)",
              "crm.objects.appointments.sensitive.write.v2" : "Write appointments (sensitive)",
              "crm.objects.appointments.write" : "Write appointments",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.carts.write" : "Write cart",
              "crm.objects.commercepayments.read" : "Read commerce payments",
              "crm.objects.commercepayments.write" : "Write commerce payments",
              "crm.objects.companies.highly_sensitive.read.v2" : "View company records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.write.v2" : "Change company records (highly-sensitive)",
              "crm.objects.companies.read" : "Create or update company records",
              "crm.objects.companies.sensitive.read.v2" : "View sensitive properties on company records",
              "crm.objects.companies.sensitive.write.v2" : "Create or update sensitive properties on company records",
              "crm.objects.companies.write" : "View company records",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.contacts.read" : "View contact records",
              "crm.objects.contacts.sensitive.read.v2" : "View sensitive properties on contact records",
              "crm.objects.contacts.sensitive.write.v2" : "Create or update sensitive properties on contact records",
              "crm.objects.contacts.write" : "Create or update contact records",
              "crm.objects.courses.read" : "Read courses",
              "crm.objects.courses.write" : "Write courses",
              "crm.objects.custom.highly_sensitive.read.v2" : "View custom object records (highly-sensitive)",
              "crm.objects.custom.highly_sensitive.write.v2" : "Change custom object records (highly-sensitive)",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.custom.sensitive.read.v2" : "View custom object records (sensitive)",
              "crm.objects.custom.sensitive.write.v2" : "Change custom object records (sensitive)",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.deals.highly_sensitive.read.v2" : "View deal records (highly-sensitive)",
              "crm.objects.deals.highly_sensitive.write.v2" : "Change deal records (highly-sensitive)",
              "crm.objects.deals.read" : "View deal records",
              "crm.objects.deals.sensitive.read.v2" : "View sensitive properties on deal records",
              "crm.objects.deals.sensitive.write.v2" : "Create or update sensitive properties on deal records",
              "crm.objects.deals.write" : "Create or update deal records",
              "crm.objects.goals.read" : "Read access to goals",
              "crm.objects.goals.write" : "Create and update goals",
              "crm.objects.invoices.read" : "Read invoices",
              "crm.objects.invoices.write" : "Write invoices",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.listings.read" : "Read listings",
              "crm.objects.listings.write" : "Write listings",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.partner-clients.write" : "Edit Partner Client CRM objects",
              "crm.objects.partner-services.read" : "View Partner Service CRM objects",
              "crm.objects.partner-services.write" : "Edit Partner Service CRM objects",
              "crm.objects.products.read" : "Read products in Products Library",
              "crm.objects.products.write" : "Write products in Products Library",
              "crm.objects.projects.highly_sensitive.read" : "Read projects (highly-sensitive)",
              "crm.objects.projects.highly_sensitive.write" : "Write projects (highly-sensitive)",
              "crm.objects.projects.read" : "Read projects",
              "crm.objects.projects.sensitive.read" : "Read projects (sensitive)",
              "crm.objects.projects.sensitive.write" : "Write projects (sensitive)",
              "crm.objects.projects.write" : "Write projects",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.services.read" : "Read services",
              "crm.objects.services.write" : "Write services",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.subscriptions.write" : "Write subscriptions",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.users.write" : "Write User CRM objects",
              "e-commerce" : "Access to ecommerce",
              "media_bridge.read" : "Read media and media events",
              "oauth" : "Basic HubSpot account information",
              "tickets" : "Tickets",
              "tickets.highly_sensitive.v2" : "Tickets (highly-sensitive)",
              "tickets.sensitive.v2" : "Tickets (sensitive)"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}