{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CMS Media Bridge",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  } ],
  "paths" : {
    "/media-bridge/2026-09/events/attention-span" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create Event",
        "description" : "Create a new attention span event in the MediaBridgeService. This endpoint is used to record attention span events, which can be useful for tracking user engagement with media content. The request must include a valid JSON body conforming to the AttentionSpanEventRequest schema.",
        "operationId" : "post-/media-bridge/2026-09/events/attention-span",
        "security" : [ {
          "oauth2" : [ "media_bridge.write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/events/media-played" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create",
        "description" : "Create a media played event in the HubSpot account. This endpoint is used to log when media content has been played, which can be useful for tracking user engagement with media resources.",
        "operationId" : "post-/media-bridge/2026-09/events/media-played",
        "security" : [ {
          "oauth2" : [ "media_bridge.write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/events/media-played-percent" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Record Media Played Percentage",
        "description" : "This endpoint allows you to record the percentage of media that has been played. It is useful for tracking user engagement with media content, such as videos or audio files, by capturing the extent to which the media has been consumed. This data can be used for analytics and improving content delivery strategies.",
        "operationId" : "post-/media-bridge/2026-09/events/media-played-percent",
        "security" : [ {
          "oauth2" : [ "media_bridge.write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/properties/{objectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve properties",
        "description" : "Retrieve properties for a specified object type within a given app. This endpoint allows you to filter properties based on whether they are archived and to specify which properties to include in the response. It is useful for accessing and managing the properties associated with different object types in your application.",
        "operationId" : "get-/media-bridge/2026-09/{appId}/properties/{objectType}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create property",
        "description" : "Create a new property for a specified object type within a given app in the MediaBridge service. This endpoint allows you to define new properties that can be used to store additional information related to the object type. The request must include the necessary property details in the request body.",
        "operationId" : "post-/media-bridge/2026-09/{appId}/properties/{objectType}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/properties/{objectType}/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch archive properties",
        "description" : "Archive multiple properties for a specified object type within a given app. This endpoint is useful for managing large sets of properties that are no longer needed or should be hidden from active use. It requires specifying the app ID and object type in the path parameters.",
        "operationId" : "post-/media-bridge/2026-09/{appId}/properties/{objectType}/batch/archive",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/properties/{objectType}/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch create properties",
        "description" : "Create multiple properties in a batch for a specified object type within a given app. This endpoint is useful for efficiently setting up multiple properties at once, reducing the need for multiple individual API calls.",
        "operationId" : "post-/media-bridge/2026-09/{appId}/properties/{objectType}/batch/create",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/properties/{objectType}/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch read properties",
        "description" : "Retrieve a batch of properties for a specified object type within a given app. This endpoint is useful for fetching multiple properties efficiently in a single request, especially when dealing with large datasets or when specific properties are needed for processing.",
        "operationId" : "post-/media-bridge/2026-09/{appId}/properties/{objectType}/batch/read",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/properties/{objectType}/groups" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List groups",
        "description" : "Retrieve a list of property groups for a specified object type within a given app. This endpoint is useful for obtaining organizational information about properties associated with different object types in your application.",
        "operationId" : "get-/media-bridge/2026-09/{appId}/properties/{objectType}/groups",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create Group",
        "description" : "Create a new property group for a specified object type within a given app. This endpoint allows you to organize properties into groups, making it easier to manage and categorize them within your application.",
        "operationId" : "post-/media-bridge/2026-09/{appId}/properties/{objectType}/groups",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/properties/{objectType}/groups/{groupName}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve group",
        "description" : "Retrieve a specific property group for a given object type within an app. This endpoint is useful for accessing detailed information about how properties are grouped under a specific group name for a particular object type in your application.",
        "operationId" : "get-/media-bridge/2026-09/{appId}/properties/{objectType}/groups/{groupName}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete group",
        "description" : "Delete a specific property group for a given object type within an app. This operation is useful for removing unnecessary or obsolete property groups, helping to maintain a clean and organized structure within your app's properties.",
        "operationId" : "delete-/media-bridge/2026-09/{appId}/properties/{objectType}/groups/{groupName}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update group",
        "description" : "Update the properties of a specific group within a specified object type for a given app. This operation allows you to modify the details of a property group, such as its label or display order, within the context of the MediaBridge service.",
        "operationId" : "patch-/media-bridge/2026-09/{appId}/properties/{objectType}/groups/{groupName}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/properties/{objectType}/{propertyName}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve property",
        "description" : "Retrieve a specific property for a given object type within a specified app. This endpoint allows you to access details about a property, including its configuration and settings, for a particular object type identified by the property name. This can be useful for understanding property configurations or for integration purposes.",
        "operationId" : "get-/media-bridge/2026-09/{appId}/properties/{objectType}/{propertyName}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete property",
        "description" : "Delete a specific property from a given object type within an app. This operation is useful for removing properties that are no longer needed or were created in error. The endpoint requires specifying the app ID, object type, and property name to identify the property to be deleted.",
        "operationId" : "delete-/media-bridge/2026-09/{appId}/properties/{objectType}/{propertyName}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update property",
        "description" : "Update an existing property for a specified object type within a given app. This operation allows you to modify the details of a property, such as its label, type, or description, to better fit your application's requirements.",
        "operationId" : "patch-/media-bridge/2026-09/{appId}/properties/{objectType}/{propertyName}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/schemas" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve schemas",
        "description" : "Retrieve the schemas associated with a specific app in the HubSpot account. This endpoint allows you to fetch schema details, which can be useful for understanding the data structure and properties associated with the app. You can optionally filter the results to include only archived schemas.",
        "operationId" : "get-/media-bridge/2026-09/{appId}/schemas",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/schemas/{objectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve schema",
        "description" : "Retrieve the schema for a specific object type within a given app in your HubSpot account. This endpoint is useful for understanding the structure and properties of a particular object type, which can assist in data integration and management tasks.",
        "operationId" : "get-/media-bridge/2026-09/{appId}/schemas/{objectType}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update schema",
        "description" : "Update the schema for a specific object type within a given app. This operation allows you to modify the existing schema details, which can be useful for adapting to changes in data structure requirements or business logic.",
        "operationId" : "patch-/media-bridge/2026-09/{appId}/schemas/{objectType}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/schemas/{objectType}/associations" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create associations",
        "description" : "Create new associations for a specified object type within a given app. This endpoint allows you to define relationships between different object types, enhancing data connectivity and integration within your HubSpot account.",
        "operationId" : "post-/media-bridge/2026-09/{appId}/schemas/{objectType}/associations",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/schemas/{objectType}/associations/{associationId}" : {
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete association",
        "description" : "Remove an existing association between schemas for a specified app in the MediaBridge service. This operation is useful when you need to disassociate entities that are no longer related or to clean up outdated associations.",
        "operationId" : "delete-/media-bridge/2026-09/{appId}/schemas/{objectType}/associations/{associationId}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/settings" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update settings",
        "description" : "Update the settings for a specific app in the MediaBridgeService. This endpoint allows you to modify the configuration settings associated with the specified appId. It is useful for updating app-specific settings to ensure they align with your current requirements.",
        "operationId" : "put-/media-bridge/2026-09/{appId}/settings",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/settings/event-visibility" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve settings",
        "description" : "Retrieve the event visibility settings for a specific app in the MediaBridge service. This endpoint provides information on how events are visible within the specified application context.",
        "operationId" : "get-/media-bridge/2026-09/{appId}/settings/event-visibility",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update settings",
        "description" : "Update the event visibility settings for a specific app in the MediaBridgeService. This operation allows you to modify how events are displayed or managed for the specified app. It is useful for configuring event visibility preferences based on your application's requirements.",
        "operationId" : "patch-/media-bridge/2026-09/{appId}/settings/event-visibility",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/settings/object-definitions" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create Object Definitions",
        "description" : "Create new object definitions for a specific app in the HubSpot Media Bridge. This endpoint is used to define new objects that can be utilized within the app, allowing for customization and integration of media-related functionalities.",
        "operationId" : "post-/media-bridge/2026-09/{appId}/settings/object-definitions",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/settings/object-definitions/{mediaType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve object definitions",
        "description" : "Retrieve the object definitions for a specified media type within an app. This endpoint allows you to access the settings related to the object definitions of various media types such as VIDEO, AUDIO, DOCUMENT, OTHER, and IMAGE. It is useful for understanding the structure and properties associated with different media types in your application.",
        "operationId" : "get-/media-bridge/2026-09/{appId}/settings/object-definitions/{mediaType}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/settings/oembed-domains" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List OEmbed Domains",
        "description" : "Retrieve the list of OEmbed domains associated with a specific app in your HubSpot account. This endpoint is useful for managing and verifying the domains that are allowed to embed media content. It provides a way to ensure that only trusted domains are used for embedding media.",
        "operationId" : "get-/media-bridge/2026-09/{appId}/settings/oembed-domains",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create",
        "description" : "Create a new oEmbed domain setting for a specific app in your HubSpot account. This endpoint allows you to define domains that can be used for oEmbed purposes, facilitating the integration of media content from external sources.",
        "operationId" : "post-/media-bridge/2026-09/{appId}/settings/oembed-domains",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete domains",
        "description" : "Delete oEmbed domains associated with a specific app in HubSpot. This operation allows you to manage and remove domains that are no longer needed for embedding media content within the app's settings.",
        "operationId" : "delete-/media-bridge/2026-09/{appId}/settings/oembed-domains",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/settings/oembed-domains/{oEmbedDomainId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve domain",
        "description" : "Retrieve details of a specific oEmbed domain for a given app. This endpoint is useful for fetching configuration or settings related to oEmbed domains associated with a particular application.",
        "operationId" : "get-/media-bridge/2026-09/{appId}/settings/oembed-domains/{oEmbedDomainId}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update oEmbed domain",
        "description" : "Update the settings for a specific oEmbed domain associated with a given app. This endpoint allows you to modify the configuration of an oEmbed domain, which can be useful for managing how media content is embedded across different domains.",
        "operationId" : "patch-/media-bridge/2026-09/{appId}/settings/oembed-domains/{oEmbedDomainId}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/settings/register" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Register Settings",
        "description" : "Register settings for a specific app in the MediaBridge service. This endpoint is deprecated and should be used with caution. It allows for the registration of settings associated with the specified app ID.",
        "operationId" : "post-/media-bridge/2026-09/{appId}/settings/register",
        "deprecated" : true,
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/2026-09/{appId}/settings/video-association-definition" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Define Video Association",
        "description" : "Create a video association definition for a specific application in the HubSpot Media Bridge. This endpoint is used to define how videos are associated with other objects within the specified app. It is particularly useful for applications that need to manage video content and its relationships programmatically.",
        "operationId" : "post-/media-bridge/2026-09/{appId}/settings/video-association-definition_/media-bridge/v1/{appId}/settings/video-association-definition",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "developers-read" : "",
              "developers-write" : "",
              "media_bridge.write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}