{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Settings Teams",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  } ],
  "paths" : {
    "/settings/teams/2026-09" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List teams",
        "description" : "Retrieve a list of teams from your HubSpot account. This endpoint allows you to paginate through the teams using the 'limit' and 'after' query parameters. It is useful for obtaining an overview of all teams configured in the account.",
        "operationId" : "get-/settings/teams/2026-09",
        "security" : [ {
          "oauth2" : [ "settings.users.teams.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create Team",
        "description" : "Create a new team in your HubSpot account. This endpoint allows you to define the team's name, parent team, and members. The request body must include the team's name and members. Upon successful creation, the response will include the URL of the newly created team resource.",
        "operationId" : "post-/settings/teams/2026-09",
        "security" : [ {
          "oauth2" : [ "settings.users.teams.write" ]
        } ]
      }
    },
    "/settings/teams/2026-09/{teamId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve team",
        "description" : "Retrieve detailed information about a specific team in your HubSpot account using the team's unique identifier. This endpoint is useful for accessing the team's properties, such as its name and parent team ID, to manage or display team-related data.",
        "operationId" : "get-/settings/teams/2026-09/{teamId}",
        "security" : [ {
          "oauth2" : [ "settings.users.teams.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete team",
        "description" : "Delete a specific team from your HubSpot account using the team's unique identifier. This operation will remove the team and its associated data. Ensure that you have the necessary permissions to perform this action.",
        "operationId" : "delete-/settings/teams/2026-09/{teamId}",
        "security" : [ {
          "oauth2" : [ "settings.users.teams.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update team",
        "description" : "Update the details of a specific team in your HubSpot account. This endpoint allows you to modify the team's information, such as its name or parent team ID. Ensure that the teamId provided in the path is correct, as it identifies the team to be updated.",
        "operationId" : "patch-/settings/teams/2026-09/{teamId}",
        "security" : [ {
          "oauth2" : [ "settings.users.teams.write" ]
        } ]
      }
    },
    "/settings/teams/2026-09/{teamId}/members" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List members",
        "description" : "Retrieve a list of members for a specified team in your HubSpot account. This endpoint allows you to paginate through the team members using the 'limit' and 'after' query parameters. It is useful for managing and viewing team compositions and roles within your organization.",
        "operationId" : "get-/settings/teams/2026-09/{teamId}/members",
        "security" : [ {
          "oauth2" : [ "settings.users.teams.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Add Team Members",
        "description" : "Assign new members to a specific team in your HubSpot account. This endpoint allows you to add users to a team by specifying their user IDs and roles. It is useful for managing team compositions and ensuring the right users have access to team resources.",
        "operationId" : "post-/settings/teams/2026-09/{teamId}/members",
        "security" : [ {
          "oauth2" : [ "settings.users.teams.write" ]
        } ]
      }
    },
    "/settings/teams/2026-09/{teamId}/members/batch" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch assign members",
        "description" : "Assign multiple members to a specific team in a single request. This endpoint allows for efficient management of team memberships by processing multiple assignments at once. It is useful for organizations looking to streamline their team management processes.",
        "operationId" : "post-/settings/teams/2026-09/{teamId}/members/batch",
        "security" : [ {
          "oauth2" : [ "settings.users.teams.write" ]
        } ]
      }
    },
    "/settings/teams/2026-09/{teamId}/members/{userId}" : {
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete member",
        "description" : "Remove a specific member from a team in your HubSpot account. This operation requires specifying both the team and user identifiers. It is useful for managing team compositions by removing users who no longer need access or association with a particular team.",
        "operationId" : "delete-/settings/teams/2026-09/{teamId}/members/{userId}",
        "security" : [ {
          "oauth2" : [ "settings.users.teams.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "settings.users.teams.read" : "",
              "settings.users.teams.write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}