{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Tags",
    "description" : "vNext REST API for Public Blog services",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "PROFESSIONAL",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "STARTER",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "Retrieve all blog tags as a part of a content audit, then update specific tags to support an upcoming company rebrand.",
    "x-hubspot-introduction" : "Use the blog tags API to create and manage available blog post tags for easy sorting and filtering on your site."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Multi-language"
  } ],
  "paths" : {
    "/cms/blogs/2026-03/authors/cursor" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/cms/blogs/2026-03/authors/cursor_/cms/blogs/v3/authors/cursor",
        "security" : [ {
          "app_cookie" : [ "blog-authors-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-authors-read" ]
        }, {
          "oauth2" : [ "blog-authors-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/authors/cursor/query" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/cms/blogs/2026-03/authors/cursor/query_/cms/blogs/v3/authors/cursor/query",
        "security" : [ {
          "app_cookie" : [ "blog-authors-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-authors-read" ]
        }, {
          "oauth2" : [ "blog-authors-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/posts/cursor" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/cms/blogs/2026-03/posts/cursor_/cms/blogs/v3/posts/cursor",
        "security" : [ {
          "app_cookie" : [ "blog-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-access" ]
        }, {
          "oauth2" : [ "blog-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/posts/cursor/query" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/cms/blogs/2026-03/posts/cursor/query_/cms/blogs/v3/posts/cursor/query",
        "security" : [ {
          "app_cookie" : [ "blog-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-access" ]
        }, {
          "oauth2" : [ "blog-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get all Blog Tags",
        "description" : "Get the list of blog tags. Supports paging and filtering. This method would be useful for an integration that examined these models and used an external service to suggest edits.\n",
        "operationId" : "get-/cms/blogs/2026-03/tags_getPage",
        "security" : [ {
          "app_cookie" : [ "blog-tags-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-tags-read" ]
        }, {
          "oauth2" : [ "blog-tags-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a new Blog Tag",
        "description" : "Create a new Blog Tag.",
        "operationId" : "post-/cms/blogs/2026-03/tags_create",
        "security" : [ {
          "app_cookie" : [ "blog-tags-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-tags-write" ]
        }, {
          "oauth2" : [ "blog-tags-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Delete a batch of Blog Tags",
        "description" : "Delete the Blog Tag objects identified in the request body.",
        "operationId" : "post-/cms/blogs/2026-03/tags/batch/archive_archiveBatch",
        "security" : [ {
          "app_cookie" : [ "blog-tags-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-tags-write" ]
        }, {
          "oauth2" : [ "blog-tags-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of Blog Tags",
        "description" : "Create the Blog Tag objects detailed in the request body.",
        "operationId" : "post-/cms/blogs/2026-03/tags/batch/create_createBatch",
        "security" : [ {
          "app_cookie" : [ "blog-tags-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-tags-write" ]
        }, {
          "oauth2" : [ "blog-tags-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve a batch of Blog Tags",
        "description" : "Retrieve the Blog Tag objects identified in the request body.",
        "operationId" : "post-/cms/blogs/2026-03/tags/batch/read_readBatch",
        "security" : [ {
          "app_cookie" : [ "blog-tags-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-tags-read" ]
        }, {
          "oauth2" : [ "blog-tags-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update a batch of Blog Tags",
        "description" : "Update the Blog Tag objects identified in the request body.",
        "operationId" : "post-/cms/blogs/2026-03/tags/batch/update_updateBatch",
        "security" : [ {
          "app_cookie" : [ "blog-tags-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-tags-write" ]
        }, {
          "oauth2" : [ "blog-tags-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags/cursor" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/cms/blogs/2026-03/tags/cursor_/cms/blogs/v3/tags/cursor",
        "security" : [ {
          "app_cookie" : [ "blog-tags-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-tags-read" ]
        }, {
          "oauth2" : [ "blog-tags-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags/cursor/query" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/cms/blogs/2026-03/tags/cursor/query_/cms/blogs/v3/tags/cursor/query",
        "security" : [ {
          "app_cookie" : [ "blog-tags-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-tags-read" ]
        }, {
          "oauth2" : [ "blog-tags-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags/multi-language/attach-to-lang-group" : {
      "post" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Attach a Blog Tag to a multi-language group",
        "description" : "Attach a Blog Tag to a multi-language group.",
        "operationId" : "post-/cms/blogs/2026-03/tags/multi-language/attach-to-lang-group_attachToLangGroup",
        "security" : [ {
          "app_cookie" : [ "blog-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-multilanguage" ]
        }, {
          "oauth2" : [ "blog-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags/multi-language/create-language-variation" : {
      "post" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Create a new language variation",
        "description" : "Create a new language variation from an existing Blog Tag",
        "operationId" : "post-/cms/blogs/2026-03/tags/multi-language/create-language-variation_createLangVariation",
        "security" : [ {
          "app_cookie" : [ "blog-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-multilanguage" ]
        }, {
          "oauth2" : [ "blog-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags/multi-language/detach-from-lang-group" : {
      "post" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Detach a Blog Tag from a multi-language group",
        "description" : "Detach a Blog Tag from a multi-language group.",
        "operationId" : "post-/cms/blogs/2026-03/tags/multi-language/detach-from-lang-group_detachFromLangGroup",
        "security" : [ {
          "app_cookie" : [ "blog-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-multilanguage" ]
        }, {
          "oauth2" : [ "blog-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags/multi-language/set-new-lang-primary" : {
      "put" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Set a new primary language",
        "description" : "Set a Blog Tag as the primary language of a multi-language group.",
        "operationId" : "put-/cms/blogs/2026-03/tags/multi-language/set-new-lang-primary_setLangPrimary",
        "security" : [ {
          "app_cookie" : [ "blog-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-multilanguage" ]
        }, {
          "oauth2" : [ "blog-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags/multi-language/update-languages" : {
      "post" : {
        "tags" : [ "Multi-language" ],
        "summary" : "Update languages of multi-language group",
        "description" : "Explicitly set new languages for each Blog Tag in a multi-language group.",
        "operationId" : "post-/cms/blogs/2026-03/tags/multi-language/update-languages_updateLangs",
        "security" : [ {
          "app_cookie" : [ "blog-multilanguage" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-multilanguage" ]
        }, {
          "oauth2" : [ "blog-multilanguage" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/cms/blogs/2026-03/tags/{objectId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve a Blog Tag",
        "description" : "Retrieve the Blog Tag object identified by the id in the path.",
        "operationId" : "get-/cms/blogs/2026-03/tags/{objectId}_getById",
        "security" : [ {
          "app_cookie" : [ "blog-tags-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-tags-read" ]
        }, {
          "oauth2" : [ "blog-tags-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete a Blog Tag",
        "description" : "Delete the Blog Tag object identified by the id in the path.",
        "operationId" : "delete-/cms/blogs/2026-03/tags/{objectId}_archive",
        "security" : [ {
          "app_cookie" : [ "blog-tags-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-tags-write" ]
        }, {
          "oauth2" : [ "blog-tags-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update a Blog Tag",
        "description" : "Sparse updates a single Blog Tag object identified by the id in the path.\nAll the column values need not be specified. Only the that need to be modified can be specified.\n",
        "operationId" : "patch-/cms/blogs/2026-03/tags/{objectId}_update",
        "security" : [ {
          "app_cookie" : [ "blog-tags-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "blog-tags-write" ]
        }, {
          "oauth2" : [ "blog-tags-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "developers-read" : "",
              "developers-write" : "",
              "private-apps-read" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "PROFESSIONAL",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}