{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Marketing Events",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "You have an external system that handles registration for your webinars and you want to ensure that attendee data and behavior is synced with your HubSpot CRM.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Marketing Events Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/marketing/marketing-events"
    } ],
    "x-hubspot-introduction" : "The marketing events API allows you to build a custom integration that will sync event and registration data with your HubSpot account.The marketing events API allows you to build a custom integration that will sync event and registration data with your HubSpot account."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Attendance Subscriber State Changes"
  }, {
    "name" : "Participant State"
  }, {
    "name" : "Subscriber State Changes"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Settings"
  } ],
  "paths" : {
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create" : {
      "post" : {
        "tags" : [ "Attendance Subscriber State Changes" ],
        "summary" : "Record a subscriber state by contact ids",
        "description" : "Record a subscriber state between multiple HubSpot contacts and a marketing event, using HubSpot contact ids.",
        "operationId" : "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create_createByContactId",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{marketingEventId}/breakdown" : {
      "get" : {
        "tags" : [ "Participant State" ],
        "summary" : "Read participations breakdown by Marketing Event internal identifier",
        "description" : "Read Marketing event's participations breakdown with optional filters by internal identifier marketingEventId.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/{marketingEventId}/breakdown_getParticipationsBreakdownByMarketingEventId",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert" : {
      "post" : {
        "tags" : [ "Subscriber State Changes" ],
        "summary" : "Record a subscriber state by contact ID",
        "description" : "Record a subscriber state between multiple HubSpot contacts and a marketing event, using HubSpot contact IDs. Note that the contact must already exist in HubSpot; a contact will not be created.",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert_upsertByContactId",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}" : {
      "get" : {
        "tags" : [ "Participant State" ],
        "summary" : "Read participations counters by Marketing Event external identifier",
        "description" : "Read Marketing event's participations counters by externalAccountId and externalEventId pair.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}_getParticipationsCountersByEventExternalId",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{marketingEventId}" : {
      "get" : {
        "tags" : [ "Participant State" ],
        "summary" : "Read participations counters by Marketing Event internal identifier",
        "description" : "Read Marketing event's participations counters by internal identifier marketingEventId.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/{marketingEventId}_getParticipationsCountersByMarketingEventId",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/delete" : {
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete multiple marketing events",
        "description" : "Bulk delete a number of marketing events in HubSpot",
        "operationId" : "post-/marketing/v3/marketing-events/events/delete_batchArchive",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/cancel" : {
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Mark a marketing event as cancelled",
        "description" : "Mark a marketing event as cancelled.",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/cancel_cancel",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get a marketing event",
        "description" : "Returns the details of the Marketing Event with the specified id, if one exists.",
        "operationId" : "get-/marketing/v3/marketing-events/events/{externalEventId}_getDetails",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Create or update a marketing event",
        "description" : "Upserts a marketing event If there is an existing marketing event with the specified ID, it will be updated; otherwise a new event will be created.",
        "operationId" : "put-/marketing/v3/marketing-events/events/{externalEventId}_upsert",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete a marketing event",
        "description" : "Deletes an existing Marketing Event with the specified id, if one exists.",
        "operationId" : "delete-/marketing/v3/marketing-events/events/{externalEventId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update a marketing event",
        "description" : "Updates an existing Marketing Event with the specified id, if one exists.",
        "operationId" : "patch-/marketing/v3/marketing-events/events/{externalEventId}_update",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/upsert" : {
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create or update multiple marketing events",
        "description" : "Upsert multiple marketing events. If there is an existing Marketing event with the specified ID, it will be updated; otherwise a new event will be created.",
        "operationId" : "post-/marketing/v3/marketing-events/events/upsert_batchUpsert",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create" : {
      "post" : {
        "tags" : [ "Attendance Subscriber State Changes" ],
        "summary" : "Record a subscriber state by contact email",
        "description" : "Record a subscriber state between multiple HubSpot contacts and a marketing event, using contact email addresses. If contact is not present it will be automatically created.\nThe contactProperties field is used only when creating a new contact. These properties will not update existing contacts. ",
        "operationId" : "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create_createByContactEmail",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert" : {
      "post" : {
        "tags" : [ "Subscriber State Changes" ],
        "summary" : "Record a subscriber state by contact email",
        "description" : "Record a subscriber state between multiple HubSpot contacts and a marketing event, using contact email addresses. Note that the contact must already exist in HubSpot; a contact will not be created. The contactProperties field is used only when creating a new contact. These properties will not update existing contacts. ",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert_upsertByContactEmail",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}/breakdown" : {
      "get" : {
        "tags" : [ "Participant State" ],
        "summary" : "Read participations breakdown by Marketing Event external identifier",
        "description" : "Read Marketing event's participations breakdown with optional filters by externalAccountId and externalEventId pair.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}/breakdown_getParticipationsBreakdownByExternalEventId",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/complete" : {
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Mark a marketing event as completed",
        "description" : "Mark a marketing event as completed",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/complete_complete",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events" : {
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a marketing event",
        "description" : "Creates a new marketing event in HubSpot",
        "operationId" : "post-/marketing/v3/marketing-events/events_create",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown" : {
      "get" : {
        "tags" : [ "Participant State" ],
        "summary" : "Read participations breakdown by Contact identifier",
        "description" : "Read Contact's participations by identifier - email or internal id.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown_getParticipationsBreakdownByContactId",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{appId}/settings" : {
      "get" : {
        "tags" : [ "Settings" ],
        "summary" : "Retrieve the application settings",
        "description" : "Retrieve the current settings for the application.",
        "operationId" : "get-/marketing/v3/marketing-events/{appId}/settings_getAll",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Settings" ],
        "summary" : "Update the application settings",
        "description" : "Create or update the current settings for the application.",
        "operationId" : "post-/marketing/v3/marketing-events/{appId}/settings_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/search" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Search for marketing events",
        "description" : "Search for marketing events that have an event id that starts with the query string",
        "operationId" : "get-/marketing/v3/marketing-events/events/search_doSearch",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.marketing_events.write" : "Write marketing events",
              "crm.objects.marketing_events.read" : "Read marketing events"
            }
          }
        }
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}