{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "マーケティングイベント",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "ウェビナーの登録を処理する外部システムを使用していて、参加者のデータや行動が確実にHubSpot CRMと同期されるようにしたいと考えています。",
    "x-hubspot-related-documentation" : [ {
      "name" : "Marketing Events Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/marketing/marketing-events"
    } ],
    "x-hubspot-introduction" : "マーケティングイベントAPIを使用すれば、イベントや登録のデータをご使用のHubSpotアカウントと同期するカスタム連携を構築できます。マーケティングイベントAPIを使用すれば、イベントや登録のデータをご使用のHubSpotアカウントと同期するカスタム連携を構築できます。"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Marketing_Events_External"
  }, {
    "name" : "Attendance_External"
  }, {
    "name" : "Settings_External"
  } ],
  "paths" : {
    "/marketing/v3/marketing-events/events/upsert" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "複数のマーケティングイベントを作成または更新",
        "description" : "複数のマーケティングイベントを更新／挿入します。指定されたIDの既存のマーケティングイベントが存在する場合は更新され、存在しない場合はイベントが新規作成されます。",
        "operationId" : "post-/marketing/v3/marketing-events/events/upsert_doUpsert",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create" : {
      "post" : {
        "tags" : [ "Attendance_External" ],
        "summary" : "記録",
        "description" : "HubSpotコンタクトIDを使用して、複数のHubSpotコンタクトとマーケティングイベント間の登録状態を記録します。",
        "operationId" : "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create_create",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create" : {
      "post" : {
        "tags" : [ "Attendance_External" ],
        "summary" : "記録",
        "description" : "コンタクトのEメールアドレスを使用して、複数のHubSpotコンタクトとマーケティングイベント間の登録状態を記録します。コンタクトが存在しない場合は、自動的に作成されます。",
        "operationId" : "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create_createByEmail",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "記録",
        "description" : "コンタクトのEメールアドレスを使用して、複数のHubSpotコンタクトとマーケティングイベント間の登録状態を記録します。コンタクトがすでにHubSpotに存在している必要がある点に注意してください。コンタクトは作成されません。",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert_doEmailUpsertById",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/complete" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/complete_complete",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "記録",
        "description" : "HubSpotコンタクトIDを使用して、複数のHubSpotコンタクトとマーケティングイベント間の登録状態を記録します。コンタクトがすでにHubSpotに存在している必要がある点に注意してください。コンタクトは作成されません。",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert_doUpsertById",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "マーケティングイベントを作成",
        "description" : "HubSpotにマーケティングイベントが新規作成されます",
        "operationId" : "post-/marketing/v3/marketing-events/events_create",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/delete" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "複数のマーケティングイベントを削除",
        "description" : "HubSpotで多数のマーケティングイベントを一括削除",
        "operationId" : "post-/marketing/v3/marketing-events/events/delete_archive",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/cancel" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "マーケティングイベントをキャンセル済みにする",
        "description" : "マーケティングイベントをキャンセル済みにします。",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/cancel_doCancel",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{appId}/settings" : {
      "get" : {
        "tags" : [ "Settings_External" ],
        "summary" : "アプリケーション設定を取得",
        "description" : "アプリケーションの現在の設定を取得します。",
        "operationId" : "get-/marketing/v3/marketing-events/{appId}/settings_getAll",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Settings_External" ],
        "summary" : "アプリケーション設定を更新",
        "description" : "アプリケーションの現在の設定を作成または更新します。",
        "operationId" : "post-/marketing/v3/marketing-events/{appId}/settings_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/search" : {
      "get" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "マーケティングイベントを検索",
        "description" : "イベントIDがクエリー文字列で始まるマーケティングイベントを検索",
        "operationId" : "get-/marketing/v3/marketing-events/events/search_doSearch",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}" : {
      "get" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "マーケティングイベントを取得",
        "description" : "指定されたIDのマーケティングイベントが存在する場合、その詳細が返されます。",
        "operationId" : "get-/marketing/v3/marketing-events/events/{externalEventId}_getById",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "マーケティングイベントを作成または更新",
        "description" : "複数のマーケティングイベントが更新／挿入されます。指定されたIDの既存のマーケティングイベントが存在する場合は更新され、存在しない場合はイベントが新規作成されます。",
        "operationId" : "put-/marketing/v3/marketing-events/events/{externalEventId}_replace",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "マーケティングイベントを削除",
        "description" : "指定されたIDの既存のマーケティングイベントが存在する場合、削除されます。",
        "operationId" : "delete-/marketing/v3/marketing-events/events/{externalEventId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "マーケティングイベントを更新",
        "description" : "指定されたIDの既存のマーケティングイベントが存在する場合、更新されます。",
        "operationId" : "patch-/marketing/v3/marketing-events/events/{externalEventId}_update",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.marketing_events.write" : "Write marketing events",
              "crm.objects.marketing_events.read" : "Read marketing events"
            }
          }
        }
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}