{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Événements marketing",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "Un système externe gère l'inscription à vos webinaires pour vous et vous souhaitez vous assurer que les données et le comportement des participants sont synchronisés avec votre CRM HubSpot.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Marketing Events Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/marketing/marketing-events"
    } ],
    "x-hubspot-introduction" : "L'API des événements marketing vous permet de créer une intégration personnalisée qui synchronisera les données des événements et des inscriptions avec votre compte HubSpot. L'API des événements marketing vous permet de créer une intégration personnalisée qui synchronisera les données des événements et des inscriptions avec votre compte HubSpot."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Marketing_Events_External"
  }, {
    "name" : "Attendance_External"
  }, {
    "name" : "Settings_External"
  } ],
  "paths" : {
    "/marketing/v3/marketing-events/events/upsert" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Créer ou mettre à jour plusieurs événements marketing",
        "description" : "Insérer plusieurs événements marketing. S'il existe un événement marketing existant avec l'identifiant spécifié, il sera mis à jour, sinon, un nouvel événement sera créé.",
        "operationId" : "post-/marketing/v3/marketing-events/events/upsert_doUpsert",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create" : {
      "post" : {
        "tags" : [ "Attendance_External" ],
        "summary" : "Enregistrer",
        "description" : "Enregistrez un statut d'abonnement entre plusieurs contacts HubSpot et un événement marketing, en utilisant les identifiants de contact HubSpot.",
        "operationId" : "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create_create",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create" : {
      "post" : {
        "tags" : [ "Attendance_External" ],
        "summary" : "Enregistrer",
        "description" : "Enregistrez un statut d'abonnement entre plusieurs contacts HubSpot et un événement marketing, en utilisant les adresses e-mail des contacts. Si le contact n'est pas présent, il sera automatiquement créé.",
        "operationId" : "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create_createByEmail",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Enregistrer",
        "description" : "Enregistrer un état d'abonnement entre plusieurs contacts HubSpot et un événement marketing, en utilisant les adresses e-mail des contacts. Remarque : le contact doit déjà exister dans HubSpot, un contact ne sera pas créé.",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert_doEmailUpsertById",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/complete" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/complete_complete",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Enregistrer",
        "description" : "Enregistrer un état d'abonnement entre plusieurs contacts HubSpot et un événement marketing, en utilisant les identifiants de contact HubSpot. Remarque : le contact doit déjà exister dans HubSpot, un contact ne sera pas créé.",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert_doUpsertById",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Créer un événement marketing",
        "description" : "Crée un nouvel événement marketing dans HubSpot",
        "operationId" : "post-/marketing/v3/marketing-events/events_create",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/delete" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Supprimer plusieurs événements marketing",
        "description" : "Supprimer en masse un certain nombre d'événements marketing dans HubSpot",
        "operationId" : "post-/marketing/v3/marketing-events/events/delete_archive",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/cancel" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Marquer un événement marketing comme annulé",
        "description" : "Marquer un événement marketing comme annulé.",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/cancel_doCancel",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{appId}/settings" : {
      "get" : {
        "tags" : [ "Settings_External" ],
        "summary" : "Récupérer les paramètres de l'application",
        "description" : "Récupérer les paramètres actuels de l'application.",
        "operationId" : "get-/marketing/v3/marketing-events/{appId}/settings_getAll",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Settings_External" ],
        "summary" : "Mettre à jour les paramètres de l'application",
        "description" : "Créer ou mettre à jour les paramètres actuels de l'application.",
        "operationId" : "post-/marketing/v3/marketing-events/{appId}/settings_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/search" : {
      "get" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Rechercher des événements marketing",
        "description" : "Rechercher des événements marketing dont l'identifiant d'événement commence par la chaîne de requête",
        "operationId" : "get-/marketing/v3/marketing-events/events/search_doSearch",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}" : {
      "get" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Obtenir un événement marketing",
        "description" : "Renvoie les détails de l'événement marketing avec l'identifiant spécifié, s'il existe.",
        "operationId" : "get-/marketing/v3/marketing-events/events/{externalEventId}_getById",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Créer ou mettre à jour un événement marketing",
        "description" : "Insère un événement marketing. S'il existe un événement marketing existant avec l'identifiant spécifié, il sera mis à jour, sinon, un nouvel événement sera créé.",
        "operationId" : "put-/marketing/v3/marketing-events/events/{externalEventId}_replace",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Supprimer un événement marketing",
        "description" : "Supprime un événement marketing existant avec l'identifiant spécifié, s'il existe.",
        "operationId" : "delete-/marketing/v3/marketing-events/events/{externalEventId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Mettez à jour un événement marketing",
        "description" : "Met à jour un événement marketing existant avec l'identifiant spécifié, s'il existe.",
        "operationId" : "patch-/marketing/v3/marketing-events/events/{externalEventId}_update",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.marketing_events.write" : "Write marketing events",
              "crm.objects.marketing_events.read" : "Read marketing events"
            }
          }
        }
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}