{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Eventos de marketing",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "Tienes un sistema externo que se ocupa del registro para tus webinars y deseas asegurarse de que los datos y el comportamiento de los asistentes estén sincronizados con tu CRM de HubSpot.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Marketing Events Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/marketing/marketing-events"
    } ],
    "x-hubspot-introduction" : "La API de eventos de marketing te permite crear una integración personalizada que sincronizará los datos de eventos y registros con tu cuenta de HubSpot. La API de eventos de marketing te permite crear una integración personalizada que sincronizará los datos de eventos y registros con tu cuenta de HubSpot."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Attendance Subscriber State Changes"
  }, {
    "name" : "Asistencia: Cambios de estado del suscriptor"
  }, {
    "name" : "Participant State"
  }, {
    "name" : "Subscriber State Changes"
  }, {
    "name" : "Cambios de estado del suscriptor"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Básico"
  }, {
    "name" : "Settings"
  }, {
    "name" : "Configuración"
  } ],
  "paths" : {
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create" : {
      "post" : {
        "tags" : [ "Attendance Subscriber State Changes", "Asistencia: Cambios de estado del suscriptor" ],
        "summary" : "Registro",
        "description" : "Registra un estado de suscripción entre múltiples contactos de HubSpot y un evento de marketing, utilizando los ID de contacto de HubSpot.",
        "operationId" : "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create_create",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{marketingEventId}/breakdown" : {
      "get" : {
        "tags" : [ "Participant State" ],
        "summary" : "Read participations breakdown by Marketing Event internal identifier",
        "description" : "Read Marketing event's participations breakdown with optional filters by internal identifier marketingEventId.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/{marketingEventId}/breakdown",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert" : {
      "post" : {
        "tags" : [ "Subscriber State Changes", "Cambios de estado del suscriptor" ],
        "summary" : "Registro",
        "description" : "Registra un estado de suscripción entre múltiples contactos de HubSpot y un evento de marketing, utilizando los ID de los contactos de HubSpot. Ten en cuenta que el contacto ya debe existir en HubSpot; no se creará un contacto.",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert_doUpsertById",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}" : {
      "get" : {
        "tags" : [ "Participant State" ],
        "summary" : "Read participations counters by Marketing Event external identifier",
        "description" : "Read Marketing event's participations counters by externalAccountId and externalEventId pair.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{marketingEventId}" : {
      "get" : {
        "tags" : [ "Participant State" ],
        "summary" : "Read participations counters by Marketing Event internal identifier",
        "description" : "Read Marketing event's participations counters by internal identifier marketingEventId.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/{marketingEventId}",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/delete" : {
      "post" : {
        "tags" : [ "Basic", "Básico" ],
        "summary" : "Eliminar múltiples eventos de marketing",
        "description" : "Eliminar en masa una serie de eventos de marketing en HubSpot",
        "operationId" : "post-/marketing/v3/marketing-events/events/delete_archive",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/cancel" : {
      "post" : {
        "tags" : [ "Basic", "Básico" ],
        "summary" : "Marcar un evento de marketing como cancelado",
        "description" : "Marcar un evento de marketing como cancelado.",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/cancel_doCancel",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}" : {
      "get" : {
        "tags" : [ "Basic", "Básico" ],
        "summary" : "Obtener un evento de marketing",
        "description" : "Devuelve los detalles de un evento de marketing con el ID especificado, si existe uno.",
        "operationId" : "get-/marketing/v3/marketing-events/events/{externalEventId}_getById",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Basic", "Básico" ],
        "summary" : "Crear o actualizar un evento de marketing",
        "description" : "Actualiza o crea un evento de marketing. Si existe un evento de marketing con el ID especificado, se actualizará; de lo contrario, se creará un nuevo evento.",
        "operationId" : "put-/marketing/v3/marketing-events/events/{externalEventId}_replace",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic", "Básico" ],
        "summary" : "Eliminar un evento de marketing",
        "description" : "Elimina un evento de marketing existente con el ID especificado, si existe uno.",
        "operationId" : "delete-/marketing/v3/marketing-events/events/{externalEventId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic", "Básico" ],
        "summary" : "Actualizar un evento de marketing",
        "description" : "Actualiza un evento de marketing existente con el ID especificado, si existe uno.",
        "operationId" : "patch-/marketing/v3/marketing-events/events/{externalEventId}_update",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/upsert" : {
      "post" : {
        "tags" : [ "Basic", "Básico" ],
        "summary" : "Crear o actualizar múltiples eventos de marketing",
        "description" : "Actualiza o crea múltiples eventos de marketing. Si existe un evento de marketing con el ID especificado, se actualizará; de lo contrario, se creará un nuevo evento.",
        "operationId" : "post-/marketing/v3/marketing-events/events/upsert_doUpsert",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create" : {
      "post" : {
        "tags" : [ "Attendance Subscriber State Changes", "Asistencia: Cambios de estado del suscriptor" ],
        "summary" : "Registro",
        "description" : "Registra un estado de suscripción entre múltiples contactos de HubSpot y un evento de marketing, utilizando las direcciones de correo de los contactos. Si el contacto no está presente, se creará automáticamente.",
        "operationId" : "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create_createByEmail",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert" : {
      "post" : {
        "tags" : [ "Subscriber State Changes", "Cambios de estado del suscriptor" ],
        "summary" : "Registro",
        "description" : "Registra un estado de suscripción entre múltiples contactos de HubSpot y un evento de marketing, utilizando las direcciones de correo de los contactos. Ten en cuenta que el contacto ya debe existir en HubSpot; no se creará un contacto.",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert_doEmailUpsertById",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}/breakdown" : {
      "get" : {
        "tags" : [ "Participant State" ],
        "summary" : "Read participations breakdown by Marketing Event external identifier",
        "description" : "Read Marketing event's participations breakdown with optional filters by externalAccountId and externalEventId pair.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}/breakdown",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/complete" : {
      "post" : {
        "tags" : [ "Basic", "Básico" ],
        "summary" : "Mark a marketing event as completed",
        "description" : "Mark a marketing event as completed",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/complete_complete",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events" : {
      "post" : {
        "tags" : [ "Basic", "Básico" ],
        "summary" : "Crear un evento de marketing",
        "description" : "Crea un nuevo evento de marketing en HubSpot",
        "operationId" : "post-/marketing/v3/marketing-events/events_create",
        "security" : [ {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown" : {
      "get" : {
        "tags" : [ "Participant State" ],
        "summary" : "Read participations breakdown by Contact identifier",
        "description" : "Read Contact's participations by identifier - email or internal id.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{appId}/settings" : {
      "get" : {
        "tags" : [ "Settings", "Configuración" ],
        "summary" : "Recuperar la configuración de la aplicación",
        "description" : "Recupera la configuración actual de la aplicación.",
        "operationId" : "get-/marketing/v3/marketing-events/{appId}/settings_getAll",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Settings", "Configuración" ],
        "summary" : "Actualizar la configuración de la aplicación",
        "description" : "Crea o actualiza la configuración actual de la aplicación.",
        "operationId" : "post-/marketing/v3/marketing-events/{appId}/settings_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/search" : {
      "get" : {
        "tags" : [ "Basic", "Básico" ],
        "summary" : "Buscar eventos de marketing",
        "description" : "Buscar eventos de marketing que tengan un ID de evento que comience con la cadena de consulta",
        "operationId" : "get-/marketing/v3/marketing-events/events/search_doSearch",
        "security" : [ {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.marketing_events.write" : "Write marketing events",
              "crm.objects.marketing_events.read" : "Read marketing events"
            }
          }
        }
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}