{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Marketing Marketing Events",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "STARTER",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "You have an external system that handles registration for your webinars and you want to ensure that attendee data and behavior is synced with your HubSpot CRM.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Marketing Events Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/marketing/marketing-events"
    } ],
    "x-hubspot-introduction" : "A marketing event is a CRM object, similar to contacts and companies, that enables you to track marketing events, such as a webinar, along with the contacts who registered and attended the event. Below, learn more about working with the marketing event API to integrate marketing events into an app."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Marketing_Events_External"
  }, {
    "name" : "Attendance_External"
  }, {
    "name" : "Lists_Reference_External"
  }, {
    "name" : "Participations_External"
  }, {
    "name" : "Marketing_Events_V2"
  }, {
    "name" : "Settings_External"
  }, {
    "name" : "Attendance_External_V2"
  } ],
  "paths" : {
    "/marketing/v3/marketing-events/participations/{marketingEventId}/breakdown" : {
      "get" : {
        "tags" : [ "Participations_External" ],
        "summary" : "Read participations breakdown by Marketing Event internal identifier",
        "description" : "Read Marketing event's participations breakdown with optional filters by internal identifier marketingEventId.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/{marketingEventId}/breakdown_getParticipationsBreakdownByMarketingEventId",
        "security" : [ {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create" : {
      "post" : {
        "tags" : [ "Attendance_External" ],
        "summary" : "Record Participants by ContactId with Marketing Event External Ids",
        "description" : "Records the participation of multiple HubSpot contacts in a Marketing Event using their HubSpot contact IDs.\n\nAdditional Functionality:\n- Adds a timeline event to the contacts.\n\nAllowed Properties:\nFor the state \"attend\":\n- joinedAt\n- leftAt",
        "operationId" : "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create_recordByContactIds",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Record a subscriber state by contact ID",
        "description" : "Record a subscriber state between multiple HubSpot contacts and a marketing event, using HubSpot contact IDs. Note that the contact must already exist in HubSpot; a contact will not be created.",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert_upsertByContactId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}" : {
      "get" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Get Marketing Event by External IDs",
        "description" : "Returns the details of a Marketing Event with the specified externalAccountId, externalEventId, if it exists.\n\nOnly Marketing Events created by the same app making the request can be retrieved.",
        "operationId" : "get-/marketing/v3/marketing-events/events/{externalEventId}_getDetails",
        "security" : [ {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Create or update a marketing event",
        "description" : "Upserts a marketing event If there is an existing marketing event with the specified ID, it will be updated; otherwise a new event will be created.",
        "operationId" : "put-/marketing/v3/marketing-events/events/{externalEventId}_upsert",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Delete Marketing Event by External Ids",
        "description" : "Deletes the existing Marketing Event with the specified externalAccountId, externalEventId, if it exists.\n\nOnly Marketing Events created by the same app can be deleted.",
        "operationId" : "delete-/marketing/v3/marketing-events/events/{externalEventId}_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Update Marketing Event by External IDs",
        "description" : "Updates the details of an existing Marketing Event identified by its externalAccountId, externalEventId if it exists.\n\nOnly Marketing Events created by the same app can be updated.",
        "operationId" : "patch-/marketing/v3/marketing-events/events/{externalEventId}_update",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/upsert" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Create or Update Multiple Marketing Events",
        "description" : "Upserts multiple Marketing Events. If a Marketing Event with the specified ID already exists, it will be updated; otherwise, a new event will be created.\n\nOnly Marketing Events originally created by the same app can be updated.",
        "operationId" : "post-/marketing/v3/marketing-events/events/upsert_upsert",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create" : {
      "post" : {
        "tags" : [ "Attendance_External" ],
        "summary" : "Record Participants by Email with Marketing Event External Ids",
        "description" : "Records the participation of multiple HubSpot contacts in a Marketing Event using their email addresses.\n\nIf a contact does not exist, it will be automatically created. The contactProperties field is used exclusively for creating new contacts and will not update properties of existing contacts.\n\nAdditional Functionality:\n- Adds a timeline event to the contacts.\n\nAllowed Properties:\nFor the state \"attend\":\n- joinedAt\n- leftAt",
        "operationId" : "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create_recordByContactEmails",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}/breakdown" : {
      "get" : {
        "tags" : [ "Participations_External" ],
        "summary" : "Read participations breakdown by Marketing Event external identifier",
        "description" : "Read Marketing event's participations breakdown with optional filters by externalAccountId and externalEventId pair.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}/breakdown_getParticipationsBreakdownByExternalEventId",
        "security" : [ {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{objectId}" : {
      "get" : {
        "tags" : [ "Marketing_Events_V2" ],
        "summary" : "Get Marketing Event by objectId",
        "description" : "Returns the details of a Marketing Event with the specified objectId, if it exists.",
        "operationId" : "get-/marketing/v3/marketing-events/{objectId}_getByObjectId",
        "security" : [ {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Marketing_Events_V2" ],
        "summary" : "Delete Marketing Event by objectId",
        "description" : "Deletes the existing Marketing Event with the specified objectId, if it exists.",
        "operationId" : "delete-/marketing/v3/marketing-events/{objectId}_archiveByObjectId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Marketing_Events_V2" ],
        "summary" : "Update Marketing Event by objectId",
        "description" : "Updates the details of an existing Marketing Event identified by its objectId, if it exists.",
        "operationId" : "patch-/marketing/v3/marketing-events/{objectId}_updateByObjectId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists" : {
      "get" : {
        "tags" : [ "Lists_Reference_External" ],
        "summary" : "Get lists associated with a marketing event",
        "description" : "Gets lists associated with a marketing event by external account id and external event id",
        "operationId" : "get-/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists_getAllByExternalAccountAndEventIds",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/associations/{marketingEventId}/lists" : {
      "get" : {
        "tags" : [ "Lists_Reference_External" ],
        "summary" : "Get lists associated with a marketing event",
        "description" : "Gets lists associated with a marketing event by marketing event id",
        "operationId" : "get-/marketing/v3/marketing-events/associations/{marketingEventId}/lists_getAllByMarketingEventId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/email-create" : {
      "post" : {
        "tags" : [ "Attendance_External_V2" ],
        "summary" : "Record Participants by Email with Marketing Event Object Id",
        "description" : "Records the participation of multiple HubSpot contacts in a Marketing Event using their email addresses.\n\nIf a contact does not exist, it will be automatically created. The contactProperties field is used exclusively for creating new contacts and will not update properties of existing contacts.\n\nAdditional Functionality:\n- Adds a timeline event to the contacts.\n\nAllowed Properties:\nFor the state \"attend\":\n- joinedAt\n- leftAt",
        "operationId" : "post-/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/email-create_recordByEmail",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/" : {
      "get" : {
        "tags" : [ "Marketing_Events_V2" ],
        "summary" : "Get all marketing event",
        "description" : "Returns all Marketing Events available on the portal, along with their properties, regardless of whether they were created manually or through the application.\n\nThe marketing events returned by this endpoint are sorted by objectId.",
        "operationId" : "get-/marketing/v3/marketing-events/_getAll",
        "security" : [ {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/create" : {
      "post" : {
        "tags" : [ "Attendance_External_V2" ],
        "summary" : "Record Participants by ContactId with Marketing Event Object Id",
        "description" : "Records the participation of multiple HubSpot contacts in a Marketing Event using their HubSpot contact IDs.\n\nAdditional Functionality:\n- Adds a timeline event to the contacts.\n\nAllowed Properties:\nFor the state \"attend\":\n- joinedAt\n- leftAt",
        "operationId" : "post-/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/create_recordByContactId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/batch/update" : {
      "post" : {
        "tags" : [ "Marketing_Events_V2" ],
        "summary" : "Update Multiple Marketing Events by ObjectId",
        "description" : "Updates multiple Marketing Events on the portal based on their objectId, if they exist.",
        "operationId" : "post-/marketing/v3/marketing-events/batch/update_updateByObjectId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/batch/archive" : {
      "post" : {
        "tags" : [ "Marketing_Events_V2" ],
        "summary" : "Delete Multiple Marketing Events by ObjectId",
        "description" : "Deletes multiple Marketing Events from the portal based on their objectId, if they exist.\n\nResponses:\n204: Returned if all specified Marketing Events were successfully deleted.\n207: Returned if some objectIds did not correspond to any existing Marketing Events.",
        "operationId" : "post-/marketing/v3/marketing-events/batch/archive_archiveByObjectId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}" : {
      "get" : {
        "tags" : [ "Participations_External" ],
        "summary" : "Read participations counters by Marketing Event external identifier",
        "description" : "Read Marketing event's participations counters by externalAccountId and externalEventId pair.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}_getParticipationsCountersByEventExternalId",
        "security" : [ {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{externalEventId}/identifiers" : {
      "get" : {
        "tags" : [ "Marketing_Events_V2" ],
        "summary" : "Find Marketing Events by External Event Id",
        "description" : "This endpoint searches the portal for all Marketing Events whose externalEventId matches the value provided in the request.\n\nIt retrieves the objectId and additional event details for each matching Marketing Event.\n\nSince multiple Marketing Events can have the same externalEventId, the endpoint returns all matching results.\n\nNote: Marketing Events become searchable by externalEventId a few minutes after creation.",
        "operationId" : "get-/marketing/v3/marketing-events/{externalEventId}/identifiers_searchPortalEvents",
        "security" : [ {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{marketingEventId}" : {
      "get" : {
        "tags" : [ "Participations_External" ],
        "summary" : "Read participations counters by Marketing Event internal identifier",
        "description" : "Read Marketing event's participations counters by internal identifier marketingEventId.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/{marketingEventId}_getParticipationsCountersByMarketingEventId",
        "security" : [ {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/delete" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Delete Multiple Marketing Events by External Ids",
        "description" : "Deletes multiple Marketing Events based on externalAccountId, externalEventId, and appId.\n\nOnly Marketing Events created by the same apps will be deleted; events from other apps cannot be removed by this endpoint. ",
        "operationId" : "post-/marketing/v3/marketing-events/events/delete_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/cancel" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Mark a marketing event as cancelled",
        "description" : "Mark a marketing event as cancelled.",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/cancel_cancel",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/associations/{marketingEventId}/lists/{listId}" : {
      "put" : {
        "tags" : [ "Lists_Reference_External" ],
        "summary" : "Associate a list with a marketing event",
        "description" : "Associates a list with a marketing event by marketing event id and ILS list id",
        "operationId" : "put-/marketing/v3/marketing-events/associations/{marketingEventId}/lists/{listId}_associateByMarketingEventId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Lists_Reference_External" ],
        "summary" : "Disassociate a list from a marketing event",
        "description" : "Disassociates a list from a marketing event by marketing event id and ILS list id",
        "operationId" : "delete-/marketing/v3/marketing-events/associations/{marketingEventId}/lists/{listId}_disassociateByMarketingEventId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Record a subscriber state by contact email",
        "description" : "Record a subscriber state between multiple HubSpot contacts and a marketing event, using contact email addresses. Note that the contact must already exist in HubSpot; a contact will not be created. The contactProperties field is used only when creating a new contact. These properties will not update existing contacts. ",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert_upsertByContactEmail",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/complete" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Mark a marketing event as completed",
        "description" : "Mark a marketing event as completed",
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/complete_complete",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists/{listId}" : {
      "put" : {
        "tags" : [ "Lists_Reference_External" ],
        "summary" : "Associate a list with a marketing event",
        "description" : "Associates a list with a marketing event by external account id, external event id, and ILS list id",
        "operationId" : "put-/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists/{listId}_associateByExternalAccountAndEventIds",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Lists_Reference_External" ],
        "summary" : "Disassociate a list from a marketing event",
        "description" : "Disassociates a list from a marketing event by external account id, external event id, and ILS list id",
        "operationId" : "delete-/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists/{listId}_disassociateByExternalAccountAndEventIds",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Create a marketing event",
        "description" : "Creates a new marketing event in HubSpot",
        "operationId" : "post-/marketing/v3/marketing-events/events_create",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown" : {
      "get" : {
        "tags" : [ "Participations_External" ],
        "summary" : "Read participations breakdown by Contact identifier",
        "description" : "Read Contact's participations by identifier - email or internal id.",
        "operationId" : "get-/marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown_getParticipationsBreakdownByContactId",
        "security" : [ {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{appId}/settings" : {
      "get" : {
        "tags" : [ "Settings_External" ],
        "summary" : "Retrieve the application settings",
        "description" : "Retrieve the current settings for the application.",
        "operationId" : "get-/marketing/v3/marketing-events/{appId}/settings_getAll",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Settings_External" ],
        "summary" : "Update the application settings",
        "description" : "Create or update the current settings for the application.",
        "operationId" : "post-/marketing/v3/marketing-events/{appId}/settings_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/search" : {
      "get" : {
        "tags" : [ "Marketing_Events_External" ],
        "summary" : "Find App-Specific Marketing Events by External Event Id",
        "description" : "Retrieves Marketing Events where the externalEventId matches the value provided in the request, limited to events created by the app making the request.\n\nMarketing Events created by other apps will not be included in the results.",
        "operationId" : "get-/marketing/v3/marketing-events/events/search_doSearch",
        "security" : [ {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.marketing_events.read" : "Read marketing events",
              "crm.objects.marketing_events.write" : "Write marketing events"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}