{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Marketing Marketing Events",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "Marketing Events Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/marketing/marketing-events"
    } ]
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Attendance_External"
  }, {
    "name" : "Attendance_External_V2"
  }, {
    "name" : "Lists_Reference_External"
  }, {
    "name" : "Marketing_Events_External"
  }, {
    "name" : "Marketing_Events_V2"
  }, {
    "name" : "Participations_External"
  }, {
    "name" : "Settings_External"
  } ],
  "paths" : {
    "/marketing/v3/marketing-events/" : {
      "get" : {
        "tags" : [ "Marketing_Events_V2" ],
        "operationId" : "get-/marketing/v3/marketing-events/_getAll",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists" : {
      "get" : {
        "tags" : [ "Lists_Reference_External" ],
        "operationId" : "get-/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists_getAllByExternalAccountAndEventIds",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists/{listId}" : {
      "put" : {
        "tags" : [ "Lists_Reference_External" ],
        "operationId" : "put-/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists/{listId}_associateByExternalAccountAndEventIds",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Lists_Reference_External" ],
        "operationId" : "delete-/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists/{listId}_disassociateByExternalAccountAndEventIds",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/associations/{marketingEventId}/lists" : {
      "get" : {
        "tags" : [ "Lists_Reference_External" ],
        "operationId" : "get-/marketing/v3/marketing-events/associations/{marketingEventId}/lists_getAllByMarketingEventId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/associations/{marketingEventId}/lists/{listId}" : {
      "put" : {
        "tags" : [ "Lists_Reference_External" ],
        "operationId" : "put-/marketing/v3/marketing-events/associations/{marketingEventId}/lists/{listId}_associateByMarketingEventId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Lists_Reference_External" ],
        "operationId" : "delete-/marketing/v3/marketing-events/associations/{marketingEventId}/lists/{listId}_disassociateByMarketingEventId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create" : {
      "post" : {
        "tags" : [ "Attendance_External" ],
        "operationId" : "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create_recordByContactIds",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create" : {
      "post" : {
        "tags" : [ "Attendance_External" ],
        "operationId" : "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create_recordByContactEmails",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/batch/archive" : {
      "post" : {
        "tags" : [ "Marketing_Events_V2" ],
        "operationId" : "post-/marketing/v3/marketing-events/batch/archive_archiveByObjectId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/batch/update" : {
      "post" : {
        "tags" : [ "Marketing_Events_V2" ],
        "operationId" : "post-/marketing/v3/marketing-events/batch/update_updateByObjectId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "post-/marketing/v3/marketing-events/events_create",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/delete" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "post-/marketing/v3/marketing-events/events/delete_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/search" : {
      "get" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "get-/marketing/v3/marketing-events/events/search_doSearch",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/upsert" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "post-/marketing/v3/marketing-events/events/upsert_upsert",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}" : {
      "get" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "get-/marketing/v3/marketing-events/events/{externalEventId}_getDetails",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "put-/marketing/v3/marketing-events/events/{externalEventId}_upsert",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "delete-/marketing/v3/marketing-events/events/{externalEventId}_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "patch-/marketing/v3/marketing-events/events/{externalEventId}_update",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/cancel" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/cancel_cancel",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/complete" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/complete_complete",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert_upsertByContactEmail",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert" : {
      "post" : {
        "tags" : [ "Marketing_Events_External" ],
        "operationId" : "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert_upsertByContactId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown" : {
      "get" : {
        "tags" : [ "Participations_External" ],
        "operationId" : "get-/marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown_getParticipationsBreakdownByContactId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}" : {
      "get" : {
        "tags" : [ "Participations_External" ],
        "operationId" : "get-/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}_getParticipationsCountersByEventExternalId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}/breakdown" : {
      "get" : {
        "tags" : [ "Participations_External" ],
        "operationId" : "get-/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}/breakdown_getParticipationsBreakdownByExternalEventId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{marketingEventId}" : {
      "get" : {
        "tags" : [ "Participations_External" ],
        "operationId" : "get-/marketing/v3/marketing-events/participations/{marketingEventId}_getParticipationsCountersByMarketingEventId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/participations/{marketingEventId}/breakdown" : {
      "get" : {
        "tags" : [ "Participations_External" ],
        "operationId" : "get-/marketing/v3/marketing-events/participations/{marketingEventId}/breakdown_getParticipationsBreakdownByMarketingEventId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{appId}/settings" : {
      "get" : {
        "tags" : [ "Settings_External" ],
        "operationId" : "get-/marketing/v3/marketing-events/{appId}/settings_getAll",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Settings_External" ],
        "operationId" : "post-/marketing/v3/marketing-events/{appId}/settings_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{externalEventId}/identifiers" : {
      "get" : {
        "tags" : [ "Marketing_Events_V2" ],
        "operationId" : "get-/marketing/v3/marketing-events/{externalEventId}/identifiers_searchPortalEvents",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{objectId}" : {
      "get" : {
        "tags" : [ "Marketing_Events_V2" ],
        "operationId" : "get-/marketing/v3/marketing-events/{objectId}_getByObjectId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Marketing_Events_V2" ],
        "operationId" : "delete-/marketing/v3/marketing-events/{objectId}_archiveByObjectId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Marketing_Events_V2" ],
        "operationId" : "patch-/marketing/v3/marketing-events/{objectId}_updateByObjectId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/create" : {
      "post" : {
        "tags" : [ "Attendance_External_V2" ],
        "operationId" : "post-/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/create_recordByContactId",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    },
    "/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/email-create" : {
      "post" : {
        "tags" : [ "Attendance_External_V2" ],
        "operationId" : "post-/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/email-create_recordByEmail",
        "security" : [ {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.marketing_events.read" : "Read marketing events",
              "crm.objects.marketing_events.write" : "Write marketing events"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}