{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Conversations Inbox & Messages",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "If you're using the conversations inbox in HubSpot, but you want to report on support agent productivity in an external tool or export message data to an external service, you can build an integration with the conversations and messages API.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Inbox & Messages Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/conversations/inbox-and-messages"
    } ],
    "x-hubspot-introduction" : "Use the conversations API to manage and send messages via the connected channels in your conversations inbox. You can retrieve existing messages, update threads, and provide internal comments for agents on your team. "
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Conversations"
  } ],
  "paths" : {
    "/conversations/v3/conversations/inboxes" : {
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get conversations inboxes.",
        "operationId" : "get-/conversations/v3/conversations/inboxes",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads/{threadId}" : {
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get a single thread.",
        "description" : "Returns a single thread.",
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Conversations" ],
        "summary" : "Archives a thread.",
        "description" : "Archives a single thread. The thread will be permanently deleted 30 days after placed in an archived state.",
        "operationId" : "delete-/conversations/v3/conversations/threads/{threadId}",
        "security" : [ {
          "private_apps_legacy" : [ "conversations.write" ]
        }, {
          "oauth2_legacy" : [ "conversations.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Conversations" ],
        "summary" : "Update a thread.",
        "description" : "Updates a single thread. Either a thread's status can be updated, or the thread can be restored.",
        "operationId" : "patch-/conversations/v3/conversations/threads/{threadId}",
        "security" : [ {
          "private_apps_legacy" : [ "conversations.write" ]
        }, {
          "oauth2_legacy" : [ "conversations.write" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads/{threadId}/messages/{messageId}/original-content" : {
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get the original content of a single message.",
        "description" : "Returns the complete original text and rich text bodies of a message. This will be different from the text and rich text in the message itself if the message's `truncationStatus` is anything other than `NOT_TRUNCATED`.",
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}/messages/{messageId}/original-content",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads/{threadId}/messages" : {
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get message history for a thread.",
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}/messages",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Conversations" ],
        "summary" : "Send a message to a thread.",
        "description" : "Send a new message on a thread at the current timestamp.",
        "operationId" : "post-/conversations/v3/conversations/threads/{threadId}/messages",
        "security" : [ {
          "private_apps_legacy" : [ "conversations.write" ]
        }, {
          "oauth2_legacy" : [ "conversations.write" ]
        } ]
      }
    },
    "/conversations/v3/conversations/actors/batch/read" : {
      "post" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get actors",
        "description" : "Resolve `ActorId`s to the underlying actors/participants.",
        "operationId" : "post-/conversations/v3/conversations/actors/batch/read",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/channel-accounts" : {
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get channel accounts.",
        "operationId" : "get-/conversations/v3/conversations/channel-accounts",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/channels/{channelId}" : {
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get a single channel.",
        "operationId" : "get-/conversations/v3/conversations/channels/{channelId}",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads/{threadId}/messages/{messageId}" : {
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get a single message.",
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}/messages/{messageId}",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/channels" : {
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get channels.",
        "operationId" : "get-/conversations/v3/conversations/channels",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/actors/{actorId}" : {
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get a single actor.",
        "operationId" : "get-/conversations/v3/conversations/actors/{actorId}",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads" : {
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get threads.",
        "operationId" : "get-/conversations/v3/conversations/threads",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/channel-accounts/{channelAccountId}" : {
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get a single channel account.",
        "operationId" : "get-/conversations/v3/conversations/channel-accounts/{channelAccountId}",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/inboxes/{inboxId}" : {
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get a single conversations inbox.",
        "operationId" : "get-/conversations/v3/conversations/inboxes/{inboxId}",
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "conversations.read" : "Read from conversations",
              "conversations.write" : "Write to conversations"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  }
}