{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Associations",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v4",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "When an existing contact has moved to a new company, update their associated company to keep your CRM up to date.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Associations guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v4"
    } ],
    "x-hubspot-introduction" : "Use the associations API to create, retrieve, update, or delete associations between records, or between records and activities. "
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Report"
  } ],
  "paths" : {
    "/crm/v4/associations/usage/high-usage-report/{userId}" : {
      "post" : {
        "tags" : [ "Report" ],
        "summary" : "Report",
        "description" : "Requests a report of all objects in the portal which have a high usage of associations",
        "operationId" : "post-/crm/v4/associations/usage/high-usage-report/{userId}_request",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Delete",
        "description" : "Batch delete associations for objects",
        "operationId" : "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/archive_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/associate/default" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : " Create Default Associations",
        "description" : "Create the default (most generic) association type between two object types",
        "operationId" : "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/associate/default_createDefault",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create",
        "description" : "Batch create associations for objects",
        "operationId" : "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/create_create",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/labels/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Delete Specific Labels",
        "description" : "Batch delete specific association labels for objects. Deleting an unlabeled association will also delete all labeled associations between those two objects",
        "operationId" : "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/labels/archive_archiveLabels",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read",
        "description" : "Batch read associations for objects to specific object type. The 'after' field in a returned paging object  can be added alongside the 'id' to retrieve the next page of associations from that objectId. The 'link' field is deprecated and should be ignored. Note: The 'paging' field will only be present if there are more pages and absent otherwise.",
        "operationId" : "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/read_getPage",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/v4/objects/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Create Default",
        "description" : "Create the default (most generic) association type between two object types",
        "operationId" : "put-/crm/v4/objects/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}_createDefault",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "oauth" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List",
        "description" : "List all associations of an object by object type. Limit 500 per call.",
        "operationId" : "get-/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}_getPage",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "oauth" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Create",
        "description" : "Set association labels between two records.",
        "operationId" : "put-/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_create",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "oauth" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete",
        "description" : "deletes all associations between two records.",
        "operationId" : "delete-/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-services.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "oauth" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_1" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.appointments.read" : "Read appointments",
              "crm.objects.appointments.sensitive.read.v2" : "Read appointments (sensitive)",
              "crm.objects.appointments.sensitive.write.v2" : "Write appointments (sensitive)",
              "crm.objects.appointments.write" : "Write appointments",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.carts.write" : "Write cart",
              "crm.objects.commercepayments.read" : "Read commerce payments",
              "crm.objects.commercepayments.write" : "Write commerce payments",
              "crm.objects.companies.highly_sensitive.read.v2" : "View company records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.write.v2" : "Change company records (highly-sensitive)",
              "crm.objects.companies.read" : "Create or update company records",
              "crm.objects.companies.sensitive.read.v2" : "View sensitive properties on company records",
              "crm.objects.companies.sensitive.write.v2" : "Create or update sensitive properties on company records",
              "crm.objects.companies.write" : "View company records",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.contacts.read" : "View contact records",
              "crm.objects.contacts.sensitive.read.v2" : "View sensitive properties on contact records",
              "crm.objects.contacts.sensitive.write.v2" : "Create or update sensitive properties on contact records",
              "crm.objects.contacts.write" : "Create or update contact records",
              "crm.objects.courses.read" : "Read courses",
              "crm.objects.courses.write" : "Write courses",
              "crm.objects.custom.highly_sensitive.read.v2" : "View custom object records (highly-sensitive)",
              "crm.objects.custom.highly_sensitive.write.v2" : "Change custom object records (highly-sensitive)",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.custom.sensitive.read.v2" : "View custom object records (sensitive)",
              "crm.objects.custom.sensitive.write.v2" : "Change custom object records (sensitive)",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.deals.highly_sensitive.read.v2" : "View deal records (highly-sensitive)",
              "crm.objects.deals.highly_sensitive.write.v2" : "Change deal records (highly-sensitive)",
              "crm.objects.deals.read" : "View deal records",
              "crm.objects.deals.sensitive.read.v2" : "View sensitive properties on deal records",
              "crm.objects.deals.sensitive.write.v2" : "Create or update sensitive properties on deal records",
              "crm.objects.deals.write" : "Create or update deal records",
              "crm.objects.goals.read" : "Read access to goals",
              "crm.objects.goals.write" : "Create and update goals",
              "crm.objects.invoices.read" : "Read invoices",
              "crm.objects.invoices.write" : "Write invoices",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.listings.read" : "Read listings",
              "crm.objects.listings.write" : "Write listings",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.partner-clients.write" : "Edit Partner Client CRM objects",
              "crm.objects.partner-services.read" : "View Partner Service CRM objects",
              "crm.objects.partner-services.write" : "Edit Partner Service CRM objects",
              "crm.objects.products.read" : "Read products in Products Library",
              "crm.objects.products.write" : "Write products in Products Library",
              "crm.objects.projects.highly_sensitive.read" : "Read projects (highly-sensitive)",
              "crm.objects.projects.highly_sensitive.write" : "Write projects (highly-sensitive)",
              "crm.objects.projects.read" : "Read projects",
              "crm.objects.projects.sensitive.read" : "Read projects (sensitive)",
              "crm.objects.projects.sensitive.write" : "Write projects (sensitive)",
              "crm.objects.projects.write" : "Write projects",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.services.read" : "Read services",
              "crm.objects.services.write" : "Write services",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.subscriptions.write" : "Write subscriptions",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.users.write" : "Write User CRM objects",
              "e-commerce" : "Access to ecommerce",
              "media_bridge.read" : "Read media and media events",
              "oauth" : "Basic HubSpot account information",
              "tickets" : "Tickets",
              "tickets.highly_sensitive.v2" : "Tickets (highly-sensitive)",
              "tickets.sensitive.v2" : "Tickets (sensitive)"
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.appointments.read" : "Read appointments",
              "crm.objects.appointments.sensitive.read.v2" : "Read appointments (sensitive)",
              "crm.objects.appointments.sensitive.write.v2" : "Write appointments (sensitive)",
              "crm.objects.appointments.write" : "Write appointments",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.carts.write" : "Write cart",
              "crm.objects.commercepayments.read" : "Read commerce payments",
              "crm.objects.commercepayments.write" : "Write commerce payments",
              "crm.objects.companies.highly_sensitive.read.v2" : "View company records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.write.v2" : "Change company records (highly-sensitive)",
              "crm.objects.companies.read" : "Create or update company records",
              "crm.objects.companies.sensitive.read.v2" : "View sensitive properties on company records",
              "crm.objects.companies.sensitive.write.v2" : "Create or update sensitive properties on company records",
              "crm.objects.companies.write" : "View company records",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.contacts.read" : "View contact records",
              "crm.objects.contacts.sensitive.read.v2" : "View sensitive properties on contact records",
              "crm.objects.contacts.sensitive.write.v2" : "Create or update sensitive properties on contact records",
              "crm.objects.contacts.write" : "Create or update contact records",
              "crm.objects.courses.read" : "Read courses",
              "crm.objects.courses.write" : "Write courses",
              "crm.objects.custom.highly_sensitive.read.v2" : "View custom object records (highly-sensitive)",
              "crm.objects.custom.highly_sensitive.write.v2" : "Change custom object records (highly-sensitive)",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.custom.sensitive.read.v2" : "View custom object records (sensitive)",
              "crm.objects.custom.sensitive.write.v2" : "Change custom object records (sensitive)",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.deals.highly_sensitive.read.v2" : "View deal records (highly-sensitive)",
              "crm.objects.deals.highly_sensitive.write.v2" : "Change deal records (highly-sensitive)",
              "crm.objects.deals.read" : "View deal records",
              "crm.objects.deals.sensitive.read.v2" : "View sensitive properties on deal records",
              "crm.objects.deals.sensitive.write.v2" : "Create or update sensitive properties on deal records",
              "crm.objects.deals.write" : "Create or update deal records",
              "crm.objects.goals.read" : "Read access to goals",
              "crm.objects.goals.write" : "Create and update goals",
              "crm.objects.invoices.read" : "Read invoices",
              "crm.objects.invoices.write" : "Write invoices",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.listings.read" : "Read listings",
              "crm.objects.listings.write" : "Write listings",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.partner-clients.write" : "Edit Partner Client CRM objects",
              "crm.objects.partner-services.read" : "View Partner Service CRM objects",
              "crm.objects.partner-services.write" : "Edit Partner Service CRM objects",
              "crm.objects.products.read" : "Read products in Products Library",
              "crm.objects.products.write" : "Write products in Products Library",
              "crm.objects.projects.highly_sensitive.read" : "Read projects (highly-sensitive)",
              "crm.objects.projects.highly_sensitive.write" : "Write projects (highly-sensitive)",
              "crm.objects.projects.read" : "Read projects",
              "crm.objects.projects.sensitive.read" : "Read projects (sensitive)",
              "crm.objects.projects.sensitive.write" : "Write projects (sensitive)",
              "crm.objects.projects.write" : "Write projects",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.services.read" : "Read services",
              "crm.objects.services.write" : "Write services",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.subscriptions.write" : "Write subscriptions",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.users.write" : "Write User CRM objects",
              "e-commerce" : "Access to ecommerce",
              "media_bridge.read" : "Read media and media events",
              "tickets" : "Tickets",
              "tickets.highly_sensitive.v2" : "Tickets (highly-sensitive)",
              "tickets.sensitive.v2" : "Tickets (sensitive)"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}