{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Associations",
    "version" : "v4",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "Lorsqu'un contact existant a rejoint une nouvelle entreprise, mettez à jour leur entreprise associée pour maintenir votre CRM à jour.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Associations Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/crm/associations"
    } ],
    "x-hubspot-introduction" : "Utilisez l'API d'associations pour créer, récupérer, mettre à jour, ou supprimer des associations entre des enregistrements, ou entre des enregistrements et des activités. "
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Lot"
  }, {
    "name" : "Basique"
  } ],
  "paths" : {
    "/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/archive" : {
      "post" : {
        "tags" : [ "Lot" ],
        "summary" : "Supprimer",
        "description" : "Supprimer en lot les associations pour les objets",
        "operationId" : "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/archive_archive",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    },
    "/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/create" : {
      "post" : {
        "tags" : [ "Lot" ],
        "summary" : "Créer",
        "description" : "Créer en lot des associations pour les objets",
        "operationId" : "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/create_create",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    },
    "/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/labels/archive" : {
      "post" : {
        "tags" : [ "Lot" ],
        "summary" : "Supprimer des étiquettes spécifiques",
        "description" : "Supprimer en lot des étiquettes d'association spécifiques pour des objets. La suppression d'une association non étiquetée supprimera également toutes les associations étiquetées entre ces deux objets.",
        "operationId" : "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/labels/archive_archiveLabels",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    },
    "/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/read" : {
      "post" : {
        "tags" : [ "Lot" ],
        "summary" : "Lu",
        "description" : "Lire en lot les associations pour des objets d'un type d'objet spécifique. Le champ « après » dans un objet de pagination retourné peut être ajouté avec l'« identifiant » pour récupérer la page suivante des associations à partir de cet identifiant d'objet. Le champ « lien » est obsolète et doit être ignoré. Remarque : le champ « pagination » ne sera présent que s'il y a plus de pages et sera absent dans le cas contraire.",
        "operationId" : "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/read_getPage",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    },
    "/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/associate/default" : {
      "post" : {
        "tags" : [ "Lot" ],
        "summary" : " Créer des associations par défaut",
        "description" : "Créer le type d'association par défaut (le plus générique) entre deux types d'objets",
        "operationId" : "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/associate/default_createDefault",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    },
    "/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Basique" ],
        "summary" : "Créer",
        "description" : "Définir des libellés d'association entre deux fiches d'informations.",
        "operationId" : "put-/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_create",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basique" ],
        "summary" : "Supprimer",
        "description" : "supprime toutes les associations entre deux fiches d'informations.",
        "operationId" : "delete-/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_archive",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    },
    "/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}" : {
      "get" : {
        "tags" : [ "Basique" ],
        "summary" : "Liste",
        "description" : "Listes toutes les associations d'un objet par type d'objet. Limite de 500 par appel.",
        "operationId" : "get-/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}_getPage",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    },
    "/crm/v4/objects/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Basique" ],
        "summary" : "Créer par défaut",
        "description" : "Créer le type d'association par défaut (le plus générique) entre deux types d'objets",
        "operationId" : "put-/crm/v4/objects/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}_createDefault",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.custom.read" : "View custom object records",
              "e-commerce" : "e-commerce",
              "crm.objects.custom.write" : "Change custom object records",
              "media_bridge.read" : "Read media and media events",
              "crm.objects.goals.read" : "Read goals",
              "tickets" : "Read and write tickets"
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.deals.write" : " ",
              "crm.objects.users.write" : "Write User CRM objects",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.companies.write" : " ",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.contacts.read" : " ",
              "crm.objects.invoices.read" : "Read invoices objects",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.partner-clients.write" : "Modify Partner Client CRM objects",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.deals.read" : " ",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.commercepayments.read" : "Read the COMMERCE_PAYMENT object.",
              "crm.objects.contacts.write" : " ",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.companies.read" : " ",
              "crm.objects.carts.write" : "Write cart"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}