{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Provisioning d'utilisateur",
    "description" : "Add, manage, and remove users from your account",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "Vous gérez les données d'accès des employés dans un système en dehors de HubSpot, et vous souhaitez vous assurer que des utilisateurs spécifiques sont dynamiquement affectés aux bonnes équipes dans votre compte HubSpot.",
    "x-hubspot-related-documentation" : [ {
      "name" : "User Provisioning Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/settings/users/user-provisioning"
    } ],
    "x-hubspot-introduction" : "Utilisez l'API de provisionnement d'utilisateur pour créer et gérer des utilisateurs dans votre compte HubSpot, ainsi que leurs équipes et rôles associés."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Équipes"
  }, {
    "name" : "Rôles"
  }, {
    "name" : "Utilisateurs"
  } ],
  "paths" : {
    "/settings/v3/users/teams" : {
      "get" : {
        "tags" : [ "Équipes" ],
        "summary" : "Voir les détails concernant les équipes de ce compte",
        "description" : "Affichez les équipes pour ce compte",
        "operationId" : "get-/settings/v3/users/teams_getAll",
        "security" : [ {
          "oauth2_legacy" : [ "settings.users.teams.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.teams.read" ]
        } ]
      }
    },
    "/settings/v3/users/roles" : {
      "get" : {
        "tags" : [ "Rôles" ],
        "summary" : "Récupère les rôles sur un compte",
        "description" : "Récupère les rôles sur un compte",
        "operationId" : "get-/settings/v3/users/roles_getAll",
        "security" : [ {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      }
    },
    "/settings/v3/users/" : {
      "get" : {
        "tags" : [ "Utilisateurs" ],
        "summary" : "Récupère une liste d'utilisateurs d'un compte",
        "description" : "Récupère une liste d'utilisateurs d'un compte",
        "operationId" : "get-/settings/v3/users/_getPage",
        "security" : [ {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Utilisateurs" ],
        "summary" : "Ajoute un utilisateur",
        "description" : "Les nouveaux utilisateurs auront uniquement des permissions minimales, basées sur les contacts. Un e-mail de bienvenue les invitera à créer un mot de passe et à se connecter à HubSpot.",
        "operationId" : "post-/settings/v3/users/_create",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/settings/v3/users/{userId}" : {
      "get" : {
        "tags" : [ "Utilisateurs" ],
        "summary" : "Récupère un utilisateur",
        "description" : "Récupère un utilisateur identifié par « userId ». « userId » désigne par défaut l'identifiant de l'utilisateur ou, optionnellement, l'e-mail comme indiqué par le paramètre de requête « IdProperty ».",
        "operationId" : "get-/settings/v3/users/{userId}_getById",
        "security" : [ {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Utilisateurs" ],
        "summary" : "Modifier un utilisateur.",
        "description" : "Modifie un utilisateur identifié par « userId ». « userId » désigne par défaut l'identifiant de l'utilisateur ou, optionnellement, l'e-mail comme indiqué par le paramètre de requête « IdProperty ».",
        "operationId" : "put-/settings/v3/users/{userId}_replace",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Utilisateurs" ],
        "summary" : "Supprime un utilisateur",
        "description" : "Supprime un utilisateur identifié par « userId ». « userId » désigne par défaut l'identifiant de l'utilisateur ou, optionnellement, l'e-mail comme indiqué par le paramètre de requête « IdProperty ».",
        "operationId" : "delete-/settings/v3/users/{userId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "settings.users.read" : "View account data.",
              "settings.users.write" : "Create, modify, and delete users on your account",
              "settings.users.teams.read" : "View teams for this account."
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.users.write" : "Write User CRM objects"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE"
  },
  "x-hubspot-documentation-banner" : "NONE"
}