{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Users",
    "description" : "Add, manage, and remove users from your account",
    "version" : "v3"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Teams"
  }, {
    "name" : "Roles"
  }, {
    "name" : "Users"
  } ],
  "paths" : {
    "/settings/v3/users/" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Retrieves a list of users from an account",
        "description" : "Retrieves a list of users from an account",
        "operationId" : "get-/settings/v3/users/_getPage",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "Adds a user",
        "description" : "New users will only have minimal permissions, which is contacts-base. A welcome email will prompt them to set a password and log in to HubSpot.",
        "operationId" : "post-/settings/v3/users/_create",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        } ]
      }
    },
    "/settings/v3/users/teams" : {
      "get" : {
        "tags" : [ "Teams" ],
        "summary" : "See details about this account's teams",
        "description" : "View teams for this account",
        "operationId" : "get-/settings/v3/users/teams_getAll",
        "security" : [ {
          "oauth2_legacy" : [ "settings.users.teams.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.teams.read" ]
        } ]
      }
    },
    "/settings/v3/users/{userId}" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Retrieves a user",
        "description" : "Retrieves a user identified by `userId`. `userId` refers to the user's ID by default, or optionally email as specified by the `IdProperty` query param.",
        "operationId" : "get-/settings/v3/users/{userId}_getById",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Users" ],
        "summary" : "Modifies a user",
        "description" : "Modifies a user identified by `userId`. `userId` refers to the user's ID by default, or optionally email as specified by the `IdProperty` query param.",
        "operationId" : "put-/settings/v3/users/{userId}_replace",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Users" ],
        "summary" : "Removes a user",
        "description" : "Removes a user identified by `userId`. `userId` refers to the user's ID by default, or optionally email as specified by the `IdProperty` query param.",
        "operationId" : "delete-/settings/v3/users/{userId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        } ]
      }
    },
    "/settings/v3/users/roles" : {
      "get" : {
        "tags" : [ "Roles" ],
        "summary" : "Retrieves the roles on an account",
        "description" : "Retrieves the roles on an account",
        "operationId" : "get-/settings/v3/users/roles_getAll",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "settings.users.read" : "View account data.",
              "settings.users.write" : "Create, modify, and delete users on your account",
              "settings.users.teams.read" : "View teams for this account."
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ]
}