{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "ユーザープロビジョニング",
    "description" : "Add, manage, and remove users from your account",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "HubSpot外のシステムで従業員のアクセスデータを管理しており、特定のユーザーが確実にHubSpotアカウントの適切なチームに動的に割り当てられるようにしたいと考えています。",
    "x-hubspot-related-documentation" : [ {
      "name" : "User Provisioning Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/settings/users/user-provisioning"
    } ],
    "x-hubspot-introduction" : "ユーザープロビジョニングAPIを使用して、関連付けられているチームや役割を含めて、HubSpotアカウントのユーザーの作成や管理を行います。"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "チーム"
  }, {
    "name" : "役割"
  }, {
    "name" : "ユーザー"
  } ],
  "paths" : {
    "/settings/v3/users/teams" : {
      "get" : {
        "tags" : [ "チーム" ],
        "summary" : "このアカウントのチームに関する詳細を確認",
        "description" : "このアカウントのチームを表示",
        "operationId" : "get-/settings/v3/users/teams_getAll",
        "security" : [ {
          "oauth2_legacy" : [ "settings.users.teams.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.teams.read" ]
        } ]
      }
    },
    "/settings/v3/users/roles" : {
      "get" : {
        "tags" : [ "役割" ],
        "summary" : "アカウントでの役割が取得されます",
        "description" : "アカウントでの役割が取得されます",
        "operationId" : "get-/settings/v3/users/roles_getAll",
        "security" : [ {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      }
    },
    "/settings/v3/users/" : {
      "get" : {
        "tags" : [ "ユーザー" ],
        "summary" : "アカウントからユーザーのリストが取得されます",
        "description" : "アカウントからユーザーのリストが取得されます",
        "operationId" : "get-/settings/v3/users/_getPage",
        "security" : [ {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "ユーザー" ],
        "summary" : "ユーザーを追加",
        "description" : "新規ユーザーにはコンタクトに基づいて最小限の権限が付与されます。ウェルカムEメールを送信すれば、パスワードを設定してHubSpotにログインするよう促すことができます。",
        "operationId" : "post-/settings/v3/users/_create",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/settings/v3/users/{userId}" : {
      "get" : {
        "tags" : [ "ユーザー" ],
        "summary" : "ユーザーが取得されます",
        "description" : "「userId」によって特定されるユーザーが取得されます。「userId」は既定ではユーザーのIDを指しますが、必要に応じて「IdProperty」クエリーパラメーターによって指定されたEメールを指すこともできます。",
        "operationId" : "get-/settings/v3/users/{userId}_getById",
        "security" : [ {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "ユーザー" ],
        "summary" : "ユーザーが変更されます",
        "description" : "「userId」によって特定されるユーザーが変更されます。「userId」は既定ではユーザーのIDを指しますが、必要に応じて「IdProperty」クエリーパラメーターによって指定されたEメールを指すこともできます。",
        "operationId" : "put-/settings/v3/users/{userId}_replace",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "ユーザー" ],
        "summary" : "ユーザーが削除されます",
        "description" : "「userId」によって特定されるユーザーが削除されます。「userId」は既定ではユーザーのIDを指しますが、必要に応じて「IdProperty」クエリーパラメーターによって指定されたEメールを指すこともできます。",
        "operationId" : "delete-/settings/v3/users/{userId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "settings.users.read" : "View account data.",
              "settings.users.write" : "Create, modify, and delete users on your account",
              "settings.users.teams.read" : "View teams for this account."
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.users.write" : "Write User CRM objects"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE"
  },
  "x-hubspot-documentation-banner" : "NONE"
}