{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Settings User Provisioning",
    "description" : "Add, manage, and remove users from your account",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "User Provisioning Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/settings/users/user-provisioning"
    } ]
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Roles"
  }, {
    "name" : "Teams"
  }, {
    "name" : "Users"
  } ],
  "paths" : {
    "/settings/v3/users/" : {
      "get" : {
        "tags" : [ "Users" ],
        "operationId" : "get-/settings/v3/users/_getPage",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "settings.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "settings.users.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Users" ],
        "operationId" : "post-/settings/v3/users/_create",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "settings.users.write" ]
        }, {
          "private_apps" : [ "settings.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/settings/v3/users/roles" : {
      "get" : {
        "tags" : [ "Roles" ],
        "operationId" : "get-/settings/v3/users/roles_getAll",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "settings.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "settings.users.read" ]
        } ]
      }
    },
    "/settings/v3/users/teams" : {
      "get" : {
        "tags" : [ "Teams" ],
        "operationId" : "get-/settings/v3/users/teams_getAll",
        "security" : [ {
          "oauth2" : [ "settings.users.teams.read" ]
        }, {
          "private_apps" : [ "settings.users.teams.read" ]
        } ]
      }
    },
    "/settings/v3/users/{userId}" : {
      "get" : {
        "tags" : [ "Users" ],
        "operationId" : "get-/settings/v3/users/{userId}_getById",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "settings.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "settings.users.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Users" ],
        "operationId" : "put-/settings/v3/users/{userId}_replace",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "settings.users.write" ]
        }, {
          "private_apps" : [ "settings.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Users" ],
        "operationId" : "delete-/settings/v3/users/{userId}_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "settings.users.write" ]
        }, {
          "private_apps" : [ "settings.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.users.write" : "Write User CRM objects",
              "settings.users.read" : "View account data.",
              "settings.users.teams.read" : "View teams for this account.",
              "settings.users.write" : "Create, modify, and delete users on your account"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}