{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "User Provisioning",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "You manage employee access data in a system outside of HubSpot, and you want to ensure that specific users are dynamically allocated to the right teams in your HubSpot account.",
    "x-hubspot-related-documentation" : [ {
      "name" : "User Provisioning Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/settings/users/user-provisioning"
    } ],
    "x-hubspot-introduction" : "Use the user provisioning API to create and manage users in your HubSpot account, along with their associated teams and roles."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Public_User_Provisioning"
  } ],
  "paths" : {
    "/settings/v3/users/" : {
      "get" : {
        "tags" : [ "Public_User_Provisioning" ],
        "summary" : "Retrieves a list of users from an account",
        "description" : "Retrieves a list of users from an account",
        "operationId" : "get-/settings/v3/users/_getPage",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "settings.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "settings.users.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Public_User_Provisioning" ],
        "summary" : "Adds a user",
        "description" : "New users will only have minimal permissions, which is contacts-base. A welcome email will prompt them to set a password and log in to HubSpot.",
        "operationId" : "post-/settings/v3/users/_create",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "settings.users.write" ]
        }, {
          "private_apps" : [ "settings.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/settings/v3/users/roles" : {
      "get" : {
        "tags" : [ "Public_User_Provisioning" ],
        "summary" : "Retrieves the roles on an account",
        "description" : "Retrieves the roles on an account",
        "operationId" : "get-/settings/v3/users/roles_getAll",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "settings.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "settings.users.read" ]
        } ]
      }
    },
    "/settings/v3/users/teams" : {
      "get" : {
        "tags" : [ "Public_User_Provisioning" ],
        "summary" : "See details about this account's teams",
        "description" : "View teams for this account",
        "operationId" : "get-/settings/v3/users/teams_getAll",
        "security" : [ {
          "oauth2" : [ "settings.users.teams.read" ]
        }, {
          "private_apps" : [ "settings.users.teams.read" ]
        } ]
      }
    },
    "/settings/v3/users/{userId}" : {
      "get" : {
        "tags" : [ "Public_User_Provisioning" ],
        "summary" : "Retrieves a user",
        "description" : "Retrieves a user identified by `userId`. `userId` refers to the user's ID by default, or optionally email as specified by the `IdProperty` query param.",
        "operationId" : "get-/settings/v3/users/{userId}_getById",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "settings.users.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "settings.users.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Public_User_Provisioning" ],
        "summary" : "Modifies a user",
        "description" : "Modifies a user identified by `userId`. `userId` refers to the user's ID by default, or optionally email as specified by the `IdProperty` query param.",
        "operationId" : "put-/settings/v3/users/{userId}_replace",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "settings.users.write" ]
        }, {
          "private_apps" : [ "settings.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Public_User_Provisioning" ],
        "summary" : "Removes a user",
        "description" : "Removes a user identified by `userId`. `userId` refers to the user's ID by default, or optionally email as specified by the `IdProperty` query param.",
        "operationId" : "delete-/settings/v3/users/{userId}_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "settings.users.write" ]
        }, {
          "private_apps" : [ "settings.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.users.write" : "Write User CRM objects",
              "settings.users.read" : "View account data.",
              "settings.users.teams.read" : "View teams for this account.",
              "settings.users.write" : "Create, modify, and delete users on your account"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}