{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Aprovisionamiento de usuarios",
    "description" : "Add, manage, and remove users from your account",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "Gestionas los datos a los que pueden acceder los empleados en un sistema fuera de HubSpot, y quieres asegurarte de que los usuarios específicos se asignen dinámicamente a los equipos correctos en tu cuenta de HubSpot.",
    "x-hubspot-related-documentation" : [ {
      "name" : "User Provisioning Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/settings/users/user-provisioning"
    } ],
    "x-hubspot-introduction" : "Utiliza la API de aprovisionamiento de usuarios para crear y gestionar usuarios en tu cuenta de HubSpot, junto con sus equipos y roles asociados."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Equipos"
  }, {
    "name" : "Roles"
  }, {
    "name" : "Usuarios"
  } ],
  "paths" : {
    "/settings/v3/users/teams" : {
      "get" : {
        "tags" : [ "Equipos" ],
        "summary" : "Ver detalles sobre los equipos de esta cuenta",
        "description" : "Ver los equipos de esta cuenta.",
        "operationId" : "get-/settings/v3/users/teams_getAll",
        "security" : [ {
          "oauth2_legacy" : [ "settings.users.teams.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.teams.read" ]
        } ]
      }
    },
    "/settings/v3/users/roles" : {
      "get" : {
        "tags" : [ "Roles" ],
        "summary" : "Recupera los roles de una cuenta",
        "description" : "Recupera los roles de una cuenta",
        "operationId" : "get-/settings/v3/users/roles_getAll",
        "security" : [ {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      }
    },
    "/settings/v3/users/" : {
      "get" : {
        "tags" : [ "Usuarios" ],
        "summary" : "Recupera una lista de usuarios de una cuenta",
        "description" : "Recupera una lista de usuarios de una cuenta",
        "operationId" : "get-/settings/v3/users/_getPage",
        "security" : [ {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Usuarios" ],
        "summary" : "Agrega un usuario",
        "description" : "Los nuevos usuarios solo tendrán permisos mínimos, que se basan en los contactos. Un correo con un mensaje de bienvenida les pedirá que establezcan una contraseña e inicien sesión en HubSpot.",
        "operationId" : "post-/settings/v3/users/_create",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/settings/v3/users/{userId}" : {
      "get" : {
        "tags" : [ "Usuarios" ],
        "summary" : "Recupera un usuario",
        "description" : "Recupera un usuario identificado por \"userId\". Por opción predeterminada, \"userId\" hace referencia al ID del usuario, u opcionalmente al correo especificado por el parámetro de consulta \"IdProperty\".",
        "operationId" : "get-/settings/v3/users/{userId}_getById",
        "security" : [ {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Usuarios" ],
        "summary" : "Modifica un usuario",
        "description" : "Modifica un usuario identificado por \"userId\". Por opción predeterminada, \"userId\" hace referencia al ID del usuario, u opcionalmente al correo especificado por el parámetro de consulta \"IdProperty\".",
        "operationId" : "put-/settings/v3/users/{userId}_replace",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Usuarios" ],
        "summary" : "Elimina un usuario",
        "description" : "Elimina un usuario identificado por \"userId\". Por opción predeterminada, \"userId\" hace referencia al ID del usuario, u opcionalmente al correo especificado por el parámetro de consulta \"IdProperty\".",
        "operationId" : "delete-/settings/v3/users/{userId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "settings.users.read" : "View account data.",
              "settings.users.write" : "Create, modify, and delete users on your account",
              "settings.users.teams.read" : "View teams for this account."
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.users.write" : "Write User CRM objects"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE"
  },
  "x-hubspot-documentation-banner" : "NONE"
}