{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Payments",
    "description" : "CRM objects such as companies, contacts, deals, line items, products, tickets, and quotes are standard objects in HubSpot’s CRM. These core building blocks support custom properties, store critical information, and play a central role in the HubSpot application.\n\n## Supported Object Types\n\nThis API provides access to collections of CRM objects, which return a map of property names to values. Each object type has its own set of default properties, which can be found by ex[...]",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-documentation-banner" : "NONE"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Batch",
    "description" : "",
    "x-hubspot-tag-name-english-source" : "Batch"
  }, {
    "name" : "Search",
    "description" : "",
    "x-hubspot-tag-name-english-source" : "Search"
  } ],
  "paths" : {
    "/crm/v3/objects/{objectType}/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of objects by internal ID, or unique property values",
        "operationId" : "post-/crm/v3/objects/{objectType}/batch/read",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    },
    "/crm/v3/objects/{objectType}/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "operationId" : "post-/crm/v3/objects/{objectType}/search",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "media_bridge.read" : "Read media and media events",
              "tickets" : "Read and write tickets",
              "crm.objects.goals.read" : "Read goals",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.custom.write" : "Change custom object records",
              "e-commerce" : "e-commerce"
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.deals.read" : " ",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.contacts.read" : " ",
              "crm.objects.contacts.write" : " ",
              "crm.objects.companies.write" : " ",
              "crm.objects.companies.read" : " ",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.deals.write" : " "
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  }
}