{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Goal Targets",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "PROFESSIONAL",
      "sales" : "STARTER",
      "service" : "PROFESSIONAL",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "Use goals data to create reports for your sales or service team to analyze how your reps are performing.",
    "x-hubspot-introduction" : "Goals in HubSpot are user-specific quotas for their sales and services teams based on templates provided by HubSpot. The goals API allows you to retrieve goals data in your HubSpot account. "
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/objects/2026-03/goal_targets" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve goal targets",
        "description" : "Read a page of goal targets. Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/objects/2026-03/goal_targets_getPage",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a goal target",
        "description" : "Create a goal target with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard goal targets is provided.",
        "operationId" : "post-/crm/objects/2026-03/goal_targets_create",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/objects/2026-03/goal_targets/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Delete goal targets",
        "description" : "Archive multiple goal targets in a single batch operation using their IDs.",
        "operationId" : "post-/crm/objects/2026-03/goal_targets/batch/archive_archive",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/objects/2026-03/goal_targets/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create goal targets",
        "description" : "Create multiple goal targets in a single batch operation.",
        "operationId" : "post-/crm/objects/2026-03/goal_targets/batch/create_create",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/objects/2026-03/goal_targets/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve goal targets",
        "description" : "Retrieve records by record ID or include the `idProperty` parameter to retrieve records by a custom unique value property. ",
        "operationId" : "post-/crm/objects/2026-03/goal_targets/batch/read_read",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/objects/2026-03/goal_targets/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update goal targets",
        "description" : "Update multiple goal targets in a single batch operation using their internal IDs or unique property values.",
        "operationId" : "post-/crm/objects/2026-03/goal_targets/batch/update_update",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/objects/2026-03/goal_targets/batch/upsert" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Upsert goal tagets",
        "description" : "Create and update a batch of goal targets by a unique property. Goal targets that don't exist will be created, while existing goal targets will be updated.",
        "operationId" : "post-/crm/objects/2026-03/goal_targets/batch/upsert_upsert",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/objects/2026-03/goal_targets/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "summary" : "Search for goal targets",
        "description" : "Search for goal targets using specified criteria.",
        "operationId" : "post-/crm/objects/2026-03/goal_targets/search_doSearch",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY",
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/objects/2026-03/goal_targets/{goalTargetId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve a goal target",
        "description" : "Retrieve a goal target by its ID. You can specify what is returned using the `properties` query parameter.",
        "operationId" : "get-/crm/objects/2026-03/goal_targets/{goalTargetId}_getById",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete a goal target",
        "description" : "Delete a goal target by `{goalTargetId}` to the recycling bin.",
        "operationId" : "delete-/crm/objects/2026-03/goal_targets/{goalTargetId}_archive",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update a goal target",
        "description" : "Perform a partial update of an Object identified by `{goalTargetId}`or optionally a unique property value as specified by the `idProperty` query param. `{goalTargetId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty strin[...]",
        "operationId" : "patch-/crm/objects/2026-03/goal_targets/{goalTargetId}_update",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/objects/2026-03/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Batch" ],
        "operationId" : "put-/crm/objects/2026-03/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}_/crm/objects/2026-03/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm-public-object-api-access" : "",
              "crm.objects.goals.read" : "",
              "crm.objects.goals.write" : "",
              "file-manager-access" : "",
              "file-manager-delete" : "",
              "file-manager-write" : "",
              "oauth" : "",
              "oauth-access" : ""
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "PROFESSIONAL",
    "sales" : "STARTER",
    "service" : "PROFESSIONAL",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}