{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Settings User Provisioning",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Roles"
  }, {
    "name" : "Seats"
  }, {
    "name" : "Teams"
  }, {
    "name" : "Users"
  } ],
  "paths" : {
    "/settings/users/2026-09-beta" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieves users",
        "description" : "Retrieve a paginated list of users in your HubSpot account. This endpoint allows you to specify the maximum number of results per page and to use a paging cursor for navigating through the list of users.",
        "operationId" : "get-/settings/users/2026-09-beta",
        "security" : [ {
          "oauth2" : [ "settings.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a user",
        "description" : "Create a new user in your HubSpot account using the specified details. This endpoint requires a JSON request body with user information such as email, first name, last name, role, and seats. A welcome email can be optionally sent to the new user. ",
        "operationId" : "post-/settings/users/2026-09-beta",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "settings.users.write" ]
        } ]
      }
    },
    "/settings/users/2026-09-beta/roles" : {
      "get" : {
        "tags" : [ "Roles" ],
        "summary" : "Retrieves the roles on an account",
        "description" : "Retrieve a list of user roles available in your HubSpot account. This endpoint provides information about the different permission sets that can be assigned to users, which is useful for managing user access and permissions within the account.",
        "operationId" : "get-/settings/users/2026-09-beta/roles",
        "security" : [ {
          "oauth2" : [ "settings.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        } ]
      }
    },
    "/settings/users/2026-09-beta/seats" : {
      "get" : {
        "tags" : [ "Seats" ],
        "summary" : "Retrieves the seats on this account",
        "description" : "Retrieve the list of seats available in the account. This endpoint provides details about each seat, including its name, description, and the number of remaining seats. It is useful for managing and reviewing seat allocations within your organization.",
        "operationId" : "get-/settings/users/2026-09-beta/seats",
        "security" : [ {
          "oauth2" : [ "settings.billing.write" ]
        } ]
      }
    },
    "/settings/users/2026-09-beta/teams" : {
      "get" : {
        "tags" : [ "Teams" ],
        "summary" : "See details about this account's teams",
        "description" : "View teams for this account",
        "operationId" : "get-/settings/users/2026-09-beta/teams",
        "security" : [ {
          "oauth2" : [ "settings.users.teams.read" ]
        } ]
      }
    },
    "/settings/users/2026-09-beta/{userId}" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Retrieves a user",
        "description" : "Retrieves a user identified by `userId`. `userId` refers to the user's ID by default, or optionally email as specified by the `IdProperty` query param.",
        "operationId" : "get-/settings/users/2026-09-beta/{userId}",
        "security" : [ {
          "oauth2" : [ "settings.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Users" ],
        "summary" : "Modifies a user",
        "description" : "Modifies a user identified by `userId`. `userId` refers to the user's ID by default, or optionally email as specified by the `IdProperty` query param.",
        "operationId" : "put-/settings/users/2026-09-beta/{userId}",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "settings.users.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Users" ],
        "summary" : "Removes a user",
        "description" : "Removes a user identified by `userId`. `userId` refers to the user's ID by default, or optionally email as specified by the `IdProperty` query param.",
        "operationId" : "delete-/settings/users/2026-09-beta/{userId}",
        "security" : [ {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "settings.users.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.users.write" : "",
              "settings.billing.write" : "",
              "settings.users.read" : "",
              "settings.users.teams.read" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}