{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Marketing Lead Scoring",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  } ],
  "paths" : {
    "/marketing/lead-scoring/2026-09-beta/score-values/object-history" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve detailed history of score property updates",
        "description" : "Retrieve the history of score values, as well as the changes that caused them, for a specific object type and object ID. This endpoint is useful for tracking changes in score values over time for a particular object, along with details about the activity that caused the score update. The results can be paginated using the limit and after parameters.",
        "operationId" : "get-/marketing/lead-scoring/2026-09-beta/score-values/object-history",
        "security" : [ {
          "oauth2" : [ "oauth" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List scores",
        "description" : "Retrieve a list of lead scoring configurations in your HubSpot account. This endpoint allows you to view the current scoring setups, which can be useful for managing and analyzing lead scoring strategies.",
        "operationId" : "get-/marketing/lead-scoring/2026-09-beta/scores",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-view" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create Score",
        "description" : "Create a new lead scoring configuration in your HubSpot account. This endpoint allows you to define scoring criteria and configurations for evaluating leads. It requires a JSON request body with the necessary configuration details.",
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve score",
        "description" : "Retrieve the configuration details of a specific lead scoring model in your HubSpot account using the score's unique identifier. This endpoint is useful for accessing the setup and parameters of a lead scoring model, allowing you to understand how scores are calculated for leads.",
        "operationId" : "get-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-view" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete",
        "description" : "Delete a specific lead scoring configuration in your HubSpot account using its unique identifier. This operation is useful for removing outdated or unnecessary scoring configurations.",
        "operationId" : "delete-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/clone" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Clone score",
        "description" : "Clone an existing lead scoring configuration in your HubSpot account. This endpoint allows you to duplicate a score configuration identified by the scoreId, which can then be modified independently of the original. This is useful for testing variations of scoring models or creating similar scoring configurations without starting from scratch.",
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/clone",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/deactivate" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Deactivate score",
        "description" : "Deactivate a specific lead scoring configuration in your HubSpot account. This operation is useful when you want to temporarily or permanently disable a scoring configuration identified by its scoreId. Once deactivated, the scoring configuration will not be used for evaluating leads until it is reactivated.",
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/deactivate",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft" : {
      "get" : {
        "tags" : [ "Advanced" ],
        "summary" : "Retrieve draft",
        "description" : "Retrieve the draft configuration of a specific lead score in your HubSpot account. This endpoint allows you to access the draft version of a lead score configuration identified by its scoreId, which can be useful for reviewing or editing before publishing.",
        "operationId" : "get-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-view" ]
        } ]
      },
      "put" : {
        "tags" : [ "Advanced" ],
        "summary" : "Update draft score",
        "description" : "Update the draft configuration of a specific lead score identified by scoreId. This endpoint allows you to modify the draft version of a lead scoring configuration, which can be useful for testing or adjusting scoring criteria before publishing.",
        "operationId" : "put-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft/publish" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Publish Draft Score",
        "description" : "Publish a draft lead scoring configuration for a specific score identified by scoreId. This action finalizes the draft and makes it the active scoring configuration. ",
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft/publish",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft/reset" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Reset Draft",
        "description" : "Reset the draft configuration for a specific lead scoring model identified by the scoreId. This operation clears any unsaved changes made to the draft, reverting it to its last published state. Use this endpoint when you need to discard draft changes and start over with the existing published configuration.",
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft/reset",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "mh-lead-scoring-edit" : "",
              "mh-lead-scoring-view" : "",
              "oauth" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}