{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Marketing Lead Scoring",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  } ],
  "paths" : {
    "/marketing/lead-scoring/2026-09-beta/score-values/object-history" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve history",
        "description" : "Retrieve the history of score values for a specific object type and ID in the lead scoring system. This endpoint is useful for tracking changes in score values over time and understanding how different factors have influenced the scores. The results can be filtered and paginated using the provided query parameters.",
        "operationId" : "get-/marketing/lead-scoring/2026-09-beta/score-values/object-history",
        "security" : [ {
          "oauth2" : [ "oauth" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List scores",
        "description" : "Retrieve a list of lead scores from the HubSpot account. This endpoint allows you to view scores for various leads, which can be useful for analyzing lead quality and prioritizing follow-up actions. The results can be paginated using the provided query parameters.",
        "operationId" : "get-/marketing/lead-scoring/2026-09-beta/scores",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-view" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create Score",
        "description" : "Create a new lead scoring configuration in your HubSpot account. This endpoint allows you to define scoring criteria for leads, which can help in prioritizing and managing leads effectively. The request body must include the necessary configuration details for the scoring setup.",
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve score",
        "description" : "Retrieve the configuration details of a specific lead scoring model in your HubSpot account using its unique score ID. This endpoint is useful for accessing the setup and parameters of a particular scoring model to understand how leads are being evaluated.",
        "operationId" : "get-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-view" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete",
        "description" : "Delete a specific lead scoring configuration in your HubSpot account using its unique identifier. This operation is useful for removing outdated or unnecessary scoring configurations to maintain a clean and efficient scoring system.",
        "operationId" : "delete-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/clone" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Clone score",
        "description" : "Clone an existing lead scoring configuration in your HubSpot account. This operation allows you to duplicate a score configuration identified by the scoreId path parameter, which can then be modified or used as a template for new scoring rules.",
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/clone",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/deactivate" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Deactivate score",
        "description" : "Deactivate a specific lead scoring configuration in your HubSpot account. This endpoint is useful when you want to temporarily disable a scoring configuration without deleting it. The operation returns the updated score configuration.",
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/deactivate",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft" : {
      "get" : {
        "tags" : [ "Advanced" ],
        "summary" : "Retrieve draft",
        "description" : "Retrieve the draft configuration of a specific lead scoring model using its score ID. This endpoint is useful for accessing the draft version of a score configuration before it is published or finalized.",
        "operationId" : "get-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-view" ]
        } ]
      },
      "put" : {
        "tags" : [ "Advanced" ],
        "summary" : "Update draft",
        "description" : "Update the draft configuration of a lead scoring model identified by the scoreId. This operation allows you to modify the draft settings of an existing lead scoring model, which can be useful for testing or adjusting scoring criteria before publishing.",
        "operationId" : "put-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft/publish" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Publish draft score",
        "description" : "Publish a draft version of a lead scoring configuration identified by the scoreId. This action makes the draft configuration active. Optionally, you can choose to backfill the score data.",
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft/publish",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft/reset" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Reset Draft",
        "description" : "Reset the draft configuration of a lead scoring model identified by the scoreId. This operation is useful for reverting any changes made to the draft configuration, effectively restoring it to its initial state. This endpoint does not return any content upon successful execution.",
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft/reset",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "mh-lead-scoring-edit" : "",
              "mh-lead-scoring-view" : "",
              "oauth" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}