{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Marketing Lead Scoring",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  } ],
  "paths" : {
    "/marketing/lead-scoring/2026-09-beta/score-values/object-history" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/marketing/lead-scoring/2026-09-beta/score-values/object-history",
        "security" : [ {
          "oauth2" : [ "oauth" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/marketing/lead-scoring/2026-09-beta/scores",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-view" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-view" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/clone" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/clone",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/deactivate" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/deactivate",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft" : {
      "get" : {
        "tags" : [ "Advanced" ],
        "operationId" : "get-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-view" ]
        } ]
      },
      "put" : {
        "tags" : [ "Advanced" ],
        "operationId" : "put-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft/publish" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft/publish",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    },
    "/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft/reset" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "operationId" : "post-/marketing/lead-scoring/2026-09-beta/scores/{scoreId}/draft/reset",
        "security" : [ {
          "oauth2" : [ "mh-lead-scoring-edit" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "mh-lead-scoring-edit" : "",
              "mh-lead-scoring-view" : "",
              "oauth" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}