{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CMS Media Bridge",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v1",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "Media Bridge Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/cms/media-bridge"
    } ]
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  } ],
  "paths" : {
    "/media-bridge/v1/events/attention-span" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create an attention span event",
        "description" : "Create an event containing the viewers attention span details for the media.",
        "operationId" : "post-/media-bridge/v1/events/attention-span",
        "security" : [ {
          "oauth2" : [ "media_bridge.write" ]
        } ]
      }
    },
    "/media-bridge/v1/events/media-played" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create a played event",
        "description" : "Create an event for when a user begins playing a piece of media.",
        "operationId" : "post-/media-bridge/v1/events/media-played",
        "security" : [ {
          "oauth2" : [ "media_bridge.write" ]
        } ]
      }
    },
    "/media-bridge/v1/events/media-played-percent" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create a quartile event",
        "description" : "Create an event representing a user reaching quarterly milestones in a piece of media they're viewing.",
        "operationId" : "post-/media-bridge/v1/events/media-played-percent",
        "security" : [ {
          "oauth2" : [ "media_bridge.write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/properties/{objectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get the properties for an object type.",
        "description" : "Get the existing properties defined for a media object type.",
        "operationId" : "get-/media-bridge/v1/{appId}/properties/{objectType}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a new property",
        "description" : "Create a new property for the specified media type",
        "operationId" : "post-/media-bridge/v1/{appId}/properties/{objectType}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/properties/{objectType}/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Archive multiple properties",
        "description" : "Archive a batch of existing properties for the specified types.",
        "operationId" : "post-/media-bridge/v1/{appId}/properties/{objectType}/batch/archive",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/properties/{objectType}/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create multiple properties",
        "description" : "Create a batch of properties of the specified object type.",
        "operationId" : "post-/media-bridge/v1/{appId}/properties/{objectType}/batch/create",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/properties/{objectType}/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Get the details for multiple properties",
        "description" : "Get the details for a batch of properties for a specified object type.",
        "operationId" : "post-/media-bridge/v1/{appId}/properties/{objectType}/batch/read",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/properties/{objectType}/groups" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get property groups",
        "description" : "Get the property groups for a specified object type.",
        "operationId" : "get-/media-bridge/v1/{appId}/properties/{objectType}/groups",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a new property group",
        "description" : "Create a new property group for the specified object type.",
        "operationId" : "post-/media-bridge/v1/{appId}/properties/{objectType}/groups",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/properties/{objectType}/groups/{groupName}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get a specific property group",
        "description" : "Get the details of an existing property group by name.",
        "operationId" : "get-/media-bridge/v1/{appId}/properties/{objectType}/groups/{groupName}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete a property group",
        "description" : "Delete an existing property group by name",
        "operationId" : "delete-/media-bridge/v1/{appId}/properties/{objectType}/groups/{groupName}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update a property group",
        "description" : "Update an existing property group by name.",
        "operationId" : "patch-/media-bridge/v1/{appId}/properties/{objectType}/groups/{groupName}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/properties/{objectType}/{propertyName}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get the details for a property",
        "description" : "Get the details for an existing property by name.",
        "operationId" : "get-/media-bridge/v1/{appId}/properties/{objectType}/{propertyName}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete a property",
        "description" : "Delete an existing property for an object type.",
        "operationId" : "delete-/media-bridge/v1/{appId}/properties/{objectType}/{propertyName}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update a property",
        "description" : "Update an existing property for an object type.",
        "operationId" : "patch-/media-bridge/v1/{appId}/properties/{objectType}/{propertyName}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/schemas" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get all schemas ",
        "description" : "Get the schemas for all object types.",
        "operationId" : "get-/media-bridge/v1/{appId}/schemas",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/schemas/{objectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get the schema for an object type",
        "description" : "Get the schema for a specified object type.",
        "operationId" : "get-/media-bridge/v1/{appId}/schemas/{objectType}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update the schema for an object type",
        "description" : "Update the schema for an existing object type",
        "operationId" : "patch-/media-bridge/v1/{appId}/schemas/{objectType}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/schemas/{objectType}/associations" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create association definition",
        "description" : "Create a new association definition for the specified object type.",
        "operationId" : "post-/media-bridge/v1/{appId}/schemas/{objectType}/associations",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/schemas/{objectType}/associations/{associationId}" : {
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete an association definition",
        "description" : "Delete an existing association definition for an object type.",
        "operationId" : "delete-/media-bridge/v1/{appId}/schemas/{objectType}/associations/{associationId}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/settings" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update the media bridge app name",
        "description" : "Update the name that your app will display when a user is selecting media bridge items.",
        "operationId" : "put-/media-bridge/v1/{appId}/settings",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/settings/event-visibility" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "View event visibility settings",
        "description" : "Get the visibility settings for media bridge events for your apps.",
        "operationId" : "get-/media-bridge/v1/{appId}/settings/event-visibility",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Create or update event visibility settings",
        "description" : "Set the visibility settings for media bridge events created by your app.",
        "operationId" : "patch-/media-bridge/v1/{appId}/settings/event-visibility",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/settings/object-definitions" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create a new object type",
        "description" : "Create a new media object type",
        "operationId" : "post-/media-bridge/v1/{appId}/settings/object-definitions",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/settings/object-definitions/{mediaType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get object types for a supported media",
        "description" : "Get the existing objects types that belong to the specified media type.",
        "operationId" : "get-/media-bridge/v1/{appId}/settings/object-definitions/{mediaType}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/settings/oembed-domains" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get oEmbed domains",
        "description" : "Get the details for existing oEmbed domains for your app",
        "operationId" : "get-/media-bridge/v1/{appId}/settings/oembed-domains",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Set up a new oEmbed domain",
        "description" : "Set up a new oEmbed domain for your media bridge app.",
        "operationId" : "post-/media-bridge/v1/{appId}/settings/oembed-domains",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete an oEmbed domain",
        "description" : "Delete an existing oEmbed domain.",
        "operationId" : "delete-/media-bridge/v1/{appId}/settings/oembed-domains",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/settings/oembed-domains/{oEmbedDomainId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get an oEmbed domain",
        "description" : "Get the details for an existing oEmbed domain.",
        "operationId" : "get-/media-bridge/v1/{appId}/settings/oembed-domains/{oEmbedDomainId}",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update an oEmbed domain",
        "description" : "Update an existing oEmbed domain.",
        "operationId" : "patch-/media-bridge/v1/{appId}/settings/oembed-domains/{oEmbedDomainId}",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/settings/register" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Register the media bridge app name",
        "description" : "Register the name that your app will display when a user is selecting media bridge items.",
        "operationId" : "post-/media-bridge/v1/{appId}/settings/register",
        "deprecated" : true,
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/media-bridge/v1/{appId}/settings/video-association-definition" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "operationId" : "post-/media-bridge/v1/{appId}/settings/video-association-definition_/media-bridge/v1/{appId}/settings/video-association-definition",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "developers-read" : "",
              "developers-write" : "",
              "media_bridge.write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}