{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Automation Actions V4",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v4",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "PROFESSIONAL",
      "sales" : "PROFESSIONAL",
      "service" : "PROFESSIONAL",
      "cms" : "PROFESSIONAL",
      "commerce" : "PROFESSIONAL",
      "crmHub" : "PROFESSIONAL",
      "dataHub" : "PROFESSIONAL"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "Custom Workflow Actions Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/automation/custom-workflow-actions"
    } ]
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Callbacks"
  }, {
    "name" : "Definitions"
  }, {
    "name" : "Functions"
  }, {
    "name" : "Revisions"
  } ],
  "paths" : {
    "/automation/v4/actions/callbacks/complete" : {
      "post" : {
        "tags" : [ "Callbacks" ],
        "summary" : "Complete a batch of callbacks",
        "description" : "Complete a batch of blocked action executions.",
        "operationId" : "post-/automation/v4/actions/callbacks/complete_completeBatch",
        "security" : [ {
          "oauth2" : [ "workflows-access" ]
        } ]
      }
    },
    "/automation/v4/actions/callbacks/{callbackId}/complete" : {
      "post" : {
        "tags" : [ "Callbacks" ],
        "summary" : "Completes a callback",
        "description" : "Complete a specific blocked action execution by ID.",
        "operationId" : "post-/automation/v4/actions/callbacks/{callbackId}/complete_complete",
        "security" : [ {
          "oauth2" : [ "workflows-access" ]
        } ]
      }
    },
    "/automation/v4/actions/{appId}" : {
      "get" : {
        "tags" : [ "Definitions" ],
        "summary" : "Retrieve custom action definitions",
        "description" : "Retrieve custom workflow action definitions by app ID.",
        "operationId" : "get-/automation/v4/actions/{appId}_getPage",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Definitions" ],
        "summary" : "Create a new custom action definition",
        "description" : "Create a new custom workflow action.",
        "operationId" : "post-/automation/v4/actions/{appId}_create",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/automation/v4/actions/{appId}/{definitionId}" : {
      "get" : {
        "tags" : [ "Definitions" ],
        "summary" : "Retrieve a custom action definition",
        "description" : "Retrieve a custom workflow action definition by ID.",
        "operationId" : "get-/automation/v4/actions/{appId}/{definitionId}_getById",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Definitions" ],
        "summary" : "Delete an action definition",
        "description" : "Delete an action definition by ID.",
        "operationId" : "delete-/automation/v4/actions/{appId}/{definitionId}_archive",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Definitions" ],
        "summary" : "Update an existing action definition",
        "description" : "Update an existing action definition by ID.",
        "operationId" : "patch-/automation/v4/actions/{appId}/{definitionId}_update",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/automation/v4/actions/{appId}/{definitionId}/functions" : {
      "get" : {
        "tags" : [ "Functions" ],
        "summary" : "Retrieve functions for a given definition",
        "description" : "Retrieve all functions included in a definition.",
        "operationId" : "get-/automation/v4/actions/{appId}/{definitionId}/functions_getPage",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      }
    },
    "/automation/v4/actions/{appId}/{definitionId}/functions/{functionType}" : {
      "get" : {
        "tags" : [ "Functions" ],
        "summary" : "Retrieve functions by a type for a given definition",
        "description" : "Retrieve functions of a specific type for a given definition.",
        "operationId" : "get-/automation/v4/actions/{appId}/{definitionId}/functions/{functionType}_getByFunctionType",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Functions" ],
        "summary" : "Insert a function for a definition",
        "description" : "Add a function for a given definition.",
        "operationId" : "put-/automation/v4/actions/{appId}/{definitionId}/functions/{functionType}_createOrReplaceByFunctionType",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Functions" ],
        "summary" : "Delete a function for a definition",
        "description" : "Delete a function within a given definition.",
        "operationId" : "delete-/automation/v4/actions/{appId}/{definitionId}/functions/{functionType}_archiveByFunctionType",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/automation/v4/actions/{appId}/{definitionId}/functions/{functionType}/{functionId}" : {
      "get" : {
        "tags" : [ "Functions" ],
        "summary" : "Retrieve a function from a given definition",
        "description" : "Retrieve a specific function from a given definition.",
        "operationId" : "get-/automation/v4/actions/{appId}/{definitionId}/functions/{functionType}/{functionId}_getById",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Functions" ],
        "summary" : "Update a function for a definition",
        "description" : "Update a function for a given definition by ID.",
        "operationId" : "put-/automation/v4/actions/{appId}/{definitionId}/functions/{functionType}/{functionId}_createOrReplace",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Functions" ],
        "summary" : "Archive a function for a definition",
        "description" : "Archive a function for a specific definition.",
        "operationId" : "delete-/automation/v4/actions/{appId}/{definitionId}/functions/{functionType}/{functionId}_archive",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/automation/v4/actions/{appId}/{definitionId}/requires-object" : {
      "get" : {
        "tags" : [ "Definitions" ],
        "summary" : "Retrieve the object requirement status for a custom action definition.",
        "description" : "Retrieve whether a custom action definition requires an object.",
        "operationId" : "get-/automation/v4/actions/{appId}/{definitionId}/requires-object_/automation/v4/actions/{appId}/{definitionId}/requires-object",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Definitions" ],
        "summary" : "Set the object requirement for a custom action definition.",
        "description" : "Set whether a custom action definition requires an object.",
        "operationId" : "post-/automation/v4/actions/{appId}/{definitionId}/requires-object_/automation/v4/actions/{appId}/{definitionId}/requires-object",
        "security" : [ {
          "oauth2" : [ "developers-write" ]
        } ]
      }
    },
    "/automation/v4/actions/{appId}/{definitionId}/revisions" : {
      "get" : {
        "tags" : [ "Revisions" ],
        "summary" : "Retrieve revisions for a given definition",
        "description" : "Retrieve the versions of a definition by ID.",
        "operationId" : "get-/automation/v4/actions/{appId}/{definitionId}/revisions_getPage",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      }
    },
    "/automation/v4/actions/{appId}/{definitionId}/revisions/{revisionId}" : {
      "get" : {
        "tags" : [ "Revisions" ],
        "summary" : "Retrieve a specific revision of a definition",
        "description" : "Retrieve a specific revision of a definition by revision ID.",
        "operationId" : "get-/automation/v4/actions/{appId}/{definitionId}/revisions/{revisionId}_getById",
        "security" : [ {
          "oauth2" : [ "developers-read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "developers-read" : "",
              "developers-write" : "",
              "workflows-access" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "PROFESSIONAL",
    "sales" : "PROFESSIONAL",
    "service" : "PROFESSIONAL",
    "cms" : "PROFESSIONAL",
    "commerce" : "PROFESSIONAL",
    "crmHub" : "PROFESSIONAL",
    "dataHub" : "PROFESSIONAL"
  }
}