{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Properties",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "Create a set of custom multi-select properties for storing contract data on company records.",
    "x-hubspot-introduction" : "Use the properties API to store information in fields on individual contact records. You can use this API to manage existing default and custom properties, create new custom properties, and more."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Groups__MA_RC_H_2026"
  }, {
    "name" : "Properties__MA_RC_H_2026"
  } ],
  "paths" : {
    "/crm/properties/2026-03/{objectType}" : {
      "get" : {
        "tags" : [ "Properties__MA_RC_H_2026" ],
        "summary" : "Read all properties",
        "description" : "Read all existing properties for the specified object type and HubSpot account.",
        "operationId" : "get-/crm/properties/2026-03/{objectType}_/crm/properties/2026-03/{objectType}",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.read" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "oauth2" : [ "automation" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.schemas.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "automation" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.read" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      },
      "post" : {
        "tags" : [ "Properties__MA_RC_H_2026" ],
        "summary" : "Create a property",
        "description" : "Create and return a copy of a new property for the specified object type.",
        "operationId" : "post-/crm/properties/2026-03/{objectType}_/crm/properties/2026-03/{objectType}",
        "security" : [ {
          "oauth2" : [ "crm.schemas.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.write" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.write" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.write" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.write" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.services.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.write" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/properties/2026-03/{objectType}/batch/archive" : {
      "post" : {
        "tags" : [ "Properties__MA_RC_H_2026" ],
        "summary" : "Archive a batch of properties",
        "description" : "Archive a provided list of properties. This method will return a 204 No Content response on success regardless of the initial state of the property (e.g. active, already archived, non-existent).",
        "operationId" : "post-/crm/properties/2026-03/{objectType}/batch/archive_/crm/properties/2026-03/{objectType}/batch/archive",
        "security" : [ {
          "oauth2" : [ "crm.schemas.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.write" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.write" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.write" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.write" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.services.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.write" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/properties/2026-03/{objectType}/batch/create" : {
      "post" : {
        "tags" : [ "Properties__MA_RC_H_2026" ],
        "summary" : "Create a batch of properties",
        "description" : "Create a batch of properties using the same rules as when creating an individual property.",
        "operationId" : "post-/crm/properties/2026-03/{objectType}/batch/create_/crm/properties/2026-03/{objectType}/batch/create",
        "security" : [ {
          "oauth2" : [ "crm.schemas.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.write" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.write" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.write" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.write" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.services.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.write" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/properties/2026-03/{objectType}/batch/read" : {
      "post" : {
        "tags" : [ "Properties__MA_RC_H_2026" ],
        "summary" : "Read a batch of properties",
        "description" : "Read a provided list of properties.",
        "operationId" : "post-/crm/properties/2026-03/{objectType}/batch/read_/crm/properties/2026-03/{objectType}/batch/read",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.read" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "oauth2" : [ "automation" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.schemas.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "automation" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.read" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/properties/2026-03/{objectType}/groups" : {
      "get" : {
        "tags" : [ "Groups__MA_RC_H_2026" ],
        "summary" : "Read all property groups",
        "description" : "Read all existing property groups for the specified object type and HubSpot account.",
        "operationId" : "get-/crm/properties/2026-03/{objectType}/groups_/crm/properties/2026-03/{objectType}/groups",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.read" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "oauth2" : [ "automation" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.schemas.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "automation" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.read" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      },
      "post" : {
        "tags" : [ "Groups__MA_RC_H_2026" ],
        "summary" : "Create a property group",
        "description" : "Create and return a copy of a new property group.",
        "operationId" : "post-/crm/properties/2026-03/{objectType}/groups_/crm/properties/2026-03/{objectType}/groups",
        "security" : [ {
          "oauth2" : [ "crm.schemas.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.write" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.write" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.write" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.write" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.services.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.write" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/properties/2026-03/{objectType}/groups/{groupName}" : {
      "get" : {
        "tags" : [ "Groups__MA_RC_H_2026" ],
        "summary" : "Read a property group",
        "description" : "Read a property group identified by {groupName}.",
        "operationId" : "get-/crm/properties/2026-03/{objectType}/groups/{groupName}_/crm/properties/2026-03/{objectType}/groups/{groupName}",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.read" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "oauth2" : [ "automation" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.schemas.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "automation" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.read" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Groups__MA_RC_H_2026" ],
        "summary" : "Archive a property group",
        "description" : "Move a property group identified by {groupName} to the recycling bin.",
        "operationId" : "delete-/crm/properties/2026-03/{objectType}/groups/{groupName}_/crm/properties/2026-03/{objectType}/groups/{groupName}",
        "security" : [ {
          "oauth2" : [ "crm.schemas.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.write" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.write" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.write" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.write" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.services.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.write" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Groups__MA_RC_H_2026" ],
        "summary" : "Update a property group",
        "description" : "Perform a partial update of a property group identified by {groupName}. Provided fields will be overwritten.",
        "operationId" : "patch-/crm/properties/2026-03/{objectType}/groups/{groupName}_/crm/properties/2026-03/{objectType}/groups/{groupName}",
        "security" : [ {
          "oauth2" : [ "crm.schemas.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.write" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.write" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.write" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.write" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.services.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.write" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/properties/2026-03/{objectType}/{propertyName}" : {
      "get" : {
        "tags" : [ "Properties__MA_RC_H_2026" ],
        "summary" : "Read a property",
        "description" : "Read a property identified by {propertyName}.",
        "operationId" : "get-/crm/properties/2026-03/{objectType}/{propertyName}_/crm/properties/2026-03/{objectType}/{propertyName}",
        "security" : [ {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.read" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "oauth2" : [ "automation" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps" : [ "crm.schemas.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.read" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "automation" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.read" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.projects.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Properties__MA_RC_H_2026" ],
        "summary" : "Archive a property",
        "description" : "Move a property identified by {propertyName} to the recycling bin.",
        "operationId" : "delete-/crm/properties/2026-03/{objectType}/{propertyName}_/crm/properties/2026-03/{objectType}/{propertyName}",
        "security" : [ {
          "oauth2" : [ "crm.schemas.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.write" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.write" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.write" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.write" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.services.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.write" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Properties__MA_RC_H_2026" ],
        "summary" : "Update a property",
        "description" : "Perform a partial update of a property identified by { propertyName }. Provided fields will be overwritten.",
        "operationId" : "patch-/crm/properties/2026-03/{objectType}/{propertyName}_/crm/properties/2026-03/{objectType}/{propertyName}",
        "security" : [ {
          "oauth2" : [ "crm.schemas.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.write" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.services.write" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.write" ]
        }, {
          "oauth2" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.write" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.services.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.write" ]
        }, {
          "private_apps" : [ "crm.schemas.projects.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "automation" : "Read from and write to my Workflows",
              "crm.objects.appointments.read" : "Read appointments",
              "crm.objects.appointments.sensitive.read.v2" : "Read appointments (sensitive)",
              "crm.objects.appointments.sensitive.write.v2" : "Write appointments (sensitive)",
              "crm.objects.appointments.write" : "Write appointments",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.carts.write" : "Write cart",
              "crm.objects.commercepayments.write" : "Write commerce payments",
              "crm.objects.companies.highly_sensitive.read.v2" : "View company records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.write.v2" : "Change company records (highly-sensitive)",
              "crm.objects.companies.read" : "Create or update company records",
              "crm.objects.companies.sensitive.read.v2" : "View sensitive properties on company records",
              "crm.objects.companies.sensitive.write.v2" : "Create or update sensitive properties on company records",
              "crm.objects.companies.write" : "View company records",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.contacts.read" : "View contact records",
              "crm.objects.contacts.sensitive.read.v2" : "View sensitive properties on contact records",
              "crm.objects.contacts.sensitive.write.v2" : "Create or update sensitive properties on contact records",
              "crm.objects.contacts.write" : "Create or update contact records",
              "crm.objects.courses.read" : "Read courses",
              "crm.objects.courses.write" : "Write courses",
              "crm.objects.custom.highly_sensitive.read.v2" : "View custom object records (highly-sensitive)",
              "crm.objects.custom.highly_sensitive.write.v2" : "Change custom object records (highly-sensitive)",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.custom.sensitive.read.v2" : "View custom object records (sensitive)",
              "crm.objects.custom.sensitive.write.v2" : "Change custom object records (sensitive)",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.deals.highly_sensitive.read.v2" : "View deal records (highly-sensitive)",
              "crm.objects.deals.highly_sensitive.write.v2" : "Change deal records (highly-sensitive)",
              "crm.objects.deals.read" : "View deal records",
              "crm.objects.deals.sensitive.read.v2" : "View sensitive properties on deal records",
              "crm.objects.deals.sensitive.write.v2" : "Create or update sensitive properties on deal records",
              "crm.objects.deals.write" : "Create or update deal records",
              "crm.objects.feedback_submissions.read" : "View feedback survey submissions",
              "crm.objects.goals.read" : "Read access to goals",
              "crm.objects.goals.write" : "Create and update goals",
              "crm.objects.invoices.read" : "Read invoices",
              "crm.objects.invoices.write" : "Write invoices",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.listings.read" : "Read listings",
              "crm.objects.listings.write" : "Write listings",
              "crm.objects.marketing_events.read" : "Read marketing events",
              "crm.objects.marketing_events.write" : "Write marketing events",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.owners.read" : "View owner records",
              "crm.objects.products.write" : "Write products in Products Library",
              "crm.objects.projects.highly_sensitive.read" : "Read projects (highly-sensitive)",
              "crm.objects.projects.highly_sensitive.write" : "Write projects (highly-sensitive)",
              "crm.objects.projects.read" : "Read projects",
              "crm.objects.projects.sensitive.read" : "Read projects (sensitive)",
              "crm.objects.projects.sensitive.write" : "Write projects (sensitive)",
              "crm.objects.projects.write" : "Write projects",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.services.read" : "Read services",
              "crm.objects.services.write" : "Write services",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.subscriptions.write" : "Write subscriptions",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.users.write" : "Write User CRM objects",
              "crm.pipelines.orders.read" : "View details about your cart pipelines including pipeline stage information",
              "crm.pipelines.orders.write" : "Create, delete, or make to your order pipelines or their respective stages",
              "crm.schemas.appointments.read" : "Read appointments property settings",
              "crm.schemas.appointments.write" : "Write appointments property settings",
              "crm.schemas.carts.read" : "Read cart property settings",
              "crm.schemas.carts.write" : "Write cart property settings",
              "crm.schemas.commercepayments.read" : "Commerce payment definitions",
              "crm.schemas.commercepayments.write" : "Write commerce payments property settings",
              "crm.schemas.companies.read" : "View company property settings",
              "crm.schemas.companies.write" : "Create new company properties or change company property settings",
              "crm.schemas.contacts.read" : "View contacts property settings",
              "crm.schemas.contacts.write" : "Create new contact properties or change contact property settings",
              "crm.schemas.courses.read" : "Read courses property settings",
              "crm.schemas.courses.write" : "Write courses property settings",
              "crm.schemas.custom.read" : "View custom object definitions",
              "crm.schemas.custom.write" : "Change custom object definitions",
              "crm.schemas.deals.read" : "View deals property settings",
              "crm.schemas.deals.write" : "Create new deal properties or change deal property settings",
              "crm.schemas.invoices.read" : "Invoices Definitions",
              "crm.schemas.invoices.write" : "Invoices Definitions",
              "crm.schemas.line_items.read" : "Line Items schemas",
              "crm.schemas.listings.read" : "Read listings property settings",
              "crm.schemas.listings.write" : "Write listings property settings",
              "crm.schemas.orders.read" : "Read order property settings",
              "crm.schemas.orders.write" : "Write order property settings",
              "crm.schemas.projects.read" : "Read projects property settings",
              "crm.schemas.projects.write" : "Write projects property settings",
              "crm.schemas.quotes.read" : "Quotes schemas",
              "crm.schemas.quotes.write" : "Modify quote property settings",
              "crm.schemas.services.read" : "Read services property settings",
              "crm.schemas.services.write" : "Write services property settings",
              "crm.schemas.subscriptions.read" : "Read subscriptions schema",
              "crm.schemas.subscriptions.write" : "Write to Subscription properties",
              "e-commerce" : "Access to ecommerce",
              "media_bridge.read" : "Read media and media events",
              "tickets" : "Tickets",
              "tickets.highly_sensitive.v2" : "Tickets (highly-sensitive)",
              "tickets.sensitive.v2" : "Tickets (sensitive)",
              "timeline" : "Create timeline events"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}