{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Lists",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/lists/2026-03" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/crm/lists/2026-03_/crm/lists/v3",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "operationId" : "post-/crm/lists/2026-03_/crm/lists/v3",
        "security" : [ {
          "app_cookie" : [ "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/folders" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/crm/lists/2026-03/folders_/crm/lists/v3/folders",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "operationId" : "post-/crm/lists/2026-03/folders_/crm/lists/v3/folders",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/folders/move-list" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/lists/2026-03/folders/move-list_/crm/lists/v3/folders/move-list",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/folders/{folderId}" : {
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/crm/lists/2026-03/folders/{folderId}_/crm/lists/v3/folders/{folderId}",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/folders/{folderId}/move/{newParentFolderId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/lists/2026-03/folders/{folderId}/move/{newParentFolderId}_/crm/lists/v3/folders/{folderId}/move/{newParentFolderId}",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/folders/{folderId}/rename" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/lists/2026-03/folders/{folderId}/rename_/crm/lists/v3/folders/{folderId}/rename",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/idmapping" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/crm/lists/2026-03/idmapping_/crm/lists/v3/idmapping",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "operationId" : "post-/crm/lists/2026-03/idmapping_/crm/lists/v3/idmapping",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/object-type-id/{objectTypeId}/name/{listName}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/crm/lists/2026-03/object-type-id/{objectTypeId}/name/{listName}_/crm/lists/v3/object-type-id/{objectTypeId}/name/{listName}",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/records/memberships/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "operationId" : "post-/crm/lists/2026-03/records/memberships/batch/read_/crm/lists/v3/records/memberships/batch/read",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/records/{objectTypeId}/{recordId}/memberships" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/crm/lists/2026-03/records/{objectTypeId}/{recordId}/memberships_/crm/lists/v3/records/{objectTypeId}/{recordId}/memberships",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "operationId" : "post-/crm/lists/2026-03/search_/crm/lists/v3/search",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/{listId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/crm/lists/2026-03/{listId}_/crm/lists/v3/{listId}",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/crm/lists/2026-03/{listId}_/crm/lists/v3/{listId}",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/{listId}/memberships" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/crm/lists/2026-03/{listId}/memberships_/crm/lists/v3/{listId}/memberships",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/crm/lists/2026-03/{listId}/memberships_/crm/lists/v3/{listId}/memberships",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/{listId}/memberships/add" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/lists/2026-03/{listId}/memberships/add_/crm/lists/v3/{listId}/memberships/add",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/{listId}/memberships/add-and-remove" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/lists/2026-03/{listId}/memberships/add-and-remove_/crm/lists/v3/{listId}/memberships/add-and-remove",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/{listId}/memberships/add-from/{sourceListId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/lists/2026-03/{listId}/memberships/add-from/{sourceListId}_/crm/lists/v3/{listId}/memberships/add-from/{sourceListId}",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/{listId}/memberships/join-order" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/crm/lists/2026-03/{listId}/memberships/join-order_/crm/lists/v3/{listId}/memberships/join-order",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/{listId}/memberships/remove" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/lists/2026-03/{listId}/memberships/remove_/crm/lists/v3/{listId}/memberships/remove",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/{listId}/restore" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/lists/2026-03/{listId}/restore_/crm/lists/v3/{listId}/restore",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/{listId}/schedule-conversion" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/crm/lists/2026-03/{listId}/schedule-conversion_/crm/lists/v3/{listId}/schedule-conversion",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/lists/2026-03/{listId}/schedule-conversion_/crm/lists/v3/{listId}/schedule-conversion",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/crm/lists/2026-03/{listId}/schedule-conversion_/crm/lists/v3/{listId}/schedule-conversion",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/{listId}/size-and-edits-history/between" : {
      "get" : {
        "tags" : [ "Basic" ],
        "operationId" : "get-/crm/lists/2026-03/{listId}/size-and-edits-history/between_/crm/lists/2026-03/{listId}/size-and-edits-history/between",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read" ]
        }, {
          "oauth2" : [ "ils-lists-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/{listId}/update-list-filters" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/lists/2026-03/{listId}/update-list-filters_/crm/lists/v3/{listId}/update-list-filters",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/lists/2026-03/{listId}/update-list-name" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/lists/2026-03/{listId}/update-list-name_/crm/lists/v3/{listId}/update-list-name",
        "security" : [ {
          "app_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "oauth2" : [ "ils-lists-read", "ils-lists-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "hubdb-data-append" : "",
              "hubdb-data-read" : "",
              "hubdb-data-write" : "",
              "hubdb-publish" : "",
              "hubdb-schemas-read" : "",
              "hubdb-schemas-write" : "",
              "hubdb-unpublish" : "",
              "ils-lists-read" : "",
              "ils-lists-write" : ""
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}