{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Subscription Lifecycle",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v1",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Subscriptions"
  } ],
  "paths" : {
    "/payments-subscriptions/v1/subscriptions/crm/{objectId}/cancel" : {
      "post" : {
        "tags" : [ "Subscriptions" ],
        "summary" : "Cancel a subscription",
        "description" : "Cancel an active commerce subscription using the subscription ID.",
        "operationId" : "post-/payments-subscriptions/v1/subscriptions/crm/{objectId}/cancel_/payments-subscriptions/v1/subscriptions/crm/{objectId}/cancel",
        "security" : [ {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.write" ]
        } ]
      }
    },
    "/payments-subscriptions/v1/subscriptions/crm/{objectId}/pause" : {
      "post" : {
        "tags" : [ "Subscriptions" ],
        "summary" : "Pause a subscription",
        "description" : "Pause an active subscription using the subscription ID.",
        "operationId" : "post-/payments-subscriptions/v1/subscriptions/crm/{objectId}/pause_/payments-subscriptions/v1/subscriptions/crm/{objectId}/pause",
        "security" : [ {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.write" ]
        } ]
      }
    },
    "/payments-subscriptions/v1/subscriptions/crm/{objectId}/unpause" : {
      "post" : {
        "tags" : [ "Subscriptions" ],
        "summary" : "Unpause a subscription.",
        "description" : "Resume a previously paused subscription using the subscription ID.",
        "operationId" : "post-/payments-subscriptions/v1/subscriptions/crm/{objectId}/unpause_/payments-subscriptions/v1/subscriptions/crm/{objectId}/unpause",
        "security" : [ {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.subscriptions.write" : "Write subscriptions",
              "crm.schemas.subscriptions.write" : "Write to Subscription properties"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}