{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Leads",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "PROFESSIONAL",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "When an existing contact shows an interest in purchasing a product or service, create a lead record to track the sales prospecting journey.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Leads Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/objects/leads"
    } ],
    "x-hubspot-introduction" : "In HubSpot, leads are contacts or companies that are potential customers who have shown interest in your products or services. Use the leads API to create and manage lead records in your HubSpot account, as well as sync lead data between HubSpot and other systems."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Search"
  }, {
    "name" : "GDPR"
  }, {
    "name" : "Public_Object__SE_PT_EM_BE_R_2025"
  }, {
    "name" : "Public_Object_Search_Post__SE_PT_EM_BE_R_2025"
  } ],
  "paths" : {
    "/crm/v3/objects/leads/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of leads by internal ID, or unique property values",
        "description" : "Retrieve records by record ID or include the `idProperty` parameter to retrieve records by a custom unique value property. ",
        "operationId" : "post-/crm/v3/objects/leads/batch/read_read",
        "security" : [ {
          "oauth2_legacy" : [ ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps_legacy" : [ ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        } ]
      }
    },
    "/crm/v3/objects/leads/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "operationId" : "post-/crm/v3/objects/leads/search_doSearch",
        "security" : [ {
          "oauth2_legacy" : [ ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps_legacy" : [ ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/v3/objects/leads" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List",
        "description" : "Read a page of leads. Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/v3/objects/leads_getPage",
        "security" : [ {
          "oauth2_legacy" : [ ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps_legacy" : [ ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create",
        "description" : "Create a lead with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard leads is provided.",
        "operationId" : "post-/crm/v3/objects/leads_create",
        "security" : [ {
          "oauth2_legacy" : [ ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps_legacy" : [ ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        } ]
      }
    },
    "/crm/v3/objects/leads/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of leads",
        "operationId" : "post-/crm/v3/objects/leads/batch/create_create",
        "security" : [ {
          "oauth2_legacy" : [ ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps_legacy" : [ ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        } ]
      }
    },
    "/crm/v3/objects/leads/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update a batch of leads by internal ID, or unique property values",
        "operationId" : "post-/crm/v3/objects/leads/batch/update_update",
        "security" : [ {
          "oauth2_legacy" : [ ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps_legacy" : [ ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        } ]
      }
    },
    "/crm/v3/objects/leads/{leadsId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read",
        "description" : "Read an Object identified by `{leadsId}`. `{leadsId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/v3/objects/leads/{leadsId}_getById",
        "security" : [ {
          "oauth2_legacy" : [ ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps_legacy" : [ ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archive",
        "description" : "Move an Object identified by `{leadsId}` to the recycling bin.",
        "operationId" : "delete-/crm/v3/objects/leads/{leadsId}_archive",
        "security" : [ {
          "oauth2_legacy" : [ ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps_legacy" : [ ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update",
        "description" : "Perform a partial update of an Object identified by `{leadsId}`or optionally a unique property value as specified by the `idProperty` query param. `{leadsId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
        "operationId" : "patch-/crm/v3/objects/leads/{leadsId}_update",
        "security" : [ {
          "oauth2_legacy" : [ ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps_legacy" : [ ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        } ]
      }
    },
    "/crm/v3/objects/leads/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Archive a batch of leads by ID",
        "operationId" : "post-/crm/v3/objects/leads/batch/archive_archive",
        "security" : [ {
          "oauth2_legacy" : [ ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps_legacy" : [ ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "oauth" : "User and Account Information",
              "crm.objects.deals.read" : "View deal records",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.services.read" : "Read services",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.listings.write" : "Write listings",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.companies.write" : "View company records",
              "crm.objects.custom.sensitive.write.v2" : "Change custom object records (sensitive)",
              "crm.objects.custom.highly_sensitive.write.v2" : "Change custom object records (highly-sensitive)",
              "crm.objects.companies.read" : "Create or update company records",
              "crm.objects.appointments.sensitive.read.v2" : "Read appointments (sensitive)",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.objects.companies.sensitive.read.v2" : "View sensitive properties on company records",
              "media_bridge.read" : "Read media and media events",
              "crm.objects.deals.highly_sensitive.read.v2" : "View deal records (highly-sensitive)",
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.read.v2" : "View company records (highly-sensitive)",
              "crm.objects.commercepayments.write" : "Write commerce payments",
              "crm.objects.invoices.write" : "Write invoices",
              "crm.objects.contacts.sensitive.write.v2" : "Create or update sensitive properties on contact records",
              "crm.objects.users.write" : "Write User CRM objects",
              "crm.objects.custom.sensitive.read.v2" : "View custom object records (sensitive)",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.partner-services.read" : "View Partner Service CRM objects",
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.partner-services.write" : "Modify Partner Service CRM objects",
              "crm.objects.appointments.write" : "Write appointments",
              "crm.objects.carts.write" : "Write cart",
              "tickets" : "Read and write tickets",
              "crm.objects.commercepayments.read" : "Read the COMMERCE_PAYMENT object.",
              "crm.objects.products.write" : "Write to my Product Library",
              "crm.objects.services.write" : "Write services",
              "crm.objects.subscriptions.write" : "Write to Commerce Subscriptions",
              "crm.objects.deals.sensitive.write.v2" : "Create or update sensitive properties on deal records",
              "crm.objects.contacts.read" : "View contact records",
              "crm.objects.appointments.sensitive.write.v2" : "Write appointments (sensitive)",
              "crm.objects.invoices.read" : "Read invoices objects",
              "tickets.sensitive.v2" : "Tickets (sensitive)",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.deals.write" : "Create or update deal records",
              "e-commerce" : "e-commerce",
              "crm.objects.appointments.read" : "Read appointments",
              "crm.objects.companies.sensitive.write.v2" : "Create or update sensitive properties on company records",
              "crm.objects.projects.read" : "Read projects",
              "crm.objects.deals.highly_sensitive.write.v2" : "Change deal records (highly-sensitive)",
              "crm.objects.custom.highly_sensitive.read.v2" : "View custom object records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.write.v2" : "Change company records (highly-sensitive)",
              "crm.objects.goals.write" : "Write goals",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.contacts.write" : "Create or update contact records",
              "crm.objects.goals.read" : "Read goals",
              "crm.objects.partner-clients.write" : "Modify Partner Client CRM objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.projects.write" : "Write projects",
              "crm.objects.deals.sensitive.read.v2" : "View sensitive properties on deal records",
              "tickets.highly_sensitive.v2" : "Tickets (highly-sensitive)",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.courses.write" : "Write courses",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.courses.read" : "Read courses",
              "crm.objects.listings.read" : "Read listings",
              "crm.objects.contacts.sensitive.read.v2" : "View sensitive properties on contact records",
              "crm.objects.products.read" : "Read from my Product Library"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "PROFESSIONAL",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}