{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Price Books Crm Reads Api",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/objects/2026-09-beta/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Create Association",
        "description" : "Create the default association type between two specified object types in HubSpot. This endpoint allows you to establish a generic association between two objects, identified by their types and IDs. It is useful for linking related records within the CRM system.",
        "operationId" : "put-/crm/objects/2026-09-beta/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}",
        "security" : [ {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        } ]
      }
    },
    "/crm/objects/2026-09-beta/{objectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List",
        "description" : "Retrieve a page of CRM objects of a specified type. You can control the data returned by specifying desired properties, associations, and whether to include archived objects. This endpoint is useful for fetching objects with specific properties and their historical values, as well as associated object IDs.",
        "operationId" : "get-/crm/objects/2026-09-beta/{objectType}",
        "security" : [ {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        } ]
      }
    },
    "/crm/objects/2026-09-beta/{objectType}/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read batch objects",
        "description" : "Retrieve a batch of CRM objects by their internal IDs or unique property values. This endpoint is useful for obtaining multiple objects in a single request, which can help optimize data retrieval processes in applications that need to handle large datasets. The response includes the objects' details, and you can specify whether to include archived objects.",
        "operationId" : "post-/crm/objects/2026-09-beta/{objectType}/batch/read",
        "security" : [ {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        } ]
      }
    },
    "/crm/objects/2026-09-beta/{objectType}/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "summary" : "Search objects",
        "description" : "Search for CRM objects of a specified type using the provided criteria. This endpoint allows you to filter and sort objects based on various properties, and retrieve a collection of objects matching the search criteria. It is useful for finding specific records or analyzing data trends within your CRM.",
        "operationId" : "post-/crm/objects/2026-09-beta/{objectType}/search",
        "security" : [ {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/objects/2026-09-beta/{objectType}/{objectId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read",
        "description" : "Read an Object identified by `{objectId}`. `{objectId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/objects/2026-09-beta/{objectType}/{objectId}",
        "security" : [ {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        } ]
      }
    },
    "/crm/objects/2026-09-beta/{objectType}/{objectId}/associations/{toObjectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List associations",
        "description" : "List all associations of an object by object type. This endpoint allows you to retrieve associations for a specified object type and object ID, with a limit of 500 results per call. It is useful for understanding the relationships between different CRM objects.",
        "operationId" : "get-/crm/objects/2026-09-beta/{objectType}/{objectId}/associations/{toObjectType}",
        "security" : [ {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        } ]
      }
    },
    "/crm/objects/2026-09-beta/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Create Association",
        "description" : "Set association labels between two records in the CRM. This endpoint allows you to define specific labels for the association between two objects identified by their types and IDs. It is useful for categorizing or labeling relationships between different CRM objects.",
        "operationId" : "put-/crm/objects/2026-09-beta/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}",
        "security" : [ {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.appointments.read" : "",
              "crm.objects.appointments.sensitive.read.v2" : "",
              "crm.objects.appointments.sensitive.write.v2" : "",
              "crm.objects.appointments.write" : "",
              "crm.objects.calls.read" : "",
              "crm.objects.carts.read" : "",
              "crm.objects.carts.write" : "",
              "crm.objects.commercepayments.read" : "",
              "crm.objects.commercepayments.write" : "",
              "crm.objects.companies.highly_sensitive.read.v2" : "",
              "crm.objects.companies.highly_sensitive.write.v2" : "",
              "crm.objects.companies.read" : "",
              "crm.objects.companies.sensitive.read.v2" : "",
              "crm.objects.companies.sensitive.write.v2" : "",
              "crm.objects.companies.write" : "",
              "crm.objects.contacts.highly_sensitive.read.v2" : "",
              "crm.objects.contacts.highly_sensitive.write.v2" : "",
              "crm.objects.contacts.read" : "",
              "crm.objects.contacts.sensitive.read.v2" : "",
              "crm.objects.contacts.sensitive.write.v2" : "",
              "crm.objects.contacts.write" : "",
              "crm.objects.courses.read" : "",
              "crm.objects.courses.write" : "",
              "crm.objects.custom.highly_sensitive.read.v2" : "",
              "crm.objects.custom.highly_sensitive.write.v2" : "",
              "crm.objects.custom.read" : "",
              "crm.objects.custom.sensitive.read.v2" : "",
              "crm.objects.custom.sensitive.write.v2" : "",
              "crm.objects.custom.write" : "",
              "crm.objects.deals.highly_sensitive.read.v2" : "",
              "crm.objects.deals.highly_sensitive.write.v2" : "",
              "crm.objects.deals.read" : "",
              "crm.objects.deals.sensitive.read.v2" : "",
              "crm.objects.deals.sensitive.write.v2" : "",
              "crm.objects.deals.write" : "",
              "crm.objects.emails.read" : "",
              "crm.objects.goals.read" : "",
              "crm.objects.goals.write" : "",
              "crm.objects.invoices.read" : "",
              "crm.objects.invoices.write" : "",
              "crm.objects.leads.read" : "",
              "crm.objects.leads.write" : "",
              "crm.objects.line_items.read" : "",
              "crm.objects.line_items.write" : "",
              "crm.objects.listings.read" : "",
              "crm.objects.listings.write" : "",
              "crm.objects.meetings.read" : "",
              "crm.objects.notes.read" : "",
              "crm.objects.orders.read" : "",
              "crm.objects.orders.write" : "",
              "crm.objects.partner-clients.read" : "",
              "crm.objects.partner-clients.write" : "",
              "crm.objects.partner-services.read" : "",
              "crm.objects.partner-services.write" : "",
              "crm.objects.products.read" : "",
              "crm.objects.products.write" : "",
              "crm.objects.projects.highly_sensitive.read" : "",
              "crm.objects.projects.highly_sensitive.write" : "",
              "crm.objects.projects.read" : "",
              "crm.objects.projects.sensitive.read" : "",
              "crm.objects.projects.sensitive.write" : "",
              "crm.objects.projects.write" : "",
              "crm.objects.quotes.read" : "",
              "crm.objects.quotes.write" : "",
              "crm.objects.services.read" : "",
              "crm.objects.services.write" : "",
              "crm.objects.subscriptions.read" : "",
              "crm.objects.subscriptions.write" : "",
              "crm.objects.tasks.read" : "",
              "crm.objects.tickets.highly_sensitive.read" : "",
              "crm.objects.tickets.highly_sensitive.write" : "",
              "crm.objects.tickets.sensitive.read" : "",
              "crm.objects.tickets.sensitive.write" : "",
              "crm.objects.users.read" : "",
              "crm.objects.users.write" : "",
              "e-commerce" : "",
              "media_bridge.read" : "",
              "oauth" : "",
              "tickets" : "",
              "tickets.highly_sensitive.v2" : "",
              "tickets.sensitive.v2" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}