{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Partner Clients",
    "description" : "CRM objects such as companies, contacts, deals, line items, products, tickets, and quotes are standard objects in HubSpot’s CRM. These core building blocks support custom properties, store critical information, and play a central role in the HubSpot application.\n\n## Supported Object Types\n\nThis API provides access to collections of CRM objects, which return a map of property names to values. Each object type has its own set of default properties, which can be found by ex[...]",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "Sync partner client data with third-party project management software.",
    "x-hubspot-introduction" : "Partner clients are HubSpot customers that Solutions Partners have a sold or managed relationship with. Use the this API to manage your client base as well as sync client data between HubSpot and other systems. Note: you can only retrieve and update existing partner clients with this API. This API doesn't support creation or deletion."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Associations"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "GDPR"
  }, {
    "name" : "Public_Object__SE_PT_EM_BE_R_2025"
  }, {
    "name" : "Public_Object_Search_Post__SE_PT_EM_BE_R_2025"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/v3/objects/partner_clients" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve a list of partner clients.",
        "description" : "Retrieve a list of partner clients with optional filtering by deleted status, associations, and specific properties. The response can be paginated using the 'after' parameter.",
        "operationId" : "get-/crm/v3/objects/partner_clients",
        "security" : [ {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        } ]
      }
    },
    "/crm/v3/objects/partner_clients/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve a batch of partner client objects.",
        "description" : "Retrieve multiple partner client objects in a single request by specifying their IDs. This endpoint is useful for efficiently accessing data for multiple clients at once, particularly when integrating with third-party systems.",
        "operationId" : "post-/crm/v3/objects/partner_clients/batch/read",
        "security" : [ {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        } ]
      }
    },
    "/crm/v3/objects/partner_clients/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update multiple partner client records in a single request.",
        "description" : "This endpoint allows you to update several partner client records at once by providing a batch of CRM object records with their respective IDs and properties. It is useful for synchronizing data across systems or making bulk updates efficiently.",
        "operationId" : "post-/crm/v3/objects/partner_clients/batch/update",
        "security" : [ {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        } ]
      }
    },
    "/crm/v3/objects/partner_clients/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "summary" : "Search for partner clients using specified criteria.",
        "description" : "Execute a search for partner clients based on defined filters, properties, and sorting options. This endpoint allows you to retrieve partner client data that matches the search criteria, facilitating integration and data synchronization with third-party systems.",
        "operationId" : "post-/crm/v3/objects/partner_clients/search",
        "security" : [ {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/v3/objects/partner_clients/{partnerClientId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve details of a specific partner client.",
        "description" : "Retrieve detailed information about a specific partner client, including selected properties and associations. This endpoint is useful for accessing comprehensive client data for analysis or integration purposes.",
        "operationId" : "get-/crm/v3/objects/partner_clients/{partnerClientId}",
        "security" : [ {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update properties of a specific partner client.",
        "description" : "Update the specified properties of an existing partner client.",
        "operationId" : "patch-/crm/v3/objects/partner_clients/{partnerClientId}",
        "security" : [ {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        } ]
      }
    },
    "/crm/v3/objects/partner_clients/{partnerClientId}/associations/{toObjectType}" : {
      "get" : {
        "tags" : [ "Associations" ],
        "summary" : "List associations of a partner client by type",
        "description" : "Retrieve a list of associations for a specific partner client based on the specified object type.",
        "operationId" : "get-/crm/v3/objects/partner_clients/{partnerClientId}/associations/{toObjectType}",
        "security" : [ {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        } ]
      }
    },
    "/crm/v3/objects/partner_clients/{partnerClientId}/associations/{toObjectType}/{toObjectId}/{associationType}" : {
      "put" : {
        "tags" : [ "Associations" ],
        "summary" : "Associate a partner client with another object",
        "description" : "Associate a partner client with another object by specifying the object type, object ID, and association type.",
        "operationId" : "put-/crm/v3/objects/partner_clients/{partnerClientId}/associations/{toObjectType}/{toObjectId}/{associationType}",
        "security" : [ {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Associations" ],
        "summary" : "Remove an association between two partner clients",
        "description" : "Remove an existing association between a partner client and another object by specifying the object type, object ID, and association type.",
        "operationId" : "delete-/crm/v3/objects/partner_clients/{partnerClientId}/associations/{toObjectType}/{toObjectId}/{associationType}",
        "security" : [ {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.appointments.read" : "Read appointments",
              "crm.objects.appointments.sensitive.read.v2" : "Read appointments (sensitive)",
              "crm.objects.appointments.sensitive.write.v2" : "Write appointments (sensitive)",
              "crm.objects.appointments.write" : "Write appointments",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.carts.write" : "Write cart",
              "crm.objects.commercepayments.read" : "Read the COMMERCE_PAYMENT object.",
              "crm.objects.commercepayments.write" : "Write commerce payments",
              "crm.objects.companies.highly_sensitive.read.v2" : "View company records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.write.v2" : "Change company records (highly-sensitive)",
              "crm.objects.companies.read" : "Create or update company records",
              "crm.objects.companies.sensitive.read.v2" : "View sensitive properties on company records",
              "crm.objects.companies.sensitive.write.v2" : "Create or update sensitive properties on company records",
              "crm.objects.companies.write" : "View company records",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.contacts.read" : "View contact records",
              "crm.objects.contacts.sensitive.read.v2" : "View sensitive properties on contact records",
              "crm.objects.contacts.sensitive.write.v2" : "Create or update sensitive properties on contact records",
              "crm.objects.contacts.write" : "Create or update contact records",
              "crm.objects.courses.read" : "Read courses",
              "crm.objects.courses.write" : "Write courses",
              "crm.objects.custom.highly_sensitive.read.v2" : "View custom object records (highly-sensitive)",
              "crm.objects.custom.highly_sensitive.write.v2" : "Change custom object records (highly-sensitive)",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.custom.sensitive.read.v2" : "View custom object records (sensitive)",
              "crm.objects.custom.sensitive.write.v2" : "Change custom object records (sensitive)",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.deals.highly_sensitive.read.v2" : "View deal records (highly-sensitive)",
              "crm.objects.deals.highly_sensitive.write.v2" : "Change deal records (highly-sensitive)",
              "crm.objects.deals.read" : "View deal records",
              "crm.objects.deals.sensitive.read.v2" : "View sensitive properties on deal records",
              "crm.objects.deals.sensitive.write.v2" : "Create or update sensitive properties on deal records",
              "crm.objects.deals.write" : "Create or update deal records",
              "crm.objects.goals.read" : "Read goals",
              "crm.objects.goals.write" : "Write goals",
              "crm.objects.invoices.read" : "Read invoices objects",
              "crm.objects.invoices.write" : "Write invoices",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.listings.read" : "Read listings",
              "crm.objects.listings.write" : "Write listings",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.partner-clients.write" : "Modify Partner Client CRM objects",
              "crm.objects.partner-services.read" : "View Partner Service CRM objects",
              "crm.objects.partner-services.write" : "Modify Partner Service CRM objects",
              "crm.objects.products.read" : "Read from my Product Library",
              "crm.objects.products.write" : "Write to my Product Library",
              "crm.objects.projects.highly_sensitive.read" : "Read projects (highly-sensitive)",
              "crm.objects.projects.highly_sensitive.write" : "Write projects (highly-sensitive)",
              "crm.objects.projects.read" : "Read projects",
              "crm.objects.projects.sensitive.read" : "Read projects (sensitive)",
              "crm.objects.projects.sensitive.write" : "Write projects (sensitive)",
              "crm.objects.projects.write" : "Write projects",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.services.read" : "Read services",
              "crm.objects.services.write" : "Write services",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.subscriptions.write" : "Write to Commerce Subscriptions",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.users.write" : "Write User CRM objects",
              "e-commerce" : "e-commerce",
              "media_bridge.read" : "Read media and media events",
              "oauth" : "User and Account Information",
              "tickets" : "Read and write tickets",
              "tickets.highly_sensitive.v2" : "Tickets (highly-sensitive)",
              "tickets.sensitive.v2" : "Tickets (sensitive)"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}