{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Orders",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/objects/2026-09/orders" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List",
        "description" : "Read a page of objects of a specified type in your HubSpot account. You can control the data returned by specifying properties, associations, and archived status through query parameters. This endpoint supports pagination to navigate through large sets of objects.",
        "operationId" : "get-/crm/objects/2026-09/orders_/crm/objects/2026-09-beta/{objectType}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create",
        "description" : "Create a CRM object with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard objects is provided.",
        "operationId" : "post-/crm/objects/2026-09/orders_/crm/objects/2026-09-beta/{objectType}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/orders/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch archive objects",
        "description" : "Archive a batch of CRM objects identified by their IDs. This operation moves the specified objects to the recycling bin, effectively archiving them. It is useful for managing large sets of objects that need to be archived simultaneously.",
        "operationId" : "post-/crm/objects/2026-09/orders/batch/archive_/crm/objects/2026-09-beta/{objectType}/batch/archive",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/orders/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch create objects",
        "description" : "Create a batch of CRM objects of a specified type in your HubSpot account. This endpoint allows you to create multiple objects in a single request, which can be useful for bulk data imports or synchronizing data from external systems. The response will include the created objects along with their IDs.",
        "operationId" : "post-/crm/objects/2026-09/orders/batch/create_/crm/objects/2026-09-beta/{objectType}/batch/create",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/orders/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read batch objects",
        "description" : "Retrieve a batch of CRM objects by their internal IDs or unique property values. This endpoint is useful for obtaining multiple objects in a single request, which can enhance performance and reduce the number of API calls needed. The response can include archived objects if specified.",
        "operationId" : "post-/crm/objects/2026-09/orders/batch/read_/crm/objects/2026-09-beta/{objectType}/batch/read",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/orders/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update batch objects",
        "description" : "Update a batch of CRM objects specified by their type. This endpoint allows you to modify multiple objects in a single request, ensuring efficient updates to your CRM data. The request body must include the objects to be updated along with their properties.",
        "operationId" : "post-/crm/objects/2026-09/orders/batch/update_/crm/objects/2026-09-beta/{objectType}/batch/update",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/orders/batch/upsert" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Upsert batch objects",
        "description" : "Create or update a batch of CRM objects based on unique property values. This endpoint allows you to efficiently manage large sets of objects by either creating new entries or updating existing ones in a single request. It is particularly useful for synchronizing data from external systems with HubSpot.",
        "operationId" : "post-/crm/objects/2026-09/orders/batch/upsert_/crm/objects/2026-09-beta/{objectType}/batch/upsert",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/orders/gdpr-delete" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "GDPR Delete",
        "description" : "Permanently delete a contact and all associated content to comply with GDPR regulations. This endpoint allows you to use the optional 'idProperty' set to 'email' to identify the contact by email address. If the email address is not found, it will be added to a blocklist, preventing future use.",
        "operationId" : "post-/crm/objects/2026-09/orders/gdpr-delete_/crm/objects/2026-09-beta/{objectType}/gdpr-delete",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ]
      }
    },
    "/crm/objects/2026-09/orders/merge" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Merge objects",
        "description" : "Merge two CRM objects of the same type within your HubSpot account. This operation combines the properties and associations of the specified objects into a single object, identified by the primary object ID. Use this endpoint to consolidate duplicate records or unify data.",
        "operationId" : "post-/crm/objects/2026-09/orders/merge_/crm/objects/2026-09-beta/{objectType}/merge",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/orders/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "summary" : "Search",
        "description" : "Search for CRM objects of a specified type using various filters and criteria. This endpoint allows you to retrieve objects based on specific properties and conditions, providing flexibility in querying your CRM data. The search results include the total number of objects matching the criteria.",
        "operationId" : "post-/crm/objects/2026-09/orders/search_/crm/objects/2026-09-beta/{objectType}/search",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/orders/{orderId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read",
        "description" : "Read an object identified by `objectId`. By default, `objectId` refers to the internal object ID, but it can be any unique property value specified by the `idProperty` query parameter. You can control the response content using the `properties` query parameter.",
        "operationId" : "get-/crm/objects/2026-09/orders/{orderId}_/crm/objects/2026-09-beta/{objectType}/{objectId}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archive",
        "description" : "Move an Object identified by `{objectId}` to the recycling bin. This operation allows you to archive a specific CRM object by its type and unique identifier, effectively removing it from active use while retaining the option to restore it later if needed.",
        "operationId" : "delete-/crm/objects/2026-09/orders/{orderId}_/crm/objects/2026-09-beta/{objectType}/{objectId}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update",
        "description" : "Perform a partial update of an object identified by `{objectId}`. The `{objectId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query parameter. Provided property values will be overwritten, while read-only and non-existent properties will be ignored. Properties can be cleared by passing an empty string.",
        "operationId" : "patch-/crm/objects/2026-09/orders/{orderId}_/crm/objects/2026-09-beta/{objectType}/{objectId}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/orders/{orderId}/associations/{toObjectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List associations",
        "description" : "List all associations of a specified object by its type. This endpoint allows you to retrieve associations between different object types, with a limit of 500 associations per call. It is useful for understanding relationships between various CRM objects in your HubSpot account.",
        "operationId" : "get-/crm/objects/2026-09/orders/{orderId}/associations/{toObjectType}_/crm/objects/2026-09-beta/{objectType}/{objectId}/associations/{toObjectType}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Batch" ],
        "summary" : "Create Association",
        "description" : "Create the default association type between two specified object types in HubSpot. This endpoint is useful for establishing a basic relationship between two CRM objects, identified by their types and IDs.",
        "operationId" : "put-/crm/objects/2026-09/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}_/crm/objects/2026-09-beta/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/crm/objects/2026-09/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Create",
        "description" : "Set association labels between two records. This endpoint allows you to establish specific relationships between two CRM objects by defining association labels. It is useful for organizing and managing related records within your HubSpot account.",
        "operationId" : "put-/crm/objects/2026-09/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_/crm/objects/2026-09-beta/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete",
        "description" : "Delete all associations between two CRM records identified by their object types and IDs. This operation is useful for removing links between specific records when they are no longer relevant or needed.",
        "operationId" : "delete-/crm/objects/2026-09/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_/crm/objects/2026-09-beta/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}",
        "security" : [ {
          "oauth2" : [ "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.tasks.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.sensitive.write" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.calls.read" ]
        }, {
          "oauth2" : [ "crm.objects.meetings.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-services.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.tickets.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.emails.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.notes.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.products.read" ]
        }, {
          "oauth2" : [ "oauth" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.appointments.read" : "",
              "crm.objects.appointments.sensitive.read.v2" : "",
              "crm.objects.appointments.sensitive.write.v2" : "",
              "crm.objects.appointments.write" : "",
              "crm.objects.calls.read" : "",
              "crm.objects.carts.read" : "",
              "crm.objects.carts.write" : "",
              "crm.objects.commercepayments.read" : "",
              "crm.objects.commercepayments.write" : "",
              "crm.objects.companies.highly_sensitive.read.v2" : "",
              "crm.objects.companies.highly_sensitive.write.v2" : "",
              "crm.objects.companies.read" : "",
              "crm.objects.companies.sensitive.read.v2" : "",
              "crm.objects.companies.sensitive.write.v2" : "",
              "crm.objects.companies.write" : "",
              "crm.objects.contacts.highly_sensitive.read.v2" : "",
              "crm.objects.contacts.highly_sensitive.write.v2" : "",
              "crm.objects.contacts.read" : "",
              "crm.objects.contacts.sensitive.read.v2" : "",
              "crm.objects.contacts.sensitive.write.v2" : "",
              "crm.objects.contacts.write" : "",
              "crm.objects.courses.read" : "",
              "crm.objects.courses.write" : "",
              "crm.objects.custom.highly_sensitive.read.v2" : "",
              "crm.objects.custom.highly_sensitive.write.v2" : "",
              "crm.objects.custom.read" : "",
              "crm.objects.custom.sensitive.read.v2" : "",
              "crm.objects.custom.sensitive.write.v2" : "",
              "crm.objects.custom.write" : "",
              "crm.objects.deals.highly_sensitive.read.v2" : "",
              "crm.objects.deals.highly_sensitive.write.v2" : "",
              "crm.objects.deals.read" : "",
              "crm.objects.deals.sensitive.read.v2" : "",
              "crm.objects.deals.sensitive.write.v2" : "",
              "crm.objects.deals.write" : "",
              "crm.objects.emails.read" : "",
              "crm.objects.goals.read" : "",
              "crm.objects.goals.write" : "",
              "crm.objects.invoices.read" : "",
              "crm.objects.invoices.write" : "",
              "crm.objects.leads.read" : "",
              "crm.objects.leads.write" : "",
              "crm.objects.line_items.read" : "",
              "crm.objects.line_items.write" : "",
              "crm.objects.listings.read" : "",
              "crm.objects.listings.write" : "",
              "crm.objects.meetings.read" : "",
              "crm.objects.notes.read" : "",
              "crm.objects.orders.read" : "",
              "crm.objects.orders.write" : "",
              "crm.objects.partner-clients.read" : "",
              "crm.objects.partner-clients.write" : "",
              "crm.objects.partner-services.read" : "",
              "crm.objects.partner-services.write" : "",
              "crm.objects.products.read" : "",
              "crm.objects.products.write" : "",
              "crm.objects.projects.highly_sensitive.read" : "",
              "crm.objects.projects.highly_sensitive.write" : "",
              "crm.objects.projects.read" : "",
              "crm.objects.projects.sensitive.read" : "",
              "crm.objects.projects.sensitive.write" : "",
              "crm.objects.projects.write" : "",
              "crm.objects.quotes.read" : "",
              "crm.objects.quotes.write" : "",
              "crm.objects.services.read" : "",
              "crm.objects.services.write" : "",
              "crm.objects.subscriptions.read" : "",
              "crm.objects.subscriptions.write" : "",
              "crm.objects.tasks.read" : "",
              "crm.objects.tickets.highly_sensitive.read" : "",
              "crm.objects.tickets.highly_sensitive.write" : "",
              "crm.objects.tickets.sensitive.read" : "",
              "crm.objects.tickets.sensitive.write" : "",
              "crm.objects.users.read" : "",
              "crm.objects.users.write" : "",
              "e-commerce" : "",
              "media_bridge.read" : "",
              "oauth" : "",
              "oauth-access" : "",
              "tickets.highly_sensitive.v2" : "",
              "tickets.sensitive.v2" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}