{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Communication Preferences Subscriptions",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "STARTER",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  } ],
  "paths" : {
    "/communication-preferences/2026-03/definitions" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve all subscription status definitions",
        "description" : "Get a list of subscription status definitions from the account.",
        "operationId" : "get-/communication-preferences/2026-03/definitions",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/links/generate" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Generate subscription links",
        "description" : "Generate communication preference links for a subscriber. This endpoint allows you to create URLs for managing preferences and unsubscribing, tailored to a specific subscriber. It is useful for integrating communication preference management into your applications.",
        "operationId" : "post-/communication-preferences/2026-03/links/generate_/communication-preferences/v4/links/generate",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read", "communication_preferences.write" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read", "communication_preferences.write" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/status/email/{emailAddress}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve subscription status",
        "description" : "Retrieve the subscription statuses for a specific email address. This endpoint allows you to check the current subscription status for email communications, which can be useful for managing communication preferences and ensuring compliance with user preferences.",
        "operationId" : "get-/communication-preferences/2026-03/status/email/{emailAddress}_/communication-preferences/2026-03/status/email/{emailAddress}",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/statuses/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch read statuses",
        "description" : "Retrieve the subscription statuses for multiple subscribers in a batch operation. This endpoint allows you to check the communication preferences of several subscribers at once, which is useful for managing large lists of contacts efficiently.",
        "operationId" : "post-/communication-preferences/2026-03/statuses/batch/read",
        "security" : [ {
          "oauth2" : [ "communication_preferences.statuses.batch.read" ]
        }, {
          "private_apps" : [ "communication_preferences.statuses.batch.read" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/statuses/batch/unsubscribe-all" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch unsubscribe contacts from all subscriptions",
        "description" : "Unsubscribe a set of contacts from all email subscriptions.",
        "operationId" : "post-/communication-preferences/2026-03/statuses/batch/unsubscribe-all",
        "security" : [ {
          "oauth2" : [ "communication_preferences.statuses.batch.write" ]
        }, {
          "private_apps" : [ "communication_preferences.statuses.batch.write" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/statuses/batch/unsubscribe-all/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch read statuses",
        "description" : "Retrieve the unsubscribe-all status for a batch of subscribers in a specified channel. This endpoint is useful for checking the current unsubscribe-all status of multiple subscribers at once, helping to manage and audit communication preferences efficiently.",
        "operationId" : "post-/communication-preferences/2026-03/statuses/batch/unsubscribe-all/read",
        "security" : [ {
          "oauth2" : [ "communication_preferences.statuses.batch.read" ]
        }, {
          "private_apps" : [ "communication_preferences.statuses.batch.read" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/statuses/batch/write" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch update subscription status",
        "description" : "Update the subscription status for a set of contacts.",
        "operationId" : "post-/communication-preferences/2026-03/statuses/batch/write",
        "security" : [ {
          "oauth2" : [ "communication_preferences.statuses.batch.write" ]
        }, {
          "private_apps" : [ "communication_preferences.statuses.batch.write" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/statuses/{subscriberIdString}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get subscription preferences for a specific contact",
        "description" : "Retrieve a contact's current email subscription preferences.",
        "operationId" : "get-/communication-preferences/2026-03/statuses/{subscriberIdString}",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Update a contact's subscription status",
        "description" : "Set the subscription status of a specific contact.",
        "operationId" : "post-/communication-preferences/2026-03/statuses/{subscriberIdString}",
        "security" : [ {
          "oauth2" : [ "communication_preferences.write" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.write" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/statuses/{subscriberIdString}/unsubscribe-all" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve a contact's unsubscribed status",
        "description" : "Check whether a contact has unsubscribed from all email subscriptions. If a contact has not opted out of all communications, the response `results` array will be empty.",
        "operationId" : "get-/communication-preferences/2026-03/statuses/{subscriberIdString}/unsubscribe-all",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Unsubscribe all",
        "description" : "Unsubscribe a subscriber from all communication channels. This endpoint allows you to remove a subscriber from all communication preferences, effectively opting them out from receiving any further communications. This can be useful for ensuring compliance with user requests or legal requirements.",
        "operationId" : "post-/communication-preferences/2026-03/statuses/{subscriberIdString}/unsubscribe-all",
        "security" : [ {
          "oauth2" : [ "communication_preferences.write" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.write" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/subscribe" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Subscribe a contact",
        "description" : "Subscribe a user to a specific communication preference using their email address and subscription ID. This endpoint allows you to manage subscription statuses by updating them to 'subscribed' for a given email address. It is useful for ensuring that users receive communications they have opted into.",
        "operationId" : "post-/communication-preferences/2026-03/subscribe_/communication-preferences/2026-03/subscribe",
        "security" : [ {
          "oauth2" : [ "communication_preferences.write" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.write" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/unsubscribe" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Unsubscribe a contact",
        "description" : "Unsubscribe a user from communication preferences. This endpoint allows you to update the subscription status of a user to 'unsubscribed' for specified communication channels. It is useful for managing user preferences and ensuring compliance with user opt-out requests.",
        "operationId" : "post-/communication-preferences/2026-03/unsubscribe_/communication-preferences/2026-03/unsubscribe",
        "security" : [ {
          "oauth2" : [ "communication_preferences.write" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "communication_preferences.read" : "Read contact subscription preferences",
              "communication_preferences.read_write" : "Update contact subscription preferences",
              "communication_preferences.statuses.batch.read" : "Batch read contact subscription preferences",
              "communication_preferences.statuses.batch.write" : "Batch update contact subscription preferences",
              "communication_preferences.write" : "Update contact subscription preferences"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "STARTER",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}