{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Lists",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "STARTER",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "PUBLIC_BETA",
    "x-hubspot-api-use-case" : "You want to bulk add contacts to a particular list, or remove company records from a company list.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Lists Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/crm/lists/overview"
    } ],
    "x-hubspot-introduction" : "Use the lists API to manage list memberships for contact, company, and custom object lists."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Lists"
  }, {
    "name" : "Memberships"
  }, {
    "name" : "Folders"
  } ],
  "paths" : {
    "/crm/v3/lists/{listId}/update-list-name" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "リスト名を更新",
        "description" : "リストの名前を更新します。名前は、ポータルの他の全ての公開リストに対してグローバルに固有である必要があります。",
        "operationId" : "put-/crm/v3/lists/{listId}/update-list-name_updateName",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-and-remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "リストのレコードを追加または削除",
        "description" : "システムにすでに作成されているレコードをリストに追加するか、リストから削除します。\n\nこのエンドポイントは、「processingType」が「MANUAL」または「SNAPSHOT」のリストでのみ機能します。",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add-and-remove_addAndRemove",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "IDでリストを取得",
        "description" : "**ILSリストID**で1つのリストを取得します。",
        "operationId" : "get-/crm/v3/lists/{listId}_getById",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Lists" ],
        "summary" : "リストを削除",
        "description" : "**ILSリストID**でリストを削除します。このエンドポイントで削除されたリストは、削除してから最大90日間復元できます。90日が経過すると、このリストは消去され、復元できなくなります。",
        "operationId" : "delete-/crm/v3/lists/{listId}_remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/update-list-filters" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "リストフィルター定義を更新",
        "description" : "「DYNAMIC」リストのフィルター分岐定義を更新します。更新されたら、リストメンバーシップが再評価され、新しい定義に合わせて更新されます。",
        "operationId" : "put-/crm/v3/lists/{listId}/update-list-filters_updateListFilters",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/search" : {
      "post" : {
        "tags" : [ "Lists" ],
        "summary" : "リストを検索",
        "description" : "リスト名でリストを検索するか、空の「クエリ」値を指定して全てのリストを表示します。",
        "operationId" : "post-/crm/v3/lists/search_doSearch",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/move-list" : {
      "put" : {
        "tags" : [ "Folders" ],
        "summary" : "指定されたフォルダーにリストを移動",
        "description" : "リストとフォルダーが指定されると、そのフォルダーにリストが移動します。",
        "operationId" : "put-/crm/v3/lists/folders/move-list",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "レコードをリストに追加",
        "description" : "指定されたレコードをリストに追加します。存在しないレコードや、すでにリストのメンバーになっているレコードは無視されます。\n\nこのエンドポイントは、「processingType」が「MANUAL」または「SNAPSHOT」のリストでのみ機能します。",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add_add",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "名前でリストを取得",
        "description" : "リスト名とオブジェクトタイプを使用して1つのリストを取得します。",
        "operationId" : "get-/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}_getByName",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/{folderId}/move/{newParentFolderId}" : {
      "put" : {
        "tags" : [ "Folders" ],
        "summary" : "フォルダーを移動",
        "description" : "これにより、フォルダーが現在の場所から新しい場所に移動し、このフォルダーの親が更新されて、指定された新しいIDになります。",
        "operationId" : "put-/crm/v3/lists/folders/{folderId}/move/{newParentFolderId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/restore" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "リストを復元",
        "description" : "以前に削除されたリストを**ILSリストID**を使用して復元します。削除されたリストは、リストが削除されてから最大90日間復元できます。",
        "operationId" : "put-/crm/v3/lists/{listId}/restore_restore",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/{folderId}/rename" : {
      "put" : {
        "tags" : [ "Folders" ],
        "summary" : "フォルダーの名前を変更",
        "description" : "新しい名前を使用して、指定されたfolderIdの名前を変更します。",
        "operationId" : "put-/crm/v3/lists/folders/{folderId}/rename",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "ソースリストの全てのレコードをターゲットリストに追加",
        "description" : "*ソースリスト*（「sourceListId」で指定される）の全てのレコードを*ターゲットリスト*（「listId」で指定される）に追加します。すでに*ターゲットリスト*のメンバーになっているレコードは無視されます。*ターゲットリスト*と*ソースリスト*のIDは異なっている必要があります。*ターゲットリスト*と*ソースリスト*には、同じタイプのレコード（コンタクトや会社など）が含まれている必要があります。\n\nこのエンドポイントは、「processingType」が「MANUAL」または「SNAPSHOT」の*ターゲットリスト*でのみ機能します。「ソースリスト」には任意の「processingType」を使用できます。",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}_addAllFromList",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/records/{objectTypeId}/{recordId}/memberships" : {
      "get" : {
        "tags" : [ "Memberships" ],
        "summary" : "レコードがメンバーであるリストを取得",
        "description" : "レコードが指定されると、このレコードがメンバーになっているリストが提供されます。",
        "operationId" : "get-/crm/v3/lists/records/{objectTypeId}/{recordId}/memberships_getLists",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "複数のリストを取得",
        "description" : "**ILSリストID**を使用して、1回のリクエストで複数のリストを取得します。レスポンスには、指定された「listIds」で存在する全てのリストの定義が含まれます。",
        "operationId" : "get-/crm/v3/lists/_getAll",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Lists" ],
        "summary" : "リストを作成",
        "description" : "指定されたオブジェクトリスト定義を使用して、新しいリストを作成します。",
        "operationId" : "post-/crm/v3/lists/_create",
        "security" : [ {
          "oauth2" : [ "crm.lists.write" ]
        }, {
          "private_apps" : [ "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/folders" : {
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "フォルダーを取得します。",
        "description" : "フォルダーを取得し、childNodes属性を使用して再帰的に全てのフォルダーを含めます。全ての子ノードの子リストのフィールドは空になります。取得されたフォルダーにのみそのフォルダーの子リストが含まれます。",
        "operationId" : "get-/crm/v3/lists/folders",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Folders" ],
        "summary" : "フォルダーを作成",
        "description" : "指定された情報を使用してフォルダーを作成します。",
        "operationId" : "post-/crm/v3/lists/folders",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/{folderId}" : {
      "delete" : {
        "tags" : [ "Folders" ],
        "summary" : "フォルダーを削除",
        "description" : "指定されたIDのフォルダーを削除します。",
        "operationId" : "delete-/crm/v3/lists/folders/{folderId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships" : {
      "get" : {
        "tags" : [ "Memberships" ],
        "summary" : "IDで並べ替えられたリストメンバーシップを取得",
        "description" : "リストのレコードの「recordId」で並べ替えられる順序でリストのメンバーシップを取得します。\n\n「after」オフセットが指定されている場合や、オフセットが指定されていない場合、「recordId」は*昇順*に並べ替えられます。「before」オフセットのみが指定されている場合、レコードは*降順*に並べ替えられます。\n\n両方のオフセットが指定されている場合、「before」オフセットパラメーターよりも「after」オフセットパラメーターが優先されます。",
        "operationId" : "get-/crm/v3/lists/{listId}/memberships_getPage",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Memberships" ],
        "summary" : "リストから全てのレコードを削除",
        "description" : "リストから**全て**のレコードを削除します。 ***メモ：*** *リストは削除されません。*\n\nこのエンドポイントは、「processingType」が「MANUAL」または「SNAPSHOT」のリストでのみ機能します。",
        "operationId" : "delete-/crm/v3/lists/{listId}/memberships_removeAll",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "リストからレコードを削除",
        "description" : "指定されたレコードをリストから削除します。存在しないレコードや、リストのメンバーでないレコードは無視されます。\n\nこのエンドポイントは、「processingType」が「MANUAL」または「SNAPSHOT」のリストでのみ機能します。",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/remove_remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.lists.read" : " ",
              "crm.lists.write" : " "
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "STARTER",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "PUBLIC_BETA"
}