{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Lists",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "STARTER",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "PUBLIC_BETA",
    "x-hubspot-api-use-case" : "You want to bulk add contacts to a particular list, or remove company records from a company list.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Lists Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/crm/lists/overview"
    } ],
    "x-hubspot-introduction" : "Use the lists API to manage list memberships for contact, company, and custom object lists."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Lists"
  }, {
    "name" : "Memberships"
  }, {
    "name" : "Folders"
  } ],
  "paths" : {
    "/crm/v3/lists/{listId}/update-list-name" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Actualizar nombre de lista",
        "description" : "Actualiza el nombre de una lista. El nombre debe ser único de forma global, en relación con todas las demás listas públicas en el portal.",
        "operationId" : "put-/crm/v3/lists/{listId}/update-list-name_updateName",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-and-remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Agregar y/o eliminar registros de una lista",
        "description" : "Agregar a y/o eliminar de una lista registros que ya han sido creados en el sistema.\n\nEste punto de terminación solo funciona para listas que tienen un \"processingType\" de \"MANUAL\" o \"INSTANTÁNEA\".",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add-and-remove_addAndRemove",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Recuperar lista por ID",
        "description" : "Obtén una lista individual por **ID de lista ILS**.",
        "operationId" : "get-/crm/v3/lists/{listId}_getById",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Lists" ],
        "summary" : "Eliminar una lista",
        "description" : "Elimina una lista por **ID de lista ILS**. Las listas eliminadas a través de este punto de terminación pueden restaurarse hasta 90 días después de la eliminación. Después de 90 días, la lista se purga y ya no se puede restaurar.",
        "operationId" : "delete-/crm/v3/lists/{listId}_remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/update-list-filters" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Actualizar definición de filtro de lista",
        "description" : "Actualiza la definición de ramificación de filtro de una lista \"DINÁMICA\". Una vez actualizada, las membresías de la lista serán reevaluadas y se actualizarán para que coincidan con la nueva definición.",
        "operationId" : "put-/crm/v3/lists/{listId}/update-list-filters_updateListFilters",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/search" : {
      "post" : {
        "tags" : [ "Lists" ],
        "summary" : "Listas de búsqueda",
        "description" : "Busca listas por nombre de lista o busca en todas las listas proporcionando un valor de \"consulta\" vacío.",
        "operationId" : "post-/crm/v3/lists/search_doSearch",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/move-list" : {
      "put" : {
        "tags" : [ "Folders" ],
        "summary" : "Mueve una lista a una carpeta especificada",
        "description" : "Si se especifica una lista y una carpeta, la lista se moverá a esa carpeta.",
        "operationId" : "put-/crm/v3/lists/folders/move-list",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Agregar registros a una lista",
        "description" : "Agrega los registros proporcionados a la lista. Se ignoran los registros que no existen o que ya son miembros de la lista.\n\nEste punto de terminación solo funciona para listas que tienen un \"processingType\" de \"MANUAL\" o \"INSTANTÁNEA\".",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add_add",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Recuperar lista por nombre",
        "description" : "Recuperar una lista individual por nombre de lista y tipo de objeto.",
        "operationId" : "get-/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}_getByName",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/{folderId}/move/{newParentFolderId}" : {
      "put" : {
        "tags" : [ "Folders" ],
        "summary" : "Mueve una carpeta",
        "description" : "Esto mueve la carpeta desde su ubicación actual a una nueva ubicación. Actualiza el elemento principal de esta carpeta con el nuevo ID especificado.",
        "operationId" : "put-/crm/v3/lists/folders/{folderId}/move/{newParentFolderId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/restore" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Restaurar una lista",
        "description" : "Restaura una lista eliminada previamente por **ID de lista ILS**. Las listas eliminadas pueden restaurarse hasta 90 días después de haber sido eliminadas.",
        "operationId" : "put-/crm/v3/lists/{listId}/restore_restore",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/{folderId}/rename" : {
      "put" : {
        "tags" : [ "Folders" ],
        "summary" : "Cambiar el nombre de una carpeta",
        "description" : "Cambia el nombre del folderId especificado por un nuevo nombre.",
        "operationId" : "put-/crm/v3/lists/folders/{folderId}/rename",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Agregar todos los registros de una lista de origen a una lista de destino",
        "description" : "Agregar todos los registros de una *lista de origen* (especificada por el \"sourceListId\") a una *lista de destino* (especificada por el \"listId\"). Se ignorarán los registros que ya sean miembros de la *lista de destino*. Los ID de *destino* y *lista de origen* deben ser diferentes. El *destino* y la *lista de origen* deben contener registros del mismo tipo (por ejemplo, contactos, empresas, etc.).\n\nEste punto de terminación solo funciona para *listas de destino* qu[...]",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}_addAllFromList",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/records/{objectTypeId}/{recordId}/memberships" : {
      "get" : {
        "tags" : [ "Memberships" ],
        "summary" : "Obtener listas de las que el registro es miembro",
        "description" : "Para un registro dado, proporciona las listas de las que este registro es miembro.",
        "operationId" : "get-/crm/v3/lists/records/{objectTypeId}/{recordId}/memberships_getLists",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Recuperar múltiples listas",
        "description" : "Recupera múltiples listas en una sola solicitud por **ID de lista ILS**. La respuesta incluirá las definiciones de todas las listas que existen para los \"listIds\" proporcionados.",
        "operationId" : "get-/crm/v3/lists/_getAll",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Lists" ],
        "summary" : "Crear lista",
        "description" : "Crea una nueva lista con la definición de lista de objetos proporcionada.",
        "operationId" : "post-/crm/v3/lists/_create",
        "security" : [ {
          "oauth2" : [ "crm.lists.write" ]
        }, {
          "private_apps" : [ "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/folders" : {
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Recupera una carpeta.",
        "description" : "Recupera una carpeta e incluye recursivamente todas las carpetas a través del atributo childNodes. El campo de listas secundarias estará vacío en todos los nodos secundarios. Solo la carpeta recuperada incluirá las listas secundarias en esa carpeta.",
        "operationId" : "get-/crm/v3/lists/folders",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Folders" ],
        "summary" : "Crea una carpeta",
        "description" : "Crea una carpeta con la información proporcionada.",
        "operationId" : "post-/crm/v3/lists/folders",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/{folderId}" : {
      "delete" : {
        "tags" : [ "Folders" ],
        "summary" : "Elimina una carpeta",
        "description" : "Elimina la carpeta con el ID especificado.",
        "operationId" : "delete-/crm/v3/lists/folders/{folderId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships" : {
      "get" : {
        "tags" : [ "Memberships" ],
        "summary" : "Obtener membresías de lista ordenadas por ID",
        "description" : "Recupera las membresías de una lista ordenadas según el \"recordId\" de los registros de la lista.\n\nLos \"recordId\" se ordenan en orden *ascendente* si se especifica un desplazamiento \"después\" o si no se especifica ningún desplazamiento. Si solo se especifica un desplazamiento \"antes\", los registros se ordenan en orden *descendente*.\n\nEl parámetro de desplazamiento \"después\" tendrá prioridad sobre el desplazamiento \"antes\" en caso de que se especifiquen amb[...]",
        "operationId" : "get-/crm/v3/lists/{listId}/memberships_getPage",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Memberships" ],
        "summary" : "Eliminar todos los registros de una lista",
        "description" : "Eliminar **todos** los registros de una lista. ***Nota:*** *La lista no se elimina.*\n\nEste punto de terminación solo funciona para listas que tienen un \"processingType\" de \"MANUAL\" o \"INSTANTÁNEA\".",
        "operationId" : "delete-/crm/v3/lists/{listId}/memberships_removeAll",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Eliminar registros de una lista",
        "description" : "Elimina los registros proporcionados de la lista. Se ignoran los registros que no existen o que no son miembros de la lista.\n\nEste punto de terminación solo funciona para listas que tienen un \"processingType\" de \"MANUAL\" o \"INSTANTÁNEA\".",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/remove_remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.lists.read" : " ",
              "crm.lists.write" : " "
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "STARTER",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "PUBLIC_BETA"
}