{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Lists",
    "description" : "CRUD operations to manage lists and list memberships",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "STARTER",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "You want to bulk add contacts to a particular list, or remove company records from a company list.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Lists Overview",
      "url" : "https://hubspot.dev/guides/api/crm/lists"
    } ],
    "x-hubspot-introduction" : "Use the lists API to manage list memberships for contact, company, and custom object lists."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Lists",
    "description" : "",
    "x-hubspot-tag-name-english-source" : "Lists"
  }, {
    "name" : "Memberships",
    "description" : "",
    "x-hubspot-tag-name-english-source" : "Memberships"
  } ],
  "paths" : {
    "/crm/v3/lists/{listId}/update-list-name" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Update List Name",
        "description" : "Update the name of a list. The name must be globally unique relative to all other public lists in the portal.",
        "operationId" : "put-/crm/v3/lists/{listId}/update-list-name",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-and-remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Add and/or Remove Records from a List",
        "description" : "Add and/or remove records that have already been created in the system to and/or from a list.\n\nThis endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add-and-remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Fetch List by ID",
        "description" : "Fetch a single list by **ILS list ID**.",
        "operationId" : "get-/crm/v3/lists/{listId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Lists" ],
        "summary" : "Delete a List",
        "description" : "Delete a list by **ILS list ID**. Lists deleted through this endpoint can be restored up to 90-days following the delete. After 90-days, the list is purged and can no longer be restored.",
        "operationId" : "delete-/crm/v3/lists/{listId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/update-list-filters" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Update List Filter Definition",
        "description" : "Update the filter branch definition of a `DYNAMIC` list. Once updated, the list memberships will be re-evaluated and updated to match the new definition.",
        "operationId" : "put-/crm/v3/lists/{listId}/update-list-filters",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/search" : {
      "post" : {
        "tags" : [ "Lists" ],
        "summary" : "Search Lists",
        "description" : "Search lists by list name or page through all lists by providing an empty `query` value.",
        "operationId" : "post-/crm/v3/lists/search",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Add Records to a List",
        "description" : "Add the records provided to the list. Records that do not exist or that are already members of the list are ignored.\n\nThis endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Fetch List by Name",
        "description" : "Fetch a single list by list name and object type.",
        "operationId" : "get-/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Add All Records from a Source List to a Destination List",
        "description" : "Add all of the records from a *source list* (specified by the `sourceListId`) to a *destination list* (specified by the `listId`). Records that are already members of the *destination list* will be ignored. The *destination* and *source list* IDs must be different. The *destination* and *source lists* must contain records of the same type (e.g. contacts, companies, etc.).\n\nThis endpoint only works for *destination lists* that have a `processingType` of `MANUAL` or `SNA[...]",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Fetch Multiple Lists",
        "description" : "Fetch multiple lists in a single request by **ILS list ID**. The response will include the definitions of all lists that exist for the `listIds` provided.",
        "operationId" : "get-/crm/v3/lists/",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Lists" ],
        "summary" : "Create List",
        "description" : "Create a new list with the provided object list definition.",
        "operationId" : "post-/crm/v3/lists/",
        "security" : [ {
          "oauth2" : [ "crm.lists.write" ]
        }, {
          "private_apps" : [ "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/restore" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Restore a List",
        "description" : "Restore a previously deleted list by **ILS list ID**. Deleted lists are eligible to be restored up-to 90-days after the list has been deleted.",
        "operationId" : "put-/crm/v3/lists/{listId}/restore",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships" : {
      "get" : {
        "tags" : [ "Memberships" ],
        "summary" : "Fetch List Memberships Ordered by ID",
        "description" : "Fetch the memberships of a list in order sorted by the `recordId` of the records in the list.\n\nThe `recordId`s are sorted in *ascending* order if an `after` offset or no offset is provided. If only a `before` offset is provided, then the records are sorted in *descending* order.\n\nThe `after` offset parameter will take precedence over the `before` offset in a case where both are provided.",
        "operationId" : "get-/crm/v3/lists/{listId}/memberships",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Memberships" ],
        "summary" : "Delete All Records from a List",
        "description" : "Remove **all** of the records from a list. ***Note:*** *The list is not deleted.*\n\nThis endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.",
        "operationId" : "delete-/crm/v3/lists/{listId}/memberships",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Remove Records from a List",
        "description" : "Remove the records provided from the list. Records that do not exist or that are not members of the list are ignored.\n\nThis endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.lists.read" : " ",
              "crm.lists.write" : " "
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "STARTER",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}