{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Lists",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "STARTER",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "PUBLIC_BETA",
    "x-hubspot-api-use-case" : "You want to bulk add contacts to a particular list, or remove company records from a company list.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Lists Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/crm/lists/overview"
    } ],
    "x-hubspot-introduction" : "Use the lists API to manage list memberships for contact, company, and custom object lists."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Lists"
  }, {
    "name" : "Memberships"
  }, {
    "name" : "Folders"
  } ],
  "paths" : {
    "/crm/v3/lists/{listId}/update-list-name" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Mettre à jour le nom de la liste",
        "description" : "Mettre à jour le nom d'une liste. Le nom doit être globalement unique par rapport à toutes les autres listes publiques du portail.",
        "operationId" : "put-/crm/v3/lists/{listId}/update-list-name_updateName",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-and-remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Ajouter et/ou Supprimer des Fiches d'informations d'une Liste",
        "description" : "Ajouter et/ou supprimer des fiches d'informations qui ont déjà été créées dans le système vers et/ou depuis une liste.\n\nCe point de terminaison ne fonctionne que pour les listes ayant un « processingType » de « MANUEL » ou « INSTANTANÉ ».",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add-and-remove_addAndRemove",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Récupérer la liste par ID",
        "description" : "Récupérer une seule liste par **ID de liste ILS**.",
        "operationId" : "get-/crm/v3/lists/{listId}_getById",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Lists" ],
        "summary" : "Supprimer une liste",
        "description" : "Supprimer une liste par **ID de liste ILS**. Les listes supprimées via ce point de terminaison peuvent être restaurées jusqu'à 90 jours après la suppression. Après 90 jours, la liste est purgée et ne peut plus être restaurée.",
        "operationId" : "delete-/crm/v3/lists/{listId}_remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/update-list-filters" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Mettre à jour la définition du filtre de liste",
        "description" : "Mettez à jour la définition de la branche de filtre pour une liste « DYNAMIQUE ». Après la mise à jour, les adhésions à la liste seront réévaluées et ajustées pour correspondre à la nouvelle définition.",
        "operationId" : "put-/crm/v3/lists/{listId}/update-list-filters_updateListFilters",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/search" : {
      "post" : {
        "tags" : [ "Lists" ],
        "summary" : "Rechercher des listes",
        "description" : "Recherchez des listes par nom de liste ou parcourez toutes les listes en fournissant une valeur « requête » vide.",
        "operationId" : "post-/crm/v3/lists/search_doSearch",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/move-list" : {
      "put" : {
        "tags" : [ "Folders" ],
        "summary" : "Déplace une liste vers un dossier donné",
        "description" : "Si vous disposez d'une liste et d'un dossier, la liste sera déplacée vers ce dossier.",
        "operationId" : "put-/crm/v3/lists/folders/move-list",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Ajouter des fiches d'informations à une liste",
        "description" : "Ajoutez les fiches d'informations fournies à la liste. Les fiches d'informations qui n'existent pas ou qui sont déjà membres de la liste sont ignorées.\n\nCe point de terminaison ne fonctionne que pour les listes ayant un « processingType » de « MANUEL » ou « INSTANTANÉ ».",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add_add",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Récupérer la liste par nom",
        "description" : "Récupérer une seule liste par nom de liste et type d'objet.",
        "operationId" : "get-/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}_getByName",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/{folderId}/move/{newParentFolderId}" : {
      "put" : {
        "tags" : [ "Folders" ],
        "summary" : "Déplace un dossier",
        "description" : "Cette action déplace le dossier de son emplacement actuel vers un nouvel emplacement. Cela met à jour le parent de ce dossier avec le nouvel Id donné.",
        "operationId" : "put-/crm/v3/lists/folders/{folderId}/move/{newParentFolderId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/restore" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Restaurer une liste",
        "description" : "Restaurez une liste précédemment supprimée par **ID de liste ILS**. Les listes supprimées peuvent être restaurées jusqu'à 90 jours après leur suppression.",
        "operationId" : "put-/crm/v3/lists/{listId}/restore_restore",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/{folderId}/rename" : {
      "put" : {
        "tags" : [ "Folders" ],
        "summary" : "Renommer un dossier",
        "description" : "Renomme le folderId donné avec un nouveau nom.",
        "operationId" : "put-/crm/v3/lists/folders/{folderId}/rename",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Ajouter toutes les fiches d'informations d'une liste source à une liste de destination",
        "description" : "Ajoutez toutes les fiches d'informations d'une *liste source* (spécifiée par « sourceListId ») à une *liste de destination* (spécifiée par le « listId »). Les fiches d'informations qui sont déjà membres de la *liste de destination* seront ignorées. Les identifiants de la *liste de destination* et de la *liste source* doivent être différents. Les *listes de destination* et *listes source* doivent contenir des fiches d'informations du même type (par exemple, contacts, entr[...]",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}_addAllFromList",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/records/{objectTypeId}/{recordId}/memberships" : {
      "get" : {
        "tags" : [ "Memberships" ],
        "summary" : "Obtenir les listes dont la fiche d'informations fait partie",
        "description" : "Pour une fiche d'informations donnée, fournir les listes dont cette fiche d'informations fait partie.",
        "operationId" : "get-/crm/v3/lists/records/{objectTypeId}/{recordId}/memberships_getLists",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Récupérer plusieurs listes",
        "description" : "Récupérez plusieurs listes en une seule requête par **ID de liste ILS**. La réponse inclura les définitions de toutes les listes qui existent pour les « listIds » fournis.",
        "operationId" : "get-/crm/v3/lists/_getAll",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Lists" ],
        "summary" : "Créer la liste",
        "description" : "Créer une nouvelle liste avec la définition de liste d'objets fournie.",
        "operationId" : "post-/crm/v3/lists/_create",
        "security" : [ {
          "oauth2" : [ "crm.lists.write" ]
        }, {
          "private_apps" : [ "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/folders" : {
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Récupère un dossier.",
        "description" : "Récupère un dossier et inclut récursivement tous les dossiers via l'attribut childNodes. Le champ des listes enfants sera vide dans tous les nœuds enfants. Seul le dossier récupéré inclura les listes enfants dans ce dossier.",
        "operationId" : "get-/crm/v3/lists/folders",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Folders" ],
        "summary" : "Crée un dossier",
        "description" : "Crée un dossier avec les informations fournies.",
        "operationId" : "post-/crm/v3/lists/folders",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/{folderId}" : {
      "delete" : {
        "tags" : [ "Folders" ],
        "summary" : "Supprime un dossier",
        "description" : "Supprime le dossier avec l'ID donné.",
        "operationId" : "delete-/crm/v3/lists/folders/{folderId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships" : {
      "get" : {
        "tags" : [ "Memberships" ],
        "summary" : "Récupérer les adhésions de la liste triées par ID.",
        "description" : "Récupérez les adhésions d'une liste dans l'ordre trié par le « recordId » des fiches d'informations dans la liste.\n\nLes « recordIds » sont triés par ordre *croissant* si un décalage « après » ou aucun décalage n'est fourni. Si seul un décalage « avant » est fourni, alors les fiches d'informations sont triés par ordre *décroissant*.\n\nLe paramètre de décalage « après » prendra le pas sur le décalage « avant » dans le cas où les deux sont fournis.",
        "operationId" : "get-/crm/v3/lists/{listId}/memberships_getPage",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Memberships" ],
        "summary" : "Supprimer toutes les fiches d'informations d'une liste",
        "description" : "Supprimez **toutes** les fiches d'informations d'une liste. ***Remarque :*** *La liste n'est pas supprimée.*\n\nCe point de terminaison ne fonctionne que pour les listes ayant un « processingType » de « MANUEL » ou « INSTANTANÉ ».",
        "operationId" : "delete-/crm/v3/lists/{listId}/memberships_removeAll",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Supprimer des fiches d'informations d'une liste",
        "description" : "Supprimez les fiches d'informations fournies de la liste. Les fiches d'informations qui n'existent pas ou qui ne sont pas membres de la liste sont ignorées.\n\nCe point de terminaison ne fonctionne que pour les listes ayant un « processingType » de « MANUEL » ou « INSTANTANÉ ».",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/remove_remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.lists.read" : " ",
              "crm.lists.write" : " "
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "STARTER",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "PUBLIC_BETA"
}