{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Lists",
    "description" : "CRUD operations to manage lists and list memberships",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "STARTER",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "STARTER",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "You want to bulk add contacts to a particular list, or remove company records from a company list.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Lists Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/lists/overview"
    } ],
    "x-hubspot-introduction" : "Use the lists API to manage list memberships for object lists."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Lists"
  }, {
    "name" : "List_App_Mapping"
  }, {
    "name" : "List_App"
  }, {
    "name" : "Memberships"
  }, {
    "name" : "List_App_Membership"
  } ],
  "paths" : {
    "/crm/v3/lists/{listId}/update-list-name" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Update List Name",
        "description" : "Update the name of a list. The name must be globally unique relative to all other public lists in the portal.",
        "operationId" : "put-/crm/v3/lists/{listId}/update-list-name_updateName",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-and-remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Add and/or Remove Records from a List",
        "description" : "Add and/or remove records that have already been created in the system to and/or from a list.\n\nThis endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add-and-remove_addAndRemove",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/update-list-filters" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Update List Filter Definition",
        "description" : "Update the filter branch definition of a `DYNAMIC` list. Once updated, the list memberships will be re-evaluated and updated to match the new definition.",
        "operationId" : "put-/crm/v3/lists/{listId}/update-list-filters_updateListFilters",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Fetch List by ID",
        "description" : "Fetch a single list by **ILS list ID**.",
        "operationId" : "get-/crm/v3/lists/{listId}_getById",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Lists" ],
        "summary" : "Delete a List",
        "description" : "Delete a list by **ILS list ID**. Lists deleted through this endpoint can be restored up to 90-days following the delete. After 90-days, the list is purged and can no longer be restored.",
        "operationId" : "delete-/crm/v3/lists/{listId}_remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/schedule-conversion" : {
      "get" : {
        "tags" : [ "List_App" ],
        "summary" : "Retrieve the conversion details for a list",
        "description" : "Retrieve the conversion details for a list. This can be used to check for an upcoming conversion, or to get the details of when a list was already converted.",
        "operationId" : "get-/crm/v3/lists/{listId}/schedule-conversion",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "List_App" ],
        "summary" : "Schedule or update the conversion of a list to static",
        "description" : "Schedule the conversion of an active list into a static list, or update the already scheduled conversion. This can be scheduled for a specific date or based on activity.",
        "operationId" : "put-/crm/v3/lists/{listId}/schedule-conversion",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "List_App" ],
        "summary" : "Cancel the conversion of a list",
        "description" : "Delete an existing scheduled conversion for a list.",
        "operationId" : "delete-/crm/v3/lists/{listId}/schedule-conversion",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/search" : {
      "post" : {
        "tags" : [ "Lists" ],
        "summary" : "Search Lists",
        "description" : "Search lists by list name or page through all lists by providing an empty `query` value.",
        "operationId" : "post-/crm/v3/lists/search_doSearch",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Add Records to a List",
        "description" : "Add the records provided to the list. Records that do not exist or that are already members of the list are ignored.\n\nThis endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add_add",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/move-list" : {
      "put" : {
        "tags" : [ "List_App" ],
        "summary" : "Moves a list to a given folder",
        "description" : "Given a list and a folder, the list will be moved to that folder.",
        "operationId" : "put-/crm/v3/lists/folders/move-list_moveList",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Fetch List by Name",
        "description" : "Fetch a single list by list name and object type.",
        "operationId" : "get-/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}_getByName",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/{folderId}/move/{newParentFolderId}" : {
      "put" : {
        "tags" : [ "List_App" ],
        "summary" : "Moves a folder",
        "description" : "This moves the folder from its current location to a new location. It updates the parent of this folder to the new Id given.",
        "operationId" : "put-/crm/v3/lists/folders/{folderId}/move/{newParentFolderId}_move",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/idmapping" : {
      "get" : {
        "tags" : [ "List_App_Mapping" ],
        "summary" : "Translate Legacy List Id to Modern List Id",
        "description" : "This API allows translation of legacy list id to list id. This is a temporary API allowed for mapping old id's to new id's and will expire on May 30th, 2025.",
        "operationId" : "get-/crm/v3/lists/idmapping_translateLegacyListIdToListId",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "List_App_Mapping" ],
        "summary" : "Translate Legacy List Id to Modern List Id in Batch",
        "description" : "This API allows translation of a batch of legacy list id's to list id's. This allows for a maximum of 10,000 id's. This is a temporary API allowed for mapping old id's to new id's and will expire on May 30th, 2025.",
        "operationId" : "post-/crm/v3/lists/idmapping_translateLegacyListIdToListIdBatch",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/restore" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Restore a List",
        "description" : "Restore a previously deleted list by **ILS list ID**. Deleted lists are eligible to be restored up-to 90-days after the list has been deleted.",
        "operationId" : "put-/crm/v3/lists/{listId}/restore_restore",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/{folderId}/rename" : {
      "put" : {
        "tags" : [ "List_App" ],
        "summary" : "Rename a folder",
        "description" : "Renames the given folderId with a new name.",
        "operationId" : "put-/crm/v3/lists/folders/{folderId}/rename_rename",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/join-order" : {
      "get" : {
        "tags" : [ "List_App_Membership" ],
        "summary" : "Fetch List Memberships Ordered by Added to List Date",
        "description" : "Fetch the memberships of a list in order sorted by the time the records were added to the list.\n\nThe `recordId`s are sorted in *ascending* order if an `after` offset or no offset is provided. If only a `before` offset is provided, then the records are sorted in *descending* order.\n\nThe `after` offset parameter will take precedence over the `before` offset in a case where both are provided.",
        "operationId" : "get-/crm/v3/lists/{listId}/memberships/join-order_getPageOrderedByAddedToListDate",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Add All Records from a Source List to a Destination List",
        "description" : "Add all of the records from a *source list* (specified by the `sourceListId`) to a *destination list* (specified by the `listId`). Records that are already members of the *destination list* will be ignored. The *destination* and *source list* IDs must be different. The *destination* and *source lists* must contain records of the same type (e.g. contacts, companies, etc.).\n\nThis endpoint only works for *destination lists* that have a `processingType` of `MANUAL` or `SNA[...]",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}_addAllFromList",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/records/{objectTypeId}/{recordId}/memberships" : {
      "get" : {
        "tags" : [ "Memberships" ],
        "summary" : "Get lists record is member of",
        "description" : "For given record provide lists this record is member of.",
        "operationId" : "get-/crm/v3/lists/records/{objectTypeId}/{recordId}/memberships_getLists",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/v3/lists/" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Fetch Multiple Lists",
        "description" : "Fetch multiple lists in a single request by **ILS list ID**. The response will include the definitions of all lists that exist for the `listIds` provided.",
        "operationId" : "get-/crm/v3/lists/_getAll",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Lists" ],
        "summary" : "Create List",
        "description" : "Create a new list with the provided object list definition.",
        "operationId" : "post-/crm/v3/lists/_create",
        "security" : [ {
          "private_apps" : [ "cms.membership.access_groups.write" ]
        }, {
          "oauth2" : [ "cms.membership.access_groups.write" ]
        }, {
          "oauth2" : [ "crm.lists.write" ]
        }, {
          "private_apps" : [ "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/folders/{folderId}" : {
      "delete" : {
        "tags" : [ "List_App" ],
        "summary" : "Deletes a folder",
        "description" : "Deletes the folder with the given Id.",
        "operationId" : "delete-/crm/v3/lists/folders/{folderId}_remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/folders" : {
      "get" : {
        "tags" : [ "List_App" ],
        "summary" : "Retrieves a folder.",
        "description" : "Retrieves a folder and recursively includes all folders via the childNodes attribute.  The child lists field will be empty in all child nodes. Only the folder retrieved will include the child lists in that folder.",
        "operationId" : "get-/crm/v3/lists/folders_getAll",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "List_App" ],
        "summary" : "Creates a folder",
        "description" : "Creates a folder with the given information.",
        "operationId" : "post-/crm/v3/lists/folders_create",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Remove Records from a List",
        "description" : "Remove the records provided from the list. Records that do not exist or that are not members of the list are ignored.\n\nThis endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/remove_remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships" : {
      "get" : {
        "tags" : [ "Memberships" ],
        "summary" : "Fetch List Memberships Ordered by ID",
        "description" : "Fetch the memberships of a list in order sorted by the `recordId` of the records in the list.\n\nThe `recordId`s are sorted in *ascending* order if an `after` offset or no offset is provided. If only a `before` offset is provided, then the records are sorted in *descending* order.\n\nThe `after` offset parameter will take precedence over the `before` offset in a case where both are provided.",
        "operationId" : "get-/crm/v3/lists/{listId}/memberships_getPage",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Memberships" ],
        "summary" : "Delete All Records from a List",
        "description" : "Remove **all** of the records from a list. ***Note:*** *The list is not deleted.*\n\nThis endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.\n\nThis endpoint only supports lists that have less than 100,000 memberships.",
        "operationId" : "delete-/crm/v3/lists/{listId}/memberships_removeAll",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        }, {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "cms.membership.access_groups.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.lists.read" : "View segments",
              "crm.lists.write" : "Create or update segments",
              "cms.membership.access_groups.write" : "Write membership access groups."
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "STARTER",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}