{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Domains",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "Retrieve all currently connected domains to see which sites are live in a given account.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Domains Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/cms/domains"
    } ],
    "x-hubspot-introduction" : "Use the domain management API to return information about the domains connected to a HubSpot account. You can return data for all currently connected domains, or for a single domain by ID."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Domain"
  }, {
    "name" : "Domains"
  } ],
  "paths" : {
    "/cms/v3/domains/" : {
      "get" : {
        "tags" : [ "Domains" ],
        "summary" : "Get current domains",
        "description" : "Returns all existing domains that have been created. Results can be limited and filtered by creation or updated date.",
        "operationId" : "get-/cms/v3/domains/_getPage",
        "security" : [ {
          "oauth2" : [ "cms.domains.read" ]
        }, {
          "oauth2" : [ "content" ]
        }, {
          "oauth2" : [ "cms.domains.write" ]
        }, {
          "oauth2" : [ "cms.knowledge_base.settings.write" ]
        }, {
          "oauth2" : [ "cms.knowledge_base.settings.read" ]
        }, {
          "private_apps" : [ "cms.domains.read" ]
        }, {
          "private_apps" : [ "cms.knowledge_base.settings.write" ]
        }, {
          "private_apps" : [ "cms.domains.write" ]
        }, {
          "private_apps" : [ "content" ]
        }, {
          "private_apps" : [ "cms.knowledge_base.settings.read" ]
        } ]
      }
    },
    "/cms/v3/domains/{domainId}" : {
      "get" : {
        "tags" : [ "Domains" ],
        "summary" : "Get a single domain",
        "description" : "Returns a single domains with the id specified.",
        "operationId" : "get-/cms/v3/domains/{domainId}_getById",
        "security" : [ {
          "oauth2" : [ "cms.domains.read" ]
        }, {
          "oauth2" : [ "content" ]
        }, {
          "oauth2" : [ "cms.domains.write" ]
        }, {
          "oauth2" : [ "cms.knowledge_base.settings.write" ]
        }, {
          "oauth2" : [ "cms.knowledge_base.settings.read" ]
        }, {
          "private_apps" : [ "cms.domains.read" ]
        }, {
          "private_apps" : [ "cms.knowledge_base.settings.write" ]
        }, {
          "private_apps" : [ "cms.domains.write" ]
        }, {
          "private_apps" : [ "content" ]
        }, {
          "private_apps" : [ "cms.knowledge_base.settings.read" ]
        } ]
      }
    },
    "/cms/v3/domains/{domainId}/security-settings" : {
      "get" : {
        "tags" : [ "Domain" ],
        "operationId" : "get-/cms/v3/domains/{domainId}/security-settings_/cms/v3/domains/{domainId}/security-settings",
        "security" : [ {
          "oauth2" : [ "cms.domains.read" ]
        }, {
          "oauth2" : [ "content" ]
        }, {
          "oauth2" : [ "cms.domains.write" ]
        }, {
          "oauth2" : [ "cms.knowledge_base.settings.write" ]
        }, {
          "oauth2" : [ "cms.knowledge_base.settings.read" ]
        }, {
          "private_apps" : [ "cms.domains.read" ]
        }, {
          "private_apps" : [ "cms.knowledge_base.settings.write" ]
        }, {
          "private_apps" : [ "cms.domains.write" ]
        }, {
          "private_apps" : [ "content" ]
        }, {
          "private_apps" : [ "cms.knowledge_base.settings.read" ]
        } ]
      }
    },
    "/cms/v3/domains/{domainId}/security-settings/sync" : {
      "post" : {
        "tags" : [ "Domain" ],
        "operationId" : "post-/cms/v3/domains/{domainId}/security-settings/sync_/cms/v3/domains/{domainId}/security-settings/sync",
        "security" : [ {
          "oauth2" : [ "cms.domains.write" ]
        }, {
          "private_apps" : [ "cms.domains.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "cms.domains.read" : "Ability to read CMS domains",
              "cms.domains.write" : "Ability to create, update and delete CMS domains",
              "cms.knowledge_base.settings.read" : "View knowledge base settings",
              "cms.knowledge_base.settings.write" : "Update knowledge base settings",
              "content" : "Content"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}