{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CMS Domains",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "Domains Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/cms/domains"
    } ]
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Domains"
  } ],
  "paths" : {
    "/cms/v3/domains/" : {
      "get" : {
        "tags" : [ "Domains" ],
        "operationId" : "get-/cms/v3/domains/_getPage",
        "security" : [ {
          "oauth2" : [ "cms.domains.read" ]
        }, {
          "oauth2" : [ "content" ]
        }, {
          "oauth2" : [ "cms.domains.write" ]
        }, {
          "oauth2" : [ "cms.knowledge_base.settings.write" ]
        }, {
          "oauth2" : [ "cms.knowledge_base.settings.read" ]
        }, {
          "private_apps" : [ "cms.domains.read" ]
        }, {
          "private_apps" : [ "cms.knowledge_base.settings.write" ]
        }, {
          "private_apps" : [ "cms.domains.write" ]
        }, {
          "private_apps" : [ "content" ]
        }, {
          "private_apps" : [ "cms.knowledge_base.settings.read" ]
        } ]
      }
    },
    "/cms/v3/domains/{domainId}" : {
      "get" : {
        "tags" : [ "Domains" ],
        "operationId" : "get-/cms/v3/domains/{domainId}_getById",
        "security" : [ {
          "oauth2" : [ "cms.domains.read" ]
        }, {
          "oauth2" : [ "content" ]
        }, {
          "oauth2" : [ "cms.domains.write" ]
        }, {
          "oauth2" : [ "cms.knowledge_base.settings.write" ]
        }, {
          "oauth2" : [ "cms.knowledge_base.settings.read" ]
        }, {
          "private_apps" : [ "cms.domains.read" ]
        }, {
          "private_apps" : [ "cms.knowledge_base.settings.write" ]
        }, {
          "private_apps" : [ "cms.domains.write" ]
        }, {
          "private_apps" : [ "content" ]
        }, {
          "private_apps" : [ "cms.knowledge_base.settings.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "cms.domains.read" : "Read domains.",
              "cms.domains.write" : "Create or update domains.",
              "cms.knowledge_base.settings.read" : "View knowledge base settings",
              "cms.knowledge_base.settings.write" : "Update knowledge base settings",
              "content" : "Read from and write to my Content"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}