{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Invoices",
    "description" : "",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-documentation-banner" : "NONE"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Batch",
    "description" : "",
    "x-hubspot-tag-name-english-source" : "Batch"
  }, {
    "name" : "Search",
    "description" : "",
    "x-hubspot-tag-name-english-source" : "Search"
  } ],
  "paths" : {
    "/crm/v3/objects/invoices/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of invoices by internal ID, or unique property values",
        "operationId" : "post-/crm/v3/objects/invoices/batch/read",
        "security" : [ ]
      }
    },
    "/crm/v3/objects/invoices/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "operationId" : "post-/crm/v3/objects/invoices/search",
        "security" : [ ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "media_bridge.read" : "Read media and media events",
              "tickets" : "Read and write tickets",
              "crm.objects.goals.read" : "Read goals",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.custom.write" : "Change custom object records",
              "e-commerce" : "e-commerce"
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.deals.read" : " ",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.contacts.read" : " ",
              "crm.objects.contacts.write" : " ",
              "crm.objects.companies.write" : " ",
              "crm.objects.companies.read" : " ",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.deals.write" : " "
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  }
}