{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Conversations Inbox & Messages",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  } ],
  "paths" : {
    "/conversations/conversations/2026-09-beta/actors/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch read actors",
        "description" : "Retrieve information about multiple actors in a batch operation. This endpoint is useful for obtaining details on various actors in a single request, streamlining data retrieval processes.",
        "operationId" : "post-/conversations/conversations/2026-09-beta/actors/batch/read_/conversations/conversations/2026-09-beta/actors/batch/read",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/conversations/2026-09-beta/actors/{actorId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve actor",
        "description" : "Retrieve information about a specific actor in the conversations system using their unique actor ID. This endpoint is useful for obtaining details about a particular actor, which could be an agent, bot, or other entity involved in conversations.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/actors/{actorId}_/conversations/conversations/2026-09-beta/actors/{actorId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/conversations/2026-09-beta/channel-accounts" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List channel accounts",
        "description" : "Retrieve a list of channel accounts associated with your HubSpot account. This endpoint allows you to filter results by channel ID, inbox ID, and other criteria. It's useful for managing and reviewing the channel accounts linked to your conversations.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/channel-accounts_/conversations/conversations/2026-09-beta/channel-accounts",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/conversations/conversations/2026-09-beta/channel-accounts/{channelAccountId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve Channel Account",
        "description" : "Retrieve details of a specific channel account in your HubSpot account using the unique channelAccountId. This endpoint is useful for accessing information about a particular channel account, including its archived status.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/channel-accounts/{channelAccountId}_/conversations/conversations/2026-09-beta/channel-accounts/{channelAccountId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/conversations/conversations/2026-09-beta/channels" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List channels",
        "description" : "Retrieve a list of channels in your HubSpot account. This endpoint supports pagination and sorting, allowing you to manage large sets of data effectively. Use this endpoint to get an overview of all available channels.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/channels_/conversations/conversations/2026-09-beta/channels",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/conversations/2026-09-beta/channels/{channelId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve channel",
        "description" : "Retrieve details of a specific channel in your HubSpot account using the channel's unique identifier. This endpoint is useful for accessing channel-specific information, which can be used for managing or analyzing communication channels.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/channels/{channelId}_/conversations/conversations/2026-09-beta/channels/{channelId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/conversations/2026-09-beta/inboxes" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List Inboxes",
        "description" : "Retrieve a list of inboxes in your HubSpot account. This endpoint allows you to paginate through results and sort them as needed. It can also filter to include only archived inboxes.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/inboxes_/conversations/conversations/2026-09-beta/inboxes",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/conversations/2026-09-beta/inboxes/{inboxId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve inbox",
        "description" : "Retrieve details of a specific inbox within your HubSpot account using its unique identifier. This endpoint allows you to access information about the inbox, including whether it is archived. It is useful for managing and organizing conversations within different inboxes.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/inboxes/{inboxId}_/conversations/conversations/2026-09-beta/inboxes/{inboxId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/conversations/conversations/2026-09-beta/threads" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List threads",
        "description" : "Retrieve a list of conversation threads from the specified inboxes. This endpoint allows filtering by associated contact or ticket, thread status, and other parameters. It supports pagination and sorting to help manage large sets of data effectively.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/threads_/conversations/conversations/2026-09-beta/threads",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/conversations/conversations/2026-09-beta/threads/{threadId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve thread",
        "description" : "Retrieve details of a specific conversation thread using its unique identifier. This endpoint allows you to access information about the thread, including its properties and associations. It is useful for fetching thread details for further processing or display.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/threads/{threadId}_/conversations/conversations/2026-09-beta/threads/{threadId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete thread",
        "description" : "Delete a specific conversation thread in your HubSpot account. This operation removes the thread identified by the threadId from the system. Use this endpoint to manage and clean up conversation threads that are no longer needed.",
        "operationId" : "delete-/conversations/conversations/2026-09-beta/threads/{threadId}_/conversations/conversations/2026-09-beta/threads/{threadId}",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update thread",
        "description" : "Update the details of a specific conversation thread in your HubSpot account. This endpoint allows you to modify the status or other attributes of the thread identified by the threadId. It is useful for managing the state of conversation threads, such as marking them as open or closed.",
        "operationId" : "patch-/conversations/conversations/2026-09-beta/threads/{threadId}_/conversations/conversations/2026-09-beta/threads/{threadId}",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/conversations/conversations/2026-09-beta/threads/{threadId}/assignee" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update assignee",
        "description" : "Assign a specific actor to a conversation thread in your HubSpot account. This endpoint allows you to update the assignee for a given thread, which can be useful for managing workload distribution among team members.",
        "operationId" : "put-/conversations/conversations/2026-09-beta/threads/{threadId}/assignee_/conversations/conversations/2026-09-beta/threads/{threadId}/assignee",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete assignee",
        "description" : "Remove the assignee from a specific conversation thread in your HubSpot account. This operation is useful when you want to unassign a thread from a user, making it available for reassignment or indicating that it no longer requires a specific assignee.",
        "operationId" : "delete-/conversations/conversations/2026-09-beta/threads/{threadId}/assignee_/conversations/conversations/2026-09-beta/threads/{threadId}/assignee",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/conversations/conversations/2026-09-beta/threads/{threadId}/messages" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve messages",
        "description" : "Retrieve messages from a specific conversation thread in your HubSpot account. This endpoint allows you to access all messages associated with a given thread, which can be useful for reviewing conversation history or analyzing communication patterns.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/threads/{threadId}/messages_/conversations/conversations/2026-09-beta/threads/{threadId}/messages",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create message",
        "description" : "Create a new message within a specific thread in your HubSpot account. This endpoint allows you to add messages to existing conversation threads, which can be useful for continuing discussions or providing additional information. Ensure that the threadId is correctly specified to target the appropriate thread.",
        "operationId" : "post-/conversations/conversations/2026-09-beta/threads/{threadId}/messages_/conversations/conversations/2026-09-beta/threads/{threadId}/messages",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/conversations/conversations/2026-09-beta/threads/{threadId}/messages/{messageId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve message",
        "description" : "Retrieve a specific message from a conversation thread in your HubSpot account. This endpoint allows you to access the details of a message identified by its messageId within a thread identified by threadId. You can specify certain properties to include in the response.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/threads/{threadId}/messages/{messageId}_/conversations/conversations/2026-09-beta/threads/{threadId}/messages/{messageId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/conversations/conversations/2026-09-beta/threads/{threadId}/messages/{messageId}/original-content" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve original content",
        "description" : "Retrieve the original content of a specific message within a thread. This endpoint is useful for accessing the unaltered text or rich text content of a message, which can be important for auditing or reviewing the initial communication in a conversation.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/threads/{threadId}/messages/{messageId}/original-content_/conversations/conversations/2026-09-beta/threads/{threadId}/messages/{messageId}/original-content",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "conversations.read" : "",
              "conversations.write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}