{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Conversations Inbox & Messages",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  } ],
  "paths" : {
    "/conversations/conversations/2026-09-beta/actors/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch retrieve actors",
        "description" : "Retrieve information about multiple actors in a batch operation. This endpoint is useful for obtaining details about several actors at once, which can help in managing or analyzing actor data efficiently.",
        "operationId" : "post-/conversations/conversations/2026-09-beta/actors/batch/read",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/actors/{actorId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve actor",
        "description" : "Retrieve details of a specific actor in the conversations API by providing the actor's unique identifier. This endpoint is useful for obtaining information about a particular actor involved in conversations, such as agents, bots, or visitors.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/actors/{actorId}",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/channel-accounts" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List channel accounts",
        "description" : "Retrieve a list of channel accounts associated with conversations in your HubSpot account. This endpoint allows you to filter results by channel ID, inbox ID, and other parameters. It supports pagination and sorting to help manage large sets of data effectively.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/channel-accounts",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/channel-accounts/{channelAccountId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve channel account",
        "description" : "Retrieve details of a specific channel account using its unique identifier. This endpoint allows you to access information about a channel account, which can be useful for managing or integrating communication channels within your HubSpot account.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/channel-accounts/{channelAccountId}",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/channels" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List Channels",
        "description" : "Retrieve a list of channels available in the HubSpot account. This endpoint supports pagination and sorting, allowing you to manage and organize the channel data effectively. Use this endpoint to access detailed information about each channel, which can be useful for integrating or managing communication platforms within your HubSpot environment.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/channels",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/channels/{channelId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve channel",
        "description" : "Retrieve details of a specific channel in the HubSpot conversations API. This endpoint is useful for accessing information about a channel using its unique identifier.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/channels/{channelId}",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/inboxes" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List inboxes",
        "description" : "Retrieve a list of inboxes in your HubSpot account. This endpoint allows you to paginate through results, set limits on the number of results per page, sort the results, and filter by archived status. Useful for managing and viewing all inboxes associated with your account.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/inboxes",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/inboxes/{inboxId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve inbox",
        "description" : "Retrieve details of a specific inbox in your HubSpot account using the inbox ID. This endpoint allows you to access information about the inbox, including whether it is archived. It is useful for managing and organizing your communication channels within HubSpot.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/inboxes/{inboxId}",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/threads" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve threads",
        "description" : "Retrieve a list of conversation threads from the specified inboxes in your HubSpot account. This endpoint allows you to filter threads by associated contacts, tickets, status, and more. Useful for managing and reviewing communication threads efficiently.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/threads",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/threads/{threadId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve thread",
        "description" : "Retrieve a specific conversation thread by its unique identifier. This endpoint allows you to access detailed information about the thread, including its properties and associations. It can be useful for reviewing the content and status of a conversation thread within your HubSpot account.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/threads/{threadId}",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete thread",
        "description" : "Delete a specific conversation thread in your HubSpot account. This operation will permanently remove the thread identified by the threadId from the system. It is useful for managing and cleaning up conversation data.",
        "operationId" : "delete-/conversations/conversations/2026-09-beta/threads/{threadId}",
        "security" : [ {
          "oauth2" : [ "conversations-api-write" ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update thread",
        "description" : "Update the details of a specific thread in the conversations API. This operation allows you to modify the status or archived state of a thread identified by its threadId. Use this endpoint to manage thread lifecycle events such as closing or reopening a conversation.",
        "operationId" : "patch-/conversations/conversations/2026-09-beta/threads/{threadId}",
        "security" : [ {
          "oauth2" : [ "conversations-api-write" ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/threads/{threadId}/assignee" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update assignee",
        "description" : "Assign a specific actor to a conversation thread in your HubSpot account. This operation allows you to set or change the assignee for a thread, which can help in managing and organizing conversations more effectively.",
        "operationId" : "put-/conversations/conversations/2026-09-beta/threads/{threadId}/assignee",
        "security" : [ {
          "oauth2" : [ "conversations-api-write" ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete Assignee",
        "description" : "Remove the assignee from a specific conversation thread in your HubSpot account. This operation is useful when you want to unassign a user from handling a particular thread, potentially allowing it to be reassigned to another user or left unassigned.",
        "operationId" : "delete-/conversations/conversations/2026-09-beta/threads/{threadId}/assignee",
        "security" : [ {
          "oauth2" : [ "conversations-api-write" ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/threads/{threadId}/messages" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve messages",
        "description" : "Retrieve messages from a specific conversation thread in your HubSpot account. This endpoint allows you to paginate through messages, sort them, and filter based on archival status. It is useful for accessing the message history of a conversation thread.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/threads/{threadId}/messages",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create message",
        "description" : "Create a new message within a specific conversation thread in your HubSpot account. This endpoint allows you to send messages as part of an ongoing conversation, which can include various types of content such as text, attachments, and more. It is useful for programmatically interacting with conversation threads and ensuring seamless communication flow.",
        "operationId" : "post-/conversations/conversations/2026-09-beta/threads/{threadId}/messages",
        "security" : [ {
          "oauth2" : [ "conversations-api-write" ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/threads/{threadId}/messages/{messageId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve message",
        "description" : "Retrieve a specific message from a conversation thread in your HubSpot account. This endpoint allows you to access the details of a message by specifying the thread and message identifiers. It is useful for fetching message content and properties for further analysis or display.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/threads/{threadId}/messages/{messageId}",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/conversations/conversations/2026-09-beta/threads/{threadId}/messages/{messageId}/original-content" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve message content",
        "description" : "Retrieve the original content of a specific message within a conversation thread. This endpoint is useful for accessing the initial message content before any modifications or formatting changes. It can be particularly helpful for auditing or reviewing the original message details.",
        "operationId" : "get-/conversations/conversations/2026-09-beta/threads/{threadId}/messages/{messageId}/original-content",
        "security" : [ {
          "app_cookie" : [ "conversations-api-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "conversations-api-read" ]
        }, {
          "oauth2" : [ "conversations-api-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "subscription-status-batch-read" : "",
              "subscription-status-batch-write" : "",
              "subscriptions-definition-read" : "",
              "subscriptions-status-read" : "",
              "subscriptions-status-write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}