{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Commerce Payments",
    "description" : "",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-api-use-case" : "Fetch all refunded payments in the account.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Payments Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/commerce/payments"
    } ],
    "x-hubspot-introduction" : "Use the payments API to fetch information about an account's payments. This is a read-only API, so it cannot be used for creating new or managing existing payments. Note that the account must be set up to collect payments through either HubSpot payments or Stripe payment processing."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Batch"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/v3/objects/commerce_payments/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Retrieve a batch of payments",
        "description" : "Retrieve a batch of payments by ID. ",
        "operationId" : "post-/crm/v3/objects/commerce_payments/batch/read",
        "security" : [ {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        } ]
      }
    },
    "/crm/v3/objects/commerce_payments/{commercePaymentId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve a payment",
        "description" : "Retrieve a payment by its ID. You can specify what is returned using the `properties` query parameter.",
        "operationId" : "get-/crm/v3/objects/commerce_payments/{commercePaymentId}",
        "security" : [ {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete a payment",
        "description" : "Permanently delete an existing payment.",
        "operationId" : "delete-/crm/v3/objects/commerce_payments/{commercePaymentId}",
        "security" : [ ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update a payment",
        "description" : "Perform a partial update of a payment identified by ID. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
        "operationId" : "patch-/crm/v3/objects/commerce_payments/{commercePaymentId}",
        "security" : [ ]
      }
    },
    "/crm/v3/objects/commerce_payments/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Delete a batch of payments",
        "description" : "Permanently delete a batch of payments.",
        "operationId" : "post-/crm/v3/objects/commerce_payments/batch/archive",
        "security" : [ ]
      }
    },
    "/crm/v3/objects/commerce_payments/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of payments",
        "description" : "Create a batch of payments. The `inputs` array can contain a `properties` object to define property values for each record, along with an `associations` array to define associations with other CRM records.",
        "operationId" : "post-/crm/v3/objects/commerce_payments/batch/create",
        "security" : [ ]
      }
    },
    "/crm/v3/objects/commerce_payments/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update a batch of payments",
        "description" : "Update a batch of existing payments.",
        "operationId" : "post-/crm/v3/objects/commerce_payments/batch/update",
        "security" : [ ]
      }
    },
    "/crm/v3/objects/commerce_payments" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve payments",
        "description" : "Retrieve all payments, using query parameters to specify the information that gets returned.",
        "operationId" : "get-/crm/v3/objects/commerce_payments",
        "security" : [ {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a payment",
        "description" : "Create a commerce payment with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard commerce payments is provided.",
        "operationId" : "post-/crm/v3/objects/commerce_payments",
        "security" : [ ]
      }
    },
    "/crm/v3/objects/commerce_payments/batch/upsert" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create or update a batch of commerce payments by unique property values",
        "description" : "Create or update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
        "operationId" : "post-/crm/v3/objects/commerce_payments/batch/upsert",
        "security" : [ ]
      }
    },
    "/crm/v3/objects/commerce_payments/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "summary" : "Search for payments",
        "description" : "Search for payments by filtering on properties, searching through associations, and sorting results. Learn more about [CRM search](https://developers.hubspot.com/docs/guides/api/crm/search#make-a-search-request).",
        "operationId" : "post-/crm/v3/objects/commerce_payments/search",
        "security" : [ {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.deals.highly_sensitive.write.v2" : "Change deal records (highly-sensitive)",
              "crm.objects.products.write" : "Write to my Product Library",
              "crm.objects.deals.sensitive.read.v2" : " ",
              "crm.objects.commercepayments.write" : "Write commerce payments",
              "crm.objects.contacts.sensitive.write.v2" : " ",
              "crm.objects.companies.highly_sensitive.read.v2" : "View company records (highly-sensitive)",
              "crm.objects.invoices.write" : "Write invoices",
              "crm.objects.companies.read" : " ",
              "crm.objects.users.write" : "Write User CRM objects",
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.services.read" : "Read services",
              "tickets.highly_sensitive.v2" : "Tickets (highly-sensitive)",
              "crm.objects.products.read" : "Read from my Product Library",
              "crm.objects.appointments.write" : "Write appointments",
              "e-commerce" : "e-commerce",
              "crm.objects.appointments.sensitive.read.v2" : "Read appointments (sensitive)",
              "crm.objects.goals.read" : "Read goals",
              "crm.objects.custom.highly_sensitive.write.v2" : "Change custom object records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.write.v2" : "Change company records (highly-sensitive)",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.contacts.read" : " ",
              "crm.objects.services.write" : "Write services",
              "crm.objects.appointments.read" : "Read appointments",
              "crm.objects.invoices.read" : "Read invoices objects",
              "crm.objects.subscriptions.write" : "Write to Commerce Subscriptions",
              "crm.objects.deals.highly_sensitive.read.v2" : "View deal records (highly-sensitive)",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.companies.write" : " ",
              "crm.objects.goals.write" : "Write goals",
              "crm.objects.custom.sensitive.write.v2" : "Change custom object records (sensitive)",
              "crm.objects.companies.sensitive.read.v2" : " ",
              "crm.objects.deals.write" : " ",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.listings.write" : "Write listings",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.deals.sensitive.write.v2" : " ",
              "crm.objects.contacts.sensitive.read.v2" : " ",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.companies.sensitive.write.v2" : " ",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.objects.commercepayments.read" : "Read the COMMERCE_PAYMENT object.",
              "crm.objects.courses.read" : "Read courses",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.courses.write" : "Write courses",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.appointments.sensitive.write.v2" : "Write appointments (sensitive)",
              "crm.objects.contacts.write" : " ",
              "crm.objects.custom.highly_sensitive.read.v2" : "View custom object records (highly-sensitive)",
              "crm.objects.partner-clients.write" : "Modify Partner Client CRM objects",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "tickets" : "Read and write tickets",
              "tickets.sensitive.v2" : "Tickets (sensitive)",
              "crm.objects.custom.sensitive.read.v2" : "View custom object records (sensitive)",
              "media_bridge.read" : "Read media and media events",
              "crm.objects.deals.read" : " ",
              "crm.objects.carts.write" : "Write cart",
              "crm.objects.listings.read" : "Read listings"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  }
}