{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Property Validations",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-api-use-case" : "View all contact properties with rules so you know how to format values when editing contact properties.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Property validations guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/property-validations"
    } ],
    "x-hubspot-introduction" : "Use the property validations API to view validation rules for a property's values."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Public_Property_Validations"
  } ],
  "paths" : {
    "/crm/v3/property-validations/{objectTypeId}" : {
      "get" : {
        "tags" : [ "Public_Property_Validations" ],
        "summary" : "Read all property validation rules for an object",
        "description" : "Read all properties with validation rules for a given object.",
        "operationId" : "get-/crm/v3/property-validations/{objectTypeId}",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.read" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "automation" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "automation" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "oauth2" : [ "crm.schemas.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    },
    "/crm/v3/property-validations/{objectTypeId}/{propertyName}" : {
      "get" : {
        "tags" : [ "Public_Property_Validations" ],
        "summary" : "Read validation rules for a property",
        "description" : "Read a property's validation rules identified by {propertyName}.",
        "operationId" : "get-/crm/v3/property-validations/{objectTypeId}/{propertyName}",
        "security" : [ {
          "private_apps" : [ "crm.objects.listings.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.listings.read" ]
        }, {
          "private_apps" : [ "crm.schemas.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "automation" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.schemas.courses.read" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.goals.write" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.pipelines.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.read" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "automation" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "oauth2" : [ "crm.schemas.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.write" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.appointments.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.schemas.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.custom.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.custom.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.listings.read" ]
        }, {
          "oauth2" : [ "crm.objects.courses.read" ]
        }, {
          "private_apps" : [ "crm.objects.courses.read" ]
        }, {
          "oauth2" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.pipelines.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.services.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.marketing_events.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.owners.read" : "View owner records",
              "crm.objects.deals.read" : "View deal records",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.services.read" : "Read services",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.listings.write" : "Write listings",
              "crm.objects.custom.read" : "View custom object records",
              "automation" : "Read from and write to my Workflows",
              "crm.objects.companies.write" : "View company records",
              "crm.objects.custom.sensitive.write.v2" : "Change custom object records (sensitive)",
              "crm.schemas.carts.read" : "Read cart property settings",
              "crm.objects.custom.highly_sensitive.write.v2" : "Change custom object records (highly-sensitive)",
              "crm.schemas.quotes.read" : "Quotes schemas",
              "crm.schemas.listings.read" : "Read listings property settings",
              "crm.objects.companies.read" : "Create or update company records",
              "crm.objects.appointments.sensitive.read.v2" : "Read appointments (sensitive)",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.objects.companies.sensitive.read.v2" : "View sensitive properties on company records",
              "media_bridge.read" : "Read media and media events",
              "crm.objects.deals.highly_sensitive.read.v2" : "View deal records (highly-sensitive)",
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.read.v2" : "View company records (highly-sensitive)",
              "crm.objects.commercepayments.write" : "Write commerce payments",
              "crm.objects.invoices.write" : "Write invoices",
              "crm.objects.contacts.sensitive.write.v2" : "Create or update sensitive properties on contact records",
              "crm.objects.custom.sensitive.read.v2" : "View custom object records (sensitive)",
              "crm.schemas.services.read" : "Read services property settings",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.schemas.line_items.read" : "Line Items schemas",
              "crm.objects.appointments.write" : "Write appointments",
              "crm.schemas.subscriptions.read" : "Read subscriptions schema",
              "crm.schemas.companies.read" : "View company property settings",
              "tickets" : "Read and write tickets",
              "crm.objects.products.write" : "Write to my Product Library",
              "crm.objects.feedback_submissions.read" : "View feedback survey submissions",
              "crm.objects.services.write" : "Write services",
              "crm.objects.subscriptions.write" : "Write to Commerce Subscriptions",
              "crm.objects.deals.sensitive.write.v2" : "Create or update sensitive properties on deal records",
              "crm.objects.contacts.read" : "View contact records",
              "crm.objects.appointments.sensitive.write.v2" : "Write appointments (sensitive)",
              "crm.objects.invoices.read" : "Read invoices objects",
              "crm.schemas.orders.read" : "Read order property settings",
              "crm.schemas.deals.read" : "View deals property settings",
              "crm.schemas.appointments.read" : "Read appointments property settings",
              "tickets.sensitive.v2" : "Tickets (sensitive)",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.deals.write" : "Create or update deal records",
              "e-commerce" : "e-commerce",
              "crm.objects.appointments.read" : "Read appointments",
              "crm.objects.companies.sensitive.write.v2" : "Create or update sensitive properties on company records",
              "crm.schemas.courses.read" : "Read courses property settings",
              "crm.objects.deals.highly_sensitive.write.v2" : "Change deal records (highly-sensitive)",
              "crm.objects.custom.highly_sensitive.read.v2" : "View custom object records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.write.v2" : "Change company records (highly-sensitive)",
              "crm.objects.goals.write" : "Write goals",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.contacts.write" : "Create or update contact records",
              "crm.objects.goals.read" : "Read goals",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.marketing_events.write" : "Write marketing events",
              "crm.objects.deals.sensitive.read.v2" : "View sensitive properties on deal records",
              "crm.schemas.contacts.read" : "View contacts property settings",
              "tickets.highly_sensitive.v2" : "Tickets (highly-sensitive)",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.schemas.custom.read" : "View custom object definitions",
              "crm.objects.carts.read" : "Read carts",
              "crm.schemas.invoices.read" : "Read invoices schema",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.courses.write" : "Write courses",
              "crm.objects.courses.read" : "Read courses",
              "timeline" : "Create timeline events",
              "crm.objects.listings.read" : "Read listings",
              "crm.schemas.commercepayments.read" : "Read the COMMERCE_PAYMENT properties.",
              "crm.pipelines.orders.read" : "View details about your cart pipelines including pipeline stage information",
              "crm.objects.marketing_events.read" : "Read marketing events",
              "crm.objects.contacts.sensitive.read.v2" : "View sensitive properties on contact records"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE"
  }
}