{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Marketing Campaigns Public Api",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "PROFESSIONAL",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Assets"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Budget"
  }, {
    "name" : "Metrics"
  }, {
    "name" : "Spend"
  } ],
  "paths" : {
    "/marketing/campaigns/2026-03" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve campaigns",
        "description" : "Retrieve a paginated list of campaigns from your HubSpot account. This endpoint allows you to specify sorting, pagination, and filtering options to tailor the results to your needs.",
        "operationId" : "get-/marketing/campaigns/2026-03_/marketing/campaigns/v3",
        "security" : [ {
          "app_cookie" : [ "campaigns-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-access" ]
        }, {
          "oauth2" : [ "campaigns-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a campaign",
        "description" : "Create a campaign with the specified properties and receive a copy of the campaign object, including its ID. Note that the 'hs_goal' property is deprecated and will be ignored if provided.",
        "operationId" : "post-/marketing/campaigns/2026-03_/marketing/campaigns/v3",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/marketing/campaigns/2026-03/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Delete a batch of campaigns",
        "description" : "This endpoint deletes a batch of campaigns. \nThe maximum number of items in a batch request is 50.\nThe response will always be 204 No Content, regardless of whether the campaigns exist or not, whether they were successfully deleted or not, or if only some of the campaigns in the batch were deleted.",
        "operationId" : "post-/marketing/campaigns/2026-03/batch/archive",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/marketing/campaigns/2026-03/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of campaigns",
        "description" : "This endpoint creates a batch of campaigns. The maximum number of items in a batch request is 50.\nThe campaigns in the response are not guaranteed to be in the same order as they were provided in the request.",
        "operationId" : "post-/marketing/campaigns/2026-03/batch/create",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/marketing/campaigns/2026-03/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of campaigns",
        "description" : "This endpoint reads a batch of campaigns based on the provided input data and returns the campaigns along with their associated assets. \nThe maximum number of items in a batch request is 50.\nThe campaigns in the response are not guaranteed to be in the same order as they were provided in the request.\nIf duplicate campaign IDs are provided in the request, duplicates will be ignored. The response will include only unique IDs and will be returned without duplicates.\n",
        "operationId" : "post-/marketing/campaigns/2026-03/batch/read",
        "security" : [ {
          "app_cookie" : [ "campaigns-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-access" ]
        }, {
          "oauth2" : [ "campaigns-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/marketing/campaigns/2026-03/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update a batch of campaigns",
        "description" : "This endpoint updates a batch of campaigns based on the provided input data.\nThe maximum number of items in a batch request is 50.\nIf an empty string (\"\") is passed for any property in the Batch Update, it will reset that property's value.",
        "operationId" : "post-/marketing/campaigns/2026-03/batch/update",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/marketing/campaigns/2026-03/{campaignGuid}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read a campaign",
        "description" : "Get a campaign identified by a specific campaignGuid with the given properties. Along with the campaign information, it also returns information about assets. Depending on the query parameters used, this can also be used to return information about the corresponding assets' metrics. Metrics are available only if startDate and endDate are provided.",
        "operationId" : "get-/marketing/campaigns/2026-03/{campaignGuid}",
        "security" : [ {
          "app_cookie" : [ "campaigns-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-access" ]
        }, {
          "oauth2" : [ "campaigns-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete campaign ",
        "description" : "Delete a specified campaign from the system.\nThis call will return a 204 No Content response regardless of whether the campaignGuid provided corresponds to an existing campaign or not.",
        "operationId" : "delete-/marketing/campaigns/2026-03/{campaignGuid}",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update campaign",
        "description" : "Perform a partial update of a campaign identified by the specified campaignGuid. Provided property values will be overwritten. Read-only and non-existent properties will cause 400 error.\nIf an empty string is passed for any property in the Batch Update, it will reset that property's value.\n",
        "operationId" : "patch-/marketing/campaigns/2026-03/{campaignGuid}",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/marketing/campaigns/2026-03/{campaignGuid}/assets/{assetType}" : {
      "get" : {
        "tags" : [ "Assets" ],
        "summary" : "List assets",
        "description" : "This endpoint lists all assets of the campaign by asset type. The assetType parameter is required, and each request can only fetch assets of a single type.\nAsset metrics can also be fetched along with the assets; they are available only if start and end dates are provided.",
        "operationId" : "get-/marketing/campaigns/2026-03/{campaignGuid}/assets/{assetType}",
        "security" : [ {
          "app_cookie" : [ "campaigns-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-access" ]
        }, {
          "oauth2" : [ "campaigns-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/marketing/campaigns/2026-03/{campaignGuid}/assets/{assetType}/{assetId}" : {
      "put" : {
        "tags" : [ "Assets" ],
        "summary" : "Add asset association",
        "description" : "Associate a specified asset with a campaign. Using the API, you can create associations for the following asset types: ads, blog posts, calls, case studies, CTAs, CTAs (legacy), external website pages, feedback surveys, forms, files, knowledge base articles, landing pages, marketing email, marketing events, meetings, playbooks, podcast episodes, sales documents, sales emails, sequences, SMS, social posts, static lists, videos, website pages, and workflows.\n\nFor other a[...]",
        "operationId" : "put-/marketing/campaigns/2026-03/{campaignGuid}/assets/{assetType}/{assetId}",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Assets" ],
        "summary" : "Remove asset association",
        "description" : "Disassociate a specified asset from a campaign. Using the API, you can remove associations for the following asset types: ads, blog posts, calls, case studies, CTAs, CTAs (legacy), external website pages, feedback surveys, forms, files, knowledge base articles, landing pages, marketing email, marketing events, meetings, playbooks, podcast episodes, sales documents, sales emails, sequences, SMS, social posts, static lists, videos, website pages, and workflows.\n\nFor othe[...]",
        "operationId" : "delete-/marketing/campaigns/2026-03/{campaignGuid}/assets/{assetType}/{assetId}",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/marketing/campaigns/2026-03/{campaignGuid}/budget" : {
      "post" : {
        "tags" : [ "Budget" ],
        "summary" : "Add budget item",
        "description" : "Add a new budget item to the campaign",
        "operationId" : "post-/marketing/campaigns/2026-03/{campaignGuid}/budget",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/marketing/campaigns/2026-03/{campaignGuid}/budget/totals" : {
      "get" : {
        "tags" : [ "Budget" ],
        "summary" : "Read budget",
        "description" : "Retrieve detailed information about the budget and spend items for a specified campaign, including the total budget, total spend, and remaining budget.\nBudget and Spend items may be returned in any order, but the order field specifies their sequence based on the creation date. The item with order 0 is the oldest, and items with higher order values are newer",
        "operationId" : "get-/marketing/campaigns/2026-03/{campaignGuid}/budget/totals",
        "security" : [ {
          "app_cookie" : [ "campaigns-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-access" ]
        }, {
          "oauth2" : [ "campaigns-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/marketing/campaigns/2026-03/{campaignGuid}/budget/{budgetId}" : {
      "get" : {
        "tags" : [ "Budget" ],
        "summary" : "Get budget item",
        "description" : "Get a specific budget item by ID",
        "operationId" : "get-/marketing/campaigns/2026-03/{campaignGuid}/budget/{budgetId}",
        "security" : [ {
          "app_cookie" : [ "campaigns-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-access" ]
        }, {
          "oauth2" : [ "campaigns-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "put" : {
        "tags" : [ "Budget" ],
        "summary" : "Update budget item",
        "description" : "Update a specific budget item by ID",
        "operationId" : "put-/marketing/campaigns/2026-03/{campaignGuid}/budget/{budgetId}",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Budget" ],
        "summary" : "Delete budget item",
        "description" : "Delete a specific budget item by ID",
        "operationId" : "delete-/marketing/campaigns/2026-03/{campaignGuid}/budget/{budgetId}",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/marketing/campaigns/2026-03/{campaignGuid}/reports/contacts/{contactType}" : {
      "get" : {
        "tags" : [ "Metrics" ],
        "summary" : "Fetch contact IDs",
        "description" : "Fetch the list of contact IDs for the specified campaign and contact type",
        "operationId" : "get-/marketing/campaigns/2026-03/{campaignGuid}/reports/contacts/{contactType}",
        "security" : [ {
          "app_cookie" : [ "campaigns-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-access" ]
        }, {
          "oauth2" : [ "campaigns-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/marketing/campaigns/2026-03/{campaignGuid}/reports/metrics" : {
      "get" : {
        "tags" : [ "Metrics" ],
        "summary" : "Get Campaign Metrics\n",
        "description" : "This endpoint retrieves key attribution metrics for a specified campaign, such as sessions, new contacts, and influenced contacts.",
        "operationId" : "get-/marketing/campaigns/2026-03/{campaignGuid}/reports/metrics",
        "security" : [ {
          "app_cookie" : [ "campaigns-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-access" ]
        }, {
          "oauth2" : [ "campaigns-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/marketing/campaigns/2026-03/{campaignGuid}/reports/revenue" : {
      "get" : {
        "tags" : [ "Metrics" ],
        "summary" : "Fetch revenue",
        "description" : "Fetch revenue attribution report data for a specified campaign\n",
        "operationId" : "get-/marketing/campaigns/2026-03/{campaignGuid}/reports/revenue",
        "security" : [ {
          "app_cookie" : [ "campaigns-revenue-pro", "revenue-attribution-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-revenue-pro", "revenue-attribution-read" ]
        }, {
          "oauth2" : [ "campaigns-revenue-pro", "revenue-attribution-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/marketing/campaigns/2026-03/{campaignGuid}/spend" : {
      "post" : {
        "tags" : [ "Spend" ],
        "summary" : "Create campaign spend item",
        "description" : "Create a new campaign spend item",
        "operationId" : "post-/marketing/campaigns/2026-03/{campaignGuid}/spend",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/marketing/campaigns/2026-03/{campaignGuid}/spend/{spendId}" : {
      "get" : {
        "tags" : [ "Spend" ],
        "summary" : "Read campaign spend item",
        "description" : "Read a campaign spend item by its spendId",
        "operationId" : "get-/marketing/campaigns/2026-03/{campaignGuid}/spend/{spendId}",
        "security" : [ {
          "app_cookie" : [ "campaigns-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-access" ]
        }, {
          "oauth2" : [ "campaigns-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "put" : {
        "tags" : [ "Spend" ],
        "summary" : "Update campaign spend item",
        "description" : "Update a specific campaign spend item by ID",
        "operationId" : "put-/marketing/campaigns/2026-03/{campaignGuid}/spend/{spendId}",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Spend" ],
        "summary" : "Delete campaign spend item",
        "description" : "Delete a specific campaign spend item by ID",
        "operationId" : "delete-/marketing/campaigns/2026-03/{campaignGuid}/spend/{spendId}",
        "security" : [ {
          "app_cookie" : [ "campaigns-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "campaigns-write" ]
        }, {
          "oauth2" : [ "campaigns-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token"
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "PROFESSIONAL",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}