{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Scheduler Meetings",
    "description" : "Meetings Service For HubSpot Sales",
    "version" : "2027-03-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  } ],
  "paths" : {
    "/scheduler/2027-03-beta/meetings/calendar" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create Meeting",
        "description" : "Create a new calendar meeting event in the HubSpot system. This endpoint allows you to schedule meetings by providing necessary details such as meeting title, start and end times, and associated user information. It is essential for organizing meetings and managing schedules within the HubSpot platform.",
        "operationId" : "post-/scheduler/2027-03-beta/meetings/calendar_/scheduler/2026-09-beta/meetings/calendar",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "meetings-write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/scheduler/2027-03-beta/meetings/meeting-links" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List meeting links",
        "description" : "Retrieve a list of meeting links available in your HubSpot account. This endpoint allows you to filter the results by various criteria such as the organizer's user ID, meeting type, and name. It supports pagination to help manage large sets of data.",
        "operationId" : "get-/scheduler/2027-03-beta/meetings/meeting-links_/scheduler/2026-09-beta/meetings/meeting-links",
        "security" : [ {
          "oauth2" : [ "scheduler.meetings.meeting-link.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/scheduler/2027-03-beta/meetings/meeting-links/book" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Book Meeting",
        "description" : "Book a meeting using a meeting link in your HubSpot account. This endpoint allows you to specify details such as the meeting duration, start time, and participant information. It is useful for scheduling meetings with external participants through a predefined meeting link.",
        "operationId" : "post-/scheduler/2027-03-beta/meetings/meeting-links/book_/scheduler/2026-09-beta/meetings/meeting-links/book",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "meetings-write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/scheduler/2027-03-beta/meetings/meeting-links/book/availability-page/{slug}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve availability",
        "description" : "Retrieve the availability and busy times for a specific meeting link using its slug. This endpoint provides information about when meetings can be scheduled, taking into account the specified timezone and any month offset. It is useful for determining available time slots for booking meetings.",
        "operationId" : "get-/scheduler/2027-03-beta/meetings/meeting-links/book/availability-page/{slug}_/scheduler/2026-09-beta/meetings/meeting-links/book/availability-page/{slug}",
        "security" : [ {
          "oauth2" : [ "scheduler.meetings.meeting-link.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/scheduler/2027-03-beta/meetings/meeting-links/book/{slug}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve booking info",
        "description" : "Retrieve information about a specific meeting booking using a unique slug identifier. This endpoint provides details such as availability and busy times for the meeting link. It is useful for checking the status and details of a meeting link before booking.",
        "operationId" : "get-/scheduler/2027-03-beta/meetings/meeting-links/book/{slug}_/scheduler/2026-09-beta/meetings/meeting-links/book/{slug}",
        "security" : [ {
          "oauth2" : [ "scheduler.meetings.meeting-link.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/scheduler/2027-03-beta/meetings/meeting-links/{meetingLinkSlug}" : {
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update meeting link",
        "description" : "Update the details of a specific meeting link using its unique slug. This operation allows you to modify the settings or metadata associated with a meeting link in your HubSpot account.",
        "operationId" : "patch-/scheduler/2027-03-beta/meetings/meeting-links/{meetingLinkSlug}_/scheduler/2026-09-beta/meetings/meeting-links/{meetingLinkSlug}",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.write" ]
        }, {
          "oauth2" : [ "crm.objects.goals.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.products.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.services.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.listings.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.courses.write" ]
        }, {
          "oauth2" : [ "crm.objects.appointments.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.projects.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "meetings-write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.contacts.sensitive.write.v2" : "",
              "meetings-write" : "",
              "scheduler.meetings.meeting-link.read" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}