{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Analytics Reporting",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2027-03-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Dashboards"
  }, {
    "name" : "Reports"
  } ],
  "paths" : {
    "/analytics/reporting/2027-03-beta/dashboards" : {
      "get" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Search dashboards",
        "description" : "Searches for and returns pages of dashboards using a variety of filters. Search is eventually-consistent; changes to dashboards may take a few seconds to reflect in search results.\n\nAlso supports retrieving pages of archived dashboards; however, the following restrictions apply: only the `limit` and `after` parameters are respected, all others are ignored; archived dashboard retrieval does not support filtering, custom sorting, or property projection. Results are alway[...]",
        "operationId" : "get-/analytics/reporting/2027-03-beta/dashboards",
        "security" : [ {
          "oauth2" : [ "reporting.full.read" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        }, {
          "oauth2" : [ "crm.hubsql.execute" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "post" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Create dashboard",
        "description" : "Creates a new dashboard. Existing reports can optionally be attached to the dashboard at creation time; report widgets will be appended sequentially.\n\nAttaching reports to the dashboard is done on a best-effort basis, and it's possible that some or all reports may fail to be attached. The dashboard will still be created, and no error will be returned. The requestor should check the `widgets` field in the response object to see which reports were successfully attached."[...]",
        "operationId" : "post-/analytics/reporting/2027-03-beta/dashboards",
        "security" : [ {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/dashboards/batch/archive" : {
      "post" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Batch archive dashboards",
        "description" : "Archives one or more dashboards. Already-archived dashboards are silently ignored. The maximum batch size is 500.\n\nIf any of the requested items fail, the response code will be `207 Multi-Status` and the response will include details of individual failures.\n\nArchived dashboards are purged after 90 days.",
        "operationId" : "post-/analytics/reporting/2027-03-beta/dashboards/batch/archive",
        "security" : [ {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/dashboards/batch/restore" : {
      "post" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Batch restore dashboards",
        "description" : "Restores one or more archived dashboards. Already-active dashboards are silently ignored. The maximum batch size is 500.\n\nIf any of the requested items fail, the response code will be `207 Multi-Status` and the response will include details of individual failures.",
        "operationId" : "post-/analytics/reporting/2027-03-beta/dashboards/batch/restore_/analytics/reporting/2027-03-beta/dashboards/batch/restore",
        "security" : [ {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/dashboards/owners/batch/update" : {
      "post" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Batch update dashboard owners",
        "description" : "Updates the owner of one or more dashboards. The maximum batch size is 500.\n\nIf any of the requested items fail, the response code will be `207 Multi-Status` and the response will include details of individual failures.",
        "operationId" : "post-/analytics/reporting/2027-03-beta/dashboards/owners/batch/update_/analytics/reporting/2027-03-beta/dashboards/owners/batch/update",
        "security" : [ {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/dashboards/permissions/batch/update" : {
      "post" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Batch update dashboard permissions",
        "description" : "Updates the permissions for one or more dashboards. The maximum batch size is 500.\n\nIf any of the requested items fail, the response code will be `207 Multi-Status` and the response will include details of individual failures.",
        "operationId" : "post-/analytics/reporting/2027-03-beta/dashboards/permissions/batch/update_/analytics/reporting/2027-03-beta/dashboards/permissions/batch/update",
        "security" : [ {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/dashboards/{dashboardId}" : {
      "get" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Get dashboard",
        "description" : "Retrieves a single dashboard.\n\nAlso supports retrieving archived dashboards via the `archived` query parameter. Retrieving archived dashboards requires the requesting user to be the dashboard owner, a reporting admin, or a super admin.",
        "operationId" : "get-/analytics/reporting/2027-03-beta/dashboards/{dashboardId}",
        "security" : [ {
          "oauth2" : [ "reporting.full.read" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        }, {
          "oauth2" : [ "crm.hubsql.execute" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "patch" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Update dashboard",
        "description" : "Partially updates a dashboard. All fields in the request are optional; only the fields which are present will be updated.\n\nCan also be used to archive or restore a dashboard using the `archived` field. When `archived` is present in a request, it must be the only field present, or it will result in an error. Archived dashboards are purged after 90 days.",
        "operationId" : "patch-/analytics/reporting/2027-03-beta/dashboards/{dashboardId}_/analytics/reporting/2027-03-beta/dashboards/{dashboardId}",
        "security" : [ {
          "oauth2" : [ "reporting.full.edit" ]
        }, {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/dashboards/{dashboardId}/batch/widgets" : {
      "post" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Batch add reports to dashboard",
        "description" : "Adds one or more reports to a dashboard. Report widgets are appended to the end of the existing dashboard layout. Any reports which are already on the dashboard, don't exist, or the requesting user doesn't have permissions for are skipped. Check the dashboard in the response to determine which reports were successfully added.\n\nDashboards cannot have more than 50 reports on them; attempting to add beyond that limit will fail.",
        "operationId" : "post-/analytics/reporting/2027-03-beta/dashboards/{dashboardId}/batch/widgets",
        "security" : [ {
          "oauth2" : [ "reporting.full.edit" ]
        }, {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/dashboards/{dashboardId}/clone" : {
      "post" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Clone dashboard",
        "description" : "Clones an existing dashboard. The cloned dashboard may either retain references to the reports on the original dashboard, or clone the original's reports and reference the clones.",
        "operationId" : "post-/analytics/reporting/2027-03-beta/dashboards/{dashboardId}/clone",
        "security" : [ {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/dashboards/{dashboardId}/export" : {
      "post" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Export dashboard",
        "description" : "Exports a dashboard's content to one or more HubSpot users via standard HubSpot communication channels (notably, email).\n\nStatus tracking is not available; a successful request will result in a `204 No Content` response.\n\nAny set of HubSpot users can be specified as the recipients. However, if a given user does not have access to reporting, does not have CRM export permissions, etc., then they will receive a notification with an error rather than a successful export.[...]",
        "operationId" : "post-/analytics/reporting/2027-03-beta/dashboards/{dashboardId}/export",
        "security" : [ {
          "oauth2" : [ "reporting.full.read" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        }, {
          "oauth2" : [ "crm.hubsql.execute" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/dashboards/{dashboardId}/widgets/{reportId}" : {
      "put" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Add report to dashboard",
        "description" : "Adds a single report to a dashboard. The report widget is appended to the end of the existing dashboard layout. If the report is already on the dashboard, does not exist, or the requesting user doesn't have permission to access it, does nothing. Check the dashboard in the response to determine whether the report was successfully added.\n\nDashboards cannot have more than 50 reports on them; attempting to add beyond that limit will fail.",
        "operationId" : "put-/analytics/reporting/2027-03-beta/dashboards/{dashboardId}/widgets/{reportId}",
        "security" : [ {
          "oauth2" : [ "reporting.full.edit" ]
        }, {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "delete" : {
        "tags" : [ "Dashboards" ],
        "summary" : "Remove report from dashboard",
        "description" : "Removes a single report from a dashboard.",
        "operationId" : "delete-/analytics/reporting/2027-03-beta/dashboards/{dashboardId}/widgets/{reportId}",
        "security" : [ {
          "oauth2" : [ "reporting.full.edit" ]
        }, {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/reports" : {
      "get" : {
        "tags" : [ "Reports" ],
        "summary" : "Search reports",
        "description" : "Searches for and returns pages of reports using a variety of filters. Search is eventually-consistent; changes to dashboards may take a few seconds to reflect in search results.\n\nAlso supports retrieving pages of archived reports; however, the following restrictions apply: only the `limit` and `after` parameters are respected, all others are ignored; archived report retrieval does not support filtering, custom sorting, or property projection. Results are always returne[...]",
        "operationId" : "get-/analytics/reporting/2027-03-beta/reports",
        "security" : [ {
          "oauth2" : [ "reporting.full.read" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        }, {
          "oauth2" : [ "crm.hubsql.execute" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/reports/batch/archive" : {
      "post" : {
        "tags" : [ "Reports" ],
        "summary" : "Batch archive reports",
        "description" : "Archives one or more reports. Already-archived reports are silently ignored. The maximum batch size is 500.\n\nIf any of the requested items fail, the response code will be `207 Multi-Status` and the response will include details of individual failures.\n\nArchived reports are purged after 90 days.",
        "operationId" : "post-/analytics/reporting/2027-03-beta/reports/batch/archive",
        "security" : [ {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/reports/batch/restore" : {
      "post" : {
        "tags" : [ "Reports" ],
        "summary" : "Batch restore reports",
        "description" : "Restores one or more archived reports. Already-active reports are silently ignored. The maximum batch size is 500.\n\nIf any of the requested items fail, the response code will be `207 Multi-Status` and the response will include details of individual failures.",
        "operationId" : "post-/analytics/reporting/2027-03-beta/reports/batch/restore_/analytics/reporting/2027-03-beta/reports/batch/restore",
        "security" : [ {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/reports/owners/batch/update" : {
      "post" : {
        "tags" : [ "Reports" ],
        "summary" : "Batch update report owners",
        "description" : "Updates the owner of one or more reports. The maximum batch size is 500.\n\nIf any of the requested items fail, the response code will be `207 Multi-Status` and the response will include details of individual failures.",
        "operationId" : "post-/analytics/reporting/2027-03-beta/reports/owners/batch/update_/analytics/reporting/2027-03-beta/reports/owners/batch/update",
        "security" : [ {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/reports/permissions/batch/update" : {
      "post" : {
        "tags" : [ "Reports" ],
        "summary" : "Batch update report permissions",
        "description" : "Updates the permissions for one or more reports. The maximum batch size is 500.\n\nIf any of the requested items fail, the response code will be `207 Multi-Status` and the response will include details of individual failures.\n\nNote that reports on any dashboards cannot have their permissions updated; they inherit the dashboards' permissions. Attempting to update them will result in an error.",
        "operationId" : "post-/analytics/reporting/2027-03-beta/reports/permissions/batch/update_/analytics/reporting/2027-03-beta/reports/permissions/batch/update",
        "security" : [ {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/reports/{reportId}" : {
      "get" : {
        "tags" : [ "Reports" ],
        "summary" : "Get report",
        "description" : "Retrieves a single report.\n\nAlso supports retrieving archived reports via the `archived` query parameter. Retrieving archived reports requires the requesting user to be the report owner, a reporting admin, or a super admin.",
        "operationId" : "get-/analytics/reporting/2027-03-beta/reports/{reportId}",
        "security" : [ {
          "oauth2" : [ "reporting.full.read" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        }, {
          "oauth2" : [ "crm.hubsql.execute" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      },
      "patch" : {
        "tags" : [ "Reports" ],
        "summary" : "Update report",
        "description" : "Partially updates a report. All fields in the request are optional; only the fields which are present will be updated.\n\nCan also be used to archive or restore a report using the `archived` field. When `archived` is present in a request, it must be the only field present, or it will result in an error. Archived reports are purged after 90 days.\n\nNote that reports on any dashboards cannot have their permissions updated; they inherit the dashboards' permissions. Attempt[...]",
        "operationId" : "patch-/analytics/reporting/2027-03-beta/reports/{reportId}_/analytics/reporting/2027-03-beta/reports/{reportId}",
        "security" : [ {
          "oauth2" : [ "reporting.full.edit" ]
        }, {
          "oauth2" : [ "reporting.full.write" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    },
    "/analytics/reporting/2027-03-beta/reports/{reportId}/export" : {
      "post" : {
        "tags" : [ "Reports" ],
        "summary" : "Export report",
        "description" : "Exports a report to one or more HubSpot users via standard HubSpot communication channels (notably, email).\n\nStatus tracking is not available; a successful request will result in a `204 No Content` response.\n\nAny set of HubSpot users can be specified as the recipients. However, if a given user does not have access to reporting, does not have CRM export permissions, etc., then they will receive a notification with an error rather than a successful export.\n\n**NOTE: T[...]",
        "operationId" : "post-/analytics/reporting/2027-03-beta/reports/{reportId}/export",
        "security" : [ {
          "oauth2" : [ "reporting.full.read" ]
        }, {
          "oauth2" : [ "reporting.full.admin" ]
        }, {
          "oauth2" : [ "crm.hubsql.execute" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : false
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.hubsql.execute" : "",
              "reporting.full.admin" : "",
              "reporting.full.edit" : "",
              "reporting.full.read" : "",
              "reporting.full.write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}