{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Files Files",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Files"
  }, {
    "name" : "Folders"
  } ],
  "paths" : {
    "/files/2026-03/files" : {
      "post" : {
        "tags" : [ "Files" ],
        "summary" : "Upload file",
        "description" : "Upload a single file with content specified in request body.",
        "operationId" : "post-/files/2026-03/files",
        "security" : [ {
          "app_cookie" : [ "file-manager-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-write" ]
        }, {
          "oauth2" : [ "file-manager-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/files/import-from-url/async" : {
      "post" : {
        "tags" : [ "Files" ],
        "summary" : "Import file from URL",
        "description" : "Asynchronously imports the file at the given URL into the file manager.",
        "operationId" : "post-/files/2026-03/files/import-from-url/async",
        "security" : [ {
          "app_cookie" : [ "file-manager-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-write" ]
        }, {
          "oauth2" : [ "file-manager-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/files/import-from-url/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Files" ],
        "summary" : "Check import status",
        "description" : "Check the status of requested import.",
        "operationId" : "get-/files/2026-03/files/import-from-url/async/tasks/{taskId}/status",
        "security" : [ {
          "app_cookie" : [ "file-manager-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-access" ]
        }, {
          "oauth2" : [ "file-manager-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/files/search" : {
      "get" : {
        "tags" : [ "Files" ],
        "summary" : "Search files",
        "description" : "Search through files in the file manager. Does not display hidden or archived files.",
        "operationId" : "get-/files/2026-03/files/search",
        "security" : [ {
          "app_cookie" : [ "file-manager-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-access" ]
        }, {
          "oauth2" : [ "file-manager-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/files/stat/{path}" : {
      "get" : {
        "tags" : [ "Files" ],
        "summary" : "Retrieve file by path",
        "description" : "Retrieve a file by its path.",
        "operationId" : "get-/files/2026-03/files/stat/{path}",
        "security" : [ {
          "app_cookie" : [ "file-manager-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-access" ]
        }, {
          "oauth2" : [ "file-manager-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/files/{fileId}" : {
      "get" : {
        "tags" : [ "Files" ],
        "summary" : "Retrieve file by ID",
        "description" : "Retrieve a file by its ID.",
        "operationId" : "get-/files/2026-03/files/{fileId}",
        "security" : [ {
          "app_cookie" : [ "file-manager-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-access" ]
        }, {
          "oauth2" : [ "file-manager-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "put" : {
        "tags" : [ "Files" ],
        "summary" : "Replace file",
        "description" : "Replace existing file data with new file data. Can be used to change image content without having to upload a new file and update all references.",
        "operationId" : "put-/files/2026-03/files/{fileId}",
        "security" : [ {
          "app_cookie" : [ "file-manager-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-write" ]
        }, {
          "oauth2" : [ "file-manager-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Files" ],
        "summary" : "Delete file by ID",
        "description" : "Delete a file by ID",
        "operationId" : "delete-/files/2026-03/files/{fileId}",
        "security" : [ {
          "app_cookie" : [ "file-manager-delete" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-delete" ]
        }, {
          "oauth2" : [ "file-manager-delete" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Files" ],
        "summary" : "Update file properties",
        "description" : "Update properties of file by ID.",
        "operationId" : "patch-/files/2026-03/files/{fileId}",
        "security" : [ {
          "app_cookie" : [ "file-manager-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-write" ]
        }, {
          "oauth2" : [ "file-manager-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/files/{fileId}/gdpr-delete" : {
      "delete" : {
        "tags" : [ "Files" ],
        "summary" : "GDPR-delete file",
        "description" : "Delete a file in accordance with GDPR regulations.",
        "operationId" : "delete-/files/2026-03/files/{fileId}/gdpr-delete",
        "security" : [ {
          "app_cookie" : [ "file-manager-delete" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-delete" ]
        }, {
          "oauth2" : [ "file-manager-delete" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/files/{fileId}/signed-url" : {
      "get" : {
        "tags" : [ "Files" ],
        "summary" : "Get signed URL to access private file",
        "description" : "Generates signed URL that allows temporary access to a private file.",
        "operationId" : "get-/files/2026-03/files/{fileId}/signed-url",
        "security" : [ {
          "app_cookie" : [ "file-manager-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-access" ]
        }, {
          "oauth2" : [ "file-manager-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/folders" : {
      "post" : {
        "tags" : [ "Files" ],
        "summary" : "Create folder",
        "description" : "Creates a folder.",
        "operationId" : "post-/files/2026-03/folders",
        "security" : [ {
          "app_cookie" : [ "file-manager-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-write" ]
        }, {
          "oauth2" : [ "file-manager-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/folders/search" : {
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Search folders",
        "description" : "Search for folders. Does not contain hidden or archived folders.",
        "operationId" : "get-/files/2026-03/folders/search",
        "security" : [ {
          "app_cookie" : [ "file-manager-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-access" ]
        }, {
          "oauth2" : [ "file-manager-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/folders/update/async" : {
      "post" : {
        "tags" : [ "Folders" ],
        "summary" : "Update folder properties",
        "description" : "Update properties of folder by given ID. This action happens asynchronously and will update all of the folder's children as well.",
        "operationId" : "post-/files/2026-03/folders/update/async",
        "security" : [ {
          "app_cookie" : [ "file-manager-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-write" ]
        }, {
          "oauth2" : [ "file-manager-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/folders/update/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Check folder update status",
        "description" : "Check status of folder update. Folder updates happen asynchronously.",
        "operationId" : "get-/files/2026-03/folders/update/async/tasks/{taskId}/status",
        "security" : [ {
          "app_cookie" : [ "file-manager-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-write" ]
        }, {
          "oauth2" : [ "file-manager-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/folders/{folderId}" : {
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Retrieve folder by ID",
        "description" : "Retrieve a folder by its ID.",
        "operationId" : "get-/files/2026-03/folders/{folderId}",
        "security" : [ {
          "app_cookie" : [ "file-manager-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-access" ]
        }, {
          "oauth2" : [ "file-manager-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Folders" ],
        "summary" : "Delete folder by ID",
        "description" : "Delete folder by ID.",
        "operationId" : "delete-/files/2026-03/folders/{folderId}",
        "security" : [ {
          "app_cookie" : [ "file-manager-delete" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-delete" ]
        }, {
          "oauth2" : [ "file-manager-delete" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Folders" ],
        "summary" : "Update folder properties by folder ID",
        "description" : "Update a folder's properties, identified by folder ID.",
        "operationId" : "patch-/files/2026-03/folders/{folderId}",
        "security" : [ {
          "app_cookie" : [ "file-manager-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-write" ]
        }, {
          "oauth2" : [ "file-manager-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/files/2026-03/folders/{folderPath}" : {
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Retrieve folder by path",
        "description" : "Retrieve a folder, identified by its path.",
        "operationId" : "get-/files/2026-03/folders/{folderPath}",
        "security" : [ {
          "app_cookie" : [ "file-manager-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-access" ]
        }, {
          "oauth2" : [ "file-manager-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Folders" ],
        "summary" : "Delete folder by path",
        "description" : "Delete a folder, identified by its path.",
        "operationId" : "delete-/files/2026-03/folders/{folderPath}",
        "security" : [ {
          "app_cookie" : [ "file-manager-delete" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "file-manager-delete" ]
        }, {
          "oauth2" : [ "file-manager-delete" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "subscription-status-batch-read" : "",
              "subscription-status-batch-write" : "",
              "subscriptions-definition-read" : "",
              "subscriptions-status-read" : "",
              "subscriptions-status-write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}