{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Timeline",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "After setting up a new set of sign-up flows on your website, update contact timelines to indicate which flow they completed. In each event, you could also include a link to open an iframe that displays additional external data about the event.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Timeline Events Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/extensions/timeline"
    } ],
    "x-hubspot-introduction" : "Use the timeline events API to add custom event information to CRM record timelines. You'll first need to create a public app, then an event template to display event data. "
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  } ],
  "paths" : {
    "/integrators/timeline/v3/events" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Send event data (single)",
        "description" : "Send a single instance of event data to a specified event type.",
        "operationId" : "post-/integrators/timeline/v3/events_create",
        "deprecated" : true,
        "security" : [ {
          "oauth2" : [ "companies-write", "contacts-write", "deals-write", "tickets-write", "timeline-write" ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/integrators/timeline/v3/events/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create multiple events",
        "description" : "Batch create multiple instances of timeline events based on an event template. Once created, these event are immutable on the object timeline and cannot be modified. If the event template was configured to update object properties via `objectPropertyName`, this call will also attempt to updates those properties, or add them if they don't exist.",
        "operationId" : "post-/integrators/timeline/v3/events/batch/create_createBatch",
        "deprecated" : true,
        "security" : [ {
          "oauth2" : [ "companies-write", "contacts-write", "deals-write", "tickets-write", "timeline-write" ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/integrators/timeline/v3/events/{eventTemplateId}/{eventId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get an event instance",
        "description" : "Retrieve an event instance, specified by template ID and event ID.",
        "operationId" : "get-/integrators/timeline/v3/events/{eventTemplateId}/{eventId}_getById",
        "deprecated" : true,
        "security" : [ {
          "oauth2" : [ "companies-read", "contacts-read", "deals-read", "tickets-read", "timeline-read" ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/integrators/timeline/v3/{appId}/event-templates" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get all event templates",
        "description" : "Retrieve all templates defined for an app.",
        "operationId" : "get-/integrators/timeline/v3/{appId}/event-templates_getAll",
        "deprecated" : true,
        "security" : [ {
          "app_cookie" : [ "developers-read" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-read" ]
        }, {
          "oauth2" : [ "developers-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create an event template",
        "description" : "Event templates define the general structure for a custom timeline event, and enable you to send event data to HubSpot. A template includes formatted copy for its heading and details, as well as any custom property definitions. A single app can include up to 750 event templates.<br/><Warning>the `v1` and `v3` timeline events APIs are only available for app partners with existing `v1`/`v3` timeline events defined in their public app. <ul><li>If your app doesn't include an[...]",
        "operationId" : "post-/integrators/timeline/v3/{appId}/event-templates_create",
        "deprecated" : true,
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Get an event template",
        "description" : "Retrieve an event type template by ID.",
        "operationId" : "get-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}_getById",
        "deprecated" : true,
        "security" : [ {
          "app_cookie" : [ "developers-read" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-read" ]
        }, {
          "oauth2" : [ "developers-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update an event template",
        "description" : "Update an existing event template, specified by ID.",
        "operationId" : "put-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}_update",
        "deprecated" : true,
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete an event template",
        "description" : "Delete an event type template by ID.",
        "operationId" : "delete-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}_archive",
        "deprecated" : true,
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Add tokens to an existing template",
        "description" : "Update an existing event type template with new tokens.",
        "operationId" : "post-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens_create",
        "deprecated" : true,
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update a template token",
        "description" : "Update an event type template token, specified by token name.",
        "operationId" : "put-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}_update",
        "deprecated" : true,
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete a template token",
        "description" : "Delete an existing token from a specific event type template.",
        "operationId" : "delete-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}_archive",
        "deprecated" : true,
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "companies-read" : "",
              "companies-write" : "",
              "contacts-read" : "",
              "contacts-write" : "",
              "deals-read" : "",
              "deals-write" : "",
              "developers-read" : "",
              "developers-write" : "",
              "properties-settings-read" : "",
              "properties-settings-write" : "",
              "tickets-read" : "",
              "tickets-write" : "",
              "timeline-read" : "",
              "timeline-write" : ""
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}