{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Timeline",
    "description" : "This feature allows an app to create and configure custom events that can show up in the timelines of certain CRM objects like contacts, companies, tickets, or deals. You'll find multiple use cases for this API in the sections below.",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "STARTER",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "After setting up a new set of sign-up flows on your website, update contact timelines to indicate which flow they completed. In each event, you could also include a link to open an iframe that displays additional external data about the event.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Timeline Events Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/extensions/timeline"
    } ],
    "x-hubspot-introduction" : "Use the timeline events API to add custom event information to CRM record timelines. You'll first need to create a public app, then an event template to display event data. "
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Events"
  }, {
    "name" : "Templates"
  }, {
    "name" : "Tokens"
  } ],
  "paths" : {
    "/integrators/timeline/v3/events/{eventTemplateId}/{eventId}/detail" : {
      "get" : {
        "tags" : [ "Events" ],
        "summary" : "Get event details",
        "description" : "Retrieve details for a specific event, specified by template ID and event ID.",
        "operationId" : "get-/integrators/timeline/v3/events/{eventTemplateId}/{eventId}/detail_getDetailById",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        } ]
      }
    },
    "/integrators/timeline/v3/events" : {
      "post" : {
        "tags" : [ "Events" ],
        "summary" : "Send event data (single)",
        "description" : "Send a single instance of event data to a specified event type.",
        "operationId" : "post-/integrators/timeline/v3/events_create",
        "security" : [ {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "timeline" ]
        }, {
          "oauth2" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      }
    },
    "/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}" : {
      "put" : {
        "tags" : [ "Tokens" ],
        "summary" : "Update a template token",
        "description" : "Update an event type template token, specified by token name.",
        "operationId" : "put-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Tokens" ],
        "summary" : "Delete a template token",
        "description" : "Delete an existing token from a specific event type template.",
        "operationId" : "delete-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}_archive",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/integrators/timeline/v3/events/{eventTemplateId}/{eventId}" : {
      "get" : {
        "tags" : [ "Events" ],
        "summary" : "Get an event instance",
        "description" : "Retrieve an event instance, specified by template ID and event ID.",
        "operationId" : "get-/integrators/timeline/v3/events/{eventTemplateId}/{eventId}_getById",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.read.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.read" ]
        }, {
          "private_apps" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read.v2" ]
        }, {
          "oauth2" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.read" ]
        } ]
      }
    },
    "/integrators/timeline/v3/events/batch/create" : {
      "post" : {
        "tags" : [ "Events" ],
        "summary" : "Create multiple events",
        "description" : "Batch create multiple instances of timeline events based on an event template. Once created, these event are immutable on the object timeline and cannot be modified. If the event template was configured to update object properties via `objectPropertyName`, this call will also attempt to updates those properties, or add them if they don't exist.",
        "operationId" : "post-/integrators/timeline/v3/events/batch/create_createBatch",
        "security" : [ {
          "private_apps" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "tickets.sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets" ]
        }, {
          "private_apps" : [ "tickets.sensitive.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.companies.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "tickets.sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.sensitive.write" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive.v2" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.objects.companies.sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.highly_sensitive.write.v2" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.sensitive.write.v2" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "tickets.highly_sensitive" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "timeline" ]
        }, {
          "oauth2" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.deals.highly_sensitive.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      }
    },
    "/integrators/timeline/v3/{appId}/event-templates" : {
      "get" : {
        "tags" : [ "Templates" ],
        "summary" : "Get all event templates",
        "description" : "Retrieve all templates defined for an app.",
        "operationId" : "get-/integrators/timeline/v3/{appId}/event-templates_getAll",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Templates" ],
        "summary" : "Create an event template",
        "description" : "Event templates define the general structure for a custom timeline event, and enable you to send event data to HubSpot. A template includes formatted copy for its heading and details, as well as any custom property definitions. A single app can include up to 750 event templates.<br/><Warning>the `v1` and `v3` timeline events APIs are only available for app partners with existing `v1`/`v3` timeline events defined in their public app. <ul><li>If your app doesn't include an[...]",
        "operationId" : "post-/integrators/timeline/v3/{appId}/event-templates_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}" : {
      "get" : {
        "tags" : [ "Templates" ],
        "summary" : "Get an event template",
        "description" : "Retrieve an event type template by ID.",
        "operationId" : "get-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}_getById",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "put" : {
        "tags" : [ "Templates" ],
        "summary" : "Update an event template",
        "description" : "Update an existing event template, specified by ID.",
        "operationId" : "put-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Templates" ],
        "summary" : "Delete an event template",
        "description" : "Delete an event type template by ID.",
        "operationId" : "delete-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}_archive",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens" : {
      "post" : {
        "tags" : [ "Tokens" ],
        "summary" : "Add tokens to an existing template",
        "description" : "Update an existing event type template with new tokens.",
        "operationId" : "post-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.contacts.write" : "Create or update contact records",
              "crm.objects.contacts.sensitive.write.v2" : "Create or update sensitive properties on contact records",
              "crm.schemas.contacts.write" : "Create new contact properties or change contact property settings",
              "crm.objects.companies.write" : "View company records",
              "crm.objects.companies.sensitive.write.v2" : "Create or update sensitive properties on company records",
              "crm.objects.companies.highly_sensitive.write.v2" : "Change company records (highly-sensitive)",
              "crm.schemas.companies.write" : "Create new company properties or change company property settings",
              "crm.schemas.deals.write" : "Create new deal properties or change deal property settings",
              "crm.objects.deals.write" : "Create or update deal records",
              "crm.objects.deals.sensitive.write.v2" : "Create or update sensitive properties on deal records",
              "crm.objects.deals.highly_sensitive.write.v2" : "Change deal records (highly-sensitive)",
              "tickets" : "Read and write tickets",
              "tickets.sensitive.v2" : "Tickets (sensitive)",
              "tickets.highly_sensitive.v2" : "Tickets (highly-sensitive)",
              "timeline" : "Create timeline events",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.schemas.contacts.read" : "View contacts property settings",
              "crm.objects.contacts.sensitive.read.v2" : "View sensitive properties on contact records",
              "crm.objects.contacts.read" : "View contact records",
              "crm.objects.companies.highly_sensitive.read.v2" : "View company records (highly-sensitive)",
              "crm.objects.companies.read" : "Create or update company records",
              "crm.schemas.companies.read" : "View company property settings",
              "crm.objects.companies.sensitive.read.v2" : "View sensitive properties on company records",
              "crm.objects.deals.highly_sensitive.read.v2" : "View deal records (highly-sensitive)",
              "crm.schemas.deals.read" : "View deals property settings",
              "crm.objects.deals.read" : "View deal records",
              "crm.objects.deals.sensitive.read.v2" : "View sensitive properties on deal records"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}