{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Postal Mail",
    "description" : "",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "Ihr Unternehmen versendet Briefpost und empfängt Rechnungen auf dem Postweg und Sie möchten diese Kommunikation zusammen mit Ihren E-Mails und Anrufen an/bei Kunden in Ihrem CRM zentralisieren.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Postal Mail Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/crm/engagements/postal-mail"
    } ],
    "x-hubspot-introduction" : "Mit der Briefpost-API können Sie Daten aus Ihren Briefpost-Kampagnen protokollieren und mit den zugehörigen Datensätzen in Ihrem CRM verknüpfen."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Batch"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/v3/objects/postal_mail/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch von Objekten nach interner ID oder eindeutigen Eigenschaftswerten lesen",
        "operationId" : "post-/crm/v3/objects/postal_mail/batch/read_read",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        } ]
      }
    },
    "/crm/v3/objects/postal_mail/{postalMailId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Lesen",
        "description" : "Ein durch „{postalMailId}“ identifiziertes Objekt wird gelesen. „{postalMailId}“ bezieht sich standardmäßig auf die interne Objekt-ID oder optional auf einen beliebigen eindeutigen Eigenschaftswert, wie im Abfrageparameter „idProperty“ spezifiziert. Es kann gesteuert werden, was über den Abfrageparameter „properties“ zurückgegeben wird.",
        "operationId" : "get-/crm/v3/objects/postal_mail/{postalMailId}_getById",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archivieren",
        "description" : "Zum Verschieben eines Objekts mit der ID „{postalMailId}“ in den Papierkorb.",
        "operationId" : "delete-/crm/v3/objects/postal_mail/{postalMailId}_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Aktualisieren",
        "description" : "Ein durch „{postalMailId}“ identifiziertes Objekt wird teilweise aktualisiert. „{postalMailId}“ bezieht sich standardmäßig auf die interne Objekt-ID oder optional auf einen beliebigen eindeutigen Eigenschaftswert, wie im Abfrageparameter „idProperty“ spezifiziert. Bereitgestellte Eigenschaftswerte werden überschrieben. Schreibgeschützte und nicht vorhandene Eigenschaften werden ignoriert. Eigenschaftswerte können durch Übergabe einer leeren Zeichenfolge gelöscht werden."[...]",
        "operationId" : "patch-/crm/v3/objects/postal_mail/{postalMailId}_update",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/objects/postal_mail/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Einen Batch mit Objekten nach ID archivieren",
        "operationId" : "post-/crm/v3/objects/postal_mail/batch/archive_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/objects/postal_mail/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Einen Batch mit Objekten erstellen",
        "operationId" : "post-/crm/v3/objects/postal_mail/batch/create_create",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/objects/postal_mail/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch von Objekten nach interner ID oder eindeutigen Eigenschaftswerten aktualisieren",
        "operationId" : "post-/crm/v3/objects/postal_mail/batch/update_update",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/objects/postal_mail" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Liste",
        "description" : "Zum Lesen einer Seite von Objekten. Steuern Sie, was über den „properties“-Abfrageparameter zurückgegeben wird.",
        "operationId" : "get-/crm/v3/objects/postal_mail_getPage",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Erstellen",
        "description" : "Erstellt ein CRM-Objekt mit den angegebenen Eigenschaften und gibt eine Kopie des Objekts einschließlich der ID zurück. Dokumentation und Beispiele zum Erstellen von Standardobjekten werden bereitgestellt.",
        "operationId" : "post-/crm/v3/objects/postal_mail_create",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/objects/postal_mail/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "operationId" : "post-/crm/v3/objects/postal_mail/search_doSearch",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "e-commerce" : "e-commerce",
              "crm.objects.custom.write" : "Change custom object records",
              "media_bridge.read" : "Read media and media events",
              "crm.objects.goals.read" : "Read goals",
              "tickets" : "Read and write tickets",
              "crm.objects.custom.read" : "View custom object records"
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.companies.write" : " ",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.contacts.read" : " ",
              "crm.objects.invoices.read" : "Read invoices objects",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.partner-clients.write" : "Modify Partner Client CRM objects",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.deals.read" : " ",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.commercepayments.read" : "Read the COMMERCE_PAYMENT object.",
              "crm.objects.contacts.write" : " ",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.companies.read" : " ",
              "crm.objects.carts.write" : "Write cart",
              "crm.objects.deals.write" : " ",
              "crm.objects.users.write" : "Write User CRM objects",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.leads.read" : "Read lead objects"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE"
  },
  "x-hubspot-documentation-banner" : "NONE"
}