{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CrmPublicAssociationsServiceV4",
    "version" : "v4"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Definitions"
  } ],
  "paths" : {
    "/crm/v4/associations/{fromObjectType}/{toObjectType}/labels" : {
      "get" : {
        "tags" : [ "Definitions" ],
        "summary" : "Read",
        "description" : "Returns all association types between two object types",
        "operationId" : "get-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Definitions" ],
        "summary" : "Update",
        "description" : "Update a user defined association definition",
        "operationId" : "put-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Definitions" ],
        "summary" : "Create",
        "description" : "Create a user defined association definition",
        "operationId" : "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    },
    "/crm/v4/associations/{fromObjectType}/{toObjectType}/labels/{associationTypeId}" : {
      "delete" : {
        "tags" : [ "Definitions" ],
        "summary" : "Delete",
        "description" : "Deletes an association definition",
        "operationId" : "delete-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels/{associationTypeId}",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "tickets" : "Read and write tickets",
              "media_bridge.read" : "Read media and media events",
              "e-commerce" : "e-commerce",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.goals.read" : "Read goals"
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.deals.write" : " ",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.companies.read" : " ",
              "crm.objects.companies.write" : " ",
              "crm.objects.contacts.write" : " ",
              "crm.objects.contacts.read" : " ",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.deals.read" : " ",
              "crm.objects.line_items.read" : "Line Items"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}