{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Meetings",
    "description" : "",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "Si estás utilizando un servicio diferente al de HubSpot para programar tus reuniones, o si deseas complementar el seguimiento integrado de la herramienta de reuniones de HubSpot, puedes utilizar esta API para llevar un registro de cómo fueron tus reuniones con prospectos y clientes en el CRM de HubSpot.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Meetings Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/crm/engagements/meetings"
    } ],
    "x-hubspot-introduction" : "La API de interacciones de reuniones te permite registrar y gestionar reuniones en los registros de CRM correspondientes, como contactos o empresas. Puedes incluir notas de la reunión y su resultado, junto con otros datos importantes de la reunión para compartir con el resto de tu equipo."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Batch"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/v3/objects/meetings/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Lee un lote de objetos por ID interno, o valores de propiedad únicos",
        "operationId" : "post-/crm/v3/objects/meetings/batch/read_read",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        } ]
      }
    },
    "/crm/v3/objects/meetings/{meetingId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Leído",
        "description" : "Lee un objeto identificado por `{meetingId}`. `{meetingId}` se refiere al ID de objeto interno por opción predeterminada, u opcionalmente a cualquier valor de propiedad único especificado por el parámetro de consulta `idProperty`. Controla lo que se devuelve mediante el parámetro de consulta `properties`.",
        "operationId" : "get-/crm/v3/objects/meetings/{meetingId}_getById",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archivar",
        "description" : "Mueve un objeto identificado por `{meetingId}` a la papelera de reciclaje.",
        "operationId" : "delete-/crm/v3/objects/meetings/{meetingId}_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Actualizar",
        "description" : "Realiza una actualización parcial de un objeto identificado por \"{meetingId}\". \"{meetingId}\" se refiere al ID interno del objeto, por opción predeterminada, u opcionalmente a cualquier valor de propiedad único según lo especificado por el parámetro de consulta \"idProperty\". Se sobrescribirán los valores de propiedad especificados. Se ignorarán las propiedades de solo lectura y las no existentes. Los valores de las propiedades pueden borrarse pasando una cadena vací[...]",
        "operationId" : "patch-/crm/v3/objects/meetings/{meetingId}_update",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/objects/meetings/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Archiva un lote de objetos por ID",
        "operationId" : "post-/crm/v3/objects/meetings/batch/archive_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/objects/meetings/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Crea un lote de objetos",
        "operationId" : "post-/crm/v3/objects/meetings/batch/create_create",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/objects/meetings/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Actualiza un lote de objetos por ID interno, o valores de propiedad únicos",
        "operationId" : "post-/crm/v3/objects/meetings/batch/update_update",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/objects/meetings" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Lista",
        "description" : "Leer una página de objetos. Controla lo que se devuelve a través del parámetro de consulta `properties`.",
        "operationId" : "get-/crm/v3/objects/meetings_getPage",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Crear",
        "description" : "Crea un objeto de CRM con las propiedades dadas y devuelve una copia del objeto, incluyendo el ID. Se proporciona documentación y ejemplos para crear objetos estándar.",
        "operationId" : "post-/crm/v3/objects/meetings_create",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        } ]
      }
    },
    "/crm/v3/objects/meetings/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "operationId" : "post-/crm/v3/objects/meetings/search_doSearch",
        "security" : [ {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "media_bridge.read" : "Read media and media events",
              "crm.objects.goals.read" : "Read goals",
              "tickets" : "Read and write tickets",
              "crm.objects.custom.read" : "View custom object records",
              "e-commerce" : "e-commerce",
              "crm.objects.custom.write" : "Change custom object records"
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.commercepayments.read" : "Read the COMMERCE_PAYMENT object.",
              "crm.objects.contacts.write" : " ",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.companies.read" : " ",
              "crm.objects.carts.write" : "Write cart",
              "crm.objects.deals.write" : " ",
              "crm.objects.users.write" : "Write User CRM objects",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.companies.write" : " ",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.contacts.read" : " ",
              "crm.objects.invoices.read" : "Read invoices objects",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.partner-clients.write" : "Modify Partner Client CRM objects",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.deals.read" : " ",
              "crm.objects.carts.read" : "Read carts"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE"
  },
  "x-hubspot-documentation-banner" : "NONE"
}