{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Files Files",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/files/2026-09-beta/files" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Upload file",
        "description" : "Upload a new file to the HubSpot file manager. This endpoint allows you to specify the file, its name, and the folder where it should be stored. It supports additional options such as specifying a character set or additional options for the file.",
        "operationId" : "post-/files/2026-09-beta/files",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2" : [ "files" ]
        } ]
      }
    },
    "/files/2026-09-beta/files/import-from-url/async" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Import File",
        "description" : "Import a file asynchronously from a specified URL into the HubSpot file manager. This endpoint allows you to specify various parameters such as access level, duplicate validation strategy, and whether to overwrite existing files. The operation is processed asynchronously, and a task locator is returned to check the status of the import.",
        "operationId" : "post-/files/2026-09-beta/files/import-from-url/async",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2" : [ "files" ]
        } ]
      }
    },
    "/files/2026-09-beta/files/import-from-url/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Advanced" ],
        "summary" : "Retrieve status",
        "description" : "Retrieve the status of an asynchronous file import task using the task ID. This endpoint provides information about the current state of the task, such as whether it is pending, processing, canceled, or complete.",
        "operationId" : "get-/files/2026-09-beta/files/import-from-url/async/tasks/{taskId}/status",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "oauth2" : [ "files.ui_hidden.read" ]
        } ]
      }
    },
    "/files/2026-09-beta/files/search" : {
      "get" : {
        "tags" : [ "Search" ],
        "summary" : "Search files",
        "description" : "Search for files in the HubSpot account using various filters and criteria. This endpoint allows you to specify multiple query parameters to narrow down the search results based on properties like creation date, size, type, and more. It supports pagination and sorting to manage large sets of data effectively.",
        "operationId" : "get-/files/2026-09-beta/files/search",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "oauth2" : [ "files.ui_hidden.read" ]
        } ]
      }
    },
    "/files/2026-09-beta/files/stat/{path}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve file stats",
        "description" : "Retrieve detailed statistics for a specific file or folder identified by its path. This endpoint provides information about the file or folder, which can be useful for managing and organizing files within your HubSpot account.",
        "operationId" : "get-/files/2026-09-beta/files/stat/{path}",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "oauth2" : [ "files.ui_hidden.read" ]
        } ]
      }
    },
    "/files/2026-09-beta/files/{fileId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve file",
        "description" : "Retrieve file metadata using its ID.",
        "operationId" : "get-/files/2026-09-beta/files/{fileId}",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "oauth2" : [ "files.ui_hidden.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update file",
        "description" : "Update an existing file in your HubSpot account by specifying the file ID. This operation allows you to modify the file's content and other attributes. It requires the file to be identified by its unique fileId.",
        "operationId" : "put-/files/2026-09-beta/files/{fileId}",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete file",
        "description" : "Delete a specific file from your HubSpot account using its ID. This will delete it from the FileManager and make its url inaccessible",
        "operationId" : "delete-/files/2026-09-beta/files/{fileId}",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2" : [ "files" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update file",
        "description" : "Update the details of a specific file in your HubSpot account using its unique identifier. This operation allows you to modify file properties such as name, parent folder, and access settings. It is useful for managing file metadata and ensuring files are organized and accessible as needed.",
        "operationId" : "patch-/files/2026-09-beta/files/{fileId}",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2" : [ "files" ]
        } ]
      }
    },
    "/files/2026-09-beta/files/{fileId}/download" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Download file",
        "description" : "Download a specific file from your HubSpot account using its ID. It is recommended that this endpoint is only used to access for SENSITIVE files. For PUBLIC files access via the public url. For PRIVATE files access via the signedUrl.",
        "operationId" : "get-/files/2026-09-beta/files/{fileId}/download",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "oauth2" : [ "files.ui_hidden.read" ]
        } ]
      }
    },
    "/files/2026-09-beta/files/{fileId}/gdpr-delete" : {
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "GDPR Delete file",
        "description" : "Delete a file from your HubSpot account in compliance with GDPR regulations. This operation ensures that the specified file is permanently removed and cannot be recovered.",
        "operationId" : "delete-/files/2026-09-beta/files/{fileId}/gdpr-delete",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2" : [ "files" ]
        } ]
      }
    },
    "/files/2026-09-beta/files/{fileId}/signed-url" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Generate signed URL",
        "description" : "Generate a signed URL for a specific file in your HubSpot account. This endpoint allows you to specify the size of the file, the expiration time for the URL, and whether the image should be upscaled. It is useful for securely sharing files with a limited lifespan.",
        "operationId" : "get-/files/2026-09-beta/files/{fileId}/signed-url",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "oauth2" : [ "files.ui_hidden.read" ]
        } ]
      }
    },
    "/files/2026-09-beta/folders" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Create folder",
        "description" : "Create a new folder in the HubSpot file manager. This endpoint allows you to organize files by creating folders, which can be nested within other folders by specifying a parent folder ID or path.",
        "operationId" : "post-/files/2026-09-beta/folders",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2" : [ "files" ]
        } ]
      }
    },
    "/files/2026-09-beta/folders/search" : {
      "get" : {
        "tags" : [ "Search" ],
        "summary" : "Search folders",
        "description" : "Search for folders in the HubSpot file manager using various query parameters to filter results. This endpoint allows you to retrieve folders based on specific criteria such as creation date, update date, folder name, and parent folder IDs. It supports pagination and sorting to help manage large sets of data efficiently.",
        "operationId" : "get-/files/2026-09-beta/folders/search",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "oauth2" : [ "files.ui_hidden.read" ]
        } ]
      }
    },
    "/files/2026-09-beta/folders/{folderId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve folder",
        "description" : "Retrieve folder metadata by its ID.",
        "operationId" : "get-/files/2026-09-beta/folders/{folderId}",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "oauth2" : [ "files.ui_hidden.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete folder by ID",
        "description" : "Delete a folder in your HubSpot account using its ID. This operation deletes the folder and its contents recursively.",
        "operationId" : "delete-/files/2026-09-beta/folders/{folderId}",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2" : [ "files" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update folder",
        "description" : "Update the details of a specific folder in the file manager by providing the folder's unique identifier. This operation allows you to modify folder attributes such as its name or parent folder ID.",
        "operationId" : "patch-/files/2026-09-beta/folders/{folderId}",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2" : [ "files" ]
        } ]
      }
    },
    "/files/2026-09-beta/folders/{folderPath}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve folder by path",
        "description" : "Retrieve details about a specific folder in the file manager using its path.",
        "operationId" : "get-/files/2026-09-beta/folders/{folderPath}",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "oauth2" : [ "files.ui_hidden.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete folder by path",
        "description" : "Delete a folder in your HubSpot account using its path. This operation deletes the folder and its contents recursively.",
        "operationId" : "delete-/files/2026-09-beta/folders/{folderPath}",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2" : [ "files" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "files.ui_hidden.read" : "",
              "files.ui_hidden.write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}