{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Fichiers",
    "description" : "Upload and manage files.",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "Lors du lancement d'un repositionnement de l'entreprise, téléchargez un nouvel ensemble d'images et de ressources de marque dans le gestionnaire de fichiers afin que les équipes marketing et commerciales puissent mettre à jour leurs ressources en conséquence.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Files Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/files"
    } ],
    "x-hubspot-introduction" : "Utilisez l'API de fichiers pour gérer et stocker des fichiers dans l'outil de gestion de fichiers de HubSpot. Les fichiers peuvent être utilisés dans divers outils HubSpot, comme pour insérer des fichiers image dans des emails."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Files"
  }, {
    "name" : "Fichiers"
  }, {
    "name" : "Folders"
  }, {
    "name" : "Dossiers"
  } ],
  "paths" : {
    "/files/v3/files/{fileId}/gdpr-delete" : {
      "delete" : {
        "tags" : [ "Files", "Fichiers" ],
        "summary" : "Supprimer en conformité avec le RGPD",
        "description" : "Supprimer le fichier le RGPD",
        "operationId" : "delete-/files/v3/files/{fileId}/gdpr-delete_archiveGDPR",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/{fileId}" : {
      "get" : {
        "tags" : [ "Files", "Fichiers" ],
        "summary" : "Obtenir le fichier.",
        "description" : "Obtenir le fichier par ID.",
        "operationId" : "get-/files/v3/files/{fileId}_getById",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "put" : {
        "tags" : [ "Files", "Fichiers" ],
        "summary" : "Remplacer le fichier.",
        "description" : "Remplacer les données du fichier existant par de nouvelles données. Cela permet de changer le contenu d'une image sans avoir à télécharger un nouveau fichier ni mettre à jour des références.",
        "operationId" : "put-/files/v3/files/{fileId}_replace",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Files", "Fichiers" ],
        "summary" : "Supprimer le fichier",
        "description" : "Supprimer le fichier par ID.",
        "operationId" : "delete-/files/v3/files/{fileId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Files", "Fichiers" ],
        "summary" : "mettre à jour propriétés du fichier",
        "description" : "Mettre à jour les propriétés du fichier par ID.",
        "operationId" : "patch-/files/v3/files/{fileId}_updateProperties",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/{folderId}" : {
      "get" : {
        "tags" : [ "Folders", "Dossiers" ],
        "summary" : "Obtenir le dossier",
        "description" : "Trouver le dossier par ID.",
        "operationId" : "get-/files/v3/folders/{folderId}_getById",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Folders", "Dossiers" ],
        "summary" : "Supprimer le dossier.",
        "description" : "Supprimer le dossier par ID.",
        "operationId" : "delete-/files/v3/folders/{folderId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files" : {
      "post" : {
        "tags" : [ "Files", "Fichiers" ],
        "summary" : "Charger le fichier",
        "description" : "Chargez un seul fichier en spécifiant le contenu dans le corps de la requête.",
        "operationId" : "post-/files/v3/files_upload",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders" : {
      "post" : {
        "tags" : [ "Folders", "Dossiers" ],
        "summary" : "Créer un dossier.",
        "description" : "Crée un dossier.",
        "operationId" : "post-/files/v3/folders_create",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/{fileId}/signed-url" : {
      "get" : {
        "tags" : [ "Files", "Fichiers" ],
        "summary" : "Obtenir une URL signée pour accéder au fichier privé.",
        "description" : "Génère une URL signée qui permet un accès temporaire à un fichier privé.",
        "operationId" : "get-/files/v3/files/{fileId}/signed-url_getSignedUrl",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/import-from-url/async" : {
      "post" : {
        "tags" : [ "Files", "Fichiers" ],
        "summary" : "Importer un fichier depuis une URL dans le gestionnaire de fichiers.",
        "description" : "Importe de manière asynchrone le fichier à l'URL donnée dans le gestionnaire de fichiers.",
        "operationId" : "post-/files/v3/files/import-from-url/async_importFromUrl",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/stat/{path}" : {
      "get" : {
        "tags" : [ "Files", "Fichiers" ],
        "operationId" : "get-/files/v3/files/stat/{path}_getMetadata",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/search" : {
      "get" : {
        "tags" : [ "Folders", "Dossiers" ],
        "summary" : "Rechercher des dossiers",
        "description" : "Rechercher des dossiers. Ne contient pas de dossiers cachés ou archivés.",
        "operationId" : "get-/files/v3/folders/search_doSearch",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/update/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Folders", "Dossiers" ],
        "summary" : "Vérifier l'état de mise à jour du dossier.",
        "description" : "Vérifiez l'état de la mise à jour du dossier. Les mises à jour de dossiers se font de manière asynchrone.",
        "operationId" : "get-/files/v3/folders/update/async/tasks/{taskId}/status_checkUpdateStatus",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/search" : {
      "get" : {
        "tags" : [ "Files", "Fichiers" ],
        "summary" : "Rechercher les fichiers",
        "description" : "Rechercher dans les fichiers du gestionnaire de fichiers. Ne pas afficher les fichiers cachés ou archivés.",
        "operationId" : "get-/files/v3/files/search_doSearch",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/{folderPath}" : {
      "get" : {
        "tags" : [ "Folders", "Dossiers" ],
        "summary" : "Obtenir le dossier.",
        "description" : "Obtenir le dossier par chemin.",
        "operationId" : "get-/files/v3/folders/{folderPath}_getByPath",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Folders", "Dossiers" ],
        "summary" : "Supprimer le dossier.",
        "description" : "Supprimer le dossier par chemin.",
        "operationId" : "delete-/files/v3/folders/{folderPath}_archiveByPath",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/update/async" : {
      "post" : {
        "tags" : [ "Folders", "Dossiers" ],
        "summary" : "Mettre à jour les propriétés du dossier",
        "description" : "Mettre à jour les propriétés du dossier par l'ID donné. Cette action se déroule de manière asynchrone et mettra également à jour tous les dossiers enfants.",
        "operationId" : "post-/files/v3/folders/update/async_updateProperties",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/import-from-url/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Files", "Fichiers" ],
        "summary" : "Vérifier le statut d'import.",
        "description" : "Vérifiez le statut de l'import demandé.",
        "operationId" : "get-/files/v3/files/import-from-url/async/tasks/{taskId}/status_checkImport",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "files" : "Read from and write to my Files",
              "files.ui_hidden.read" : "View hidden files"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}