{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "ファイル",
    "description" : "Upload and manage files.",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "会社のリブランドを開始する場合は、マーケティングチームや営業チームがアセットを更新できるようにブランド設定された一連の画像やアセットをファイルマネージャーにアップロードしてください。",
    "x-hubspot-related-documentation" : [ {
      "name" : "Files Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/files"
    } ],
    "x-hubspot-introduction" : "ファイルAPIを使用して、HubSpotのファイル マネージャー ツールでファイルの管理や保存を行います。ファイルはEメールへの画像ファイルの挿入など、さまざまなHubSpotツールで使用できます。"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Files"
  }, {
    "name" : "ファイル"
  }, {
    "name" : "Folders"
  }, {
    "name" : "フォルダー"
  } ],
  "paths" : {
    "/files/v3/files/{fileId}/gdpr-delete" : {
      "delete" : {
        "tags" : [ "Files", "ファイル" ],
        "summary" : "GDPR削除",
        "description" : "ファイルをGDRP削除",
        "operationId" : "delete-/files/v3/files/{fileId}/gdpr-delete_archiveGDPR",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/{fileId}" : {
      "get" : {
        "tags" : [ "Files", "ファイル" ],
        "summary" : "ファイルを取得します。",
        "description" : "IDを基準にファイルを取得します。",
        "operationId" : "get-/files/v3/files/{fileId}_getById",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "put" : {
        "tags" : [ "Files", "ファイル" ],
        "summary" : "ファイルを置き換えます。",
        "description" : "既存のファイルデータを新しいファイルデータに置き換えます。新しいファイルをアップロードして全ての参照を更新することなく画像コンテンツを変更するために使用できます。",
        "operationId" : "put-/files/v3/files/{fileId}_replace",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Files", "ファイル" ],
        "summary" : "ファイルを削除",
        "description" : "IDを基準にファイルを削除",
        "operationId" : "delete-/files/v3/files/{fileId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Files", "ファイル" ],
        "summary" : "ファイルプロパティーを更新",
        "description" : "IDを基準にファイルのプロパティーを更新します。",
        "operationId" : "patch-/files/v3/files/{fileId}_updateProperties",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/{folderId}" : {
      "get" : {
        "tags" : [ "Folders", "フォルダー" ],
        "summary" : "フォルダーを取得",
        "description" : "IDを基準にフォルダーを取得",
        "operationId" : "get-/files/v3/folders/{folderId}_getById",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Folders", "フォルダー" ],
        "summary" : "フォルダーを削除します。",
        "description" : "IDを基準にフォルダーを削除します。",
        "operationId" : "delete-/files/v3/folders/{folderId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files" : {
      "post" : {
        "tags" : [ "Files", "ファイル" ],
        "summary" : "ファイルをアップロード",
        "description" : "リクエスト本文で指定されたコンテンツを含めて1つのファイルをアップロードしてください。",
        "operationId" : "post-/files/v3/files_upload",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders" : {
      "post" : {
        "tags" : [ "Folders", "フォルダー" ],
        "summary" : "フォルダーを作成します。",
        "description" : "フォルダーが作成されます。",
        "operationId" : "post-/files/v3/folders_create",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/{fileId}/signed-url" : {
      "get" : {
        "tags" : [ "Files", "ファイル" ],
        "summary" : "非公開ファイルにアクセスするための署名付きURLを取得します。",
        "description" : "非公開ファイルへの一時的なアクセスを可能にする署名付きのURLが生成されます。",
        "operationId" : "get-/files/v3/files/{fileId}/signed-url_getSignedUrl",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/import-from-url/async" : {
      "post" : {
        "tags" : [ "Files", "ファイル" ],
        "summary" : "ファイルをURLからファイルマネージャーにインポートします。",
        "description" : "指定されたURLにあるファイルが非同期でファイルマネージャーにインポートされます。",
        "operationId" : "post-/files/v3/files/import-from-url/async_importFromUrl",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/stat/{path}" : {
      "get" : {
        "tags" : [ "Files", "ファイル" ],
        "operationId" : "get-/files/v3/files/stat/{path}_getMetadata",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/search" : {
      "get" : {
        "tags" : [ "Folders", "フォルダー" ],
        "summary" : "フォルダーを検索",
        "description" : "フォルダーを検索します。非表示のフォルダーやアーカイブされたフォルダーは含まれません。",
        "operationId" : "get-/files/v3/folders/search_doSearch",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/update/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Folders", "フォルダー" ],
        "summary" : "フォルダー更新のステータスをチェックします。",
        "description" : "フォルダー更新のステータスをチェックします。フォルダー更新は非同期で行われます。",
        "operationId" : "get-/files/v3/folders/update/async/tasks/{taskId}/status_checkUpdateStatus",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/search" : {
      "get" : {
        "tags" : [ "Files", "ファイル" ],
        "summary" : "ファイルを検索",
        "description" : "ファイルマネージャーでファイルを検索してください。非表示のファイルやアーカイブされたファイルは表示されません。",
        "operationId" : "get-/files/v3/files/search_doSearch",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/{folderPath}" : {
      "get" : {
        "tags" : [ "Folders", "フォルダー" ],
        "summary" : "フォルダーを取得します。",
        "description" : "パスを基準にフォルダーを取得します。",
        "operationId" : "get-/files/v3/folders/{folderPath}_getByPath",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Folders", "フォルダー" ],
        "summary" : "フォルダーを削除します。",
        "description" : "パスを基準にフォルダーを削除します。",
        "operationId" : "delete-/files/v3/folders/{folderPath}_archiveByPath",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/update/async" : {
      "post" : {
        "tags" : [ "Folders", "フォルダー" ],
        "summary" : "フォルダープロパティーを更新",
        "description" : "指定したIDを基準にフォルダーのプロパティーを更新します。この操作は非同期で行われ、フォルダーの子も全て更新されます。",
        "operationId" : "post-/files/v3/folders/update/async_updateProperties",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/import-from-url/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Files", "ファイル" ],
        "summary" : "インポートのステータスを確認してください。",
        "description" : "リクエストされたインポートのステータスを確認してください。",
        "operationId" : "get-/files/v3/files/import-from-url/async/tasks/{taskId}/status_checkImport",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "files" : "Read from and write to my Files",
              "files.ui_hidden.read" : "View hidden files"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}