{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Archivos",
    "description" : "Upload and manage files.",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "Al lanzar una renovación de marca de la empresa, carga un nuevo conjunto de imágenes y activos de marca en el administrador de archivos para que los equipos de marketing y ventas puedan actualizar sus activos en consecuencia.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Files Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/files"
    } ],
    "x-hubspot-introduction" : "Utiliza la API de archivos para gestionar y almacenar archivos en la herramienta de gestión de archivos de HubSpot. Los archivos pueden utilizarse en otras herramientas de HubSpot, como por ejemplo, al insertar archivos de imagen en correos electrónicos."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Files"
  }, {
    "name" : "Archivos"
  }, {
    "name" : "Folders"
  }, {
    "name" : "Carpetas"
  } ],
  "paths" : {
    "/files/v3/files/{fileId}/gdpr-delete" : {
      "delete" : {
        "tags" : [ "Files", "Archivos" ],
        "summary" : "Eliminación en virtud del RGPD",
        "description" : "Eliminación de archivo en virtud del RGPD",
        "operationId" : "delete-/files/v3/files/{fileId}/gdpr-delete_archiveGDPR",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/{fileId}" : {
      "get" : {
        "tags" : [ "Files", "Archivos" ],
        "summary" : "Obtener archivo.",
        "description" : "Obtener archivo por ID.",
        "operationId" : "get-/files/v3/files/{fileId}_getById",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "put" : {
        "tags" : [ "Files", "Archivos" ],
        "summary" : "Reemplazar el archivo.",
        "description" : "Reemplaza los datos del archivo existente con datos nuevos. Esto permite cambiar el contenido de la imagen sin necesidad de cargar un archivo nuevo y actualizar todas las referencias.",
        "operationId" : "put-/files/v3/files/{fileId}_replace",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Files", "Archivos" ],
        "summary" : "Eliminar archivo",
        "description" : "Eliminar archivo por ID",
        "operationId" : "delete-/files/v3/files/{fileId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Files", "Archivos" ],
        "summary" : "actualizar propiedades de archivo",
        "description" : "Actualizar propiedades del archivo por ID.",
        "operationId" : "patch-/files/v3/files/{fileId}_updateProperties",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/{folderId}" : {
      "get" : {
        "tags" : [ "Folders", "Carpetas" ],
        "summary" : "Obtener carpeta",
        "description" : "Obtener carpeta por ID",
        "operationId" : "get-/files/v3/folders/{folderId}_getById",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Folders", "Carpetas" ],
        "summary" : "Eliminar carpeta.",
        "description" : "Eliminar carpeta por ID.",
        "operationId" : "delete-/files/v3/folders/{folderId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files" : {
      "post" : {
        "tags" : [ "Files", "Archivos" ],
        "summary" : "Subir archivo",
        "description" : "Cargar un único archivo con el contenido especificado en el cuerpo de la solicitud.",
        "operationId" : "post-/files/v3/files_upload",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders" : {
      "post" : {
        "tags" : [ "Folders", "Carpetas" ],
        "summary" : "Crear carpeta.",
        "description" : "Crea una carpeta.",
        "operationId" : "post-/files/v3/folders_create",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/{fileId}/signed-url" : {
      "get" : {
        "tags" : [ "Files", "Archivos" ],
        "summary" : "Obtener la URL firmada para acceder al archivo privado.",
        "description" : "Genera una URL firmada que permite acceso temporal a un archivo privado.",
        "operationId" : "get-/files/v3/files/{fileId}/signed-url_getSignedUrl",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/import-from-url/async" : {
      "post" : {
        "tags" : [ "Files", "Archivos" ],
        "summary" : "Importar un archivo desde una URL al administrador de archivos.",
        "description" : "Importa de forma asíncrona el archivo de la URL indicada en el administrador de archivos.",
        "operationId" : "post-/files/v3/files/import-from-url/async_importFromUrl",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/stat/{path}" : {
      "get" : {
        "tags" : [ "Files", "Archivos" ],
        "operationId" : "get-/files/v3/files/stat/{path}_getMetadata",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/search" : {
      "get" : {
        "tags" : [ "Folders", "Carpetas" ],
        "summary" : "Buscar carpetas",
        "description" : "Buscar carpetas. No contiene carpetas ocultas o archivadas.",
        "operationId" : "get-/files/v3/folders/search_doSearch",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/update/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Folders", "Carpetas" ],
        "summary" : "Verificar estado de actualización de la carpeta.",
        "description" : "Verificar el estado de la actualización de la carpeta. Las actualizaciones de carpetas ocurren de manera asíncrona.",
        "operationId" : "get-/files/v3/folders/update/async/tasks/{taskId}/status_checkUpdateStatus",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/search" : {
      "get" : {
        "tags" : [ "Files", "Archivos" ],
        "summary" : "Buscar archivos",
        "description" : "Buscar archivos en el administrador de archivos. No muestra los archivos ocultos o archivados.",
        "operationId" : "get-/files/v3/files/search_doSearch",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/{folderPath}" : {
      "get" : {
        "tags" : [ "Folders", "Carpetas" ],
        "summary" : "Obtener carpeta.",
        "description" : "Obtener carpeta por ruta.",
        "operationId" : "get-/files/v3/folders/{folderPath}_getByPath",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Folders", "Carpetas" ],
        "summary" : "Eliminar carpeta.",
        "description" : "Eliminar carpeta por ruta.",
        "operationId" : "delete-/files/v3/folders/{folderPath}_archiveByPath",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/update/async" : {
      "post" : {
        "tags" : [ "Folders", "Carpetas" ],
        "summary" : "Actualizar propiedades de carpeta",
        "description" : "Actualizar las propiedades de la carpeta por el ID dado. Esta acción ocurre de manera asincrónica y actualizará también todos los elementos secundarios de la carpeta.",
        "operationId" : "post-/files/v3/folders/update/async_updateProperties",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/import-from-url/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Files", "Archivos" ],
        "summary" : "Verificar estado de importación.",
        "description" : "Verificar el estado de la importación solicitada.",
        "operationId" : "get-/files/v3/files/import-from-url/async/tasks/{taskId}/status_checkImport",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "files" : "Read from and write to my Files",
              "files.ui_hidden.read" : "View hidden files"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}