{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Files Files",
    "description" : "Upload and manage files.",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "Files Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/library/files"
    } ]
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Files"
  }, {
    "name" : "Folders"
  } ],
  "paths" : {
    "/files/v3/files" : {
      "post" : {
        "tags" : [ "Files" ],
        "operationId" : "post-/files/v3/files_upload",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/import-from-url/async" : {
      "post" : {
        "tags" : [ "Files" ],
        "operationId" : "post-/files/v3/files/import-from-url/async_importFromUrl",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/import-from-url/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Files" ],
        "operationId" : "get-/files/v3/files/import-from-url/async/tasks/{taskId}/status_checkImport",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/search" : {
      "get" : {
        "tags" : [ "Files" ],
        "operationId" : "get-/files/v3/files/search_doSearch",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/stat/{path}" : {
      "get" : {
        "tags" : [ "Files" ],
        "operationId" : "get-/files/v3/files/stat/{path}_getMetadata",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/{fileId}" : {
      "get" : {
        "tags" : [ "Files" ],
        "operationId" : "get-/files/v3/files/{fileId}_getById",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      },
      "put" : {
        "tags" : [ "Files" ],
        "operationId" : "put-/files/v3/files/{fileId}_replace",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Files" ],
        "operationId" : "delete-/files/v3/files/{fileId}_archive",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Files" ],
        "operationId" : "patch-/files/v3/files/{fileId}_updateProperties",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/{fileId}/gdpr-delete" : {
      "delete" : {
        "tags" : [ "Files" ],
        "operationId" : "delete-/files/v3/files/{fileId}/gdpr-delete_delete",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/{fileId}/signed-url" : {
      "get" : {
        "tags" : [ "Files" ],
        "operationId" : "get-/files/v3/files/{fileId}/signed-url_getSignedUrl",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders" : {
      "post" : {
        "tags" : [ "Folders" ],
        "operationId" : "post-/files/v3/folders_create",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/search" : {
      "get" : {
        "tags" : [ "Folders" ],
        "operationId" : "get-/files/v3/folders/search_doSearch",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/update/async" : {
      "post" : {
        "tags" : [ "Folders" ],
        "operationId" : "post-/files/v3/folders/update/async_updatePropertiesRecursively",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/update/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Folders" ],
        "operationId" : "get-/files/v3/folders/update/async/tasks/{taskId}/status_checkUpdateStatus",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/{folderId}" : {
      "get" : {
        "tags" : [ "Folders" ],
        "operationId" : "get-/files/v3/folders/{folderId}_getById",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Folders" ],
        "operationId" : "delete-/files/v3/folders/{folderId}_archive",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Folders" ],
        "operationId" : "patch-/files/v3/folders/{folderId}_updateProperties",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/{folderPath}" : {
      "get" : {
        "tags" : [ "Folders" ],
        "operationId" : "get-/files/v3/folders/{folderPath}_getByPath",
        "security" : [ {
          "oauth2" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Folders" ],
        "operationId" : "delete-/files/v3/folders/{folderPath}_archiveByPath",
        "security" : [ {
          "oauth2" : [ "files" ]
        }, {
          "private_apps" : [ "files" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "files" : "Read from and write to my Files",
              "files.ui_hidden.read" : "View hidden files"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}