{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Arquivos",
    "description" : "Upload and manage files.",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "Ao lançar o rebranding da empresa, faça upload de um novo conjunto de imagens e ativos de marca no gerenciador de arquivos para que as equipes de marketing e vendas possam atualizar seus ativos apropriadamente.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Files Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/files"
    } ],
    "x-hubspot-introduction" : "Use a API de arquivos para gerenciar e armazenar arquivos na ferramenta de gerenciador de arquivos do HubSpot. Os arquivos podem ser usados em todas as outras ferramentas da HubSpot, como inserir arquivos de imagem em e-mails."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Files"
  }, {
    "name" : "Arquivos"
  }, {
    "name" : "Folders"
  }, {
    "name" : "Pastas"
  } ],
  "paths" : {
    "/files/v3/files/{fileId}/gdpr-delete" : {
      "delete" : {
        "tags" : [ "Files", "Arquivos" ],
        "summary" : "Excluir permanentemente",
        "description" : "Excluir arquivo permanentemente",
        "operationId" : "delete-/files/v3/files/{fileId}/gdpr-delete_archiveGDPR",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/{fileId}" : {
      "get" : {
        "tags" : [ "Files", "Arquivos" ],
        "summary" : "Obter arquivo.",
        "description" : "Obtenha o arquivo pelo ID.",
        "operationId" : "get-/files/v3/files/{fileId}_getById",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "put" : {
        "tags" : [ "Files", "Arquivos" ],
        "summary" : "Substituir o arquivo.",
        "description" : "Substitua os dados existentes do arquivo pelos novos. Pode ser usado para alterar o conteúdo da imagem sem precisar carregar um novo arquivo e atualizar todas as referências.",
        "operationId" : "put-/files/v3/files/{fileId}_replace",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Files", "Arquivos" ],
        "summary" : "Excluir arquivo",
        "description" : "Exclua o arquivo por ID",
        "operationId" : "delete-/files/v3/files/{fileId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Files", "Arquivos" ],
        "summary" : "atualizar propriedades do arquivo",
        "description" : "Atualize as propriedades do arquivo pelo ID.",
        "operationId" : "patch-/files/v3/files/{fileId}_updateProperties",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/{folderId}" : {
      "get" : {
        "tags" : [ "Folders", "Pastas" ],
        "summary" : "Obter pasta",
        "description" : "Obtenha a pasta por ID",
        "operationId" : "get-/files/v3/folders/{folderId}_getById",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Folders", "Pastas" ],
        "summary" : "Excluir a pasta.",
        "description" : "Exclua a pasta pelo ID.",
        "operationId" : "delete-/files/v3/folders/{folderId}_archive",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files" : {
      "post" : {
        "tags" : [ "Files", "Arquivos" ],
        "summary" : "Carregar arquivo",
        "description" : "Faça upload de um arquivo com o conteúdo especificado no corpo da solicitação.",
        "operationId" : "post-/files/v3/files_upload",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders" : {
      "post" : {
        "tags" : [ "Folders", "Pastas" ],
        "summary" : "Criar a pasta.",
        "description" : "Cria uma pasta.",
        "operationId" : "post-/files/v3/folders_create",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/{fileId}/signed-url" : {
      "get" : {
        "tags" : [ "Files", "Arquivos" ],
        "summary" : "Obter o URL assinado para acessar o arquivo privado.",
        "description" : "Gera o URL assinado que permite acesso temporário a um arquivo privado.",
        "operationId" : "get-/files/v3/files/{fileId}/signed-url_getSignedUrl",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/import-from-url/async" : {
      "post" : {
        "tags" : [ "Files", "Arquivos" ],
        "summary" : "Importe um arquivo de um URL no gerenciador de arquivos.",
        "description" : "Importa o arquivo do URL especificado no gerenciador de arquivos de forma assíncrona.",
        "operationId" : "post-/files/v3/files/import-from-url/async_importFromUrl",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/stat/{path}" : {
      "get" : {
        "tags" : [ "Files", "Arquivos" ],
        "operationId" : "get-/files/v3/files/stat/{path}_getMetadata",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/search" : {
      "get" : {
        "tags" : [ "Folders", "Pastas" ],
        "summary" : "Pesquisar pastas",
        "description" : "Pesquise pastas. Não contém pastas ocultas ou arquivadas.",
        "operationId" : "get-/files/v3/folders/search_doSearch",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/update/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Folders", "Pastas" ],
        "summary" : "Verificar o status de atualização da pasta.",
        "description" : "Verifique o status da atualização da pasta. As atualizações de pastas acontecem de forma assíncrona.",
        "operationId" : "get-/files/v3/folders/update/async/tasks/{taskId}/status_checkUpdateStatus",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/search" : {
      "get" : {
        "tags" : [ "Files", "Arquivos" ],
        "summary" : "Pesquisar arquivos",
        "description" : "Pesquise arquivos no gerenciador de arquivos. Não exibe arquivos ocultos ou arquivados.",
        "operationId" : "get-/files/v3/files/search_doSearch",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/{folderPath}" : {
      "get" : {
        "tags" : [ "Folders", "Pastas" ],
        "summary" : "Obter a pasta.",
        "description" : "Obtenha a pasta pelo caminho.",
        "operationId" : "get-/files/v3/folders/{folderPath}_getByPath",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Folders", "Pastas" ],
        "summary" : "Excluir a pasta.",
        "description" : "Exclua a pasta pelo caminho.",
        "operationId" : "delete-/files/v3/folders/{folderPath}_archiveByPath",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/folders/update/async" : {
      "post" : {
        "tags" : [ "Folders", "Pastas" ],
        "summary" : "Atualizar propriedades da pasta",
        "description" : "Atualize as propriedades da pasta pelo ID especificado. Essa ação acontece de forma assíncrona e atualizará todos os objetos secundários da pasta.",
        "operationId" : "post-/files/v3/folders/update/async_updateProperties",
        "security" : [ {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    },
    "/files/v3/files/import-from-url/async/tasks/{taskId}/status" : {
      "get" : {
        "tags" : [ "Files", "Arquivos" ],
        "summary" : "Verificar o status da importação.",
        "description" : "Verifique o status da importação solicitada.",
        "operationId" : "get-/files/v3/files/import-from-url/async/tasks/{taskId}/status_checkImport",
        "security" : [ {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "files" : "Read from and write to my Files",
              "files.ui_hidden.read" : "View hidden files"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}