{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Pipelines",
    "description" : "Pipelines represent distinct stages in a workflow, like closing a deal or servicing a support ticket. These endpoints provide access to read and modify pipelines in HubSpot. Pipelines support `deals` and `tickets` object types.\n\n## Pipeline ID validation\n\nWhen calling endpoints that take pipelineId as a parameter, that ID must correspond to an existing, un-archived pipeline. Otherwise the request will fail with a `404 Not Found` response.",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "To streamline customer support processes, use this API to retrieve your existing ticket pipelines and add new stages based on your business needs. Support reps can then assign tickets to those pipeline stages to track progress on customer issues.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Pipelines Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/pipelines"
    } ],
    "x-hubspot-introduction" : "Use the pipelines API to create and manage deal and ticket pipelines. Pipelines enable you to track the status or progress of deals and tickets, such as closing deals and opening support tickets."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  } ],
  "paths" : {
    "/crm/v3/pipelines/{objectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve all pipelines",
        "description" : "Return all pipelines for the object type specified by `{objectType}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}_getAll",
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a pipeline",
        "description" : "Create a new pipeline with the provided property values. The entire pipeline object, including its unique ID, will be returned in the response.",
        "operationId" : "post-/crm/v3/pipelines/{objectType}_create",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Return a pipeline by ID",
        "description" : "Return a single pipeline object identified by its unique `{pipelineId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}_getById",
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Replace a pipeline",
        "operationId" : "put-/crm/v3/pipelines/{objectType}/{pipelineId}_replace",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete a pipeline",
        "operationId" : "delete-/crm/v3/pipelines/{objectType}/{pipelineId}_archive",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "description" : "Perform a partial update of the pipeline identified by `{pipelineId}`. The updated pipeline will be returned in the response.",
        "operationId" : "patch-/crm/v3/pipelines/{objectType}/{pipelineId}_update",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/audit" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Return an audit of all changes to the pipeline",
        "description" : "Return a reverse chronological list of all mutations that have occurred on the pipeline identified by `{pipelineId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/audit_getAudit",
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Return all stages of a pipeline",
        "description" : "Return all the stages associated with the pipeline identified by `{pipelineId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_getAll",
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a pipeline stage",
        "operationId" : "post-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_create",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Return a pipeline stage by ID",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_getById",
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Replace a pipeline stage",
        "description" : "Replace all the properties of an existing pipeline stage with the values provided. The updated stage will be returned in the response.",
        "operationId" : "put-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_replace",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete a pipeline stage",
        "operationId" : "delete-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_archive",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "operationId" : "patch-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_update",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit" : {
      "get" : {
        "tags" : [ "Basic" ],
        "description" : "Return a reverse chronological list of all mutations that have occurred on the pipeline stage identified by `{stageId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit_getAudit",
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "properties-settings-read" : "",
              "properties-settings-write" : "",
              "visitor-identification-access" : ""
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}