{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Pipelines",
    "description" : "Pipelines represent distinct stages in a workflow, like closing a deal or servicing a support ticket. These endpoints provide access to read and modify pipelines in HubSpot. Pipelines support `deals` and `tickets` object types.\n\n## Pipeline ID validation\n\nWhen calling endpoints that take pipelineId as a parameter, that ID must correspond to an existing, un-archived pipeline. Otherwise the request will fail with a `404 Not Found` response.",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "To streamline customer support processes, use this API to retrieve your existing ticket pipelines and add new stages based on your business needs. Support reps can then assign tickets to those pipeline stages to track progress on customer issues.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Pipelines Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/crm/pipelines"
    } ],
    "x-hubspot-introduction" : "Use the pipelines API to create and manage deal and ticket pipelines. Pipelines enable you to track the status or progress of deals and tickets, such as closing deals and opening support tickets."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Pipeline Stage Audits"
  }, {
    "name" : "Pipelines"
  }, {
    "name" : "Pipeline Audits"
  }, {
    "name" : "Pipeline Stages"
  } ],
  "paths" : {
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit" : {
      "get" : {
        "tags" : [ "Pipeline Stage Audits" ],
        "summary" : "パイプラインステージに対する全ての変更の監査を返す",
        "description" : "「{stageId}」で識別されるパイプラインステージで発生した全ての変換のリスト（新しい順）を返します。",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit_getAudit",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}" : {
      "get" : {
        "tags" : [ "Pipelines" ],
        "summary" : "IDを基準にパイプラインを返す",
        "description" : "固有の「{pipelineId}」で識別される1つのパイプラインオブジェクトを返します。",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}_getById",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Pipelines" ],
        "summary" : "パイプラインを置換",
        "description" : "既存のパイプラインの全てのプロパティーを指定された値で置換します。これにより、既存のパイプラインステージが上書きされます。更新されたパイプラインはレスポンスで返されます。",
        "operationId" : "put-/crm/v3/pipelines/{objectType}/{pipelineId}_replace",
        "security" : [ {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Pipelines" ],
        "summary" : "パイプラインを削除",
        "description" : "「{pipelineId}」で識別されるパイプラインを削除します。",
        "operationId" : "delete-/crm/v3/pipelines/{objectType}/{pipelineId}_archive",
        "security" : [ {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Pipelines" ],
        "summary" : "パイプラインを更新",
        "description" : "「{pipelineId}」で識別されるパイプラインの部分的な更新を実行します。更新されたパイプラインはレスポンスで返されます。",
        "operationId" : "patch-/crm/v3/pipelines/{objectType}/{pipelineId}_update",
        "security" : [ {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/audit" : {
      "get" : {
        "tags" : [ "Pipeline Audits" ],
        "summary" : "パイプラインに対する全ての変更の監査を返す",
        "description" : "「{pipelineId}」で識別されるパイプラインで発生した全ての変換のリスト（新しい順）を返します。",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/audit_getAudit",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages" : {
      "get" : {
        "tags" : [ "Pipeline Stages" ],
        "summary" : "パイプラインの全てのステージを返す",
        "description" : "「{pipelineId}」で識別されるパイプラインに関連付けられた全てのステージを返します。",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_getAll",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Pipeline Stages" ],
        "summary" : "パイプラインステージを作成",
        "description" : "「{pipelineId}」で識別されるパイプラインに関連付けられた新しいステージを作成します。ステージオブジェクト全体（その固有IDを含む）がレスポンスで返されます。",
        "operationId" : "post-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_create",
        "security" : [ {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      }
    },
    "/crm/v3/pipelines/{objectType}" : {
      "get" : {
        "tags" : [ "Pipelines" ],
        "summary" : "全てのパイプラインを取得",
        "description" : "「{objectType}」で指定されたオブジェクトタイプの全てのパイプラインを返します。",
        "operationId" : "get-/crm/v3/pipelines/{objectType}_getAll",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Pipelines" ],
        "summary" : "パイプラインを作成",
        "description" : "指定されたプロパティー値を使用して新しパイプラインを作成します。パイプラインオブジェクト全体（その固有IDを含む）がレスポンスで返されます。",
        "operationId" : "post-/crm/v3/pipelines/{objectType}_create",
        "security" : [ {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}" : {
      "get" : {
        "tags" : [ "Pipeline Stages" ],
        "summary" : "IDを基準にパイプラインステージを返す",
        "description" : "「{pipelineId}」で識別されるパイプラインに関連付けられた、「{stageId}」で識別されるステージを返します。",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_getById",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2" : [ "crm.objects.owners.read" ]
        }, {
          "oauth2_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.marketing_events.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.marketing_events.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.schemas.commercepayments.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.schemas.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Pipeline Stages" ],
        "summary" : "パイプラインステージを置換",
        "description" : "既存のパイプラインステージの全てのプロパティーを指定された値で置換します。更新されたステージはレスポンスで返されます。",
        "operationId" : "put-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_replace",
        "security" : [ {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Pipeline Stages" ],
        "summary" : "パイプラインステージを削除",
        "description" : "「{pipelineId}」で識別されるパイプラインに関連付けられた、「{stageId}」で識別されるパイプラインステージを削除します。",
        "operationId" : "delete-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_archive",
        "security" : [ {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Pipeline Stages" ],
        "summary" : "パイプラインステージを更新",
        "description" : "「{pipelineId}」で識別されるパイプラインに関連付けられた、「{stageId}」で識別されるパイプラインステージの部分的な更新を実行します。この更新に含まれていないプロパティーは既存の値のままになります。更新されたステージはレスポンスで返されます。",
        "operationId" : "patch-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_update",
        "security" : [ {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.orders.write" ]
        }, {
          "private_apps" : [ "crm.schemas.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.carts.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "crm.pipelines.orders.write" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.carts.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "tickets" : "Read and write tickets",
              "crm.objects.marketing_events.read" : "Read marketing events",
              "crm.schemas.custom.read" : "View custom object definitions",
              "crm.pipelines.orders.read" : "View details about your cart pipelines including pipeline stage information",
              "media_bridge.read" : "Read media and media events",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.feedback_submissions.read" : "View feedback survey submissions",
              "timeline" : "Create timeline events",
              "e-commerce" : "e-commerce",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.marketing_events.write" : "Write marketing events",
              "crm.objects.goals.read" : "Read goals",
              "crm.pipelines.orders.write" : "Create, delete, or make to your order pipelines or their respective stages"
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.contacts.write" : " ",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.companies.read" : " ",
              "crm.objects.invoices.read" : "Read invoices objects",
              "crm.objects.line_items.write" : "Line Items",
              "crm.schemas.subscriptions.read" : "Read subscriptions schema",
              "crm.schemas.line_items.read" : "Line Items schemas",
              "crm.objects.deals.read" : " ",
              "crm.objects.owners.read" : " ",
              "crm.schemas.invoices.read" : "Read invoices schema",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.contacts.read" : " ",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.schemas.deals.read" : " ",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.quotes.read" : "Quotes",
              "crm.schemas.commercepayments.read" : "Read the COMMERCE_PAYMENT properties.",
              "crm.schemas.companies.read" : " ",
              "crm.schemas.quotes.read" : "Quotes schemas",
              "crm.objects.orders.read" : "Read Orders",
              "crm.schemas.contacts.read" : " ",
              "crm.objects.companies.write" : " ",
              "crm.schemas.orders.read" : "Read order property settings",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.deals.write" : " ",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.schemas.carts.read" : "Read cart property settings",
              "crm.objects.orders.write" : "Write orders",
              "crm.schemas.contacts.write" : " ",
              "crm.schemas.orders.write" : "Write order property settings",
              "crm.schemas.companies.write" : " ",
              "crm.schemas.carts.write" : "Write cart property settings",
              "crm.objects.carts.write" : "Write cart",
              "crm.schemas.deals.write" : " ",
              "crm.objects.users.write" : "Write User CRM objects"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}