{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Calling Extensions",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  } ],
  "paths" : {
    "/crm/extensions/calling/2026-03/inbound-call" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Submit details of an inbound call to the CRM.",
        "description" : "This endpoint allows you to submit information about an inbound call to the CRM system. The request must include details such as the external call ID, call status, and involved phone numbers. This operation helps in logging and managing inbound call data within the CRM.",
        "operationId" : "post-/crm/extensions/calling/2026-03/inbound-call_/crm/v3/extensions/calling/inbound-call",
        "security" : [ {
          "app_cookie" : [ "contacts-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "contacts-write" ]
        }, {
          "oauth2" : [ "contacts-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/extensions/calling/2026-03/recordings/ready" : {
      "post" : {
        "tags" : [ "Advanced" ],
        "summary" : "Mark a call recording as ready for retrieval.",
        "description" : "This endpoint is used to mark a call recording as ready. It requires the engagementId to identify the specific recording.",
        "operationId" : "post-/crm/extensions/calling/2026-03/recordings/ready_markAsReady",
        "security" : [ {
          "app_cookie" : [ "contacts-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "contacts-write" ]
        }, {
          "oauth2" : [ "contacts-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/extensions/calling/2026-03/{appId}/settings" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve the calling extension settings for a specific app.",
        "description" : "Retrieve the current settings of the calling extension for the specified appId. ",
        "operationId" : "get-/crm/extensions/calling/2026-03/{appId}/settings_get",
        "security" : [ {
          "app_cookie" : [ "developers-read" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-read" ]
        }, {
          "oauth2" : [ "developers-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create new calling extension settings for a specific app.",
        "description" : "Create new settings for the calling extension associated with the specified appId.",
        "operationId" : "post-/crm/extensions/calling/2026-03/{appId}/settings_create",
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete the calling extension settings for a specific app.",
        "description" : "Remove the calling extension settings associated with the specified appId. This action cannot be undone.",
        "operationId" : "delete-/crm/extensions/calling/2026-03/{appId}/settings_remove",
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update the calling extension settings for a specific app.",
        "description" : "Modify existing calling extension settings for the specified appId. Only the fields provided in the request will be updated.",
        "operationId" : "patch-/crm/extensions/calling/2026-03/{appId}/settings_update",
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/extensions/calling/2026-03/{appId}/settings/channel-connection" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve the channel connection settings for a specific app.",
        "description" : "Access the current channel connection settings for the specified app.",
        "operationId" : "get-/crm/extensions/calling/2026-03/{appId}/settings/channel-connection_get",
        "security" : [ {
          "app_cookie" : [ "developers-read" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-read" ]
        }, {
          "oauth2" : [ "developers-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create new channel connection settings for a specific app.",
        "description" : "Establish new channel connection settings for the specified app.",
        "operationId" : "post-/crm/extensions/calling/2026-03/{appId}/settings/channel-connection_create",
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Remove the channel connection settings for a specific app.",
        "description" : "Delete the channel connection settings associated with the specified app.",
        "operationId" : "delete-/crm/extensions/calling/2026-03/{appId}/settings/channel-connection_remove",
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update the channel connection settings for a specific app.",
        "description" : "Modify the existing channel connection settings for the specified app.",
        "operationId" : "patch-/crm/extensions/calling/2026-03/{appId}/settings/channel-connection_update",
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/extensions/calling/2026-03/{appId}/settings/recording" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve recording settings for an app.",
        "description" : "Retrieve the current recording settings for a specific app using the provided app ID.",
        "operationId" : "get-/crm/extensions/calling/2026-03/{appId}/settings/recording_get",
        "security" : [ {
          "app_cookie" : [ "developers-read" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-read" ]
        }, {
          "oauth2" : [ "developers-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create recording settings for an app.",
        "description" : "Create new recording settings for a specific app using the provided app ID.",
        "operationId" : "post-/crm/extensions/calling/2026-03/{appId}/settings/recording_create",
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update recording settings for an app.",
        "description" : "Update the recording settings for a specific app using the provided app ID.",
        "operationId" : "patch-/crm/extensions/calling/2026-03/{appId}/settings/recording_update",
        "security" : [ {
          "app_cookie" : [ "developers-write" ]
        }, {
          "developer_hapikey" : [ ]
        }, {
          "internal_cookie" : [ "developers-write" ]
        }, {
          "oauth2" : [ "developers-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "contacts-read" : "",
              "contacts-write" : "",
              "crm-transcription-api-read" : "",
              "crm-transcription-api-write" : "",
              "developers-read" : "",
              "developers-write" : ""
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}