{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "関連付けスキーマ",
    "description" : "Associations define the relationships between objects in HubSpot. These endpoints allow you to create, read, and remove associations.",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "STARTER"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "コンタクトと会社を関連付けるには、このAPIを使用して必要なassociationTypeIdとassociationCategoryを取得します。",
    "x-hubspot-related-documentation" : [ {
      "name" : "Associations Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/crm/associations"
    } ],
    "x-hubspot-introduction" : "関連付けスキーマAPIを使用して、さまざまなタイプのCRMレコードとアクティビティーの相互関係を把握したり、独自のカスタム関連付けを定義したりします。"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "タイプ"
  } ],
  "paths" : {
    "/crm/v3/associations/{fromObjectType}/{toObjectType}/types" : {
      "get" : {
        "tags" : [ "タイプ" ],
        "summary" : "関連付けタイプを示す",
        "description" : "2つのオブジェクトタイプ間で使用できる全ての有効な関連付けタイプを示します",
        "operationId" : "get-/crm/v3/associations/{fromObjectType}/{toObjectType}/types_getAll",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.read" ]
        }, {
          "oauth2" : [ "crm.objects.orders.read" ]
        }, {
          "private_apps" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "private_apps" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2" : [ "crm.objects.carts.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.orders.write" ]
        }, {
          "oauth2" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.commercepayments.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.invoices.read" ]
        }, {
          "private_apps" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.write" ]
        }, {
          "oauth2" : [ "crm.objects.leads.read" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.write" ]
        }, {
          "private_apps" : [ "crm.objects.leads.read" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.custom.read" ]
        }, {
          "oauth2" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.line_items.write" ]
        }, {
          "private_apps" : [ "crm.objects.carts.read" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.partner-clients.read" ]
        }, {
          "oauth2" : [ "crm.objects.carts.read" ]
        }, {
          "private_apps" : [ "crm.objects.partner-clients.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "e-commerce" : "e-commerce",
              "crm.objects.custom.write" : "Change custom object records",
              "media_bridge.read" : "Read media and media events",
              "crm.objects.goals.read" : "Read goals",
              "tickets" : "Read and write tickets",
              "crm.objects.custom.read" : "View custom object records"
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.companies.write" : " ",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.contacts.read" : " ",
              "crm.objects.invoices.read" : "Read invoices objects",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.partner-clients.write" : "Modify Partner Client CRM objects",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.deals.read" : " ",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.commercepayments.read" : "Read the COMMERCE_PAYMENT object.",
              "crm.objects.contacts.write" : " ",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.companies.read" : " ",
              "crm.objects.carts.write" : "Write cart",
              "crm.objects.deals.write" : " ",
              "crm.objects.users.write" : "Write User CRM objects",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.leads.read" : "Read lead objects"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER"
  },
  "x-hubspot-documentation-banner" : "NONE"
}