{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Feedback Submissions",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "PROFESSIONAL",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "To prepare for an upcoming product redesign, programmatically retrieve all feedback survey responses to better understand customer sentiment.",
    "x-hubspot-introduction" : "Use the feedback submissions API to retrieve information submitted to your NPS, CSAT, CES, and custom feedback surveys."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/objects/2026-03/feedback_submissions" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List",
        "description" : "Read a page of feedback submissions. Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/objects/2026-03/feedback_submissions_getPage",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read", "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read", "crm.objects.feedback_submissions.read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/objects/2026-03/feedback_submissions/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of feedback submissions by internal ID, or unique property values",
        "description" : "Retrieve records by record ID or include the `idProperty` parameter to retrieve records by a custom unique value property. ",
        "operationId" : "post-/crm/objects/2026-03/feedback_submissions/batch/read_read",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read", "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read", "crm.objects.feedback_submissions.read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/objects/2026-03/feedback_submissions/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "summary" : "Search for feedback submissions using specified criteria.",
        "description" : "Execute a search to retrieve feedback submissions based on defined filters, properties, and sorting options.",
        "operationId" : "post-/crm/objects/2026-03/feedback_submissions/search_doSearch",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read", "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read", "crm.objects.feedback_submissions.read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY",
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/objects/2026-03/feedback_submissions/{feedbackSubmissionId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read",
        "description" : "Read an Object identified by `{feedbackSubmissionId}`. `{feedbackSubmissionId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/objects/2026-03/feedback_submissions/{feedbackSubmissionId}_getById",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read", "crm.objects.feedback_submissions.read" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read", "crm.objects.feedback_submissions.read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/objects/2026-03/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Batch" ],
        "operationId" : "put-/crm/objects/2026-03/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}_/crm/objects/2026-03/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_/crm/objects/2026-03/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}",
        "security" : [ {
          "app_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "oauth2" : [ "crm-public-object-api-access", "oauth", "oauth-access" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm-public-object-api-access" : "",
              "crm.objects.contacts.read" : "",
              "crm.objects.feedback_submissions.read" : "",
              "developers-read" : "",
              "developers-write" : "",
              "marketing-events-read" : "",
              "marketing-events-write" : "",
              "oauth" : "",
              "oauth-access" : ""
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "PROFESSIONAL",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}