{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Properties",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2025-09",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  } ],
  "paths" : {
    "/crm/properties/2025-09/{objectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read all properties",
        "description" : "Read all existing properties for the specified object type and HubSpot account.",
        "operationId" : "get-/crm/properties/2025-09/{objectType}_/crm/properties/2025-09/{objectType}",
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a property",
        "description" : "Create and return a copy of a new property for the specified object type.",
        "operationId" : "post-/crm/properties/2025-09/{objectType}_/crm/properties/2025-09/{objectType}",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/properties/2025-09/{objectType}/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Archive a batch of properties",
        "description" : "Archive a provided list of properties. This method will return a 204 No Content response on success regardless of the initial state of the property (e.g. active, already archived, non-existent).",
        "operationId" : "post-/crm/properties/2025-09/{objectType}/batch/archive_/crm/properties/2025-09/{objectType}/batch/archive",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/properties/2025-09/{objectType}/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of properties",
        "description" : "Create a batch of properties using the same rules as when creating an individual property.",
        "operationId" : "post-/crm/properties/2025-09/{objectType}/batch/create_/crm/properties/2025-09/{objectType}/batch/create",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/properties/2025-09/{objectType}/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of properties",
        "description" : "Read a provided list of properties.",
        "operationId" : "post-/crm/properties/2025-09/{objectType}/batch/read_/crm/properties/2025-09/{objectType}/batch/read",
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/properties/2025-09/{objectType}/groups" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read all property groups",
        "description" : "Read all existing property groups for the specified object type and HubSpot account.",
        "operationId" : "get-/crm/properties/2025-09/{objectType}/groups_/crm/properties/2025-09/{objectType}/groups",
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a property group",
        "description" : "Create and return a copy of a new property group.",
        "operationId" : "post-/crm/properties/2025-09/{objectType}/groups_/crm/properties/2025-09/{objectType}/groups",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/properties/2025-09/{objectType}/groups/{groupName}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read a property group",
        "description" : "Read a property group identified by {groupName}.",
        "operationId" : "get-/crm/properties/2025-09/{objectType}/groups/{groupName}_/crm/properties/2025-09/{objectType}/groups/{groupName}",
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archive a property group",
        "description" : "Move a property group identified by {groupName} to the recycling bin.",
        "operationId" : "delete-/crm/properties/2025-09/{objectType}/groups/{groupName}_/crm/properties/2025-09/{objectType}/groups/{groupName}",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update a property group",
        "description" : "Perform a partial update of a property group identified by {groupName}. Provided fields will be overwritten.",
        "operationId" : "patch-/crm/properties/2025-09/{objectType}/groups/{groupName}_/crm/properties/2025-09/{objectType}/groups/{groupName}",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/properties/2025-09/{objectType}/{propertyName}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read a property",
        "description" : "Read a property identified by {propertyName}.",
        "operationId" : "get-/crm/properties/2025-09/{objectType}/{propertyName}_/crm/properties/2025-09/{objectType}/{propertyName}",
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archive a property",
        "description" : "Move a property identified by {propertyName} to the recycling bin.",
        "operationId" : "delete-/crm/properties/2025-09/{objectType}/{propertyName}_/crm/properties/2025-09/{objectType}/{propertyName}",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update a property",
        "description" : "Perform a partial update of a property identified by '{propertyName}'. Provided fields will be overwritten.",
        "operationId" : "patch-/crm/properties/2025-09/{objectType}/{propertyName}_/crm/properties/2025-09/{objectType}/{propertyName}",
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "properties-settings-read" : "",
              "properties-settings-write" : ""
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}