{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Conversations Custom Channels",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "PROFESSIONAL",
      "service" : "PROFESSIONAL",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "Allow admins to install an integration with a third-party messaging channel that your team uses to communicate with customers, to allow users in your account to manage their conversations for that channel directly in HubSpot.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Custom Channels Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/conversations/create-custom-channels"
    } ],
    "x-hubspot-introduction" : "Use the custom channels API to create custom channels to build a bridge between an external message service and HubSpot's inbox or help desk features. "
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "External_Channel_Accounts"
  }, {
    "name" : "External_Channel_Account_Staging_Tokens"
  }, {
    "name" : "External_Channels"
  }, {
    "name" : "External_Messages"
  } ],
  "paths" : {
    "/conversations/v3/custom-channels/{channelId}/messages/{messageId}" : {
      "get" : {
        "tags" : [ "External_Messages" ],
        "summary" : "Get a message",
        "description" : "Get the details for a specific message sent over a custom channel",
        "operationId" : "get-/conversations/v3/custom-channels/{channelId}/messages/{messageId}",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "External_Messages" ],
        "summary" : "Update a message ",
        "description" : "Update a message's status to indicate if it was successfully sent, failed to send, or was read. For failed messages, this can also include the error message for the failure.",
        "operationId" : "patch-/conversations/v3/custom-channels/{channelId}/messages/{messageId}",
        "security" : [ {
          "private_apps" : [ "conversations.custom_channels.write" ]
        }, {
          "oauth2" : [ "conversations.custom_channels.write" ]
        } ]
      }
    },
    "/conversations/v3/custom-channels/{channelId}" : {
      "get" : {
        "tags" : [ "External_Channels" ],
        "summary" : "Get a custom channel",
        "description" : "Retrieve the details about a custom channel. This API allows you to see a custom channel's current capabilties and other configuration metadata",
        "operationId" : "get-/conversations/v3/custom-channels/{channelId}",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "External_Channels" ],
        "summary" : "Archive a custom channel",
        "description" : "Archive an existing registered custom channel",
        "operationId" : "delete-/conversations/v3/custom-channels/{channelId}",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "patch" : {
        "tags" : [ "External_Channels" ],
        "summary" : "Update a custom channel",
        "description" : "Update the capabilities for an existing. You can also use it to update the channel's webhookUri and its channelAccountConnectionRedirectUrl.",
        "operationId" : "patch-/conversations/v3/custom-channels/{channelId}",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/conversations/v3/custom-channels/{channelId}/channel-account-staging-tokens/{accountToken}" : {
      "patch" : {
        "tags" : [ "External_Channel_Account_Staging_Tokens" ],
        "summary" : "Update a channel account staging token",
        "description" : "Update a channel account staging token's account name and delivery identifier. This information will be applied to the channel account created from this staging token. This is used for public apps.",
        "operationId" : "patch-/conversations/v3/custom-channels/{channelId}/channel-account-staging-tokens/{accountToken}",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.write" ]
        }, {
          "oauth2" : [ "conversations.custom_channels.write" ]
        } ]
      }
    },
    "/conversations/v3/custom-channels/{channelId}/channel-accounts" : {
      "get" : {
        "tags" : [ "External_Channel_Accounts" ],
        "summary" : "Get accounts for a channel",
        "description" : "Retrieve a list of accounts for a custom channel.",
        "operationId" : "get-/conversations/v3/custom-channels/{channelId}/channel-accounts",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.write" ]
        }, {
          "oauth2" : [ "conversations.custom_channels.write" ]
        } ]
      },
      "post" : {
        "tags" : [ "External_Channel_Accounts" ],
        "summary" : "Create a channel account",
        "description" : "Create a new account for a channel. Multiple accounts can communicate over a single channel using different delivery identifiers.",
        "operationId" : "post-/conversations/v3/custom-channels/{channelId}/channel-accounts",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.write" ]
        }, {
          "oauth2" : [ "conversations.custom_channels.write" ]
        } ]
      }
    },
    "/conversations/v3/custom-channels/{channelId}/channel-accounts/{channelAccountId}" : {
      "get" : {
        "tags" : [ "External_Channel_Accounts" ],
        "summary" : "Get a channel account by id",
        "description" : "Retrieve the details for a specific channel account. This contains all the metadata about your channel account, including its channel, associated inbox id, and delivery identifier information.",
        "operationId" : "get-/conversations/v3/custom-channels/{channelId}/channel-accounts/{channelAccountId}",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.write" ]
        }, {
          "oauth2" : [ "conversations.custom_channels.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "External_Channel_Accounts" ],
        "summary" : "Update a channel account",
        "description" : "This API is used to update the name of the channel account and it's isAuthorized status. Setting to isAuthorized flag to False disables the channel account.",
        "operationId" : "patch-/conversations/v3/custom-channels/{channelId}/channel-accounts/{channelAccountId}",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.write" ]
        }, {
          "oauth2" : [ "conversations.custom_channels.write" ]
        } ]
      }
    },
    "/conversations/v3/custom-channels/" : {
      "get" : {
        "tags" : [ "External_Channels" ],
        "summary" : "Get all channels for app",
        "description" : "Retrieve all custom channels associated with the app.",
        "operationId" : "get-/conversations/v3/custom-channels/",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "External_Channels" ],
        "summary" : "Create a custom channel",
        "description" : "Register a new channel along with its capabilities and the webhook url that will be used to receive messages published over the channel",
        "operationId" : "post-/conversations/v3/custom-channels/",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/conversations/v3/custom-channels/{channelId}/messages" : {
      "post" : {
        "tags" : [ "External_Messages" ],
        "summary" : "Publish a message",
        "description" : "Publish a message over your custom channel",
        "operationId" : "post-/conversations/v3/custom-channels/{channelId}/messages",
        "security" : [ {
          "private_apps" : [ "conversations.custom_channels.write" ]
        }, {
          "oauth2" : [ "conversations.custom_channels.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "conversations.custom_channels.read" : "Read messages and manage Channel Accounts for an included Custom Channel.",
              "conversations.custom_channels.write" : "Publish messages into HubSpot and manage Channel Accounts for an included Custom Channel."
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "PROFESSIONAL",
    "service" : "PROFESSIONAL",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}