{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Conversations Custom Channels",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "PROFESSIONAL",
      "service" : "PROFESSIONAL",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "Allow admins to install an integration with a third-party messaging channel that your team uses to communicate with customers, to allow users in your account to manage their conversations for that channel directly in HubSpot.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Custom Channels Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/conversations/create-custom-channels"
    } ],
    "x-hubspot-introduction" : "Use the custom channels API to create custom channels to build a bridge between an external message service and HubSpot's inbox or help desk features. "
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "External_Channel_Account_Staging_Tokens"
  }, {
    "name" : "External_Channel_Accounts"
  }, {
    "name" : "External_Channels"
  }, {
    "name" : "External_Messages"
  } ],
  "paths" : {
    "/conversations/v3/custom-channels/" : {
      "get" : {
        "tags" : [ "External_Channels" ],
        "operationId" : "get-/conversations/v3/custom-channels/",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "External_Channels" ],
        "operationId" : "post-/conversations/v3/custom-channels/",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/conversations/v3/custom-channels/{channelId}" : {
      "get" : {
        "tags" : [ "External_Channels" ],
        "operationId" : "get-/conversations/v3/custom-channels/{channelId}",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "External_Channels" ],
        "operationId" : "delete-/conversations/v3/custom-channels/{channelId}",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "patch" : {
        "tags" : [ "External_Channels" ],
        "operationId" : "patch-/conversations/v3/custom-channels/{channelId}",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/conversations/v3/custom-channels/{channelId}/channel-account-staging-tokens/{accountToken}" : {
      "patch" : {
        "tags" : [ "External_Channel_Account_Staging_Tokens" ],
        "operationId" : "patch-/conversations/v3/custom-channels/{channelId}/channel-account-staging-tokens/{accountToken}",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.read" ]
        }, {
          "oauth2" : [ "conversations.custom_channels.write" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.write" ]
        } ]
      }
    },
    "/conversations/v3/custom-channels/{channelId}/channel-accounts" : {
      "get" : {
        "tags" : [ "External_Channel_Accounts" ],
        "operationId" : "get-/conversations/v3/custom-channels/{channelId}/channel-accounts",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.read" ]
        }, {
          "oauth2" : [ "conversations.custom_channels.write" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.write" ]
        } ]
      },
      "post" : {
        "tags" : [ "External_Channel_Accounts" ],
        "operationId" : "post-/conversations/v3/custom-channels/{channelId}/channel-accounts",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.read" ]
        }, {
          "oauth2" : [ "conversations.custom_channels.write" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.write" ]
        } ]
      }
    },
    "/conversations/v3/custom-channels/{channelId}/channel-accounts/{channelAccountId}" : {
      "get" : {
        "tags" : [ "External_Channel_Accounts" ],
        "operationId" : "get-/conversations/v3/custom-channels/{channelId}/channel-accounts/{channelAccountId}",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.read" ]
        }, {
          "oauth2" : [ "conversations.custom_channels.write" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "External_Channel_Accounts" ],
        "operationId" : "patch-/conversations/v3/custom-channels/{channelId}/channel-accounts/{channelAccountId}",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.read" ]
        }, {
          "oauth2" : [ "conversations.custom_channels.write" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.write" ]
        } ]
      }
    },
    "/conversations/v3/custom-channels/{channelId}/messages" : {
      "post" : {
        "tags" : [ "External_Messages" ],
        "operationId" : "post-/conversations/v3/custom-channels/{channelId}/messages",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.write" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.write" ]
        } ]
      }
    },
    "/conversations/v3/custom-channels/{channelId}/messages/{messageId}" : {
      "get" : {
        "tags" : [ "External_Messages" ],
        "operationId" : "get-/conversations/v3/custom-channels/{channelId}/messages/{messageId}",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.read" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "External_Messages" ],
        "operationId" : "patch-/conversations/v3/custom-channels/{channelId}/messages/{messageId}",
        "security" : [ {
          "oauth2" : [ "conversations.custom_channels.write" ]
        }, {
          "private_apps" : [ "conversations.custom_channels.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "conversations.custom_channels.read" : "Read messages and manage Channel Accounts for an included Custom Channel.",
              "conversations.custom_channels.write" : "Publish messages into HubSpot and manage Channel Accounts for an included Custom Channel."
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "PROFESSIONAL",
    "service" : "PROFESSIONAL",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}