{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Commerce Payments Settings",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2027-03-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  } ],
  "paths" : {
    "/commerce/payments-settings/2027-03-beta/payments-settings/billing" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve billing settings",
        "description" : "Retrieve the current billing settings for your HubSpot account's payment settings. This endpoint allows you to access billing configurations, which can be useful for managing and reviewing your account's payment setup.",
        "operationId" : "get-/commerce/payments-settings/2027-03-beta/payments-settings/billing",
        "security" : [ {
          "oauth2" : [ "contracts-read" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "oauth2" : [ "payment-links-read" ]
        }, {
          "oauth2" : [ "payments-checkout-settings-read" ]
        }, {
          "oauth2" : [ "cpq.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "cpq.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update billing settings",
        "description" : "Update the billing settings for your HubSpot account's payment settings. This endpoint allows you to modify the billing configurations, which can be essential for managing how payments are processed and billed. Ensure you have the necessary permissions to write payment checkout settings before making changes.",
        "operationId" : "patch-/commerce/payments-settings/2027-03-beta/payments-settings/billing",
        "security" : [ {
          "oauth2" : [ "payments-checkout-settings-write" ]
        } ]
      }
    },
    "/commerce/payments-settings/2027-03-beta/payments-settings/checkout-fees" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve checkout fees",
        "description" : "Retrieve the current checkout fee settings for your HubSpot account. This endpoint provides information about any fees applied during the checkout process, which can be useful for understanding transaction costs and configuring payment settings.",
        "operationId" : "get-/commerce/payments-settings/2027-03-beta/payments-settings/checkout-fees",
        "security" : [ {
          "oauth2" : [ "contracts-read" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "oauth2" : [ "payment-links-read" ]
        }, {
          "oauth2" : [ "payments-checkout-settings-read" ]
        }, {
          "oauth2" : [ "cpq.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "cpq.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update checkout fees",
        "description" : "Update the checkout fees settings in your HubSpot account. This endpoint allows you to modify the configuration of checkout fees, which can be useful for adjusting fee structures or implementing new pricing strategies. Ensure that the request body contains the necessary details for the update.",
        "operationId" : "patch-/commerce/payments-settings/2027-03-beta/payments-settings/checkout-fees",
        "security" : [ {
          "oauth2" : [ "payments-checkout-settings-write" ]
        } ]
      }
    },
    "/commerce/payments-settings/2027-03-beta/payments-settings/checkout-fees/{checkoutFeeId}" : {
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete checkout fee",
        "description" : "Remove a specific checkout fee from the payments settings in your HubSpot account. This operation is useful for managing and updating the fees associated with checkout processes. Ensure you have the necessary permissions to perform this action.",
        "operationId" : "delete-/commerce/payments-settings/2027-03-beta/payments-settings/checkout-fees/{checkoutFeeId}",
        "security" : [ {
          "oauth2" : [ "payments-checkout-settings-write" ]
        } ]
      }
    },
    "/commerce/payments-settings/2027-03-beta/payments-settings/policy" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve policy settings",
        "description" : "Retrieve the current payment policy settings for your HubSpot account. This endpoint provides access to the policy configurations related to payment settings, allowing you to review the existing setup. It is useful for ensuring compliance with organizational or regulatory requirements by reviewing the policy settings in place.",
        "operationId" : "get-/commerce/payments-settings/2027-03-beta/payments-settings/policy",
        "security" : [ {
          "oauth2" : [ "contracts-read" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "oauth2" : [ "payment-links-read" ]
        }, {
          "oauth2" : [ "payments-checkout-settings-read" ]
        }, {
          "oauth2" : [ "cpq.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "cpq.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update policy settings",
        "description" : "Update the payment policy settings for your HubSpot account. This endpoint allows you to modify existing policy configurations, which can include terms and conditions related to payments. Ensure that you have the necessary permissions to write payment checkout settings before making changes.",
        "operationId" : "patch-/commerce/payments-settings/2027-03-beta/payments-settings/policy",
        "security" : [ {
          "oauth2" : [ "payments-checkout-settings-write" ]
        } ]
      }
    },
    "/commerce/payments-settings/2027-03-beta/payments-settings/shipping" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve shipping settings",
        "description" : "Retrieve the current shipping settings for your HubSpot account. This endpoint provides information about the configured shipping options, which can be useful for managing and reviewing your shipping policies and configurations.",
        "operationId" : "get-/commerce/payments-settings/2027-03-beta/payments-settings/shipping",
        "security" : [ {
          "oauth2" : [ "contracts-read" ]
        }, {
          "oauth2" : [ "crm.objects.invoices.read" ]
        }, {
          "oauth2" : [ "crm.schemas.invoices.read" ]
        }, {
          "oauth2" : [ "payment-links-read" ]
        }, {
          "oauth2" : [ "payments-checkout-settings-read" ]
        }, {
          "oauth2" : [ "cpq.quotes.write" ]
        }, {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "cpq.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.subscriptions.read" ]
        }, {
          "oauth2" : [ "crm.schemas.subscriptions.read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update shipping settings",
        "description" : "Update the shipping settings for your HubSpot account. This endpoint allows you to modify existing shipping configurations to better suit your business needs. Ensure that the request body contains the necessary fields as defined in the UpdateShippingSettingsPublicRequest schema.",
        "operationId" : "patch-/commerce/payments-settings/2027-03-beta/payments-settings/shipping",
        "security" : [ {
          "oauth2" : [ "payments-checkout-settings-write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "contracts-read" : "",
              "cpq.quotes.read" : "",
              "cpq.quotes.write" : "",
              "crm.objects.invoices.read" : "",
              "crm.objects.subscriptions.read" : "",
              "payment-links-read" : "",
              "payments-checkout-settings-read" : "",
              "payments-checkout-settings-write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}