{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Lists",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09-beta",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/lists/2026-09-beta" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List",
        "description" : "Retrieve a list of CRM lists in your HubSpot account. This endpoint allows you to filter the lists by their IDs and optionally include filters applied to the lists. It is useful for managing and organizing your CRM data by accessing specific lists.",
        "operationId" : "get-/crm/lists/2026-09-beta",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create List",
        "description" : "Create a new list in your HubSpot account using the specified parameters. This endpoint allows you to define the properties and criteria for the list, which can be used for organizing and managing contacts or other CRM objects.",
        "operationId" : "post-/crm/lists/2026-09-beta",
        "security" : [ {
          "oauth2" : [ "crm.lists.write" ]
        }, {
          "oauth2" : [ "cms.membership.access_groups.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    },
    "/crm/lists/2026-09-beta/all" : {
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "List all",
        "description" : "Retrieve all lists in the CRM system. This endpoint allows you to fetch a comprehensive list of all available lists, which can be useful for managing and organizing your CRM data effectively.",
        "operationId" : "post-/crm/lists/2026-09-beta/all_/crm/lists/2026-09-beta/all",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/lists/2026-09-beta/folders" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List folders",
        "description" : "Retrieve a list of folders within the CRM lists. This endpoint can be used to navigate through the folder structure by specifying a folder ID. It is useful for organizing and managing lists within folders.",
        "operationId" : "get-/crm/lists/2026-09-beta/folders",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create Folder",
        "description" : "Create a new folder within the CRM lists in your HubSpot account. This operation allows you to organize your lists into folders for better management and accessibility.",
        "operationId" : "post-/crm/lists/2026-09-beta/folders",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    },
    "/crm/lists/2026-09-beta/folders/move-list" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Move List",
        "description" : "Move a list to a different folder within your HubSpot account. This operation requires specifying the list and the target folder. It is useful for organizing lists into different categories or structures.",
        "operationId" : "put-/crm/lists/2026-09-beta/folders/move-list",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    },
    "/crm/lists/2026-09-beta/folders/{folderId}" : {
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete folder",
        "description" : "Delete a specific folder within the CRM lists by providing the folder's unique identifier. This operation is useful for removing folders that are no longer needed or to clean up the folder structure within your CRM lists.",
        "operationId" : "delete-/crm/lists/2026-09-beta/folders/{folderId}",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    },
    "/crm/lists/2026-09-beta/folders/{folderId}/move/{newParentFolderId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Move Folder",
        "description" : "Move a folder to a new parent folder within the CRM lists. This operation is useful for reorganizing your folder structure by changing the parent folder of a specified folder.",
        "operationId" : "put-/crm/lists/2026-09-beta/folders/{folderId}/move/{newParentFolderId}",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    },
    "/crm/lists/2026-09-beta/folders/{folderId}/rename" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Rename folder",
        "description" : "Rename an existing folder in the CRM lists by specifying the folder's ID and the new desired name. This can be useful for organizing and updating folder structures within your account.",
        "operationId" : "put-/crm/lists/2026-09-beta/folders/{folderId}/rename",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    },
    "/crm/lists/2026-09-beta/idmapping" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve ID Mapping",
        "description" : "Retrieve the mapping of legacy list IDs to their current IDs in the HubSpot system. This endpoint is useful for migrating or updating systems that rely on legacy list identifiers.",
        "operationId" : "get-/crm/lists/2026-09-beta/idmapping",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Map IDs",
        "description" : "Map legacy list IDs to their corresponding new IDs in the HubSpot system. This endpoint is useful for migrating data from older systems to the current HubSpot structure, ensuring that all list references are updated correctly.",
        "operationId" : "post-/crm/lists/2026-09-beta/idmapping",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/lists/2026-09-beta/object-type-id/{objectTypeId}/name/{listName}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve List",
        "description" : "Retrieve a specific list by its name and object type ID in your HubSpot account. This endpoint allows you to access the details of a list, which can be useful for managing and analyzing your CRM data. You can also choose to include filters in the response.",
        "operationId" : "get-/crm/lists/2026-09-beta/object-type-id/{objectTypeId}/name/{listName}",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    },
    "/crm/lists/2026-09-beta/records/memberships/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch read memberships",
        "description" : "Retrieve batch membership information for records within specified lists. This endpoint is useful for obtaining membership details in bulk, allowing for efficient data retrieval when dealing with multiple records.",
        "operationId" : "post-/crm/lists/2026-09-beta/records/memberships/batch/read",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/lists/2026-09-beta/records/{objectTypeId}/{recordId}/memberships" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve memberships",
        "description" : "Retrieve the list memberships for a specific record within a specified object type. This endpoint is useful for understanding which lists a particular record is a member of, based on the object type and record ID provided.",
        "operationId" : "get-/crm/lists/2026-09-beta/records/{objectTypeId}/{recordId}/memberships",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/lists/2026-09-beta/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "summary" : "Search Lists",
        "description" : "Search for lists within your HubSpot account using various criteria. This endpoint allows you to filter and retrieve lists based on specific search parameters, making it easier to manage and organize your lists effectively.",
        "operationId" : "post-/crm/lists/2026-09-beta/search",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    },
    "/crm/lists/2026-09-beta/{listId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve list",
        "description" : "Retrieve details of a specific list in your HubSpot account using the list's unique identifier. This endpoint allows you to optionally include filters associated with the list in the response.",
        "operationId" : "get-/crm/lists/2026-09-beta/{listId}",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete",
        "description" : "Delete a specific list in your HubSpot account using its unique identifier. This operation will permanently remove the list and its associated data, ensuring it is no longer accessible.",
        "operationId" : "delete-/crm/lists/2026-09-beta/{listId}",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    },
    "/crm/lists/2026-09-beta/{listId}/memberships" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List memberships",
        "description" : "Retrieve the memberships of a specific list in your HubSpot account. This endpoint allows you to paginate through the list memberships using cursor-based pagination. It is useful for obtaining detailed membership information for a given list.",
        "operationId" : "get-/crm/lists/2026-09-beta/{listId}/memberships",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete memberships",
        "description" : "Delete all memberships associated with a specific list in your HubSpot account. This operation is useful when you need to remove all members from a list, effectively clearing its membership data.",
        "operationId" : "delete-/crm/lists/2026-09-beta/{listId}/memberships",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/lists/2026-09-beta/{listId}/memberships/add" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Add memberships",
        "description" : "Add memberships to a specified list in your HubSpot account. This endpoint allows you to add multiple memberships to a list identified by the listId. It is useful for managing list memberships in bulk, ensuring that the specified records are included in the list.",
        "operationId" : "put-/crm/lists/2026-09-beta/{listId}/memberships/add",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/lists/2026-09-beta/{listId}/memberships/add-and-remove" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update memberships",
        "description" : "Update the memberships of a list by adding and removing members in a single operation. This endpoint allows you to efficiently manage list memberships by specifying which members to add and which to remove in one request.",
        "operationId" : "put-/crm/lists/2026-09-beta/{listId}/memberships/add-and-remove",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/lists/2026-09-beta/{listId}/memberships/add-from/{sourceListId}" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Add memberships",
        "description" : "Add memberships to a specified list from another source list. This operation is useful for consolidating list memberships by transferring members from one list to another. The endpoint does not return any content upon successful execution.",
        "operationId" : "put-/crm/lists/2026-09-beta/{listId}/memberships/add-from/{sourceListId}",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/lists/2026-09-beta/{listId}/memberships/join-order" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve join order",
        "description" : "Retrieve the join order of memberships for a specific list in your HubSpot account. This endpoint allows you to view the order in which records joined the list, which can be useful for tracking membership changes over time.",
        "operationId" : "get-/crm/lists/2026-09-beta/{listId}/memberships/join-order",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/lists/2026-09-beta/{listId}/memberships/remove" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Remove memberships",
        "description" : "Remove memberships from a specific list in your HubSpot account. This operation is useful for managing list memberships by removing specified records from the list. The request requires a list of record IDs to be removed from the specified list.",
        "operationId" : "put-/crm/lists/2026-09-beta/{listId}/memberships/remove",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/lists/2026-09-beta/{listId}/restore" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Restore",
        "description" : "Restore a previously deleted list in your HubSpot account. This operation allows you to recover lists that have been removed, ensuring that any associated data or configurations are reinstated. This can be useful for retrieving lists that were mistakenly deleted or are needed again for ongoing operations.",
        "operationId" : "put-/crm/lists/2026-09-beta/{listId}/restore",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    },
    "/crm/lists/2026-09-beta/{listId}/schedule-conversion" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve",
        "description" : "Retrieve the scheduled conversion details for a specific list in your HubSpot account. This endpoint provides information about any scheduled conversions for the specified list, allowing you to manage and track list conversions effectively.",
        "operationId" : "get-/crm/lists/2026-09-beta/{listId}/schedule-conversion",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      },
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Schedule Conversion",
        "description" : "Schedule a conversion for a specific list in your HubSpot account. This operation allows you to set a conversion time for the list identified by the listId. Use this endpoint to manage the conversion schedule of your lists effectively.",
        "operationId" : "put-/crm/lists/2026-09-beta/{listId}/schedule-conversion",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete schedule conversion",
        "description" : "Delete a scheduled conversion for a specific list in your HubSpot account. This operation is useful when you need to cancel a previously scheduled conversion for a list identified by its listId.",
        "operationId" : "delete-/crm/lists/2026-09-beta/{listId}/schedule-conversion",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    },
    "/crm/lists/2026-09-beta/{listId}/size-and-edits-history/between" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve history",
        "description" : "Retrieve the size and edits history of a specific list within a defined date range. This endpoint is useful for tracking changes and understanding the evolution of list size over time.",
        "operationId" : "get-/crm/lists/2026-09-beta/{listId}/size-and-edits-history/between",
        "security" : [ {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/crm/lists/2026-09-beta/{listId}/update-list-filters" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update list filters",
        "description" : "Update the filters for a specific list in your HubSpot account. This operation allows you to modify the criteria used to include objects in the list. You can also specify whether objects should be enrolled in workflows based on the updated filters.",
        "operationId" : "put-/crm/lists/2026-09-beta/{listId}/update-list-filters",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    },
    "/crm/lists/2026-09-beta/{listId}/update-list-name" : {
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Update list name",
        "description" : "Update the name of a specific list in your HubSpot account. This endpoint allows you to change the list's name by specifying the new name as a query parameter. It is useful for keeping your lists organized and up-to-date with relevant titles.",
        "operationId" : "put-/crm/lists/2026-09-beta/{listId}/update-list-name",
        "security" : [ {
          "oauth2" : [ "cms.membership.access_groups.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ],
        "x-hubspot-user-level-auth" : {
          "internalOnly" : true
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "cms.membership.access_groups.write" : "",
              "crm.lists.read" : "",
              "crm.lists.write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}