{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Settings Multicurrency",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "If your company conducts business in different countries, use this API to adjust your account's currency settings based on requirements or data from a third-party provider.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Currencies guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/settings/currencies"
    } ],
    "x-hubspot-introduction" : "Use the currencies API to manage the currency settings in your HubSpot account, including your company's primary currency, any additional currencies, and updating exchange rates."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Currency"
  }, {
    "name" : "Central_Fx_Rates"
  } ],
  "paths" : {
    "/settings/v3/currencies/exchange-rates" : {
      "get" : {
        "tags" : [ "Currency" ],
        "summary" : "Get exchange rates",
        "description" : "Get a list of exchange rates",
        "operationId" : "get-/settings/v3/currencies/exchange-rates",
        "security" : [ {
          "private_apps" : [ "settings.currencies.read" ]
        }, {
          "oauth2" : [ "settings.currencies.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Currency" ],
        "summary" : "Add a new exchange rate",
        "description" : "Create a new exchange rate with specified conversion rate and currency codes.",
        "operationId" : "post-/settings/v3/currencies/exchange-rates",
        "security" : [ {
          "private_apps" : [ "settings.currencies.write" ]
        }, {
          "oauth2" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/batch/update" : {
      "post" : {
        "tags" : [ "Currency" ],
        "summary" : "Update multiple exchange rates",
        "description" : "Update the conversion rates for multiple exchange rates in a batch operation.",
        "operationId" : "post-/settings/v3/currencies/exchange-rates/batch/update",
        "security" : [ {
          "private_apps" : [ "settings.currencies.write" ]
        }, {
          "oauth2" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/codes" : {
      "get" : {
        "tags" : [ "Currency" ],
        "summary" : "Get all currency codes",
        "description" : "Retrieve a list of all available currency codes and their names.",
        "operationId" : "get-/settings/v3/currencies/codes",
        "security" : [ {
          "private_apps" : [ "settings.currencies.read" ]
        }, {
          "oauth2" : [ "settings.currencies.read" ]
        } ]
      }
    },
    "/settings/v3/currencies/company-currency" : {
      "get" : {
        "tags" : [ "Currency" ],
        "summary" : "Get the company currency",
        "description" : "Get the details for the company currency. The company currency is used in deal totals, reports, and the default currency for new deals.",
        "operationId" : "get-/settings/v3/currencies/company-currency",
        "security" : [ {
          "private_apps" : [ "settings.currencies.read" ]
        }, {
          "oauth2" : [ "settings.currencies.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Currency" ],
        "summary" : "Set or update the company currency.",
        "description" : "Set or update the primary company currency.",
        "operationId" : "put-/settings/v3/currencies/company-currency",
        "security" : [ {
          "private_apps" : [ "settings.currencies.write" ]
        }, {
          "oauth2" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/current" : {
      "get" : {
        "tags" : [ "Currency" ],
        "summary" : "Get all current exchange rates",
        "description" : "Retrieve all current exchange rates for all currency pairs.",
        "operationId" : "get-/settings/v3/currencies/exchange-rates/current",
        "security" : [ {
          "private_apps" : [ "settings.currencies.read" ]
        }, {
          "oauth2" : [ "settings.currencies.read" ]
        } ]
      }
    },
    "/settings/v3/currencies/central-fx-rates/unsupported-currencies" : {
      "get" : {
        "tags" : [ "Central_Fx_Rates" ],
        "operationId" : "get-/settings/v3/currencies/central-fx-rates/unsupported-currencies_/settings/v3/currencies/central-fx-rates/unsupported-currencies",
        "security" : [ {
          "private_apps" : [ "settings.currencies.read" ]
        }, {
          "oauth2" : [ "settings.currencies.read" ]
        } ]
      }
    },
    "/settings/v3/currencies/central-fx-rates/add-currency" : {
      "post" : {
        "tags" : [ "Central_Fx_Rates" ],
        "operationId" : "post-/settings/v3/currencies/central-fx-rates/add-currency_/settings/v3/currencies/central-fx-rates/add-currency",
        "security" : [ {
          "private_apps" : [ "settings.currencies.write" ]
        }, {
          "oauth2" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/update-visibility" : {
      "post" : {
        "tags" : [ "Currency" ],
        "summary" : "Change the visibility of a specific currency pairs",
        "description" : "Change the visibility setting for a currency pair. This will hide or display a currency pair for users in the HubSpot app.",
        "operationId" : "post-/settings/v3/currencies/exchange-rates/update-visibility",
        "security" : [ {
          "private_apps" : [ "settings.currencies.write" ]
        }, {
          "oauth2" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/{exchangeRateId}" : {
      "get" : {
        "tags" : [ "Currency" ],
        "summary" : "Get the details for a specific exchange rate",
        "description" : "Retrieve the details for a specific exchange rate specified by its ID.",
        "operationId" : "get-/settings/v3/currencies/exchange-rates/{exchangeRateId}",
        "security" : [ {
          "private_apps" : [ "settings.currencies.read" ]
        }, {
          "oauth2" : [ "settings.currencies.read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Currency" ],
        "summary" : "Update a conversion rate",
        "description" : "Update an existing conversion rate, specified by its ID.",
        "operationId" : "patch-/settings/v3/currencies/exchange-rates/{exchangeRateId}",
        "security" : [ {
          "private_apps" : [ "settings.currencies.write" ]
        }, {
          "oauth2" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/batch/create" : {
      "post" : {
        "tags" : [ "Currency" ],
        "summary" : "Create multiple exchange rates",
        "description" : "Create multiple exchange rates in a single request.",
        "operationId" : "post-/settings/v3/currencies/exchange-rates/batch/create",
        "security" : [ {
          "private_apps" : [ "settings.currencies.write" ]
        }, {
          "oauth2" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/batch/read" : {
      "post" : {
        "tags" : [ "Currency" ],
        "summary" : "Retrieve multiple rates",
        "description" : "Retrieve the details of multiple exchange rates in a single request, specified by their IDs.",
        "operationId" : "post-/settings/v3/currencies/exchange-rates/batch/read",
        "security" : [ {
          "private_apps" : [ "settings.currencies.read" ]
        }, {
          "oauth2" : [ "settings.currencies.read" ]
        } ]
      }
    },
    "/settings/v3/currencies/central-fx-rates/information" : {
      "get" : {
        "tags" : [ "Central_Fx_Rates" ],
        "operationId" : "get-/settings/v3/currencies/central-fx-rates/information_/settings/v3/currencies/central-fx-rates/information",
        "security" : [ {
          "private_apps" : [ "settings.currencies.read" ]
        }, {
          "oauth2" : [ "settings.currencies.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "settings.currencies.write" : "Write currency and exchange rate data.",
              "settings.currencies.read" : "Read currency and exchange rate data."
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}