{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "MultiCurrencyPublicService",
    "version" : "v3"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Currency"
  } ],
  "paths" : {
    "/settings/v3/currencies/exchange-rates" : {
      "get" : {
        "tags" : [ "Currency" ],
        "operationId" : "get-/settings/v3/currencies/exchange-rates",
        "security" : [ {
          "private_apps_legacy" : [ "settings.currencies.read" ]
        }, {
          "oauth2_legacy" : [ "settings.currencies.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Currency" ],
        "operationId" : "post-/settings/v3/currencies/exchange-rates",
        "security" : [ {
          "private_apps_legacy" : [ "settings.currencies.write" ]
        }, {
          "oauth2_legacy" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/codes" : {
      "get" : {
        "tags" : [ "Currency" ],
        "operationId" : "get-/settings/v3/currencies/codes",
        "security" : [ {
          "private_apps_legacy" : [ "settings.currencies.read" ]
        }, {
          "oauth2_legacy" : [ "settings.currencies.read" ]
        } ]
      }
    },
    "/settings/v3/currencies/company-currency" : {
      "get" : {
        "tags" : [ "Currency" ],
        "operationId" : "get-/settings/v3/currencies/company-currency",
        "security" : [ {
          "private_apps_legacy" : [ "settings.currencies.read" ]
        }, {
          "oauth2_legacy" : [ "settings.currencies.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Currency" ],
        "operationId" : "put-/settings/v3/currencies/company-currency",
        "security" : [ {
          "private_apps_legacy" : [ "settings.currencies.write" ]
        }, {
          "oauth2_legacy" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/batch/update" : {
      "post" : {
        "tags" : [ "Currency" ],
        "operationId" : "post-/settings/v3/currencies/exchange-rates/batch/update",
        "security" : [ {
          "private_apps_legacy" : [ "settings.currencies.write" ]
        }, {
          "oauth2_legacy" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/current" : {
      "get" : {
        "tags" : [ "Currency" ],
        "operationId" : "get-/settings/v3/currencies/exchange-rates/current",
        "security" : [ {
          "private_apps_legacy" : [ "settings.currencies.read" ]
        }, {
          "oauth2_legacy" : [ "settings.currencies.read" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/update-visibility" : {
      "post" : {
        "tags" : [ "Currency" ],
        "operationId" : "post-/settings/v3/currencies/exchange-rates/update-visibility",
        "security" : [ {
          "private_apps_legacy" : [ "settings.currencies.write" ]
        }, {
          "oauth2_legacy" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/{exchangeRateId}" : {
      "get" : {
        "tags" : [ "Currency" ],
        "operationId" : "get-/settings/v3/currencies/exchange-rates/{exchangeRateId}",
        "security" : [ {
          "private_apps_legacy" : [ "settings.currencies.read" ]
        }, {
          "oauth2_legacy" : [ "settings.currencies.read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Currency" ],
        "operationId" : "patch-/settings/v3/currencies/exchange-rates/{exchangeRateId}",
        "security" : [ {
          "private_apps_legacy" : [ "settings.currencies.write" ]
        }, {
          "oauth2_legacy" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/batch/create" : {
      "post" : {
        "tags" : [ "Currency" ],
        "operationId" : "post-/settings/v3/currencies/exchange-rates/batch/create",
        "security" : [ {
          "private_apps_legacy" : [ "settings.currencies.write" ]
        }, {
          "oauth2_legacy" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/batch/read" : {
      "post" : {
        "tags" : [ "Currency" ],
        "operationId" : "post-/settings/v3/currencies/exchange-rates/batch/read",
        "security" : [ {
          "private_apps_legacy" : [ "settings.currencies.read" ]
        }, {
          "oauth2_legacy" : [ "settings.currencies.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "settings.currencies.read" : "Read currency and exchange rate data.",
              "settings.currencies.write" : "Write currency and exchange rate data."
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  }
}