{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Settings Multicurrency",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "Currencies guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/settings/currencies"
    } ]
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Central_Fx_Rates"
  }, {
    "name" : "Currency"
  } ],
  "paths" : {
    "/settings/v3/currencies/central-fx-rates/add-currency" : {
      "post" : {
        "tags" : [ "Central_Fx_Rates" ],
        "operationId" : "post-/settings/v3/currencies/central-fx-rates/add-currency_/settings/v3/currencies/central-fx-rates/add-currency",
        "security" : [ {
          "oauth2" : [ "settings.currencies.write" ]
        }, {
          "private_apps" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/central-fx-rates/information" : {
      "get" : {
        "tags" : [ "Central_Fx_Rates" ],
        "operationId" : "get-/settings/v3/currencies/central-fx-rates/information_/settings/v3/currencies/central-fx-rates/information",
        "security" : [ {
          "oauth2" : [ "settings.currencies.read" ]
        }, {
          "private_apps" : [ "settings.currencies.read" ]
        } ]
      }
    },
    "/settings/v3/currencies/central-fx-rates/unsupported-currencies" : {
      "get" : {
        "tags" : [ "Central_Fx_Rates" ],
        "operationId" : "get-/settings/v3/currencies/central-fx-rates/unsupported-currencies_/settings/v3/currencies/central-fx-rates/unsupported-currencies",
        "security" : [ {
          "oauth2" : [ "settings.currencies.read" ]
        }, {
          "private_apps" : [ "settings.currencies.read" ]
        } ]
      }
    },
    "/settings/v3/currencies/codes" : {
      "get" : {
        "tags" : [ "Currency" ],
        "operationId" : "get-/settings/v3/currencies/codes",
        "security" : [ {
          "oauth2" : [ "settings.currencies.read" ]
        }, {
          "private_apps" : [ "settings.currencies.read" ]
        } ]
      }
    },
    "/settings/v3/currencies/company-currency" : {
      "get" : {
        "tags" : [ "Currency" ],
        "operationId" : "get-/settings/v3/currencies/company-currency",
        "security" : [ {
          "oauth2" : [ "settings.currencies.read" ]
        }, {
          "private_apps" : [ "settings.currencies.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Currency" ],
        "operationId" : "put-/settings/v3/currencies/company-currency",
        "security" : [ {
          "oauth2" : [ "settings.currencies.write" ]
        }, {
          "private_apps" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates" : {
      "get" : {
        "tags" : [ "Currency" ],
        "operationId" : "get-/settings/v3/currencies/exchange-rates",
        "security" : [ {
          "oauth2" : [ "settings.currencies.read" ]
        }, {
          "private_apps" : [ "settings.currencies.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Currency" ],
        "operationId" : "post-/settings/v3/currencies/exchange-rates",
        "security" : [ {
          "oauth2" : [ "settings.currencies.write" ]
        }, {
          "private_apps" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/batch/create" : {
      "post" : {
        "tags" : [ "Currency" ],
        "operationId" : "post-/settings/v3/currencies/exchange-rates/batch/create",
        "security" : [ {
          "oauth2" : [ "settings.currencies.write" ]
        }, {
          "private_apps" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/batch/read" : {
      "post" : {
        "tags" : [ "Currency" ],
        "operationId" : "post-/settings/v3/currencies/exchange-rates/batch/read",
        "security" : [ {
          "oauth2" : [ "settings.currencies.read" ]
        }, {
          "private_apps" : [ "settings.currencies.read" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/batch/update" : {
      "post" : {
        "tags" : [ "Currency" ],
        "operationId" : "post-/settings/v3/currencies/exchange-rates/batch/update",
        "security" : [ {
          "oauth2" : [ "settings.currencies.write" ]
        }, {
          "private_apps" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/current" : {
      "get" : {
        "tags" : [ "Currency" ],
        "operationId" : "get-/settings/v3/currencies/exchange-rates/current",
        "security" : [ {
          "oauth2" : [ "settings.currencies.read" ]
        }, {
          "private_apps" : [ "settings.currencies.read" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/update-visibility" : {
      "post" : {
        "tags" : [ "Currency" ],
        "operationId" : "post-/settings/v3/currencies/exchange-rates/update-visibility",
        "security" : [ {
          "oauth2" : [ "settings.currencies.write" ]
        }, {
          "private_apps" : [ "settings.currencies.write" ]
        } ]
      }
    },
    "/settings/v3/currencies/exchange-rates/{exchangeRateId}" : {
      "get" : {
        "tags" : [ "Currency" ],
        "operationId" : "get-/settings/v3/currencies/exchange-rates/{exchangeRateId}",
        "security" : [ {
          "oauth2" : [ "settings.currencies.read" ]
        }, {
          "private_apps" : [ "settings.currencies.read" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Currency" ],
        "operationId" : "patch-/settings/v3/currencies/exchange-rates/{exchangeRateId}",
        "security" : [ {
          "oauth2" : [ "settings.currencies.write" ]
        }, {
          "private_apps" : [ "settings.currencies.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "settings.currencies.read" : "Read currency and exchange rate data.",
              "settings.currencies.write" : "Write currency and exchange rate data."
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}