{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Communication Preferences Subscriptions",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v4",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "STARTER",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "Subscriptions preferences guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/marketing/subscriptions"
    } ]
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Public_Definition"
  }, {
    "name" : "Public_Link_Generation"
  }, {
    "name" : "Public_Status"
  } ],
  "paths" : {
    "/communication-preferences/v4/definitions" : {
      "get" : {
        "tags" : [ "Public_Definition" ],
        "summary" : "Retrieve all subscription status definitions",
        "description" : "Get a list of subscription status definitions from the account.",
        "operationId" : "get-/communication-preferences/v4/definitions",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        } ]
      }
    },
    "/communication-preferences/v4/links/generate" : {
      "post" : {
        "tags" : [ "Public_Link_Generation" ],
        "operationId" : "post-/communication-preferences/v4/links/generate_/communication-preferences/v4/links/generate",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read", "communication_preferences.write" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read", "communication_preferences.write" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        } ]
      }
    },
    "/communication-preferences/v4/statuses/batch/read" : {
      "post" : {
        "tags" : [ "Public_Status" ],
        "summary" : "Batch retrieve subscription statuses",
        "description" : "Batch retrieve subscription statuses for a set of contacts.",
        "operationId" : "post-/communication-preferences/v4/statuses/batch/read",
        "security" : [ {
          "oauth2" : [ "communication_preferences.statuses.batch.read" ]
        }, {
          "private_apps" : [ "communication_preferences.statuses.batch.read" ]
        } ]
      }
    },
    "/communication-preferences/v4/statuses/batch/unsubscribe-all" : {
      "post" : {
        "tags" : [ "Public_Status" ],
        "summary" : "Batch unsubscribe contacts from all subscriptions",
        "description" : "Unsubscribe a set of contacts from all email subscriptions.",
        "operationId" : "post-/communication-preferences/v4/statuses/batch/unsubscribe-all",
        "security" : [ {
          "oauth2" : [ "communication_preferences.statuses.batch.write" ]
        }, {
          "private_apps" : [ "communication_preferences.statuses.batch.write" ]
        } ]
      }
    },
    "/communication-preferences/v4/statuses/batch/unsubscribe-all/read" : {
      "post" : {
        "tags" : [ "Public_Status" ],
        "summary" : "Batch retrieve contacts who have opted out of all communications",
        "description" : "Checks whether a set of contacts have opted out of all communications.",
        "operationId" : "post-/communication-preferences/v4/statuses/batch/unsubscribe-all/read",
        "security" : [ {
          "oauth2" : [ "communication_preferences.statuses.batch.read" ]
        }, {
          "private_apps" : [ "communication_preferences.statuses.batch.read" ]
        } ]
      }
    },
    "/communication-preferences/v4/statuses/batch/write" : {
      "post" : {
        "tags" : [ "Public_Status" ],
        "summary" : "Batch update subscription status",
        "description" : "Update the subscription status for a set of contacts.",
        "operationId" : "post-/communication-preferences/v4/statuses/batch/write",
        "security" : [ {
          "oauth2" : [ "communication_preferences.statuses.batch.write" ]
        }, {
          "private_apps" : [ "communication_preferences.statuses.batch.write" ]
        } ]
      }
    },
    "/communication-preferences/v4/statuses/{subscriberIdString}" : {
      "get" : {
        "tags" : [ "Public_Status" ],
        "summary" : "Get subscription preferences for a specific contact",
        "description" : "Retrieve a contact's current email subscription preferences.",
        "operationId" : "get-/communication-preferences/v4/statuses/{subscriberIdString}",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        } ]
      },
      "post" : {
        "tags" : [ "Public_Status" ],
        "summary" : "Update a contact's subscription status",
        "description" : "Set the subscription status of a specific contact.",
        "operationId" : "post-/communication-preferences/v4/statuses/{subscriberIdString}",
        "security" : [ {
          "oauth2" : [ "communication_preferences.write" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.write" ]
        } ]
      }
    },
    "/communication-preferences/v4/statuses/{subscriberIdString}/unsubscribe-all" : {
      "get" : {
        "tags" : [ "Public_Status" ],
        "summary" : "Retrieve a contact's unsubscribed status",
        "description" : "Check whether a contact has unsubscribed from all email subscriptions. If a contact has not opted out of all communications, the response `results` array will be empty.",
        "operationId" : "get-/communication-preferences/v4/statuses/{subscriberIdString}/unsubscribe-all",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        } ]
      },
      "post" : {
        "tags" : [ "Public_Status" ],
        "summary" : "Unsubscribe a contact from all subscriptions",
        "description" : "Unsubscribe a contact from all email subscriptions.",
        "operationId" : "post-/communication-preferences/v4/statuses/{subscriberIdString}/unsubscribe-all",
        "security" : [ {
          "oauth2" : [ "communication_preferences.write" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.read_write" ]
        }, {
          "private_apps" : [ "communication_preferences.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "communication_preferences.read" : "Read contact subscription preferences",
              "communication_preferences.read_write" : "Update contact subscription preferences",
              "communication_preferences.statuses.batch.read" : "Batch read contact subscription preferences",
              "communication_preferences.statuses.batch.write" : "Batch update contact subscription preferences",
              "communication_preferences.write" : "Update contact subscription preferences"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "STARTER",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}