{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Deals",
    "description" : "CRM objects such as companies, contacts, deals, line items, products, tickets, and quotes are standard objects in HubSpot’s CRM. These core building blocks support custom properties, store critical information, and play a central role in the HubSpot application.\n\n## Supported Object Types\n\nThis API provides access to collections of CRM objects, which return a map of property names to values. Each object type has its own set of default properties, which can be found by ex[...]",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "When a sales rep starts working with a prospective customer, create a deal record to track the negotiation process. When the customer later makes their purchase, you can update the deal to a closed stage.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Deals Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/objects/deals"
    } ],
    "x-hubspot-introduction" : "Use the deals API to create and manage CRM records that represent transactions with contacts and/or companies. Deals progress through pipeline stages to reflect whether the transaction has been completed, is active, or has otherwise been lost."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Public_Object__SE_PT_EM_BE_R_2025"
  }, {
    "name" : "Public_Object_Search_Post__SE_PT_EM_BE_R_2025"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/v3/objects/0-3" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List",
        "description" : "Read a page of deals. Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/v3/objects/0-3_getPage",
        "security" : [ {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create",
        "description" : "Create a deal with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard deals is provided.",
        "operationId" : "post-/crm/v3/objects/0-3_create",
        "security" : [ {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        } ]
      }
    },
    "/crm/v3/objects/0-3/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Archive a batch of deals by ID",
        "description" : "Archive multiple deals using their IDs.",
        "operationId" : "post-/crm/v3/objects/0-3/batch/archive_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        } ]
      }
    },
    "/crm/v3/objects/0-3/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of deals",
        "description" : "Create multiple deals in a single request.",
        "operationId" : "post-/crm/v3/objects/0-3/batch/create_create",
        "security" : [ {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        } ]
      }
    },
    "/crm/v3/objects/0-3/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of deals by internal ID, or unique property values",
        "description" : "Retrieve records by record ID or include the `idProperty` parameter to retrieve records by a custom unique value property. ",
        "operationId" : "post-/crm/v3/objects/0-3/batch/read_read",
        "security" : [ {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        } ]
      }
    },
    "/crm/v3/objects/0-3/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update a batch of deals by internal ID, or unique property values",
        "description" : "Update multiple deals using their internal IDs or unique property values.",
        "operationId" : "post-/crm/v3/objects/0-3/batch/update_update",
        "security" : [ {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        } ]
      }
    },
    "/crm/v3/objects/0-3/batch/upsert" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create or update a batch of deals by unique property values",
        "description" : "Create or update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
        "operationId" : "post-/crm/v3/objects/0-3/batch/upsert_upsert",
        "security" : [ {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        } ]
      }
    },
    "/crm/v3/objects/0-3/merge" : {
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Merge two deals with same type",
        "description" : "Combine two deals of the same type into a single deal.",
        "operationId" : "post-/crm/v3/objects/0-3/merge_merge",
        "security" : [ {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        } ]
      }
    },
    "/crm/v3/objects/0-3/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "summary" : "Search for deals using various filters and criteria to retrieve specific records.",
        "description" : "Search for deals using specified criteria and filters.",
        "operationId" : "post-/crm/v3/objects/0-3/search_doSearch",
        "security" : [ {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/v3/objects/0-3/{dealId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read",
        "description" : "Read an Object identified by `{dealId}`. `{dealId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/v3/objects/0-3/{dealId}_getById",
        "security" : [ {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archive",
        "description" : "Move an Object identified by `{dealId}` to the recycling bin.",
        "operationId" : "delete-/crm/v3/objects/0-3/{dealId}_archive",
        "security" : [ {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update",
        "description" : "Perform a partial update of an Object identified by `{dealId}`or optionally a unique property value as specified by the `idProperty` query param. `{dealId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
        "operationId" : "patch-/crm/v3/objects/0-3/{dealId}_update",
        "security" : [ {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.appointments.read" : "Read appointments",
              "crm.objects.appointments.sensitive.read.v2" : "Read appointments (sensitive)",
              "crm.objects.appointments.sensitive.write.v2" : "Write appointments (sensitive)",
              "crm.objects.appointments.write" : "Write appointments",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.carts.write" : "Write cart",
              "crm.objects.commercepayments.read" : "Read the COMMERCE_PAYMENT object.",
              "crm.objects.commercepayments.write" : "Write commerce payments",
              "crm.objects.companies.highly_sensitive.read.v2" : "View company records (highly-sensitive)",
              "crm.objects.companies.highly_sensitive.write.v2" : "Change company records (highly-sensitive)",
              "crm.objects.companies.read" : "Create or update company records",
              "crm.objects.companies.sensitive.read.v2" : "View sensitive properties on company records",
              "crm.objects.companies.sensitive.write.v2" : "Create or update sensitive properties on company records",
              "crm.objects.companies.write" : "View company records",
              "crm.objects.contacts.highly_sensitive.read.v2" : "View contact records (highly-sensitive)",
              "crm.objects.contacts.highly_sensitive.write.v2" : "Change contact records (highly-sensitive)",
              "crm.objects.contacts.read" : "View contact records",
              "crm.objects.contacts.sensitive.read.v2" : "View sensitive properties on contact records",
              "crm.objects.contacts.sensitive.write.v2" : "Create or update sensitive properties on contact records",
              "crm.objects.contacts.write" : "Create or update contact records",
              "crm.objects.courses.read" : "Read courses",
              "crm.objects.courses.write" : "Write courses",
              "crm.objects.custom.highly_sensitive.read.v2" : "View custom object records (highly-sensitive)",
              "crm.objects.custom.highly_sensitive.write.v2" : "Change custom object records (highly-sensitive)",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.custom.sensitive.read.v2" : "View custom object records (sensitive)",
              "crm.objects.custom.sensitive.write.v2" : "Change custom object records (sensitive)",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.deals.highly_sensitive.read.v2" : "View deal records (highly-sensitive)",
              "crm.objects.deals.highly_sensitive.write.v2" : "Change deal records (highly-sensitive)",
              "crm.objects.deals.read" : "View deal records",
              "crm.objects.deals.sensitive.read.v2" : "View sensitive properties on deal records",
              "crm.objects.deals.sensitive.write.v2" : "Create or update sensitive properties on deal records",
              "crm.objects.deals.write" : "Create or update deal records",
              "crm.objects.goals.read" : "Read goals",
              "crm.objects.goals.write" : "Write goals",
              "crm.objects.invoices.read" : "Read invoices objects",
              "crm.objects.invoices.write" : "Write invoices",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.listings.read" : "Read listings",
              "crm.objects.listings.write" : "Write listings",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.partner-clients.write" : "Modify Partner Client CRM objects",
              "crm.objects.partner-services.read" : "View Partner Service CRM objects",
              "crm.objects.partner-services.write" : "Modify Partner Service CRM objects",
              "crm.objects.products.read" : "Read from my Product Library",
              "crm.objects.products.write" : "Write to my Product Library",
              "crm.objects.projects.highly_sensitive.read" : "Read projects (highly-sensitive)",
              "crm.objects.projects.highly_sensitive.write" : "Write projects (highly-sensitive)",
              "crm.objects.projects.read" : "Read projects",
              "crm.objects.projects.sensitive.read" : "Read projects (sensitive)",
              "crm.objects.projects.sensitive.write" : "Write projects (sensitive)",
              "crm.objects.projects.write" : "Write projects",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.services.read" : "Read services",
              "crm.objects.services.write" : "Write services",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.subscriptions.write" : "Write to Commerce Subscriptions",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.users.write" : "Write User CRM objects",
              "e-commerce" : "e-commerce",
              "media_bridge.read" : "Read media and media events",
              "oauth" : "User and Account Information",
              "tickets" : "Read and write tickets",
              "tickets.highly_sensitive.v2" : "Tickets (highly-sensitive)",
              "tickets.sensitive.v2" : "Tickets (sensitive)"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}