name: Raise PR

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2 # Use v2 for compatibility
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'


      - name: Delete Remote Branch if Exists
        run: |
          BRANCH_NAME="update_postman_commits"
          if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
            echo "Deleting existing remote branch: $BRANCH_NAME"
            git push https://$PAT@github.com/rpanicker06/HubSpot-public-api-spec-collection.git --delete $BRANCH_NAME
          else
            echo "No existing remote branch to delete."
          fi
        env:
          PAT: ${{ secrets.PAT }}

      - name: Create or Checkout Branch
        run: |
          BRANCH_NAME="update_postman_commits"
          echo "Using branch: $BRANCH_NAME"
          git checkout -B $BRANCH_NAME

      - name: Remove Workflow File from Commit
        run: |
          git rm --cached .github/workflows/sync.yml || echo "Workflow file not staged, skipping removal."
          git rm --cached .github/workflows/raisePR.yml || echo "Workflow file not staged, skipping removal."
          git commit -m "Remove workflow file for PR" || echo "Nothing to commit, skipping."

      - name: Push Changes to Forked Repo
        run: |
          BRANCH_NAME="update_postman_commits"
          git push -u https://$PAT@github.com/rpanicker06/HubSpot-public-api-spec-collection.git $BRANCH_NAME
        env:
          PAT: ${{ secrets.PAT }}

      - name: Create Pull Request
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          REPO_OWNER="HubSpot"
          REPO_NAME="HubSpot-public-api-spec-collection"
          HEAD_BRANCH="update_postman_commits"
          BASE_BRANCH="main"
          PR_TITLE="Add new feature"
          PR_BODY="This PR adds a new feature to the project."
        
          #Make API request to create the pull request
          curl -s -X POST \
            -H "Authorization: token $PAT" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls" \
            -d @- <<EOF
          {
          "title": "Amazing new feature",
          "body": "Please pull these awesome changes in!",
          "head": "rpanicker06:update_postman_commits",
          "base": "main",
          "head_repo":"HubSpot-public-api-spec-collection"
          }
          EOF

