name: Raise PR

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2 # Use v2 for compatibility
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Verify Current Branch and Status
        run: |
          echo "Current branch:"
          git branch
          echo "Current status:"
          git status

#      - name: Delete Remote Branch if Exists
#        run: |
#          BRANCH_NAME="update_postman_commits"
#          if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
#            echo "Deleting existing remote branch: $BRANCH_NAME"
#            git push https://$PAT@github.com/rpanicker06/HubSpot-public-api-spec-collection.git --delete $BRANCH_NAME
#          else
#            echo "No existing remote branch to delete."
#          fi
#        env:
#          PAT: ${{ secrets.PAT }}

#      - name: Create or Checkout Branch
#        run: |
#          BRANCH_NAME="update_postman_commits"
#          echo "Using branch: $BRANCH_NAME"
#          git checkout -B $BRANCH_NAME

#      - name: Remove Workflow File from Commit
#        run: |
#          git rm --cached .github/workflows/sync.yml || echo "Workflow file not staged, skipping removal."
#          git rm --cached .github/workflows/raisePR.yml || echo "Workflow file not staged, skipping removal."
#          git commit -m "Remove workflow file for PR" || echo "Nothing to commit, skipping."

#      - name: Push Changes to Forked Repo
#        run: |
#          BRANCH_NAME="update_postman_commits"
#          git push -u https://$PAT@github.com/rpanicker06/HubSpot-public-api-spec-collection.git $BRANCH_NAME
#        env:
#          PAT: ${{ secrets.PAT }}

      - name: Create Pull Request to HubSpot Repo
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync updates from Forked Repo"
          title: "Sync updates from Forked Repo"
          body: |
            This PR contains updates synced from forked repo to HubSpot Repo.
          base: main
          draft: false

